Repository mendix/docs, pull requests merged in 2018-05, with the labels that each got.

#1167 Add known issue to release notes
  content/releasenotes/desktop-modeler/7.13.md
  content/releasenotes/desktop-modeler/7.14.md
Labels: 7.14

#1168 Ats2 add local selenium howtos
  content/ats/howtos/ht-version-2/attachments/setup-local-selenium-index-2/setup-local-docker-selenium-hub-2/docker_grid.png
  content/ats/howtos/ht-version-2/attachments/setup-local-selenium-index-2/setup-local-selenium-hub-2/grid_hub.png
  content/ats/howtos/ht-version-2/attachments/setup-local-selenium-index-2/setup-local-selenium-hub-2/grid_nodes.png
  content/ats/howtos/ht-version-2/attachments/setup-local-selenium-index-2/setup-local-selenoid-hub-2/add_capability.png
  content/ats/howtos/ht-version-2/attachments/setup-local-selenium-index-2/setup-local-selenoid-hub-2/enable_vnc.png
  content/ats/howtos/ht-version-2/attachments/setup-local-selenium-index-2/setup-local-selenoid-hub-2/selenoidui1.png
  content/ats/howtos/ht-version-2/attachments/setup-local-selenium-index-2/setup-local-selenoid-hub-2/selenoidui2.png
  content/ats/howtos/ht-version-2/attachments/setup-local-selenium-index-2/setup-local-selenoid-hub-2/video_name.png
  content/ats/howtos/ht-version-2/ht-version-2.md
  content/ats/howtos/ht-version-2/setting-up-a-local-selenium-solution-2.md
  content/ats/howtos/ht-version-2/setup-local-docker-selenium-hub-2.md
  content/ats/howtos/ht-version-2/setup-local-selenium-hub-2.md
  content/ats/howtos/ht-version-2/setup-local-selenium-index-2.md
  content/ats/howtos/ht-version-2/setup-local-selenoid-hub-2.md
Labels: Needs language review

#1200 Add desktop modeler release notes 7.15.1
  content/releasenotes/desktop-modeler/7.15.md
Labels: 7.15

#1190 Integration changes for 7.15
  content/howto/integration/version-rest-service.md
  content/refguide/attachments/19202819/19399020.png
  content/refguide/attachments/19203256/19399080.png
  content/refguide/call-rest-action.md
  content/refguide/call-web-service-action.md
  content/refguide/message-definition.md
  content/refguide/module-security.md
  content/refguide/open-api.md
  content/refguide/project-settings.md
  content/refguide/publish-microflow-as-rest-operation.md
  content/refguide/published-rest-operation.md
  content/refguide/published-rest-services.md
Labels: 7.15

#1171 Decimal formatting update [7.15]
  content/refguide/columns-document-template.md
  content/refguide/columns.md
  content/refguide/data-grid.md
  content/refguide/dynamic-label-document-template.md
  content/refguide/reference-selector.md
  content/refguide/text-box.md
  snippets/refguide/Numeric+Formatting+Properties.md
Labels: 7.15

#1192 Merge after 7.15 RN
  content/releasenotes/desktop-modeler/7.10.md
  content/releasenotes/desktop-modeler/7.11.md
  content/releasenotes/desktop-modeler/7.12.md
  content/releasenotes/desktop-modeler/7.13.md
  content/releasenotes/desktop-modeler/7.14.md
  content/releasenotes/desktop-modeler/7.9.md
Labels: 7.15
