Repository mendix/docs, pull requests merged in 2018-04, with the labels that each got.

#1122 Added a hint how to get '1987-12-31T23:59:00'
  content/refguide/parse-and-format-date-function-calls.md
Labels: Waiting for verification

#1158 Add desktop modeler release notes 7.14.0
  content/releasenotes/desktop-modeler/7.14.md
Labels: 7.14

#1152 Integration features for 7.14
  content/refguide/published-rest-operation.md
  content/refguide/published-rest-service-json-schema.md
  content/refguide/published-rest-services.md
Labels: 7.14

#1135 Add known limitation for select all and edit buttons [7.14]
  content/refguide/select-all-button.md
Labels: 7.14

#1160 7.13 RN linked to fixed issue
  content/releasenotes/desktop-modeler/7.13.md
Labels: 7.14, Verify after merge
