Repository mendix/docs, pull requests merged in 2018-07, with the labels that each got.

#1249 Added docs for delete API
  content/apidocs-mxsdk/apidocs/attachments/14778446/ProjectsAPI_10.msd
  content/apidocs-mxsdk/apidocs/attachments/14778446/ProjectsAPI_11.msd
  content/apidocs-mxsdk/apidocs/projects-api.md
Labels: Future release

#1214 Add page editor theme how-to
  content/howto/theming/configuring-your-theme.md
Labels: 7.16, Verify after merge

#1250 Release notes for release 7.16.0
  content/releasenotes/desktop-modeler/6.10.md
  content/releasenotes/desktop-modeler/7.16.md
Labels: 7.16

#1242 Add known issue fixes
  content/releasenotes/desktop-modeler/7.0.md
  content/releasenotes/desktop-modeler/7.1.md
  content/releasenotes/desktop-modeler/7.10.md
  content/releasenotes/desktop-modeler/7.11.md
  content/releasenotes/desktop-modeler/7.12.md
  content/releasenotes/desktop-modeler/7.13.md
  content/releasenotes/desktop-modeler/7.14.md
  content/releasenotes/desktop-modeler/7.15.md
  content/releasenotes/desktop-modeler/7.2.md
  content/releasenotes/desktop-modeler/7.3.md
  content/releasenotes/desktop-modeler/7.4.md
  content/releasenotes/desktop-modeler/7.5.md
  content/releasenotes/desktop-modeler/7.6.md
  content/releasenotes/desktop-modeler/7.7.md
  content/releasenotes/desktop-modeler/7.8.md
  content/releasenotes/desktop-modeler/7.9.md
Labels: 7.16

#1219 Integration changes for 7.16
  content/howto/integration/version-rest-service.md
  content/refguide/call-web-service-action.md
  content/refguide/generate-rest-resource.md
  content/refguide/message-definitions.md
  content/refguide/module-security.md
  content/refguide/project-settings.md
  content/refguide/publish-microflow-as-rest-operation.md
  content/refguide/published-rest-service.md
  content/refguide/published-rest-services.md
Labels: 7.16

#1251 SAP SSO Release Notes PR
  content/releasenotes/developer-portal/index.md
Labels: Internal WIP (R&D review before language review), Needs review by R&D

#1256 Maria RN restructure
  content/refguide/web-modeler/attachments/versions-wm/wm-about-dialog.png
  content/refguide/web-modeler/attachments/versions-wm/wm-top-bar-upgrade.png
  content/refguide/web-modeler/index.md
  content/refguide/web-modeler/versions-wm.md
  content/releasenotes/web-modeler/7.11-7.14.md
  content/releasenotes/web-modeler/7.15-and-above.md
  content/releasenotes/web-modeler/index.md
  data/spaces.yml
Labels: Changes requested

#1272 Dep 49 APIs for env tags
  content/apidocs-mxsdk/apidocs/deploy-api.md
Labels: Changes requested, Fix merge conflicts

#1276 Maria web modeler ref guide
  content/refguide/web-modeler/attachments/microflows-exclusive-split-wm/wm-configure-condition-dialog-excl-split.png
  content/refguide/web-modeler/attachments/microflows-exclusive-split-wm/wm-example-of-using-var-activities.png
  content/refguide/web-modeler/attachments/microflows-exclusive-split-wm/wm-exclusive-split-boolean.png
  content/refguide/web-modeler/attachments/microflows-exclusive-split-wm/wm-exclusive-split-enumeration.png
  content/refguide/web-modeler/attachments/microflows-exclusive-split-wm/wm-exclusive-split.png
  content/refguide/web-modeler/attachments/microflows-expressions-wm/wm-customer-empty-and-name-example.png
  content/refguide/web-modeler/attachments/microflows-expressions-wm/wm-example-excl-split.png
  content/refguide/web-modeler/attachments/microflows-expressions-wm/wm-expression-error.png
  content/refguide/web-modeler/attachments/microflows-expressions-wm/wm-expression-excl-split.png
  content/refguide/web-modeler/attachments/microflows-expressions-wm/wm-expression-tab.png
  content/refguide/web-modeler/attachments/microflows-expressions-wm/wm-expressions-list.png
  content/refguide/web-modeler/attachments/microflows-setting-and-changing-value-wm/wm-add-new-value.png
  content/refguide/web-modeler/attachments/microflows-setting-and-changing-value-wm/wm-change-value-var-dialog.png
  content/refguide/web-modeler/attachments/microflows-setting-and-changing-value-wm/wm-configure-retuen-value-dialog.png
  content/refguide/web-modeler/attachments/microflows-setting-and-changing-value-wm/wm-configure-return-value.png
  content/refguide/web-modeler/attachments/microflows-setting-and-changing-value-wm/wm-end-event-returns-value-setting.png
  content/refguide/web-modeler/attachments/microflows-setting-and-changing-value-wm/wm-set-initial-value-object-dialog.png
  content/refguide/web-modeler/attachments/microflows-setting-and-changing-value-wm/wm-set-initial-value-var.png
  content/refguide/web-modeler/attachments/page-editor-data-view-list-view-wm/wm-design-section-info-icon.png
  content/refguide/web-modeler/attachments/page-editor-data-view-list-view-wm/wm-info-icon.png
  content/refguide/web-modeler/attachments/page-editor-widgets-wm/wm-info-icon.png
  content/refguide/web-modeler/checks-wm.md
  content/refguide/web-modeler/domain-models-attributes-wm.md
  content/refguide/web-modeler/domain-models-wm.md
  content/refguide/web-modeler/index.md
  content/refguide/web-modeler/microflows-exclusive-split-wm.md
  content/refguide/web-modeler/microflows-expressions-wm.md
  content/refguide/web-modeler/microflows-setting-and-changing-value-wm.md
  content/refguide/web-modeler/microflows-wm.md
  content/refguide/web-modeler/overview-wm.md
  content/refguide/web-modeler/page-editor-data-view-list-view-wm.md
  content/refguide/web-modeler/page-editor-widgets-wm.md
  content/refguide/web-modeler/page-editor-wm.md
  content/refguide/web-modeler/theme-customizer-wm.md
  content/releasenotes/web-modeler/index.md
Labels: Changes requested

#1280 Maria howtos web modeler
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-blocked-attribute.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-call-microflow-button-in-data-view.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-call-microflow-button-selected-microflow.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-configure-condition-grade.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-configure-condition-pop-up.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-create-button-properties.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-data-view-properties.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-data-view-select-data-view-source.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-data-view.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-details-button-microflow.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-empty-customer-grade-message.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-excl-split-go-back.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-excl-split-possible-cases.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-grade-attribute.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-list-view-list4.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-microflow-blocked-completed.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-microflow-empty-flow-show-message.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-microflow-not-set-parameter.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-new-attribute-create-dialog.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-new-customer-page-blocked-attribute.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-new-enumeration-add-item-bronze.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-new-enumeration-add-item.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-new-enumeration-bronze-silver-gold.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-parameter-properties.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-pre-fill-contents.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-setting-cases-for-excl-split.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-show-message-properties-true-flow.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-show-page-select-page.png
  content/howto/web-modeler/attachments/webmodeler-how-to-microflows-exclsplit/wm-true-false-flows-microflow.png
  content/howto/web-modeler/index.md
  content/howto/web-modeler/webmodeler-how-to-microflows-exclsplit-p2.md
  content/howto/web-modeler/webmodeler-how-to-microflows-exclsplit.md
Labels: Changes requested

#1268 Update read-only style documentation for 7.17
  snippets/refguide/Read+Only+Style.md
Labels: 7.17

#1260 Updated docs to reflect new createXPathQuery Core API
  content/howto/logic-business-rules/java-api-tutorial.md
Labels: 7.17

#1239 Documentation for delete action (to be merged for 7.17)
  content/refguide/action-button.md
  content/refguide/delete-button.md
  content/refguide/edit-button.md
  content/refguide/grid-action-button.md
  content/refguide/new-button.md
  content/refguide/opening-pages.md
  snippets/refguide/On+Click+Event+Action.md
Labels: 7.17

#1220 Page Editor documentation for new 7.17 property 'Documentation URL'
  content/refguide/building-block.md
Labels: 7.17
