Repository mendix/docs, pull requests merged in 2018-06, with the labels that each got.

#1195 Update for APM 2.0
  content/apm/installation-guide/ig-2/installation-2.md
  content/apm/reference-guide/rg-2/apps.md
  content/apm/reference-guide/rg-2/attachments/Browser_agent_recording_notice.png
  content/apm/reference-guide/rg-2/attachments/Documentation.png
  content/apm/reference-guide/rg-2/attachments/Tour.png
  content/apm/reference-guide/rg-2/attachments/TourStep.png
  content/apm/reference-guide/rg-2/attachments/dashboard.png
  content/apm/reference-guide/rg-2/attachments/environments.png
  content/apm/reference-guide/rg-2/attachments/exclude_dialog.png
  content/apm/reference-guide/rg-2/attachments/exclusions.png
  content/apm/reference-guide/rg-2/attachments/logs.png
  content/apm/reference-guide/rg-2/attachments/new_environment.png
  content/apm/reference-guide/rg-2/attachments/profile_menu.png
  content/apm/reference-guide/rg-2/attachments/select-browsers.png
  content/apm/reference-guide/rg-2/attachments/settings.png
  content/apm/reference-guide/rg-2/attachments/statistics_history.png
  content/apm/reference-guide/rg-2/attachments/trap.png
  content/apm/reference-guide/rg-2/attachments/user_settings.png
  content/apm/reference-guide/rg-2/browser-recorder-results.md
  content/apm/reference-guide/rg-2/environments.md
  content/apm/reference-guide/rg-2/logs.md
  content/apm/reference-guide/rg-2/long-running-actions.md
  content/apm/reference-guide/rg-2/recorder.md
  content/apm/reference-guide/rg-2/reference-guide-2.md
  content/apm/reference-guide/rg-2/settings.md
  content/apm/reference-guide/rg-2/statistics.md
  content/apm/use-cases/uc-2/use-cases-2.md
  content/releasenotes/apm/2.0.md
Labels: Waiting for CLA

#1215 Update release notes + API documentation for CP 175 release.
  content/apidocs-mxsdk/apidocs/deploy-api.md
  content/releasenotes/platform-portal/attachments/CPHealthIcon.png
  content/releasenotes/platform-portal/index.md
Labels: Future release

#1217 Update release notes for kapacitor release
  content/releasenotes/platform-portal/index.md
Labels: Future release

#1211 Update feedback-api.md
  content/apidocs-mxsdk/apidocs/feedback-api.md
Labels: Waiting for CLA

#1184 Converting an Apple certificate to a p12 key.
  content/refguide/managing-app-signing-keys.md
Labels: Needs review by R&D
