Repository mendix/docs, pull requests merged in 2018-10, with the labels that each got.

#1372 Update dev-best-practices.md
  content/howtogeneral/bestpractices/dev-best-practices.md
Labels: Waiting for CLA

#1383 Add autonumber issue to known issue case.
  content/releasenotes/desktop-modeler/7.18.md
Labels: Needs review by R&D

#1384 ATS 2.9.3 release notes do not publish before October 16
  content/releasenotes/ats/2.9.md
Labels: Future release

#1400 7.19 RN
  content/releasenotes/desktop-modeler/7.18.md
  content/releasenotes/desktop-modeler/7.19.md
Labels: 7.19

#1385 Integration team changes for release 7.19
  content/refguide/custom-settings.md
  content/refguide/published-odata-resource.md
Labels: 7.19

#1327 Add note that as of 7.19.0 more additional parameters are supported
  content/refguide/starting-microflows.md
Labels: 7.19

#1297 Update documentation for "Refresh in client" option (to be merged for 7.19)
  content/refguide/change-object.md
  content/refguide/committing-objects.md
  content/refguide/create-object.md
  content/refguide/deleting-objects.md
  content/refguide/rollback-object.md
Labels: 7.19

#1356 Introduce custom setting com.mendix.storage.PerformDeleteFromStorage; deprecate com.mendix.storage.s3.PerformDeleteFromStorage since Mendix 7.19
  content/refguide/custom-settings.md
Labels: 7.19
