Repository mendix/docs, pull requests merged in 2018-12, with the labels that each got.

#1433 7.21 RN
  content/releasenotes/desktop-modeler/7.19.md
  content/releasenotes/desktop-modeler/7.20.md
  content/releasenotes/desktop-modeler/7.21.md
Labels: 7.21

#1428 Integration changes for release 7.21
  content/refguide/attachments/16713721/16843927.png
  content/refguide/custom-settings.md
  content/refguide/odata-representation.md
  content/refguide/project-settings.md
  content/refguide/published-odata-services.md
Labels: 7.21

#1435 ATS 2.9.4 release notes
  content/ats/refguide/rg-version-2/app.md
  content/ats/refguide/rg-version-2/function-reference.md
  content/releasenotes/add-ons/ats-2.9.md
Labels: Changes requested

#1447 New MxDM updates association names automatically
  content/howtogeneral/bestpractices/dev-best-practices.md
Labels: Verify after merge

#1440 Added Credit Balance Warning
  content/developerportal/operate/monitoring-application-health.md
Labels: Needs review by R&D

#1462 7.18.3 RN
  content/releasenotes/desktop-modeler/7.18.md
Labels: 7.18.3

#1461 7.22 RN
  content/releasenotes/desktop-modeler/7.20.md
  content/releasenotes/desktop-modeler/7.21.md
  content/releasenotes/desktop-modeler/7.22.md
Labels: 7.22

#1463 6.10.17 RN
  content/releasenotes/desktop-modeler/6.10.md
Labels: 6.10.17

#1437 Integration changes for Mendix 6.10.17
  content/refguide6/custom-settings.md
Labels: 6.10.17
