Repository mendix/docs, pull requests merged in 2018-11, with the labels that each got.

#1404 Integration changes for release 7.20
  content/refguide/call-web-service-action.md
  content/refguide/custom-settings.md
  content/refguide/project-settings.md
Labels: 7.20

#1392 [for 7.20] Fix documentation ("Show control bar" property of the data grid)
  content/refguide/data-grid.md
Labels: 7.20

#1408 Proposal to improve readability by using smallcaps for some prefix-ch…
  content/howtogeneral/bestpractices/dev-best-practices.md
Labels: Needs review by R&D

#1418 Update 7.20.md
  content/releasenotes/desktop-modeler/7.20.md
Labels: Waiting for verification

#1422 Add RN for 7.20.1
  content/releasenotes/desktop-modeler/7.20.md
Labels: Future release

#1421 Add RN for 7.19.1
  content/releasenotes/desktop-modeler/7.19.md
Labels: Future release
