Repository mendix/docs, pull requests merged in 2019-11, with the labels that each got.

#2054 Update Apps
  content/developerportal/apps-list/attachments/apps-list.png
  content/developerportal/apps-list/attachments/apps-page-menu.png
  content/developerportal/apps-list/attachments/apps-tiles.png
  content/developerportal/apps-list/attachments/company-apps-list.png
  content/developerportal/apps-list/attachments/favorites-toggle.png
  content/developerportal/apps-list/attachments/favoriting.png
  content/developerportal/apps-list/attachments/quick-action-menu.png
  content/developerportal/apps-list/attachments/search-apps.png
  content/developerportal/apps-list/attachments/search-company-apps.png
  content/developerportal/apps-list/attachments/sort-drop-down.png
  content/developerportal/apps-list/attachments/sort-dropdown.png
  content/developerportal/apps-list/attachments/view-switch.png
  content/developerportal/apps-list/index.md
  content/developerportal/attachments/developerportal-apps.png
Labels: Future release

#2055 Update index.md
  content/releasenotes/developer-portal/index.md
Labels: Future release

#2032 MendixSSO - Modifying and Upgrading
  content/developerportal/deploy/attachments/mendix-sso/after-startup.png
  content/developerportal/deploy/attachments/mendix-sso/associate-accountpassworddata.png
  content/developerportal/deploy/attachments/mendix-sso/create-new-entity.png
  content/developerportal/deploy/attachments/mendix-sso/custom-afterstartup-microflow.png
  content/developerportal/deploy/attachments/mendix-sso/edit-members.png
  content/developerportal/deploy/attachments/mendix-sso/entity-access.png
  content/developerportal/deploy/attachments/mendix-sso/my-tokens.png
  content/developerportal/deploy/attachments/mendix-sso/reselect-page-role.png
  content/developerportal/deploy/attachments/mendix-sso/snippets.png
  content/developerportal/deploy/attachments/mendix-sso/token-administration.png
  content/developerportal/deploy/attachments/mendix-sso/token-navigation.png
  content/developerportal/deploy/attachments/mendix-sso/token-pages.png
  content/developerportal/deploy/attachments/mendix-sso/token-snippets.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/add-association.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/attributes-to-change.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/change-layouts.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/create-new-entity.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/custom-afterstartup-microflow.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/edit-members.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/exclude-duplicate-services.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/import-custom-mxsso.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/keep-associated-entities.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/migration-concepts.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/migration-microflow.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/modified-domain-model.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/process-flow.pptx
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/retrieve-associated-objects.png
  content/developerportal/deploy/attachments/upgrading-to-mendix-sso-from-acs/updated-domain-models.png
  content/developerportal/deploy/integrate-with-mendix-sso.md
  content/developerportal/deploy/mendix-cloud-deploy.md
  content/developerportal/deploy/mendix-sso.md
  content/developerportal/deploy/troubleshooting-iis.md
  content/developerportal/deploy/upgrading-to-mendix-sso-from-ACS.md
  content/developerportal/settings/general-settings.md
  content/howto/mobile/implementation-guide.md
  content/howto/monitoring-troubleshooting/clear-warning-messages.md
  content/howto/monitoring-troubleshooting/debug-a-hybrid-mobile-application.md
  content/howto/monitoring-troubleshooting/debug-java-actions-remotely.md
  content/howto/monitoring-troubleshooting/debug-java-actions.md
  content/howto/monitoring-troubleshooting/debug-microflows-remotely.md
  content/howto/monitoring-troubleshooting/debug-microflows.md
  content/howto/monitoring-troubleshooting/finding-the-root-cause-of-runtime-errors.md
  content/howto/monitoring-troubleshooting/handle-common-mendix-sso-errors.md
  content/howto/monitoring-troubleshooting/index.md
  content/howto/monitoring-troubleshooting/log-levels.md
  content/howto/monitoring-troubleshooting/manage-app-performance-with-appdynamics.md
  content/howto/monitoring-troubleshooting/manage-app-performance-with-new-relic.md
  content/howto/monitoring-troubleshooting/monitoring-mendix-using-jmx.md
  content/howto/monitoring-troubleshooting/solving-load-and-import-errors.md
  content/howto/testing/testing-web-services-using-soapui.md
  content/refguide/retrieve.md
Labels: Internal WIP

#2058 App Store Favorites
  content/developerportal/app-store/app-store-overview.md
  content/developerportal/app-store/attachments/app-store-overview/favorites.png
  content/releasenotes/app-store/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2064 Update index.md
  content/developerportal/mendix-profile/index.md
Labels: Waiting for CLA

#2071 Update layout grid documentation for 8.3.0
  content/refguide/layout-grid.md
Labels: Needs language review

#2079 ats-2.12 release notes
  content/releasenotes/add-ons/ats-2.12.md
Labels: Changes requested

#2086 Draft App Store RN
  content/releasenotes/app-store/index.md
Labels: Future release, Internal WIP

#2093 Draft troubleshooting
  content/howto/logic-business-rules/extending-your-application-with-custom-java.md
Labels: Internal WIP

#2088 Added explanation for passed arguments
  content/refguide/microflow-call.md
Labels: Needs technical review

#2091 7.23.9 Release Notes
  content/releasenotes/studio-pro/7.23.md
Labels: Future release

#2109 8.4 RN
  content/howto/logic-business-rules/attachments/8784287/8946349.png
  content/howto/logic-business-rules/working-with-lists-in-a-microflow.md
  content/howto/mobile/attachments/18448692/18581186.png
  content/releasenotes/studio-pro/8.3.md
  content/releasenotes/studio-pro/8.4.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 8.4.0

#2115 Add 'Nanoflow' as new parameter type to JavaScript actions
  content/refguide/javascript-actions.md
Labels: 8.4.0

#2107 Update documentation for the new Project Explorer
  content/refguide/attachments/project-explorer/project-explorer.png
  content/refguide/preferences-dialog.md
  content/refguide/project-explorer.md
Labels: 8.4.0

#2012 Added documentation for new pluggable property type decimal
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/decimal.png
  content/apidocs-mxsdk/apidocs/property-types-pluggable-widgets.md
Labels: 8.4.0

#2080 Add dynamic image support for PW
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/image.png
  content/apidocs-mxsdk/apidocs/property-types-pluggable-widgets.md
Labels: 8.4.0

#2118 Add 8.3 retract note
  content/releasenotes/studio-pro/8.3.md
Labels: Future release

#2123 8.4.1 RN
  content/releasenotes/studio-pro/8.4.md
Labels: Future release
