Repository mendix/docs, pull requests merged in 2019-12, with the labels that each got.

#2130 Add runtime-core fix notes for 8.3.1 Release
  content/releasenotes/studio-pro/8.3.md
Labels: Future release

#2142 Update index.md
  content/releasenotes/developer-portal/index.md
Labels: Changes requested

#2137 Update string-function-calls.md
  content/refguide/string-function-calls.md
Labels: Needs technical review

#2148 Added a note to warn against branching outside of Studio Pro.
  content/refguide/using-version-control-in-studio-pro.md
Labels: Needs technical review

#2153 Update date-creation.md
  content/refguide/date-creation.md
Labels: Waiting for CLA

#2159 8.3.2 RN
  content/releasenotes/studio-pro/8.3.md
Labels: Future release

#2161 7.23.10 Release Notes
  content/releasenotes/studio-pro/7.23.md
Labels: Future release

#2157 8.4.2 RN
  content/releasenotes/studio-pro/8.4.md
Labels: Future release

#2164 Update index.md
  content/releasenotes/developer-portal/index.md
Labels: Future release

#2167 Story beta sprintr
  content/developerportal/attachments/Screenshot 2019-12-12 at 14.50.57.png
  content/developerportal/attachments/developerportal-enable-storybeta.png
  content/developerportal/collaborate/attachments/stories-contextual-menu.png
  content/developerportal/collaborate/attachments/stories-enable-new-ui.png
  content/developerportal/collaborate/attachments/stories-new-ui.png
  content/developerportal/collaborate/stories.md
Labels: Future release

#2165 Native Template 2.1.0 release notes
  content/releasenotes/mobile/native-template.md
Labels: 8.5.0, Needs technical review

#2163 New release notes for MakeItNative
  content/releasenotes/mobile/make-it-native-app.md
Labels: 8.5.0

#2166 Native Builder 3.1.0 release notes
  content/howto/mobile/deploying-native-app.md
  content/refguide/native-builder.md
  content/releasenotes/mobile/native-builder.md
Labels: 8.5.0

#2168 8.5 RN
  content/releasenotes/studio-pro/8.5.md
Labels: 8.5.0

#2147 Document file property for PW
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/file.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/xml-element.png
  content/apidocs-mxsdk/apidocs/client-apis-for-pluggable-widgets.md
  content/apidocs-mxsdk/apidocs/property-types-pluggable-widgets.md
Labels: 8.5.0

#2096 Added new type for java action parameter
  content/refguide/java-actions.md
Labels: 8.5.0

#2139 Update Toolbox documetation
  content/refguide/preferences-dialog.md
Labels: 8.5.0

#2098 In 8.5.0, call REST and call web services actions have a timeout
  content/refguide/call-rest-action.md
  content/refguide/call-web-service-action.md
Labels: 8.5.0

#2176 Add 8.4.3 RNs
  content/releasenotes/studio-pro/8.4.md
Labels: Future release

#2182 7.23.11 release notes
  content/releasenotes/studio-pro/7.23.md
Labels: Future release
