Repository mendix/docs, pull requests merged in 2019-10, with the labels that each got.

#1971 Update example-implementation.md
  content/apidocs-mxsdk/apidocs/example-implementation.md
Labels: Waiting for CLA

#2005 Update changing-things-in-the-model.md
  content/apidocs-mxsdk/mxsdk/changing-things-in-the-model.md
Labels: Needs technical review

#2018 Release notes for 8.2.2
  content/releasenotes/studio-pro/8.2.md
Labels: Future release

#2026 App Store updates
  content/developerportal/app-store/app-store-content.md
  content/developerportal/app-store/app-store-overview.md
  content/developerportal/app-store/attachments/app-store-overview/company-content.png
  content/developerportal/app-store/attachments/app-store-overview/company-only-content.png
  content/developerportal/app-store/attachments/app-store-overview/content-management.png
  content/developerportal/app-store/attachments/app-store-overview/content-managers.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_1.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_2.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_5.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_6.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_7.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_8.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_9.png
  content/developerportal/app-store/attachments/app-store-overview/drafts.png
  content/developerportal/app-store/attachments/app-store-overview/external-downloaders.png
  content/developerportal/app-store/attachments/app-store-overview/group-content.png
  content/developerportal/app-store/attachments/app-store-overview/guests.png
  content/developerportal/app-store/attachments/app-store-overview/home_page.png
  content/developerportal/app-store/attachments/app-store-overview/members.png
  content/developerportal/app-store/attachments/app-store-overview/my-content.png
  content/developerportal/app-store/attachments/app-store-overview/my_app_store.png
  content/developerportal/app-store/attachments/app-store-overview/notifications.png
  content/developerportal/app-store/attachments/app-store-overview/shared-with-me.png
  content/developerportal/app-store/attachments/app-store-overview/shared-with-others.png
  content/developerportal/app-store/attachments/app-store-overview/your-company-reviews.png
  content/developerportal/app-store/attachments/app-store-overview/your-reviews.png
  content/developerportal/app-store/attachments/share-app-store-content/add_content_3.png
  content/developerportal/app-store/attachments/share-app-store-content/add_content_4.png
  content/developerportal/app-store/attachments/share-app-store-content/add_content_5.png
  content/developerportal/app-store/attachments/share-app-store-content/add_content_8.png
  content/developerportal/app-store/attachments/share-app-store-content/add_content_button.png
  content/developerportal/app-store/attachments/share-app-store-content/update_content_1.png
  content/developerportal/app-store/attachments/share-app-store-content/update_content_2.png
  content/developerportal/app-store/share-app-store-content.md
  content/developerportal/company-app-roles/manage-roles.md
  content/releasenotes/app-store/index.md
Labels: Internal WIP

#2040 Draft 8.3 RN
  content/releasenotes/sdk/model-sdk-4.md
  content/releasenotes/studio-pro/8.1.md
  content/releasenotes/studio-pro/8.2.md
  content/releasenotes/studio-pro/8.3.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 8.3.0

#2023 add pluggable widget help
  content/apidocs-mxsdk/apidocs/attachments/pluggable-widgets/widget-dialog-help-button.png
  content/apidocs-mxsdk/apidocs/pluggable-widgets.md
Labels: 8.3.0

#2019 Update native navigation styling options
  content/refguide/native-styling-refguide.md
Labels: 8.3.0

#2000 Add text for removal of 1000 options limit on drop-down search field
  content/refguide/drop-down-search-field.md
  content/refguide7/drop-down-search-field.md
Labels: 8.3.0

#2038 Updated Full Screen and added Distraction Free Mode for 8.3.0
  content/refguide/studio-pro-overview.md
Labels: 8.3.0

#2021 Update container docs with description about click event
  content/refguide/container.md
  content/refguide/native-styling-refguide.md
Labels: 8.3.0

#2010 Description of REST operation parameter
  content/refguide/published-rest-operation-parameter.md
Labels: 8.3.0

#1988 Add description of consistency errors
  content/refguide/attachments/consistency-errors-pages/data-source-list-view.png
  content/refguide/attachments/consistency-errors-pages/data-view-city-context.png
  content/refguide/attachments/consistency-errors-pages/data-view-data-source.png
  content/refguide/attachments/consistency-errors-pages/data-view-employee-context.png
  content/refguide/attachments/consistency-errors-pages/details-button.png
  content/refguide/attachments/consistency-errors-pages/microflow-parameter.png
  content/refguide/attachments/consistency-errors-pages/on-click-event-button.png
  content/refguide/attachments/consistency-errors-pages/selecting-the-owner.png
  content/refguide/consistency-errors-navigation.md
  content/refguide/consistency-errors-pages.md
  content/refguide/consistency-errors.md
  content/studio/attachments/consistency-errors-pages/button-on-click-action.png
  content/studio/attachments/consistency-errors-pages/data-view-photo-data-source.png
  content/studio/attachments/consistency-errors-pages/list-view-data-source.png
  content/studio/attachments/consistency-errors-pages/microflow-parameter.png
  content/studio/consistency-errors-domain-model.md
  content/studio/consistency-errors-navigation.md
  content/studio/consistency-errors-pages.md
Labels: 8.3.0

#2031 Extend how-to with server-side searching
  content/howto/logic-business-rules/attachments/server-side-paging/fourth-param.png
  content/howto/logic-business-rules/attachments/server-side-paging/template-add-search.png
  content/howto/logic-business-rules/server-side-paging.md
Labels: 8.3.0
