Repository mendix/docs, pull requests merged in 2019-08, with the labels that each got.

#1821 8.0.0 GA RN
  content/releasenotes/studio-pro/8.0.md
  data/spaces.yml
Labels: 8.0.0.GA

#1829 Maria studio moving to 8
  content/studio/general-upgrade-to-8.md
  content/studio/general-versions.md
Labels: 8.0.0.GA, Internal WIP

#1816 Mendix 8.0.0 GA introduces setting com.mendix.storage.s3.Region
  content/refguide/custom-settings.md
Labels: 8.0.0.GA

#1840 Update Make It Native release notes
  content/releasenotes/mobile/make-it-native-app.md
Labels: 8.0.0.GA

#1832 Update migration-atlas.md
  content/refguide/migration-atlas.md
Labels: 8.0.0.GA

#1822 Update native-styling.md
  content/howto/mobile/native-styling.md
Labels: 8.0.0.GA

#1773 Document nanoflow call action
  content/refguide/action-call-activities.md
  content/refguide/activities.md
  content/refguide/attachments/819203/918005.png
  content/refguide/attachments/819203/918008.png
  content/refguide/nanoflow-call.md
  content/refguide/nanoflows.md
Labels: 8.0.0.GA

#1804 Update props
  content/refguide/native-styling-refguide.md
Labels: 8.0.0.GA

#1849 Add Studio RN
  content/releasenotes/studio/7.11-7.14.md
  content/releasenotes/studio/7.15-7.22.md
  content/releasenotes/studio/7.23.md
  content/releasenotes/studio/8.0-and-above.md
  content/releasenotes/studio/attachments/checks-panel.png
  content/releasenotes/studio/attachments/sort-order.png
  content/releasenotes/studio/index.md
  content/studio/general-upgrade-to-8.md
Labels: 8.0.0.GA

#1850 Add info on Studio upgrade
  content/refguide/moving-from-7-to-8.md
Labels: 8.0.0.GA, Needs language review

#1843 Update trends-v4.md
  content/developerportal/operate/trends-v4.md
Labels: Needs technical review

#1857 Add multiple constraint known issue to Mendix 8 GA
  content/releasenotes/studio-pro/8.0.md
Labels: Internal WIP

#1860 Update import information on associations
  content/studio/start-with-data.md
Labels: Internal WIP

#1874 Some minor changes
  content/howto/extensibility/create-a-pluggable-widget-one.md
Labels: Needs technical review

#1867 Improve dev UX
  .travis.yml
  Dockerfile
  README.md
  docker-compose.yml
  package-lock.json
  package.json
Labels: Internal WIP

#1891 Add Client APIs for Pluggable Widgets
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/action.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/boolean.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/enumeration.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/expression.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/icon.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/image.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/integer.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/object.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/string-multiline.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/string.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/text.png
  content/apidocs-mxsdk/apidocs/attachments/widget-property-types/xml-element.png
  content/apidocs-mxsdk/apidocs/client-apis-for-pluggable-widgets.md
  content/apidocs-mxsdk/apidocs/index.md
  content/apidocs-mxsdk/apidocs/pluggable-widgets.md
  content/apidocs-mxsdk/apidocs/property-types-pluggable-widgets.md
  content/refguide/data-view.md
Labels: 8.1.0

#1919 Restructure and add info on empty cells
  content/studio/start-with-data.md
Labels: Internal WIP

#1825 Add mx command line tool documentation
  content/refguide/mx-command-line-tool.md
  content/refguide/system-requirements.md
Labels: 8.1.0
