Repository mendix/docs, pull requests merged in 2019-04, with the labels that each got.

#1568 #COL-407: Updated Settings for Webhooks Information
  content/apidocs-mxsdk/apidocs/webhooks-sprints.md
  content/developerportal/settings/attachments/general-settings.png
  content/developerportal/settings/attachments/webhooks-list.png
  content/developerportal/settings/general-settings.md
Labels: Future release

#1556 add scope descriptions for mx:app:stories:read and mx:app:stories:write
  content/developerportal/mendix-profile/oauth-scopes.md
Labels: Future release

#1572 Webhooks for publication
  content/apidocs-mxsdk/apidocs/webhooks-sprints.md
  content/developerportal/settings/attachments/general-settings.png
  content/developerportal/settings/attachments/webhooks-list.png
  content/developerportal/settings/general-settings.md
  content/releasenotes/developer-portal/index.md
Labels: Future release

#1580 Minor fixes monitoring-mendix-runtime.md
  content/refguide/monitoring-mendix-runtime.md
Labels: Needs review by R&D, Waiting for CLA

#1583 Added the required END keyword
  content/refguide/oql-case-expression.md
Labels: Internal WIP

#1595 App Store category of DeveloperPortal: Rename Modeler to Studio
  content/developerportal/app-store/app-store-content.md
  content/developerportal/app-store/app-store-overview.md
  content/developerportal/app-store/attachments/share-app-store-content/add_content_8.png
  content/developerportal/app-store/index.md
  content/developerportal/app-store/share-app-store-content.md
Labels: 8.0.0.B1

#1577 App Store updates
  content/developerportal/app-store/app-store-overview.md
  content/developerportal/app-store/attachments/app-store-content/toolbar.png
  content/developerportal/app-store/attachments/app-store-overview/company-content.png
  content/developerportal/app-store/attachments/app-store-overview/company-only-content.png
  content/developerportal/app-store/attachments/app-store-overview/content-management.png
  content/developerportal/app-store/attachments/app-store-overview/content-managers.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_5.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_6.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_7.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_8.png
  content/developerportal/app-store/attachments/app-store-overview/content_detail_9.png
  content/developerportal/app-store/attachments/app-store-overview/external-downloaders.png
  content/developerportal/app-store/attachments/app-store-overview/home_page.png
  content/developerportal/app-store/attachments/app-store-overview/my-content.png
  content/developerportal/app-store/attachments/app-store-overview/my_app_store.png
  content/developerportal/app-store/attachments/app-store-overview/notifications.png
  content/developerportal/app-store/attachments/app-store-overview/shared-with-me.png
  content/developerportal/app-store/attachments/app-store-overview/shared-with-others.png
  content/developerportal/app-store/attachments/app-store-overview/your-company-reviews.png
  content/developerportal/app-store/attachments/app-store-overview/your-reviews.png
  content/developerportal/app-store/share-app-store-content.md
  content/developerportal/company-app-roles/manage-roles.md
  content/releasenotes/developer-portal/index.md
Labels: Future release

#1593 Mx8 adam 1
  content/apidocs-mxsdk/apidocs/feedback-api.md
  content/apidocs-mxsdk/apidocs/profile-api.md
  content/apidocs-mxsdk/apidocs/projects-api.md
  content/apidocs-mxsdk/mxsdk/attachments/sdk-intro/sdk-diagram.png
  content/apidocs-mxsdk/mxsdk/changing-things-in-the-model.md
  content/apidocs-mxsdk/mxsdk/creating-the-domain-model.md
  content/apidocs-mxsdk/mxsdk/creating-your-first-script.md
  content/apidocs-mxsdk/mxsdk/domain-model-metamodel.md
  content/apidocs-mxsdk/mxsdk/faq.md
  content/apidocs-mxsdk/mxsdk/finding-things-in-the-model.md
  content/apidocs-mxsdk/mxsdk/generating-code-from-the-model.md
  content/apidocs-mxsdk/mxsdk/microflows-metamodel.md
  content/apidocs-mxsdk/mxsdk/pages-metamodel.md
  content/apidocs-mxsdk/mxsdk/projects-metamodel.md
  content/apidocs-mxsdk/mxsdk/tutorial-for-the-mendix-sdk.md
  content/apidocs-mxsdk/mxsdk/understanding-the-metamodel.md
  content/apidocs-mxsdk/mxsdk/working-with-when.js-and-promises-in-typescript.md
  content/apm/installation-guide/ig-2/installation-2.md
  content/apm/reference-guide/rg-2/apps.md
  content/apm/reference-guide/rg-2/browser-recorder-results.md
  content/apm/reference-guide/rg-2/environments.md
  content/apm/reference-guide/rg-2/logs.md
  content/apm/reference-guide/rg-2/settings.md
  content/ats/bestpractices/bp-version-2/finding-the-action-you-need-2.md
  content/ats/howtos/ht-version-2/custom-action-prerequisites-2.md
  content/ats/howtos/ht-version-2/increase-recorder-helper-coverage-2.md
  content/ats/refguide/rg-version-2/supported-widgets.md
Labels: 8.0.0.B1

#1598 MX8 Support Docs update - Merge into Developer Portal Branch first
  content/developerportal/support/escalation-management-process.md
  content/developerportal/support/index.md
  content/developerportal/support/submit-support-request.md
Labels: 8.0.0.B1, Needs review by R&D

#1597 MX8 Developer Portal updates (except App Store)
  content/developerportal/collaborate/attachments/edit-app.png
  content/developerportal/collaborate/attachments/view-stories.png
  content/developerportal/collaborate/stories.md
  content/developerportal/community-tools/index.md
  content/developerportal/community-tools/mendix-forum.md
  content/developerportal/deploy/app-services.md
  content/developerportal/deploy/attachments/studio-deployment-settings/developer-portal-deploy-environments.png
  content/developerportal/deploy/attachments/studio-deployment-settings/developer-portal-environments-details.png
  content/developerportal/deploy/attachments/studio-deployment-settings/developer-portal-web-modeler-target.png
  content/developerportal/deploy/azure-deploy.md
  content/developerportal/deploy/cloud-foundry-deploy.md
  content/developerportal/deploy/deploy-mendix-on-microsoft-windows.md
  content/developerportal/deploy/deploying-to-mindsphere.md
  content/developerportal/deploy/docker-deploy.md
  content/developerportal/deploy/environments-details.md
  content/developerportal/deploy/environments.md
  content/developerportal/deploy/high-availability.md
  content/developerportal/deploy/ibm-cloud.md
  content/developerportal/deploy/index.md
  content/developerportal/deploy/integrate-with-mendix-sso.md
  content/developerportal/deploy/java-in-the-cloud.md
  content/developerportal/deploy/licensing-apps.md
  content/developerportal/deploy/managing-mendix-sso.md
  content/developerportal/deploy/mendix-cloud-deploy.md
  content/developerportal/deploy/mobileapp.md
  content/developerportal/deploy/mxcloudv4.md
  content/developerportal/deploy/sap-cloud-platform.md
  content/developerportal/deploy/security-checklist-for-your-on-premises-installation.md
  content/developerportal/deploy/studio-deployment-settings.md
  content/developerportal/deploy/updating-a-mendix-application.md
  content/developerportal/deploy/web-modeler-deployment-settings.md
  content/developerportal/develop/index.md
  content/developerportal/develop/modeling-environments.md
  content/developerportal/develop/planning-development.md
  content/developerportal/develop/team-server.md
  content/developerportal/feedback/use-feedback-widget.md
  content/developerportal/mendix-profile/index.md
  content/developerportal/operate/backups.md
  content/developerportal/operate/index.md
  content/developerportal/operate/metrics.md
  content/developerportal/operate/restore-backup-locally.md
  content/developerportal/operate/trends-v4.md
  content/developerportal/operate/trends.md
  content/developerportal/operate/troubleshooting-mxcloud-cache.md
  content/developerportal/settings/general-settings.md
  content/developerportal/settings/index.md
  content/developerportal/support/escalation-management-process.md
  content/developerportal/support/index.md
  content/developerportal/support/submit-support-request.md
  content/web-modeler/publishing-app.md
Labels: 8.0.0.B1
