Repository mendix/docs, pull requests merged in 2019-07, with the labels that each got.

#1765 8.0.0 Beta 3 Release Notes
  content/releasenotes/studio-pro/8.0.md
Labels: 8.0.0.B3

#1789 Updated Emulate Cloud Security documentation
  content/refguide7/configuration.md
  content/releasenotes/studio-pro/7.21.md
Labels: Needs language review

#1775 Document nanoflow error handling
  content/refguide/attachments/819203/918248.png
  content/refguide/nanoflows.md
Labels: Needs technical review

#1788 Redo Beta 3 RN PR
  content/releasenotes/studio-pro/8.0.md
Labels: 8.0.0.B3

#1689 Renamed entity set name to exposed set name in published OData
  content/refguide/published-odata-resource.md
Labels: 8.0.0.B3

#1711 Updated specs to Java 11 for Mx8
  content/refguide/system-requirements.md
Labels: 8.0.0.B3

#1744 Form-data support in consume REST
  content/refguide/call-rest-action.md
Labels: 8.0.0.B3

#1751 Document exposing microflows as a microflow action
  content/refguide/microflow.md
Labels: 8.0.0.B3

#1750 DOM Changes RefGuide
  content/howto/front-end/atlas-ui.md
  content/howto/front-end/migrate-existing-projects-to-atlasui.md
  content/refguide/migration-atlas.md
  content/refguide/migration-dom-issues.md
  content/refguide/moving-from-7-to-8.md
Labels: 8.0.0.B3

#1742 Upgrade required .NET and Mono versions
  content/refguide/system-requirements.md
Labels: 8.0.0.B3

#1770 Proofread and restructure Pages
  _assets/mappings/redirect.js
  content/refguide/attachments/page-resources/project-explorer-page-resources.png
  content/refguide/attachments/pages/image-collection-icon.png
  content/refguide/attachments/pages/menu-icon.png
  content/refguide/attachments/pages/page-structure.png
  content/refguide/building-block.md
  content/refguide/document-template.md
  content/refguide/images.md
  content/refguide/layout.md
  content/refguide/menu-bar.md
  content/refguide/menu-item.md
  content/refguide/menu.md
  content/refguide/navigation-tree.md
  content/refguide/page-resources.md
  content/refguide/page-templates.md
  content/refguide/page.md
  content/refguide/pages.md
  content/refguide/simple-menu-bar.md
  content/refguide/snippet.md
  content/refguide/translatable-texts.md
Labels: 8.0.0.B3, Future release

#1776 Updated migration-atlas.md
  content/refguide/migration-atlas.md
Labels: 8.0.0.B3

#1703 Add note about Java 11 migration.
  content/refguide/moving-from-7-to-8.md
Labels: 8.0.0.B3

#1708 Update documentation on fixing float and currency deprecations in mendix 8
  content/refguide/attachments/moving-from-7-to-8/convert-to-decimal-warning.png
  content/refguide/attachments/moving-from-7-to-8/currency-float-change-options.png
  content/refguide/attachments/moving-from-7-to-8/currency-float-error.png
  content/refguide/moving-from-7-to-8.md
Labels: 8.0.0.B3

#1783 Update App Store docs
  content/developerportal/app-store/app-store-overview.md
  content/developerportal/app-store/attachments/app-store-overview/drafts.png
  content/developerportal/app-store/attachments/app-store-overview/my_app_store.png
  content/developerportal/app-store/share-app-store-content.md
Labels: Future release

#1794 [TW-612] Clarify SQL Server manual steps
  content/developerportal/deploy/setting-up-a-new-sql-server-database.md
Labels: Needs technical review

#1801 Correct XPath restrictions for multi-tenant in Development Considerations
  content/partners/siemens/mindsphere-development-considerations.md
Labels: Needs partner review

#1810 Add step explaining scaling requires a restart
  content/developerportal/deploy/scale-environment.md
Labels: Needs language review

#1813 Ticket 85976 - Add Known Issue for 7.23.6
  content/releasenotes/studio-pro/7.23.md
Labels: Needs technical review

#1814 weekly release notes update for Studio
  content/releasenotes/studio/7.23-and-above.md
Labels: Future release, Needs language review

#1806 Adding without getting a duplicate object
  content/refguide/change-list.md
  content/refguide7/change-list.md
Labels: Needs language review

#1817 Use correct SPDX license expression
  package.json
Labels: Needs language review

#1819 Added the missing END keyword
  content/refguide/oql-case-expression.md
Labels: Needs technical review

#1815 7.23.7
  content/releasenotes/studio-pro/7.23.md
Labels: 7.23.7, Needs language review

#1812 Update syntax highlighting library
  _assets/js/prism.js
  _assets/styles/_sass/_base.scss
  _assets/styles/_sass/vendor/_prism-codehighlighting.scss
Labels: Needs technical review

#1838 Appstore 6.1.0 release
  content/developerportal/app-store/attachments/share-app-store-content/add_content_1.png
  content/developerportal/app-store/attachments/share-app-store-content/add_content_5.png
  content/developerportal/app-store/share-app-store-content.md
  content/releasenotes/developer-portal/index.md
Labels: July 31st App Store/6.1.0

#1837 Add Native Builder doc
  content/howto/mobile/native-builder.md
  content/howto/mobile/native-mobile.md
Labels: 8.0.0.GA
