Repository mendix/docs, pull requests merged in 2019-06, with the labels that each got.

#1699 SAP Fiori Data Model removal
  content/howto/sap/attachments/use-sap-odata-connector/data-model.png
  content/howto/sap/attachments/use-sap-odata-connector/generate-mpk.png
  content/howto/sap/attachments/use-sap-odata-connector/get-list.png
  content/howto/sap/attachments/use-sap-odata-connector/import-module.png
  content/howto/sap/attachments/use-sap-odata-connector/login-catalog.png
  content/howto/sap/attachments/use-sap-odata-connector/show-get-list-result.png
  content/howto/sap/attachments/use-sap-odata-model-creator/model-creator-generated-catalog.png
  content/howto/sap/attachments/use-sap-odata-model-creator/model-creator-wizard-1.png
  content/howto/sap/attachments/use-sap-odata-model-creator/model-creator-wizard-2-1-catalog.png
  content/howto/sap/attachments/use-sap-odata-model-creator/model-creator-wizard-2-catalog.png
  content/howto/sap/attachments/use-sap-odata-model-creator/model-creator-wizard-3-catalog.png
  content/howto/sap/attachments/use-sap-odata-model-creator/model-creator-wizard-4-catalog.png
  content/howto/sap/attachments/use-sap-odata-model-creator/project_explorer.png
  content/howto/sap/use-sap-odata-connector.md
  content/howto/sap/use-sap-odata-model-creator.md
  content/refguide/sap/attachments/sap-odata-connector/create-params.png
  content/refguide/sap/attachments/sap-odata-connector/delete-params.png
  content/refguide/sap/attachments/sap-odata-connector/domainmodelgwsample_basic-sapodataconnector.png
  content/refguide/sap/attachments/sap-odata-connector/editbox-sapodataconnector.png
  content/refguide/sap/attachments/sap-odata-connector/errorhandling-sapodataconnector.png
  content/refguide/sap/attachments/sap-odata-connector/execute-entry-params.png
  content/refguide/sap/attachments/sap-odata-connector/execute-list-params.png
  content/refguide/sap/attachments/sap-odata-connector/functionnames-sapodataconnector.png
  content/refguide/sap/attachments/sap-odata-connector/functionsandfunctionparameters-sapodataconnector.png
  content/refguide/sap/attachments/sap-odata-connector/get-entry-params.png
  content/refguide/sap/attachments/sap-odata-connector/get-list-params.png
  content/refguide/sap/attachments/sap-odata-connector/refresh-params.png
  content/refguide/sap/attachments/sap-odata-connector/serviceroot.png
  content/refguide/sap/attachments/sap-odata-connector/tolineitems-sapodataconnector.png
  content/refguide/sap/attachments/sap-odata-connector/update-params.png
  content/refguide/sap/sap-data-models.md
  content/refguide/sap/sap-odata-connector.md
Labels: Internal WIP

#1713 Added 'Set return value' to step 5
  content/howto/logic-business-rules/extract-and-use-sub-microflows.md
Labels: Needs technical review

#1698 Add RN and MX Assist doc
  content/refguide/attachments/mx-assist-studio-pro/mendix-assist-icon.png
  content/refguide/attachments/mx-assist-studio-pro/mendix-assist-salutation.png
  content/refguide/attachments/mx-assist-studio-pro/mx-assist-add-check.png
  content/refguide/attachments/mx-assist-studio-pro/mx-assist-add-other-element.png
  content/refguide/attachments/mx-assist-studio-pro/mx-assist-properties.png
  content/refguide/attachments/mx-assist-studio-pro/mx-assist-recommendations.png
  content/refguide/attachments/mx-assist-studio-pro/mx-assist-system-variables.png
  content/refguide/mx-assist-studio-pro.md
  content/releasenotes/studio-pro/8.0.md
Labels: 8.0.0.B2

#1656 Added published OData resource exposed association name
  content/refguide/published-odata-resource.md
Labels: 8.0.0.B2

#1692 Add a note about breaking change in java code generation to the migration guide
  content/refguide/moving-from-7-to-8.md
Labels: 8.0.0.B2

#1719 Update references to using old versions of TortoiseSVN
  content/howto/collaboration-requirements-management/on-premises-svn-howto.md
  content/howto/collaboration-requirements-management/troubleshoot-version-control-issues.md
  content/howto/front-end/style-with-gulp-and-sass.md
  content/refguide/system-requirements.md
  content/refguide/using-version-control-in-studio-pro.md
Labels: 8.0.0.B2

#1668 Add Mendix Cloud HTTP request headers documentation
  content/developerportal/deploy/mendix-cloud-request-headers.md
Labels: Internal WIP, Needs language review

#1752 Add 7.23.6 RN
  content/releasenotes/studio-pro/7.23.md
Labels: Future release

#1757 Added Make It Native release notes
  content/refguide/getting-the-make-it-native-app.md
  content/refguide/native-mobile.md
  content/releasenotes/mobile/hybrid-app.md
  content/releasenotes/mobile/index.md
  content/releasenotes/mobile/make-it-native-app.md
  content/releasenotes/mobile/mendix-mobile-app.md
Labels: Internal WIP

#1749 Release Notes for Developer Portal - 27 June
  content/releasenotes/developer-portal/index.md
Labels: Future release

#1761 SAP Logger Connector
  content/developerportal/operate/logs.md
  content/partners/sap/attachments/sap-logger/logger_drag_component.png
  content/partners/sap/attachments/sap-logger/logger_edit_action.png
  content/partners/sap/attachments/sap-logger/logger_in_microflow.png
  content/partners/sap/attachments/sap-logger/logger_open_project_settings.png
  content/partners/sap/attachments/sap-logger/logger_project_runtime_create_microflow.png
  content/partners/sap/attachments/sap-logger/logger_project_runtime_nostartup.png
  content/partners/sap/attachments/sap-logger/logger_project_runtime_show_startup.png
  content/partners/sap/sap-logger.md
  content/releasenotes/developer-portal/index.md
Labels: Needs language review
