Repository mendix/docs, pull requests merged in 2019-05, with the labels that each got.

#1628 HTTP Header Hotfix Release Note
  content/releasenotes/developer-portal/index.md
Labels: Future release

#1626 add RN
  content/releasenotes/studio-pro/7.23.md
Labels: 7.23.4

#1622 7.23.4 rework prs
  content/refguide7/actions.md
  content/refguide7/clustered-mendix-runtime.md
  content/refguide7/consumed-app-services.md
  content/refguide7/desktop-modeler.md
  content/refguide7/integration.md
  content/refguide7/modules.md
  content/refguide7/published-app-service.md
  content/refguide7/published-app-services.md
  content/refguide7/select-app-service.md
Labels: 7.23.4

#1637 Corrected code error and incorrect image
  content/howto/extensibility/create-a-pluggable-widget-one.md
Labels: Needs review by R&D

#1664 Add more detailed description of design properties feature in release notes
  content/releasenotes/studio-pro/8.0.md
Labels: Needs language review

#1663 Update service-integration.md
  content/best-practices/architecture/integration/service-integration.md
Labels: Needs language review

#1639 Upload JS RefGuide docs
  content/howto/extensibility/best-practices-javascript-actions.md
  content/howto/extensibility/write-javascript-actions.md
  content/refguide/action-call-activities.md
  content/refguide/attachments/javascript-action-call/argument-edit.png
  content/refguide/attachments/javascript-action-call/properties.png
  content/refguide/attachments/javascript-actions/call-js-action-dialog.png
  content/refguide/attachments/javascript-actions/documentation-js-file.png
  content/refguide/attachments/javascript-actions/documentation-pro.png
  content/refguide/attachments/javascript-actions/expose-jsaction.png
  content/refguide/attachments/javascript-actions/javascript-action-settings-no-para.png
  content/refguide/attachments/javascript-actions/parameter-code.png
  content/refguide/attachments/javascript-actions/parameter-naming.png
  content/refguide/attachments/javascript-actions/type-parameter.png
  content/refguide/attachments/javascript-actions/workshop-exposed.png
  content/refguide/java-action-call.md
  content/refguide/javascript-action-call.md
  content/refguide/javascript-actions.md
  content/refguide/microflow-call.md
  content/refguide/nanoflows.md
Labels: Internal WIP

#1682 Draft App User Management content
  content/developerportal/company-app-roles/users.md
  content/developerportal/settings/attachments/app-user-management.png
  content/developerportal/settings/attachments/authorize.png
  content/developerportal/settings/attachments/invite-app-user.png
  content/developerportal/settings/general-settings.md
  content/studio/settings-security.md
Labels: Internal WIP
