Repository mendix/docs, pull requests merged in 2020-04, with the labels that each got.

#2364 Add 8.8 RN
  content/releasenotes/studio-pro/8.7.md
  content/releasenotes/studio-pro/8.8.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 8.8.0

#2366 Add release notes model SDK and metamodel for release 8.8
  content/releasenotes/sdk/metamodel-8.8.md
  content/releasenotes/sdk/metamodel-8.md
  content/releasenotes/sdk/model-sdk-4.md
Labels: 8.8.0

#2318 Add Sql Server 2019 to the supported database list
  content/refguide/system-requirements.md
Labels: 8.8.0

#2360 Update warning suppression screenshots to match Studio Pro 8.8
  content/refguide/attachments/suppression-rules/new-warning-window.png
  content/refguide/attachments/suppression-rules/rule-settings-window.png
  content/refguide/suppression-rules.md
Labels: 8.8.0

#2345 Update mx offline-first and related docs - for new offline microflow feature
  content/refguide/change-object.md
  content/refguide/close-page.md
  content/refguide/committing-objects.md
  content/refguide/create-object.md
  content/refguide/deleting-objects.md
  content/refguide/download-file.md
  content/refguide/microflow-call.md
  content/refguide/offline-first.md
  content/refguide/rollback-object.md
  content/refguide/show-home-page.md
  content/refguide/show-message.md
  content/refguide/show-page.md
  content/refguide/validation-feedback.md
Labels: 8.8.0

#2361 Native Template 3.2.0 release notes
  content/releasenotes/mobile/native-template.md
Labels: 8.8.0

#2380 Prefix is not always needed
  content/howto/general/dev-best-practices.md
Labels: Needs technical verification

#2385 Release notes for Appstore Release 7.5.0
  content/releasenotes/app-store/index.md
Labels: Future release

#2387 Add warnings to cross-reference App Store RN issue
  content/releasenotes/studio-pro/6.0.md
  content/releasenotes/studio-pro/6.1.md
  content/releasenotes/studio-pro/6.10.md
  content/releasenotes/studio-pro/6.2.md
  content/releasenotes/studio-pro/6.3.md
  content/releasenotes/studio-pro/6.4.md
  content/releasenotes/studio-pro/6.5.md
  content/releasenotes/studio-pro/6.6.md
  content/releasenotes/studio-pro/6.7.md
  content/releasenotes/studio-pro/6.8.md
  content/releasenotes/studio-pro/6.9.md
  content/releasenotes/studio-pro/7.0.md
  content/releasenotes/studio-pro/7.1.md
  content/releasenotes/studio-pro/7.10.md
  content/releasenotes/studio-pro/7.11.md
  content/releasenotes/studio-pro/7.12.md
  content/releasenotes/studio-pro/7.13.md
  content/releasenotes/studio-pro/7.14.md
  content/releasenotes/studio-pro/7.15.md
  content/releasenotes/studio-pro/7.16.md
  content/releasenotes/studio-pro/7.17.md
  content/releasenotes/studio-pro/7.18.md
  content/releasenotes/studio-pro/7.19.md
  content/releasenotes/studio-pro/7.2.md
  content/releasenotes/studio-pro/7.20.md
  content/releasenotes/studio-pro/7.21.md
  content/releasenotes/studio-pro/7.22.md
  content/releasenotes/studio-pro/7.23.md
  content/releasenotes/studio-pro/7.3.md
  content/releasenotes/studio-pro/7.4.md
  content/releasenotes/studio-pro/7.5.md
  content/releasenotes/studio-pro/7.6.md
  content/releasenotes/studio-pro/7.7.md
  content/releasenotes/studio-pro/7.8.md
  content/releasenotes/studio-pro/7.9.md
  content/releasenotes/studio-pro/8.0.md
  content/releasenotes/studio-pro/8.1.md
  content/releasenotes/studio-pro/8.2.md
  content/releasenotes/studio-pro/8.3.md
  content/releasenotes/studio-pro/8.4.md
  content/releasenotes/studio-pro/8.5.md
  content/releasenotes/studio-pro/8.6.md
  content/releasenotes/studio-pro/8.7.md
  content/releasenotes/studio-pro/8.8.md
Labels: Future release

#2375 Document parameterized actions of db-connector
  content/appstore/connectors/database-connector.md
Labels: Future release

#2270 8 April 2020 - Remove MxID2 API documentation
  content/apidocs-mxsdk/apidocs/attachments/18449455/18582264.png
  content/apidocs-mxsdk/apidocs/index.md
  content/apidocs-mxsdk/apidocs/invite-api.md
  content/apidocs-mxsdk/apidocs/permissions-api.md
  content/apidocs-mxsdk/apidocs/profile-api.md
  content/apidocs-mxsdk/apidocs/single-sign-on-api.md
Labels: Future release

#2392 Update exposed libraries for Mendix 8.9
  content/apidocs-mxsdk/apidocs/client-apis-for-pluggable-widgets.md
Labels: 8.9.0

#2388 8.8.1 RN
  content/releasenotes/studio-pro/8.8.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2399 remove appbar2
  _assets/js/main.js
Labels: Internal WIP

#2389 8.6.3 RN
  content/releasenotes/studio-pro/8.6.md
Labels: Future release

#2401 Update for SSO
  content/developerportal/collaborate/attachments/feedback/app-store.png
  content/developerportal/collaborate/use-feedback-widget.md
Labels: Internal WIP

#2398 Improve Runtime Description
  content/refguide/attachments/runtime/mendix-client.png
  content/refguide/attachments/runtime/runtime-deployment.png
  content/refguide/attachments/runtime/runtime-diagrams.pptx
  content/refguide/attachments/runtime/runtime-overview.png
  content/refguide/attachments/runtime/runtime-server.png
  content/refguide/mendix-client.md
  content/refguide/runtime-deployment.md
  content/refguide/runtime-server.md
  content/refguide/runtime.md
Labels: Needs technical verification

#2397 Fieldset widget documentation
  content/appstore/widgets/fieldset.md
Labels: Internal WIP

#2416 Modified SAP OData Connector Document
  content/partners/sap/sap-odata-connector.md
Labels: Needs language review, Needs technical verification

#2422 How To Use the Excel Exporter
  content/howto/integration/attachments/18448732/18581902.png
  content/howto/integration/attachments/18448732/java-action.png
  content/howto/integration/attachments/using-the-excel-exporter/18581165.png
  content/howto/integration/attachments/using-the-excel-exporter/18581166.png
  content/howto/integration/attachments/using-the-excel-exporter/18581900.png
  content/howto/integration/attachments/using-the-excel-exporter/18581901.png
  content/howto/integration/attachments/using-the-excel-exporter/18581903.png
  content/howto/integration/attachments/using-the-excel-exporter/18581904.png
  content/howto/integration/attachments/using-the-excel-exporter/18581905.png
  content/howto/integration/attachments/using-the-excel-exporter/18581906.png
  content/howto/integration/attachments/using-the-excel-exporter/18581907.png
  content/howto/integration/attachments/using-the-excel-exporter/18581908.png
  content/howto/integration/attachments/using-the-excel-exporter/18581909.png
  content/howto/integration/attachments/using-the-excel-exporter/18581910.png
  content/howto/integration/attachments/using-the-excel-exporter/exporter.png
  content/howto/integration/attachments/using-the-excel-exporter/java-action.png
  content/howto/integration/attachments/using-the-excel-exporter/microflow-for-generate.png
  content/howto/integration/attachments/using-the-excel-exporter/new-excel-template.png
  content/howto/integration/attachments/using-the-excel-exporter/retrieve-template.png
  content/howto/integration/attachments/using-the-excel-exporter/security.png
  content/howto/integration/using-the-excel-exporter.md
Labels: Internal WIP

#2343 Cloud Security: Update and remove information
  _assets/mappings/redirect.js
  content/developerportal/deploy/index.md
  content/developerportal/deploy/java-in-the-cloud.md
  content/developerportal/deploy/migrating-to-v4.md
  content/refguide/java-programming.md
  content/refguide6/configuration.md
  content/refguide6/java-programming.md
  content/refguide7/configuration.md
  content/refguide7/java-programming.md
Labels: Needs language review

#2429 Add release notes model SDK and metamodel for release 8.9
  content/releasenotes/sdk/metamodel-8.9.md
  content/releasenotes/sdk/metamodel-8.md
  content/releasenotes/sdk/model-sdk-4.md
Labels: 8.9.0

#2373 Update dependencies in docs for 8.9+
  content/howto/general/install.md
  content/refguide/system-requirements.md
Labels: 8.9.0

#2410 Add toggle for 8.9
  content/refguide/attachments/page/conditional-visibility.jpg
  content/refguide/page.md
Labels: 8.9.0

#2421 Update button for 8.9
  content/refguide/attachments/collaborative-development/history.png
  content/refguide/attachments/history-dialog/history-dialog.png
  content/refguide/collaborative-development.md
  content/refguide/history-dialog.md
Labels: 8.9.0

#2423 Add MiN 2.0.0 release notes
  content/releasenotes/mobile/make-it-native-app.md
Labels: 8.9.0

#2396 Document dataSource attribute for action property [8.9]
  content/apidocs-mxsdk/apidocs/property-types-pluggable-widgets.md
Labels: 8.9.0

#2415 Add docs for sync to device activity
  content/refguide/sync-to-device.md
Labels: 8.9.0
