Repository mendix/docs, pull requests merged in 2020-01, with the labels that each got.

#2199 Warn that Period is being deprecated
  content/refguide/date-range-field.md
Labels: Needs technical review

#2201 Update deploying-native-app.md
  content/howto/mobile/deploying-native-app.md
Labels: Waiting for CLA

#2203 Draft KI
  content/releasenotes/studio-pro/8.5.md
Labels: Internal WIP

#2172 How-to create custom developer apps
  content/howto/mobile/attachments/how-to-devapps/github-branch-switching.png
  content/howto/mobile/attachments/how-to-devapps/github-download-branch.png
  content/howto/mobile/attachments/how-to-devapps/ios-folder.png
  content/howto/mobile/attachments/how-to-devapps/xcode-target-selection.png
  content/howto/mobile/how-to-devapps.md
Labels: 8.6.0

#2215 Known issue on MySQL 8.0.19 and unique validation rules
  content/releasenotes/studio-pro/8.5.md
Labels: Internal WIP

#2210 Datadog - Add metrics and more explanation
  content/developerportal/operate/datadog-metrics.md
Labels: Internal WIP

#2218 Add information on CSP [SC-314]
  content/developerportal/deploy/security-checklist-for-your-on-premises-installation.md
Labels: Internal WIP

#2214 Correct offline data sources
  content/refguide/data-sources.md
Labels: Needs language review

#2217 Add 8.5.1 draft
  content/releasenotes/studio-pro/8.5.md
Labels: Future release

#2238 Add a remark about the US-only implementation
  content/developerportal/operate/datadog-metrics.md
Labels: Needs Support technical verification

#2220 Draft to resolve feedback item 480864
  content/howto/monitoring-troubleshooting/log-levels.md
Labels: Internal WIP
