Repository mendix/docs, pull requests merged in 2020-07, with the labels that each got.

#2547 Release documentation metamodel & Model SDK 8.11.0
  content/releasenotes/sdk/metamodel-8.11.md
  content/releasenotes/sdk/metamodel-8.md
  content/releasenotes/sdk/model-sdk-4.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 8.11

#2550 Add release notes for the unused java heap fixes
  content/releasenotes/developer-portal/deployment.md
Labels: Future release

#2548 8.10.3 RN
  content/releasenotes/studio-pro/8.10.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2558 Update committing-objects.md
  content/refguide/committing-objects.md
Labels: Verify after merge

#2541 8.11 RN
  content/releasenotes/studio-pro/8.11.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 8.11

#2561 OData expand
  content/refguide/odata-query-options.md
Labels: 8.11

#2524 Add docs for new Preferences setting in 8.11
  content/refguide/preferences-dialog.md
Labels: 8.11

#2500 Added SameSiteCookies custom setting.
  content/refguide/custom-settings.md
Labels: 8.11

#2549 Document change of User Role for Admin(MxAdmin) account
  content/developerportal/deploy/environments-details.md
  content/refguide/administrator.md
Labels: Needs technical verification

#2491 Update Dropdown for 8.11 release
  content/refguide/native-styling-refguide.md
Labels: 8.11

#2497 [DAT-2081] Make string-functions perform case-insensitively on SapHana
  content/refguide/case-sensitive-database-behavior.md
  content/refguide/saphana.md
Labels: 8.11

#2566 Release Notes - Mendix Cloud 8 Jul 2020
  content/releasenotes/developer-portal/deployment.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2565 Just correcting a reverted buttoncolor description
  content/howto/mobile/how-to-use-native-styling.md
Labels: Needs technical verification

#2552 Add table of plans to Mendix Deployment page - 2nd attempt
  content/developerportal/deploy/mendix-cloud-deploy.md
Labels: Internal WIP, Needs Support verification

#2578 Release notes Sprintr 10.5.0
  content/releasenotes/developer-portal/index.md
Labels: Future release

#2579 Release Mendix for Private Cloud Operator 1.3.0
  content/developerportal/deploy/attachments/private-cloud-cluster/image18.png
  content/developerportal/deploy/attachments/private-cloud-cluster/image19.png
  content/developerportal/deploy/attachments/private-cloud-cluster/image20.png
  content/developerportal/deploy/private-cloud-cluster.md
  content/developerportal/deploy/private-cloud-operator.md
  content/developerportal/deploy/private-cloud-supported-environments.md
  content/developerportal/deploy/private-cloud-upgrade-guide.md
  content/releasenotes/developer-portal/deployment.md
Labels: Future release, Needs language review

#2586 Add database timeout settings to custom settings page
  content/refguide/custom-settings.md
  content/refguide7/custom-settings.md
Labels: Needs language review

#2593 Host feedback locally
  _assets/js/sprintrfeedback.js
  _assets/styles/_sass/_feedback.scss
  _assets/styles/main.scss
  content/appstore/widgets/mendix-feedback.md
  static/public/images/feedback-new.png
  themes/mendix/layouts/partials/resource_loading.html
  themes/mendix/layouts/partials/sprintrfeedback.html
Labels: Needs technical verification

#2592 22 July - Deployment Release Note
  content/releasenotes/developer-portal/deployment.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2594 Add 8.11.1 release notes
  content/releasenotes/studio-pro/8.11.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2600 Release documentation for metamodel & Model SDK 8.12.0
  content/releasenotes/sdk/metamodel-8.12.md
  content/releasenotes/sdk/metamodel-8.md
  content/releasenotes/sdk/model-sdk-4.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 8.12

#2604 Add 7.23.15 release notes
  content/refguide7/system-requirements.md
  content/releasenotes/studio-pro/7.23.md
Labels: Future release

#2601 Add 8.6.5 release notes
  content/releasenotes/studio-pro/8.6.md
Labels: Future release

#2617 Sprintr release 10.5.1
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2607 Add 8.12.0 release notes
  content/releasenotes/studio-pro/8.12.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 8.12

#2556 New setting com.mendix.storage.s3.UseCACertificates
  content/refguide/custom-settings.md
Labels: 8.12

#2572 Fix docs for Disabled During Action on buttons
  content/refguide/button-properties.md
Labels: 8.12

#2573 8.12 release: add Disabled During Action to On Click events
  content/refguide/on-click-event.md
Labels: 8.12

#2570 Introducing S3 storage setting ForceGlobalBucketAccessEnabled
  content/refguide/custom-settings.md
Labels: 8.12

#2587 Update a11y attributes for widgets
  content/refguide/attachments/container-widgets/container-properties.png
  content/refguide/attachments/text-box/text-box-properties.png
  content/refguide/common-widget-properties.md
  content/refguide/container.md
  content/refguide/menu.md
  content/refguide/text-box.md
Labels: 8.12

#2576 8.12 release: add application icon property
  content/refguide/attachments/navigation/navigation-profile-properties.png
  content/refguide/navigation.md
Labels: 8.12

#2590 Invalid XML characters in published OData services
  content/refguide/published-odata-services.md
Labels: 8.12
