Repository mendix/docs, pull requests merged in 2020-05, with the labels that each got.

#2409 May 1st: Whitelist for Mendix Dedicated IPs
  content/developerportal/deploy/attachments/environments-details/network1.png
  content/developerportal/deploy/attachments/environments-details/whitelist.png
  content/developerportal/deploy/environments-details.md
  content/releasenotes/developer-portal/deployment.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2443 7.23.14 RN
  content/releasenotes/app-store/index.md
  content/releasenotes/studio-pro/7.23.md
Labels: Future release

#2433 7.23.14 - Add/db versions to lts
  content/refguide7/system-requirements.md
Labels: Future release

#2446 Update description of associations via feedback item
  content/refguide/associations.md
  content/refguide/domain-model.md
  content/studio/domain-models-association-properties.md
Labels: Internal WIP

#2437 Release notes for AppStore Release 7.7.0
  content/releasenotes/app-store/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2439 Update stories 2.0 beta
  content/developerportal/collaborate/stories.md
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2448 Add 8.6.4 Release Notes
  content/releasenotes/studio-pro/8.0.md
  content/releasenotes/studio-pro/8.1.md
  content/releasenotes/studio-pro/8.2.md
  content/releasenotes/studio-pro/8.3.md
  content/releasenotes/studio-pro/8.4.md
  content/releasenotes/studio-pro/8.5.md
  content/releasenotes/studio-pro/8.6.md
Labels: Future release

#2452 Added warning on long-running microflows.
  content/refguide6/custom-settings.md
Labels: Future release

#2454 Move SSO to ASG
  content/appstore/modules/mendix-sso.md
Labels: Internal WIP

#2467 Mendix Log Node Descriptions
  content/refguide/log-message.md
  content/refguide/logging.md
Labels: Internal WIP

#2483 typo
  content/apidocs-mxsdk/apidocs/deploy-api.md
Labels: Needs technical verification

#2490 Sprintr 10.2.0. Release 27.05.2020
  content/developerportal/collaborate/attachments/stories/delete-linked-story.png
  content/developerportal/collaborate/attachments/stories/delete-selection.png
  content/developerportal/collaborate/stories.md
  content/releasenotes/developer-portal/index.md
Labels: Future release

#2484 Add 8.10 RN
  content/releasenotes/app-store/index.md
  content/releasenotes/studio-pro/8.0.md
  content/releasenotes/studio-pro/8.1.md
  content/releasenotes/studio-pro/8.10.md
  content/releasenotes/studio-pro/8.2.md
  content/releasenotes/studio-pro/8.3.md
  content/releasenotes/studio-pro/8.4.md
  content/releasenotes/studio-pro/8.5.md
  content/releasenotes/studio-pro/8.6.md
  content/releasenotes/studio-pro/8.7.md
  content/releasenotes/studio-pro/8.8.md
  content/releasenotes/studio-pro/8.9.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 8.10.0

#2469 Add documentation for `mx create-project` command
  content/refguide/mx-command-line-tool.md
Labels: 8.10.0

#2386 Add mention of long paths in microflows
  content/refguide/expressions.md
Labels: 8.10.0

#2475 Added documentation for the new sync config option
  content/refguide/navigation.md
  content/refguide/offline-first.md
  content/refguide/sync-to-device.md
Labels: 8.10.0

#2488 Documented how to set contants & schedule events.
  content/developerportal/deploy/attachments/private-cloud-operator/constant-name.png
  content/developerportal/deploy/private-cloud-operator.md
Labels: Needs technical verification

#2477 [DAT-2105] Improve public documentation on db case sensitivity
  content/developerportal/deploy/setting-up-a-new-sql-server-database.md
  content/refguide/case-sensitive-database-behavior.md
  content/refguide/saphana.md
Labels: Needs technical verification
