Repository mendix/docs, pull requests merged in 2020-10, with the labels that each got.

#2763 8.14 KI
  content/releasenotes/studio-pro/8.14.md
Labels: Internal WIP

#2764 8.14.1 RN
  content/releasenotes/studio-pro/8.14.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2771 Fixes for: Run Mendix on Kubernetes
  content/developerportal/deploy/run-mendix-on-kubernetes.md
Labels: Needs language review

#2743 Remove Documentation on using id() in XPath
  content/refguide/xpath-id.md
  content/refguide/xpath-query-functions.md
  content/refguide/xpath.md
Labels: Needs technical verification

#2785 Add known issue to 8.13
  content/releasenotes/studio-pro/8.13.md
Labels: Internal WIP

#2786 Add fix of 8.13 KI in 8.14
  content/releasenotes/studio-pro/8.14.md
Labels: Internal WIP

#2787 Sprintr 10.8.1 Releasenotes
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#2781 8.13.2 RN draft
  content/releasenotes/studio-pro/8.13.md
Labels: Future release

#2779 7.23.17 RN draft
  content/releasenotes/studio-pro/7.23.md
Labels: Future release

#2780 8.12.2 RN draft
  content/releasenotes/studio-pro/8.12.md
Labels: Future release

#2810 Known issue deleting a branch in 8.14
  content/releasenotes/studio-pro/8.14.md
Labels: Needs language review

#2782 8.6.7 RN draft
  content/releasenotes/studio-pro/8.6.md
Labels: Future release

#2815 Warn about spamhouse.org and Mendix mail server on V3
  content/developerportal/deploy/sending-email.md
Labels: Needs Support Tech Lead verification

#2817 20 October SAP Release Note
  content/releasenotes/developer-portal/deployment.md
Labels: Update RN/Featured date or other

#2825 Deployment Release Notes - 22 October
  content/developerportal/deploy/attachments/node-permissions/download-to-csv.png
  content/developerportal/deploy/attachments/node-permissions/permissions-csv.png
  content/developerportal/deploy/node-permissions.md
  content/developerportal/operate/attachments/backups/backup-details.png
  content/developerportal/operate/attachments/restore-a-backup/restore-backup.png
  content/developerportal/operate/backups.md
  content/developerportal/operate/restore-backup.md
  content/releasenotes/developer-portal/deployment.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release, Update RN/Featured date or other

#2827 22 October - release notes for alerts migration
  content/releasenotes/developer-portal/deployment.md
Labels: Future release

#2753 Tabbed UI for consumed web service
  content/howto/integration/attachments/18448738/18582084.png
  content/howto/integration/attachments/18448738/18582085.png
  content/howto/integration/attachments/18448738/18582087.png
  content/howto/integration/attachments/18448738/create-microflow.png
  content/howto/integration/attachments/18448738/wsdl-source.png
  content/howto/integration/attachments/consume-complex/18581779.png
  content/howto/integration/attachments/consume-complex/enter-wsdl-url.png
  content/howto/integration/consume-a-complex-web-service.md
  content/howto/integration/consume-a-simple-web-service.md
  content/refguide/attachments/16713734/16843949.png
  content/refguide/consumed-web-service.md
Labels: 8.15

#2831 pr2753-joostverhoog:consumed-web-service-tabbed
  content/howto/integration/attachments/18448738/18582084.png
  content/howto/integration/attachments/18448738/18582085.png
  content/howto/integration/attachments/18448738/18582087.png
  content/howto/integration/attachments/18448738/create-microflow.png
  content/howto/integration/attachments/18448738/wsdl-source.png
  content/howto/integration/attachments/consume-complex/18581779.png
  content/howto/integration/attachments/consume-complex/enter-wsdl-url.png
  content/howto/integration/consume-a-complex-web-service.md
  content/howto/integration/consume-a-simple-web-service.md
  content/refguide/attachments/16713734/16843949.png
  content/refguide/consumed-odata-services.md
  content/refguide/consumed-web-service.md
Labels: 8.15

#2834 Travis Migration Test
  content/developerportal/deploy/private-cloud-cluster.md
Labels: Internal WIP

#2836 8.12.3 RN
  content/releasenotes/studio-pro/8.12.md
Labels: Future release

#2824 8.15 RN
  content/releasenotes/studio-pro/8.14.md
  content/releasenotes/studio-pro/8.15.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 8.15

#2732 Update documentation for new Mendix expression functions: epochToDateTime, dateTimeToEpoch, calendarMonthsBetween and calendarYearsBetween
  content/refguide/between-date-function-calls.md
  content/refguide/expressions.md
  content/refguide/parse-and-format-date-function-calls.md
Labels: 8.15

#2838 Improve deep linking docs for Native Mobile App Builder release
  content/howto/mobile/attachments/native-deep-link/capability-menu-option.png
  content/howto/mobile/attachments/native-deep-link/deep-link-input-field.png
  content/howto/mobile/attachments/native-deep-link/launch-native-mobile-app-builder.png
  content/howto/mobile/native-deep-link.md
Labels: 8.15

#2829 Native mobile custom fonts how-to
  content/howto/mobile/attachments/nbui/advanced-fonts-snippet.png
  content/howto/mobile/attachments/nbui/advanced-fonts.png
  content/howto/mobile/attachments/nbui/advanced-fonts2.png
  content/howto/mobile/attachments/nbui/advanced-fonts3.png
  content/howto/mobile/attachments/nbui/advanced-fonts4.png
  content/howto/mobile/attachments/nbui/app-builds-for-distribution-download-last-build.png
  content/howto/mobile/attachments/nbui/app-builds-for-distribution.png
  content/howto/mobile/attachments/nbui/build-custom-dev-app.png
  content/howto/mobile/attachments/nbui/build-release-app-appcenter-organization.png
  content/howto/mobile/attachments/nbui/build-release-app-build-done-android.png
  content/howto/mobile/attachments/nbui/build-release-app-build-done-both.png
  content/howto/mobile/attachments/nbui/build-release-app-build-step1.png
  content/howto/mobile/attachments/nbui/build-release-app-build-step2.png
  content/howto/mobile/attachments/nbui/build-release-app-filled-version-runtime-url.png
  content/howto/mobile/attachments/nbui/build-release-app-github-repository.png
  content/howto/mobile/attachments/nbui/build-release-app.png
  content/howto/mobile/attachments/nbui/custom-fonts-android-repo.png
  content/howto/mobile/attachments/nbui/custom-fonts-ios-repo.png
  content/howto/mobile/attachments/nbui/custom-fonts-project-explorer-filled.png
  content/howto/mobile/attachments/nbui/custom-fonts-xcode-dialog.png
  content/howto/mobile/attachments/nbui/custom-style.png
  content/howto/mobile/attachments/nbui/custom-variables.png
  content/howto/mobile/attachments/nbui/home-screen.png
  content/howto/mobile/attachments/nbui/postscript-name.png
  content/howto/mobile/attachments/nbui/signing-android.png
  content/howto/mobile/attachments/nbui/signing-ios.png
  content/howto/mobile/attachments/nbui/start-nbui.png
  content/howto/mobile/attachments/nbui/wizard-app-details.png
  content/howto/mobile/attachments/nbui/wizard-fonts-filled.png
  content/howto/mobile/attachments/nbui/wizard-fonts.png
  content/howto/mobile/attachments/nbui/wizard-icons.png
  content/howto/mobile/attachments/nbui/wizard-splashscreens.png
  content/howto/mobile/attachments/nbui/wizard-tokens.png
  content/howto/mobile/attachments/nbui/xcode-open-infoplist.png
  content/howto/mobile/attachments/nbui/xcode-plist-fonts-filled.png
  content/howto/mobile/attachments/nbui/xcode-plist-fonts.png
  content/howto/mobile/build-native-apps.md
  content/howto/mobile/native-custom-fonts.md
Labels: 8.15

#2762 Add release notes for Mendix Native Mobile Builder
  content/releasenotes/mobile/mendix-native-mobile-builder.md
Labels: 8.15

#2833 Tabbed UI for consumed web service (original PR 2753)
  content/howto/integration/attachments/18448738/18582084.png
  content/howto/integration/attachments/18448738/18582085.png
  content/howto/integration/attachments/18448738/18582087.png
  content/howto/integration/attachments/18448738/call-web-serv-SOAP-resp.png
  content/howto/integration/attachments/18448738/create-microflow.png
  content/howto/integration/attachments/18448738/wsdl-source.png
  content/howto/integration/attachments/consume-complex/18581779.png
  content/howto/integration/attachments/consume-complex/enter-wsdl-url.png
  content/howto/integration/consume-a-complex-web-service.md
  content/howto/integration/consume-a-simple-web-service.md
  content/refguide/attachments/16713734/16843949.png
  content/refguide/consumed-odata-services.md
  content/refguide/consumed-web-service.md
Labels: 8.15

#2728 Add necessary documentation for on Focus styles (8.15)
  content/refguide/native-styling-refguide.md
Labels: 8.15

#2729 Introduce new on change behaviour documentation (8.15)
  content/refguide/text-box.md
Labels: 8.15

#2755 Add web widget popup menu
  content/appstore/widgets/popup-menu.md
Labels: Future release, Verify after merge

#2851 Add 1.4 user facing release items
  content/releasenotes/data-hub/index.md
Labels: Future release
