Repository mendix/docs, pull requests merged in 2021-10, with the labels that each got.

#3730 Update deep-link.md
  content/appstore/modules/deep-link.md
Labels: Needs technical verification

#3731 Weekday is dependent on database
  content/refguide/xpath-weekday-from-datetime.md
Labels: Needs technical verification

#3722 Feature/mds 329132 replace pump asset example app
  content/developerportal/deploy/deploying-to-mindsphere.md
  content/partners/siemens/attachments/mindsphere-development-considerations/mindsphere-icons.png
  content/partners/siemens/attachments/mindsphere-development-considerations/svg-icon.png
  content/partners/siemens/attachments/mindsphere-example-app/app-store-download-project.png
  content/partners/siemens/attachments/mindsphere-example-app/app-store-download.png
  content/partners/siemens/attachments/mindsphere-example-app/app-store-icon.png
  content/partners/siemens/attachments/mindsphere-example-app/app-store-import-app-package.png
  content/partners/siemens/attachments/mindsphere-example-app/app-store-search.png
  content/partners/siemens/attachments/mindsphere-example-app/autoreg-choose-app-registration.png
  content/partners/siemens/attachments/mindsphere-example-app/autoreg-name-description.png
  content/partners/siemens/attachments/mindsphere-example-app/autoreg-publish.png
  content/partners/siemens/attachments/mindsphere-example-app/autoreg-registration-completed.png
  content/partners/siemens/attachments/mindsphere-example-app/autoreg-view-app.png
  content/partners/siemens/attachments/mindsphere-example-app/autoreg-web-key.png
  content/partners/siemens/attachments/mindsphere-example-app/devcockpit-app-details.png
  content/partners/siemens/attachments/mindsphere-example-app/devcockpit-app-roles.png
  content/partners/siemens/attachments/mindsphere-example-app/devcockpit-app-scopes.png
  content/partners/siemens/attachments/mindsphere-example-app/devcockpit-mdsp-api-roles.png
  content/partners/siemens/attachments/mindsphere-example-app/image1.png
  content/partners/siemens/attachments/mindsphere-example-app/image10.png
  content/partners/siemens/attachments/mindsphere-example-app/image11.png
  content/partners/siemens/attachments/mindsphere-example-app/image12.png
  content/partners/siemens/attachments/mindsphere-example-app/image13.png
  content/partners/siemens/attachments/mindsphere-example-app/image14.png
  content/partners/siemens/attachments/mindsphere-example-app/image15.png
  content/partners/siemens/attachments/mindsphere-example-app/image16.png
  content/partners/siemens/attachments/mindsphere-example-app/image2.png
  content/partners/siemens/attachments/mindsphere-example-app/image3.png
  content/partners/siemens/attachments/mindsphere-example-app/image4.png
  content/partners/siemens/attachments/mindsphere-example-app/image5.png
  content/partners/siemens/attachments/mindsphere-example-app/image7.png
  content/partners/siemens/attachments/mindsphere-example-app/image8.png
  content/partners/siemens/attachments/mindsphere-example-app/image9.png
  content/partners/siemens/attachments/mindsphere-example-app/oi-home.png
  content/partners/siemens/attachments/mindsphere-module-details/image10.png
  content/partners/siemens/attachments/mindsphere-module-details/image2.png
  content/partners/siemens/attachments/mindsphere-module-details/image3.png
  content/partners/siemens/mendix-on-mindsphere.md
  content/partners/siemens/mindsphere-app-service.md
  content/partners/siemens/mindsphere-asset-management-connector.md
  content/partners/siemens/mindsphere-development-considerations.md
  content/partners/siemens/mindsphere-example-app.md
  content/partners/siemens/mindsphere-module-details.md
Labels: Future release, Internal WIP

#3755 Update screenshots for 9.6 redesign
  .gitignore
  content/appstore/connectors/attachments/database/database-connector-in-toolbox.png
  content/appstore/connectors/attachments/ibm-watson-connector/connectorlist.png
  content/appstore/connectors/attachments/opc-ua/opc-ua-connector-module.png
  content/appstore/connectors/attachments/opc-ua/opc-ua-toolbox.png
  content/appstore/connectors/database-connector.md
  content/appstore/connectors/opc-ua.md
  content/appstore/general/app-store-content.md
  content/appstore/general/attachments/app-store-content/add-widget.png
  content/appstore/general/attachments/app-store-content/email-template-app-explorer.png
  content/appstore/general/attachments/app-store-content/select-attribute.png
  content/appstore/general/attachments/app-store-content/select-widget.png
  content/appstore/general/attachments/app-store-content/toolbar.png
  content/appstore/modules/attachments/user-migration-module/image1.png
  content/appstore/modules/attachments/user-migration-module/start-migration-wizard-microflow.png
  content/appstore/modules/attachments/user-migration-module/user-migration-step1.png
  content/appstore/modules/attachments/user-migration-module/user-migration-step2.png
  content/appstore/modules/attachments/user-migration-module/user-migration-step3.png
  content/appstore/modules/attachments/user-migration-module/user-migration-step4.png
  content/appstore/modules/user-migration-module.md
  content/developerportal/community-tools/attachments/documentation-writing-guidelines/image_examples.png
  content/developerportal/deploy/attachments/qianfan-sso/image37.png
  content/developerportal/deploy/attachments/qianfan-sso/image38.png
  content/developerportal/deploy/attachments/qianfan-sso/image39.png
  content/developerportal/deploy/attachments/qianfan-sso/image40.png
  content/developerportal/deploy/attachments/qianfan-sso/image41.png
  content/developerportal/deploy/attachments/qianfan-sso/image43.png
  content/developerportal/deploy/attachments/qianfan-sso/image44.png
  content/developerportal/deploy/attachments/qianfan-sso/image45.png
  content/developerportal/deploy/attachments/qianfan-sso/image46.png
  content/developerportal/deploy/attachments/qianfan-sso/image47.png
  content/developerportal/deploy/attachments/qianfan-sso/image48.png
  content/developerportal/deploy/attachments/qianfan-sso/security-production.png
  content/developerportal/deploy/qianfan-sso.md
  content/refguide/attachments/domain-model/access-rule-discount-read.png
Labels: Internal WIP
