Repository mendix/docs, pull requests merged in 2021-12, with the labels that each got.

#3927 Datahub/release 2.10
  content/data-hub/data-hub-catalog/curate.md
  content/data-hub/data-hub-catalog/register-data.md
  content/developerportal/control-center/attachments/data-hub-admin/Admin-Settings.PNG
  content/developerportal/control-center/data-hub-admin.md
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release, Post-publish edit images

#3924 9.6.3 RN
  content/releasenotes/studio-pro/9.6.md
Labels: 9.6.3

#3926 Remove the limitation of associated attributes in DB2 and SAP HANA in Mx 9 MTS version.
  content/refguide/db2.md
  content/refguide/saphana.md
Labels: Verify after merge, 9.6.3

#3939 Known issue added
  content/releasenotes/studio-pro/9.6.md
  content/releasenotes/studio-pro/9.8.md
Labels: Needs R&D technical verification

#3930 Release notes for Operator 2.2.0.
  content/releasenotes/developer-portal/mendix-for-private-cloud.md
Labels: Update RN & featured date

#3938 9.8.1 RN
  content/releasenotes/studio-pro/9.6.md
  content/releasenotes/studio-pro/9.8.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3950 Update 9.8.md
  content/releasenotes/studio-pro/9.8.md
Labels: Needs R&D technical verification

#3954 DataHub Catalog Release 2.11.0
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3953 added release note for private cloud portal
  content/releasenotes/developer-portal/mendix-for-private-cloud.md
Labels: Update RN & featured date

#3963 9.8.2 RN
  content/releasenotes/studio-pro/9.8.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3967 Clarify BYOIDP configuration details
  content/developerportal/control-center/index.md
  content/developerportal/control-center/set-up-sso-byoidp.md
Labels: Needs R&D technical verification, Internal WIP

#3975 Added release notes for DH release 2.12.0
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3973 Marketplace release
  content/appstore/general/attachments/share-app-store-content/general.jpg
  content/appstore/general/attachments/share-app-store-content/general.png
  content/appstore/general/attachments/share-app-store-content/publish.png
  content/appstore/general/share-app-store-content.md
  content/releasenotes/app-store/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3979 7.23.27 RN
  content/releasenotes/studio-pro/7.23.md
Labels: Future release

#3970 9.9 RN
  content/releasenotes/studio-pro/9.9.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Needs R&D technical verification, 9.9.0

#3948 Document cleanup of system events (Mendix 9.9.0)
  content/refguide/custom-settings.md
  content/refguide/scheduled-events.md
  content/refguide/task-queue.md
Labels: 9.9.0

#3928 Remove limit on total number of task queue threads
  content/refguide/task-queue.md
Labels: 9.9.0

#3876 [WIP] Add support for PostgreSQL 14. #DAT-2753
  content/refguide/system-requirements.md
  content/refguide7/system-requirements.md
  content/refguide8/system-requirements.md
Labels: 9.9.0

#3889 Add MXP010 documentation to Performance Best Practices page (needs to be published with respect to the Studio Pro 9.9 release - Dec 21, 2021)
  content/refguide/performance-best-practices.md
Labels: 9.9.0

#3897 Add Best Practice MXP011 - Nested List Views [SP 9.9]
  content/refguide/performance-best-practices.md
Labels: 9.9.0

#3986 Add docs about Styling Editor
  content/howto/front-end/attachments/customize-styling/styling-editor-settings.png
  content/howto/front-end/customize-styling-new.md
  content/refguide/attachments/preferences-dialog/preferences.jpg
  content/refguide/attachments/preferences-dialog/preferences.png
  content/refguide/preferences-dialog.md
Labels: 9.9.0

#3900 Add automatic retry on task queue to Java API
  content/refguide/task-queue.md
Labels: 9.9.0

#3977 8.18.14 RN
  content/releasenotes/studio-pro/8.18.md
Labels: 8.18.14

#3978 9.6.4 RN
  content/releasenotes/studio-pro/9.6.md
Labels: 9.6.4

#3943 Update some country names
  content/refguide/language-settings.md
Labels: 9.6.4

#3996 Added release notes for 2.12.1 hotfix
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3992 7.23.28 RN
  content/releasenotes/studio-pro/7.23.md
Labels: Future release

#4000 Best practice for storing passwords
  content/howto8/general/dev-best-practices.md
Labels: Needs R&D technical verification

#3995 9.9.1 RN
  content/releasenotes/studio-pro/9.9.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release, Needs R&D technical verification

#3994 9.6.5 RN
  content/releasenotes/studio-pro/9.6.md
Labels: Future release, Needs R&D technical verification

#3993 8.18.15 RN
  content/releasenotes/studio-pro/8.18.md
Labels: Future release

#4012 Update Configure Parallels document
  content/howto/general/attachments/using-mendix-studio-pro-on-a-mac/ip-in-dev-app.png
  content/howto/general/using-mendix-studio-pro-on-a-mac.md
  content/howto8/general/attachments/using-mendix-studio-pro-on-a-mac/ip-in-dev-app.png
  content/howto8/general/using-mendix-studio-pro-on-a-mac.md
  content/refguide/system-requirements.md
  content/refguide8/system-requirements.md
Labels: Future release, Internal WIP

#4017 Release notes Sprintr 2021.12.23
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#4013 Added release notes for Catalog release-2.13.0
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3893 Implement redesigned highlighting in screenshots
  content/refguide/attachments/input-reference-set-selector/16844007.jpg
  content/refguide/attachments/input-reference-set-selector/domain-model-owner-both.png
  content/refguide/attachments/input-reference-set-selector/domain-model-owner-default.png
  content/refguide/attachments/language/reload-with-state.png
  content/refguide/attachments/reference-selector/generate-select-page.png
  content/refguide/attachments/reference-selector/orderline-constrained-by.png
  content/refguide/attachments/reference-set-selector/domain-model-owner-both.png
  content/refguide/attachments/reference-set-selector/domain-model-owner-default.png
  content/refguide/attachments/reference-set-selector/reference-set-selector.png
  content/refguide/attachments/reference-set-selector/sort-bar.png
  content/refguide8/attachments/input-reference-set-selector/16844007.jpg
Labels: Internal WIP

#4028 9.6.6 Studio Pro release notes
  content/releasenotes/studio-pro/9.6.md
Labels: Future release

#4031 Release notes - Data Hub 2.14 (CAT-2136, REG-67)
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release
