Repository mendix/docs, pull requests merged in 2021-03, with the labels that each got.

#3087 Add information about ScheduledEventInformation entity.
  content/apidocs-mxsdk/apidocs/runtime-api.md
  content/refguide/scheduled-events.md
Labels: Needs technical verification

#3062 DEP Release 3 March
  content/apidocs-mxsdk/apidocs/deploy-api.md
  content/developerportal/deploy/attachments/environments-details/actions-v4.png
  content/developerportal/deploy/attachments/environments-details/clear-environment.png
  content/developerportal/deploy/environments-details.md
  content/releasenotes/developer-portal/deployment.md
  content/releasenotes/developer-portal/mendix-cloud.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release, Needs technical verification, Update RN/featured date

#3065 7.14.2 RN
  content/releasenotes/studio-pro/7.14.md
Labels: Future release

#3101 Revert change to date format returned by API.
  content/apidocs-mxsdk/apidocs/deploy-api.md
  content/releasenotes/developer-portal/mendix-cloud.md
Labels: Future release

#3104 Sprintr release 10.17.0
  content/developerportal/settings/attachments/general-settings.png
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3106 Clarify pinning certificates on web service and REST calls
  content/developerportal/deploy/certificates.md
  content/refguide/attachments/integration-activities/general-tab.png
  content/refguide/call-rest-action.md
  content/refguide/call-web-service-action.md
Labels: Needs Support Tech Lead verification

#3075 8.18.2 RN
  content/releasenotes/studio-pro/8.18.md
Labels: 8.18.2

#3103 7.23.20 RN
  content/releasenotes/studio-pro/7.23.md
Labels: 7.23.20

#3061 Add support to Postgres 13 in Mendix 7.23.20
  content/refguide7/system-requirements.md
Labels: 7.23.20

#3110 added release notes for control center 1.2 release
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3098 Control Center release 3.9
  content/developerportal/control-center/index.md
Labels: Future release

#3114 External Release Notes - Create New App Flow
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3125 Release notes Sprintr 10.17.2
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3131 Small changes to shutdown behaviour
  content/refguide/task-queue.md
Labels: 9.0.5

#3126 Release Notes for usage data collection - March 15th
  content/releasenotes/developer-portal/deployment.md
  content/releasenotes/developer-portal/mendix-cloud.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release, Needs technical verification

#3134 Add missing Native Template release notes
  content/releasenotes/mobile/native-template.md
Labels: Update RN/featured date

#3136 8.18.3 RN
  content/releasenotes/studio-pro/8.18.md
Labels: 8.18.3

#3119 Free apps are no longer limited for Data Hub
  content/refguide8/consumed-odata-service-requirements.md
Labels: 8.18.3

#3139 Add release notes for Native Template 5.1.8 5.0.12
  content/releasenotes/mobile/native-template.md
Labels: Update RN/featured date

#3141 Mendix Cloud Release Notes - 18 March 2021
  content/developerportal/deploy/environments-details.md
  content/releasenotes/developer-portal/deployment.md
  content/releasenotes/developer-portal/mendix-cloud.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release, Update RN/featured date

#3135 Private Cloud release March 18
  content/developerportal/deploy/attachments/private-cloud-cluster/download-executable.png
  content/developerportal/deploy/attachments/private-cloud-config-script/cluster-details.png
  content/developerportal/deploy/attachments/private-cloud-config-script/custom-tls.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image10.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image11.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image12.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image13.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image14.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image15.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image16.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image18.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image19.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image20.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image21.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image23.png
  content/developerportal/deploy/attachments/private-cloud-config-script/image9.png
  content/developerportal/deploy/attachments/private-cloud-config-script/namespace-scripts.png
  content/developerportal/deploy/attachments/private-cloud-config-script/use-old-script.png
  content/developerportal/deploy/attachments/private-cloud-upgrade-guide/mxpc-cli-welcome.png
  content/developerportal/deploy/attachments/private-cloud-upgrade-guide/upgrade-wizard.png
  content/developerportal/deploy/private-cloud-cluster.md
  content/developerportal/deploy/private-cloud-config-script.md
  content/developerportal/deploy/private-cloud-deploy.md
  content/developerportal/deploy/private-cloud-migrating.md
  content/developerportal/deploy/private-cloud-operator.md
  content/developerportal/deploy/private-cloud-upgrade-guide.md
  content/releasenotes/developer-portal/mendix-for-private-cloud.md
Labels: Update RN/featured date

#3140 Update version control documents for Mx9
  content/howto/collaboration-requirements-management/attachments/on-premises-git-howto/sign-in-dialog.png
  content/refguide/attachments/collaborative-development/create-git-branch-dialog.png
  content/refguide/attachments/merge-dialog/merge-dialog-git.png
  content/refguide/attachments/upload-to-version-control/enable-private-version-control.png
  content/refguide/attachments/version-control-menu/create-git-branch-line.png
  content/refguide/attachments/version-control-menu/git-branch-line-manager.png
  content/refguide/branch-line-manager-dialog.md
  content/refguide/collaborative-development.md
  content/refguide/create-branch-line-git-dialog.md
  content/refguide/download-from-version-control-dialog.md
  content/refguide/merge-dialog.md
  content/refguide/upload-to-version-control-dialog.md
  content/refguide/version-control-menu.md
  content/refguide/version-control.md
Labels: 9.0.5

#3149 Update new merge algorithm docs for 9.0.5
  content/appstore/widgets/camera.md
  content/developerportal/collaborate/app-roles.md
  content/developerportal/collaborate/team.md
  content/developerportal/deploy/access-restrictions.md
  content/developerportal/deploy/attachments/basic-package/configure-basic-package.png
  content/developerportal/deploy/attachments/basic-package/confirm-unlink.png
  content/developerportal/deploy/attachments/basic-package/download-backup.png
  content/developerportal/deploy/attachments/basic-package/free-app-message.png
  content/developerportal/deploy/attachments/basic-package/invoice-details.png
  content/developerportal/deploy/attachments/basic-package/link-node.png
  content/developerportal/deploy/attachments/basic-package/restore-backup.png
  content/developerportal/deploy/attachments/basic-package/unlink-free-app.png
  content/developerportal/deploy/attachments/basic-package/unlink-your-app.png
  content/developerportal/deploy/basic-package.md
  content/developerportal/deploy/certificates.md
  content/developerportal/deploy/cloud-version-region.md
  content/developerportal/deploy/custom-domains.md
  content/developerportal/deploy/environments-details.md
  content/developerportal/deploy/licensing-apps.md
  content/developerportal/deploy/maintenance-windows.md
  content/developerportal/deploy/mendix-cloud-deploy.md
  content/developerportal/deploy/migrate-free-app-to-basic.md
  content/developerportal/deploy/migrating-to-v4.md
  content/developerportal/deploy/node-permissions.md
  content/developerportal/deploy/private-cloud-upgrade-guide.md
  content/developerportal/deploy/scale-environment.md
  content/developerportal/deploy/two-factor-authentication.md
  content/developerportal/deploy/updating-a-mendix-application.md
  content/developerportal/index.md
  content/developerportal/operate/create-backup.md
  content/developerportal/operate/download-backup.md
  content/developerportal/operate/metrics.md
  content/developerportal/operate/receive-alerts.md
  content/developerportal/operate/trends-v4.md
  content/developerportal/operate/trends.md
  content/developerportal/operate/troubleshooting-mxcloud-runningnow.md
  content/developerportal/settings/leave-delete-app.md
  content/howto6/create-and-deploy-your-first-app.md
  content/howto6/debug-microflows-remotely.md
  content/howto7/monitoring-troubleshooting/debug-microflows-remotely.md
  content/refguide/attachments/data-hub-pane/data-hub-pane-update.png
  content/refguide/attachments/new-merge-algorithm/new-merge-algorithm-all-conflicts-resolved.PNG
  content/refguide/attachments/new-merge-algorithm/new-merge-algorithm-base-page.png
  content/refguide/attachments/new-merge-algorithm/new-merge-algorithm-branch-page.png
  content/refguide/attachments/new-merge-algorithm/new-merge-algorithm-conflicts.png
  content/refguide/attachments/new-merge-algorithm/new-merge-algorithm-main-page.png
  content/refguide/attachments/new-merge-algorithm/new-merge-algorithm-orange-tab.png
  content/refguide/attachments/new-merge-algorithm/new-merge-algorithm-resolve-mode.png
  content/refguide/consumed-odata-service.md
  content/refguide/consumed-odata-services.md
  content/refguide/data-hub-pane.md
  content/refguide/new-merge-algorithm.md
  content/refguide/progressive-web-app.md
  content/releasenotes/studio-pro/windows-service.md
Labels: 9.0.5

#3148 Appstore release 8.8.0
  content/appstore/general/app-store-overview.md
  content/appstore/general/attachments/app-store-overview/my-content.png
  content/appstore/general/attachments/app-store-overview/your-reviews.png
  content/releasenotes/app-store/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3164 Add release notes for App Templates app release.
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3165 UI Design documentation - Introduce get started documentation
  content/howto/front-end/get-started.md
Labels: 9.0.5, Atlas

#3167 Introduce UI Design > Customize Styling page
  content/howto/front-end/attachments/customize-styling/compilation-error.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig1.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig2.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig3.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig4.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig5.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig6.png
  content/howto/front-end/customize-styling-new.md
Labels: 9.0.5, Atlas, Internal WIP

#3169 UI Design documentation - Introduce extend design properties documentation
  content/howto/front-end/attachments/extend-design-properties/studio-design-properties.png
  content/howto/front-end/attachments/extend-design-properties/studio-pro-design-properties.png
  content/howto/front-end/extend-design-properties-to-customize.md
  content/howto/front-end/extend-design-properties.md
Labels: 9.0.5, Atlas

#3173 Improve UI Design > customize styling
  content/howto/front-end/customize-styling-new.md
Labels: 9.0.5, Atlas

#3175 UI Design documentation - Add create a company design system documentation
  content/howto/front-end/create-a-company-design-system.md
Labels: 9.0.5, Atlas

#3178 Atlas docs - Add links
  content/howto/front-end/create-a-company-design-system.md
  content/howto/front-end/extend-design-properties.md
  content/howto/front-end/get-started.md
Labels: 9.0.5, Atlas

#3186 Release Note Mendix Cloud 30 March
  content/releasenotes/developer-portal/deployment.md
  content/releasenotes/developer-portal/mendix-cloud.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Update RN/featured date

#3194 Add AppName to the new header
  _assets/styles/_sass/components/_header.scss
  package-lock.json
  package.json
  themes/mendix/layouts/partials/base/foot.html
Labels: Needs language review

#3199 Control Center
  content/developerportal/control-center/attachments/admin-exists.jpg
Labels: Future release

#3085 LTS/MTS
  content/releasenotes/studio-pro/7.23.md
  content/releasenotes/studio-pro/8.12.md
  content/releasenotes/studio-pro/8.18.md
  content/releasenotes/studio-pro/8.6.md
  content/releasenotes/studio-pro/attachments/lts.png
  content/releasenotes/studio-pro/attachments/mts.png
  content/releasenotes/studio-pro/lts-mts.md
Labels: 9.0.5, Internal WIP

#3064 Add Java actions to Task Queue
  content/refguide/task-queue.md
Labels: 9.0.5

#3118 Free apps are no longer limited for Data Hub
  content/refguide/consumed-odata-service-requirements.md
Labels: 9.0.5

#3168 Mx9 Atlas Changes
  content/apidocs-mxsdk/apidocs/design-properties.md
  content/developerportal/deploy/upgrading-to-mendix-sso-from-acs.md
  content/howto/front-end/atlas-ui.md
  content/howto/front-end/attachments/customize-styling/compilation-error.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig1.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig2.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig3.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig4.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig5.png
  content/howto/front-end/attachments/customize-styling/exclusion-vars-fig6.png
  content/howto/front-end/attachments/extend-design-properties/studio-design-properties.png
  content/howto/front-end/attachments/extend-design-properties/studio-pro-design-properties.png
  content/howto/front-end/calypso.md
  content/howto/front-end/create-a-company-design-system.md
  content/howto/front-end/create-company-atlas-ui-resources.md
  content/howto/front-end/create-custom-preview-images-for-building-blocks-and-page-templates.md
  content/howto/front-end/customize-styling-new.md
  content/howto/front-end/customize-styling.md
  content/howto/front-end/extend-design-properties-to-customize.md
  content/howto/front-end/extend-design-properties.md
  content/howto/front-end/get-started-with-atlasui.md
  content/howto/front-end/get-started.md
  content/howto/front-end/index.md
  content/howto/front-end/migrate-existing-projects-to-atlasui.md
  content/howto/front-end/sass-eight.md
  content/howto/front-end/share-company-atlas-ui-resources.md
  content/howto/front-end/style-with-gulp-and-sass.md
  content/howto/front-end/use-gulp-and-sass.md
  content/howto/mobile/ui-best-practices.md
  content/refguide/attachments/atlas-mig/1-errors.png
  content/refguide/attachments/atlas-mig/10-edge.png
  content/refguide/attachments/atlas-mig/11-edge-profiles.png
  content/refguide/attachments/atlas-mig/2-rename.png
  content/refguide/attachments/atlas-mig/3-import.png
  content/refguide/attachments/atlas-mig/4-errors.png
  content/refguide/attachments/atlas-mig/5-nav.png
  content/refguide/attachments/atlas-mig/6-hybrid-phone.png
  content/refguide/attachments/atlas-mig/7-errors.png
  content/refguide/attachments/atlas-mig/8-errors-background.png
  content/refguide/attachments/atlas-mig/9-set-prop.png
  content/refguide/attachments/atlas-mig/set-hybrid-nav.png
  content/refguide/moving-from-atlas-2-to-3.md
Labels: 9.0.5, Atlas

#3172 Mx9: Add docs for long-lived sessions
  content/refguide/custom-settings.md
  content/refguide/progressive-web-app.md
  content/refguide/tricky-custom-runtime-settings.md
Labels: 9.0.5

#3123 [UICORE-1217] Describe 'close all' option in refguide
  content/refguide/close-page.md
  content/refguide/native-navigation.md
  content/refguide/show-page.md
Labels: 9.0.5

#3113 [WC-170] Add docs for renaming dropdown option to toggle in Mendix 9 [9.0.5]
  content/apidocs-mxsdk/apidocs/design-properties.md
Labels: 9.0.5

#3100 [WC-109] Add documentation for refactored progress bar widget
  content/appstore/widgets/progress-bar.md
Labels: 9.0.5

#3079 [WTF-726] Update pluggable widget client API docs [9.0.5]
  content/apidocs-mxsdk/apidocs/client-apis-for-pluggable-widgets.md
  content/apidocs-mxsdk/apidocs/pluggable-parent-9.md
Labels: 9.0.5

#3086 [WC-97] Add documentation for rewritten badge widget
  content/appstore/widgets/badge.md
Labels: 9.0.5

#3155 Add docs for Data grid 2 module
  content/appstore/modules/attachments/data-grid-2/column-alignment.png
  content/appstore/modules/attachments/data-grid-2/column-custom-content.png
  content/appstore/modules/attachments/data-grid-2/column-dynamic-text.png
  content/appstore/modules/attachments/data-grid-2/column-properties.png
  content/appstore/modules/attachments/data-grid-2/column-width.png
  content/appstore/modules/attachments/data-grid-2/configuration.png
  content/appstore/modules/attachments/data-grid-2/date-filter-not-adjustable.png
  content/appstore/modules/attachments/data-grid-2/date-filter-settings.png
  content/appstore/modules/attachments/data-grid-2/date-filter-types.png
  content/appstore/modules/attachments/data-grid-2/date-filter.png
  content/appstore/modules/attachments/data-grid-2/dropdown-filter-item.png
  content/appstore/modules/attachments/data-grid-2/dropdown-filter-multiselect.png
  content/appstore/modules/attachments/data-grid-2/dropdown-filter-settings.png
  content/appstore/modules/attachments/data-grid-2/dropdown-filter.png
  content/appstore/modules/attachments/data-grid-2/dropzones-for-filters.png
  content/appstore/modules/attachments/data-grid-2/dynamic-cell-class.png
  content/appstore/modules/attachments/data-grid-2/dynamic-row-class.png
  content/appstore/modules/attachments/data-grid-2/empty-list-message.png
  content/appstore/modules/attachments/data-grid-2/example.png
  content/appstore/modules/attachments/data-grid-2/hidden-columns-design-mode.png
  content/appstore/modules/attachments/data-grid-2/hidden-columns-structure-mode.png
  content/appstore/modules/attachments/data-grid-2/hiding.png
  content/appstore/modules/attachments/data-grid-2/no-sorting.png
  content/appstore/modules/attachments/data-grid-2/number-filter-not-adjustable.png
  content/appstore/modules/attachments/data-grid-2/number-filter-settings.png
  content/appstore/modules/attachments/data-grid-2/number-filter-types.png
  content/appstore/modules/attachments/data-grid-2/number-filter.png
  content/appstore/modules/attachments/data-grid-2/paging-buttons.png
  content/appstore/modules/attachments/data-grid-2/reordering.gif
  content/appstore/modules/attachments/data-grid-2/resizing.png
  content/appstore/modules/attachments/data-grid-2/settings-show-column-filters.png
  content/appstore/modules/attachments/data-grid-2/sorting-asc.png
  content/appstore/modules/attachments/data-grid-2/sorting-desc.png
  content/appstore/modules/attachments/data-grid-2/text-filter-not-adjustable.png
  content/appstore/modules/attachments/data-grid-2/text-filter-settings.png
  content/appstore/modules/attachments/data-grid-2/text-filter-types.png
  content/appstore/modules/attachments/data-grid-2/text-filter.png
  content/appstore/modules/attachments/data-grid-2/unlimited-string-attribute.png
  content/appstore/modules/data-grid-2.md
Labels: 9.0.5
