Repository mendix/docs, pull requests merged in 2021-11, with the labels that each got.

#3840 Sec Advisories
  content/releasenotes/mx-world-2021/index.md
  content/releasenotes/security-advisories/index.md
  content/releasenotes/studio-pro/7.14.md
  content/releasenotes/studio-pro/7.23.md
  content/releasenotes/studio-pro/8.18.md
  content/releasenotes/studio-pro/9.6.md
  content/releasenotes/studio-pro/9.7.md
  data/spaces.yml
Labels: Internal WIP

#3828 Remove workaround for not having SAP HANA trial database
  content/developerportal/deploy/sap-cloud-platform.md
Labels: Needs R&D technical verification

#3835 9.6.2 RN
  content/releasenotes/security-advisories/index.md
  content/releasenotes/studio-pro/9.6.md
Labels: Future release, Needs R&D technical verification, Update RN & featured date

#3848 Update images in Partner Profile section in Docs
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/add-project.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/address.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/close-edit.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/edit-partner-profile.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/edit-profile-field.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/geo-focus.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/header.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/icon.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/industries.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/project-buttons.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/project-comment.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/project-editor.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/published.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/service.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/skills.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/summary.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/team-members.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/testimonials.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/unpublished.png
  content/developerportal/community-tools/attachments/how-to-set-up-your-partner-profile/video.png
  content/developerportal/community-tools/how-to-set-up-your-partner-profile.md
Labels: Waiting for CLA, Post-publish edit images

#3834 8.18.13 RN
  content/releasenotes/security-advisories/index.md
  content/releasenotes/studio-pro/8.18.md
Labels: Future release, Update RN & featured date

#3864 DataHub Release 2.7.0
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3866 Add missing cluster leader task
  content/refguide/clustered-mendix-runtime.md
Labels: Needs R&D technical verification, Needs language review

#3872 Remove references to reschedule button for planned maintenance.
  content/developerportal/deploy/attachments/maintenance-windows/maintenance.png
  content/developerportal/deploy/maintenance-windows.md
Labels: Needs Support verification

#3875 Add the information about enabling automatic syncing of IdP metadata
  content/appstore/modules/saml.md
Labels: Internal WIP

#3885 Implement redesigned highlighting in screenshots
  content/partners/sap/attachments/sap-logger/logger_drag_component.png
  content/partners/sap/attachments/sap-logger/logger_edit_action.png
  content/partners/sap/sap-logger.md
  content/refguide/associations.md
  content/refguide/attachments/associations/association-accountant-group.png
  content/refguide/attachments/associations/association-move-arrow.png
  content/refguide/attachments/associations/association-order-customer.png
  content/refguide/attachments/associations/edit-association.png
  content/refguide/attachments/associations/edit-entity-association.png
  content/refguide/attachments/associations/limitation.png
  content/refguide/attachments/datastorage/unique-validation-rule-resolved.png
  content/refguide/attachments/datastorage/unique-validation-rule-unresolved.png
  content/refguide/attachments/domain-model/customer-event-handlers.png
  content/refguide/attachments/domain-model/customer-index-example.png
  content/refguide/attachments/domain-model/customer-validation-rules.png
  content/refguide/attachments/domain-model/validation-rule-properties.png
  content/refguide8/attachments/associations/edit-entity-association.png
Labels: Internal WIP

#3888 Release notes Sprintr 11.11.0
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3862 Added entry for contributor release
  content/appstore/general/attachments/share-app-store-content/capabilities.png
  content/appstore/general/share-app-store-content.md
  content/releasenotes/app-store/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release, Post-publish edit images

#3874 Marketplace Premium
  content/appstore/general/app-store-overview.md
Labels: Future release

#3892 Private Cloud Portal Release Notes (November 18)
  content/developerportal/deploy/private-cloud-deploy.md
  content/releasenotes/developer-portal/mendix-for-private-cloud.md
Labels: Needs language review

#3886 Datahub Catalog Release 2.8.0
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3868 Mendix Operator Technical Appendix: 1 Introduction to Operators
  content/developerportal/deploy/private-cloud-technical-appendix-01.md
  content/developerportal/deploy/private-cloud-technical-appendix.md
Labels: Needs R&D technical verification, Internal WIP

#3906 changes for 6.1.0 release
  content/appstore/modules/imap.md
Labels: Future release

#3907 removed mentioning datadog in Private Cloud Monitoring docs to preven…
  content/developerportal/deploy/private-cloud-monitor.md
Labels: Needs language review

#3803 Update version-control.md
  content/refguide/attachments/version-control/Collaboration Flow.pptx
  content/refguide/attachments/version-control/image10.png
  content/refguide/version-control.md
Labels: 9.8.0

#3901 Update deep-link.md
  content/appstore/modules/deep-link.md
Labels: Needs R&D technical verification, Internal WIP

#3914 Remove requirement for sticky sessions
  content/developerportal/deploy/on-premises-design.md
Labels: Needs language review

#3911 Add avoiding exclusive access rules for the same user
  content/howto/general/community-best-practices-for-app-performance.md
Labels: Needs R&D technical verification

#3904 9.8 RN
  content/releasenotes/studio-pro/9.8.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 9.8.0

#3814 Document default values support for offline-first
  content/refguide/attributes.md
  content/refguide/offline-first.md
Labels: 9.8.0

#3818 [NC] Add PIW Switch documentation and update core checkbox documentation
  content/appstore/modules/native-mobile-resources.md
  content/refguide/attachments/check-box/check-box-properties.png
  content/refguide/attachments/native-styling-refguide/check-box-checkbox.png
  content/refguide/check-box.md
  content/refguide/native-styling-refguide.md
Labels: 9.8.0

#3908 Remove the limitation of associated attributes in DB2 and SAP HANA
  content/refguide/db2.md
  content/refguide/saphana.md
Labels: 9.8.0

#3867 Remove the limitation of associated attributes in DB2 and SAP HANA in Mx 9 MTS version.
  content/refguide/db2.md
  content/refguide/saphana.md
Labels: Verify after merge, 9.6.3

#3854 Studio Pro 9.8.0 adds associations to the send external object activity
  content/refguide/send-external-object.md
Labels: 9.8.0

#3887 Update Version Control documents with Git information
  content/refguide/attachments/collaborative-development/create-branch-dialog.png
  content/refguide/attachments/collaborative-development/disable-for-studio.png
  content/refguide/attachments/collaborative-development/enable-another-branch.png
  content/refguide/attachments/collaborative-development/globe-icon.png
  content/refguide/attachments/collaborative-development/switch-branch.png
  content/refguide/attachments/merge-dialog/merge-dialog-git.png
  content/refguide/attachments/using-version-control-in-studio-pro/2018-02-21_14-19-47.png
  content/refguide/attachments/using-version-control-in-studio-pro/2018-02-28_13-50-39.png
  content/refguide/attachments/using-version-control-in-studio-pro/commit-git.png
  content/refguide/attachments/using-version-control-in-studio-pro/merge-git.png
  content/refguide/attachments/using-version-control-in-studio-pro/revert-changes-git.png
  content/refguide/attachments/version-control-menu/version-control-menu.png
  content/refguide/attachments/version-control/Collaboration Flow.pptx
  content/refguide/attachments/version-control/image10.png
  content/refguide/collaborative-development.md
  content/refguide/history-dialog.md
  content/refguide/merge-dialog.md
  content/refguide/using-version-control-in-studio-pro.md
  content/refguide/version-control-menu.md
  content/refguide/version-control.md
Labels: 9.8.0

#3847 Add MXP009 documentation to Performance Best Practices page (needs to be published with respect to the Studio Pro 9.8 release - Nov 30, 2021)
  content/refguide/performance-best-practices.md
Labels: 9.8.0

#3917 Studio release notes
  content/releasenotes/studio/9.7-and-above.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Internal WIP, 9.8.0

#3824 Update Create Git branch docs
  content/refguide/attachments/version-control-menu/branch-line-manager-private-server-app.png
  content/refguide/attachments/version-control-menu/branch-line-manager.png
  content/refguide/attachments/version-control-menu/create-git-branch-line.png
  content/refguide/attachments/version-control-menu/git-branch-line-manager.png
  content/refguide/branch-line-manager-dialog.md
  content/refguide/create-branch-line-dialog.md
  content/refguide/create-branch-line-git-dialog.md
  content/refguide/version-control-menu.md
  content/releasenotes/studio-pro/9.8.md
Labels: 9.8.0

#3898 Add API description for writable OData
  content/refguide/odata-query-options.md
  content/refguide/published-odata-resource.md
Labels: 9.8.0
