Repository mendix/docs, pull requests merged in 2021-08, with the labels that each got.

#3543 Add heading for introduction, change numbering, add borders to images
  content/appstore/modules/attachments/web-actions/check.png
  content/appstore/modules/attachments/web-actions/confirmation.png
  content/appstore/modules/attachments/web-actions/entity.png
  content/appstore/modules/attachments/web-actions/nanoflow.png
  content/appstore/modules/attachments/web-actions/properties.png
  content/appstore/modules/web-actions.md
Labels: Internal WIP

#3544 [DAT-2574] Callable Statements Documentation
  content/appstore/connectors/attachments/database/Thumbs.db
  content/appstore/connectors/attachments/database/callable-statement-action.png
  content/appstore/connectors/attachments/database/database-connector-in-toolbox.png
  content/appstore/connectors/attachments/database/parameter-list-parameter.png
  content/appstore/connectors/attachments/database/parameter-object-parameter.png
  content/appstore/connectors/attachments/database/parameter-ref-cursor-parameter.png
  content/appstore/connectors/attachments/database/primitive-types-parameters.png
  content/appstore/connectors/attachments/database/statement-parameter-diagram.png
  content/appstore/connectors/database-connector.md
Labels: Needs technical verification

#3377 Reinstate V3 to V4 Migration Tool
  content/developerportal/deploy/attachments/migrating-to-v4/migration-flow.pptx
  content/developerportal/deploy/attachments/migrating-to-v4/migration-page.png
  content/developerportal/deploy/attachments/migrating-to-v4/migration-process-overview.png
  content/developerportal/deploy/attachments/migrating-to-v4/migration-status.png
  content/developerportal/deploy/attachments/migrating-to-v4/select-v3-node-to-migrate.png
  content/developerportal/deploy/migrating-to-v4.md
Labels: Internal WIP

#3574 Added release notes for Catalog August 5, 2021
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3585 Merge doc tab in marketplace to the MG page
  content/appstore/modules/community-commons-function-library.md
Labels: Needs technical verification, Internal WIP

#3587 Write release notes for Datahub Catalog 1.42 release
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3590 Private Cloud release notes (for August 12)
  content/developerportal/deploy/private-cloud-cluster.md
  content/developerportal/deploy/private-cloud-migrating.md
  content/developerportal/deploy/private-cloud-supported-environments.md
  content/developerportal/deploy/private-cloud-upgrade-guide.md
  content/releasenotes/developer-portal/mendix-for-private-cloud.md
Labels: Update RN/featured date

#3588 7.23.24 RN
  content/releasenotes/studio-pro/7.23.md
Labels: Future release, Update RN/featured date

#3589 8.18.10 RN
  content/releasenotes/studio-pro/8.18.md
Labels: Future release

#3609 Release 1.43 - August 19 , 2021
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3600 OData Release Note and Documentation
  content/partners/sap/attachments/sap-destination-service/get-destination-error-flow.png
  content/partners/sap/attachments/sap-destination-service/xsuaaenabled.png
  content/partners/sap/sap-destination-service.md
  content/releasenotes/developer-portal/deployment.md
  content/releasenotes/developer-portal/sap-cloud-platform.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Update RN/featured date

#3580 How to Register OData resources in the Data Hub Catalog (with or without the Mendix Cloud)
  content/data-hub/data-hub-catalog/attachments/register-data/create-token.png
  content/data-hub/data-hub-catalog/attachments/register-data/generated-token.png
  content/data-hub/data-hub-catalog/attachments/register-data/register-data-source-contract.png
  content/data-hub/data-hub-catalog/attachments/register-data/register-data-source-details.png
  content/data-hub/data-hub-catalog/attachments/register-data/register-data-source-odata-connector.png
  content/data-hub/data-hub-catalog/attachments/register-data/warden-home-screen.png
  content/data-hub/data-hub-catalog/attachments/register-data/warden-home-with-token.png
  content/data-hub/data-hub-catalog/attachments/register/register-data-source-asset-details.png
  content/data-hub/data-hub-catalog/attachments/register/register-data-source-exist-app.png
  content/data-hub/data-hub-catalog/attachments/register/register-data-source-home.png
  content/data-hub/data-hub-catalog/attachments/register/register-data-source-hurrah.png
  content/data-hub/data-hub-catalog/attachments/register/register-data-source-new-app.png
  content/data-hub/data-hub-catalog/attachments/register/register-data-source-new-env.png
  content/data-hub/data-hub-catalog/attachments/register/register-data-source-odata-connector.png
  content/data-hub/data-hub-catalog/attachments/register/register-data-source-tag-list.png
  content/data-hub/data-hub-catalog/attachments/register/register-data-source-validate.png
  content/data-hub/data-hub-catalog/index.md
  content/data-hub/data-hub-catalog/register-data.md
  content/data-hub/data-hub-catalog/register.md
  content/releasenotes/data-hub/index.md
Labels: Internal WIP

#3615 Give execute procedure permission.
  content/developerportal/deploy/setting-up-the-database-user.md
Labels: Internal WIP

#3616 Update tencent-deploy.md
  content/developerportal/deploy/tencent-deploy.md
Labels: Internal WIP

#3617 Add the note text with the translation link
  content/developerportal/deploy/tencent-deploy.md
Labels: Internal WIP

#3608 Add a warning about the possible error
  content/appstore/widgets/list-view-controls.md
Labels: Internal WIP

#3624 Update stories.md
  content/developerportal/collaborate/stories.md
Labels: Internal WIP

#3601 Update screenshots
  content/appstore/connectors/attachments/aws-iot/certificates.jpg
  content/appstore/connectors/attachments/aws-iot/certificates.png
  content/appstore/connectors/attachments/aws-iot/data-change-shadow.png
  content/appstore/connectors/attachments/aws-iot/data-get-shadow.png
  content/appstore/connectors/attachments/aws-iot/data-publish-mqtt-message-properties.png
  content/appstore/connectors/attachments/aws-iot/data-publish-mqtt-message.png
  content/appstore/connectors/attachments/aws-iot/data-subscribe-mqtt-topic-properties.png
  content/appstore/connectors/attachments/aws-iot/data-subscribe-mqtt-topic.png
  content/appstore/connectors/attachments/aws-iot/log-message.png
  content/appstore/connectors/attachments/aws-iot/thing-describe.png
  content/appstore/connectors/attachments/aws-iot/thing-get-list-properties.png
  content/appstore/connectors/attachments/aws-iot/thing-get-list.jpg
  content/appstore/connectors/attachments/aws-iot/thing-get-list.png
  content/appstore/connectors/aws-iot.md
Labels: Internal WIP

#3641 Added clarification for branch name format
  content/apidocs-mxsdk/apidocs/team-server-api.md
Labels: Needs language review

#3629 9.5 RN
  content/releasenotes/studio-pro/9.5.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 9.5.0
