Repository mendix/docs, pull requests merged in 2021-06, with the labels that each got.

#3370 Control Center Release 1.5.0
  content/developerportal/control-center/attachments/cloud.jpg
  content/developerportal/control-center/index.md
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3397 Deprecation notice outdated app templates
  content/apidocs-mxsdk/apidocs/projects-api.md
  content/releasenotes/developer-portal/index.md
Labels: Future release

#3396 Appstore Release 8.13.0
  content/releasenotes/app-store/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3388 Proofread Java Programming
  content/refguide/attachments/java-programming/917527.png
  content/refguide/attachments/java-programming/917580.png
  content/refguide/attachments/java-programming/917582.png
  content/refguide/attachments/java-programming/917584.png
  content/refguide/attachments/java-programming/917586.png
  content/refguide/attachments/java-programming/918120.png
  content/refguide/attachments/java-programming/918186.png
  content/refguide/attachments/java-programming/eclipse-debug-log.png
  content/refguide/attachments/java-programming/eclipse-jdk.png
  content/refguide/attachments/java-programming/eclipse-run-configuration.png
  content/refguide/attachments/java-programming/eclipse-select-import.png
  content/refguide/attachments/java-programming/eclipse-utf8-encoding.png
  content/refguide/attachments/java-programming/import-eclipse-project.png
  content/refguide/java-programming.md
  content/refguide/troubleshooting.md
  content/refguide/using-eclipse.md
Labels: Internal WIP

#3390 Add workflow consistency errors
  content/howto/logic-business-rules/attachments/workflow-how-to-configure/entity-properties.png
  content/howto/logic-business-rules/attachments/workflow-how-to-configure/new-access-rule.png
  content/howto/logic-business-rules/workflow-how-to-configure.md
  content/studio/consistency-errors-microflows.md
  content/studio/consistency-errors-pages.md
  content/studio/consistency-errors-workflows.md
  content/studio/consistency-errors.md
Labels: Needs technical verification

#3392 Proofreading dialog boxes (refguide7)
  content/refguide7/app-settings-dialog.md
  content/refguide7/attachments/app-settings-dialog/app-settings-dialg-box.png
  content/refguide7/attachments/commit-dialog/commit-branch.png
  content/refguide7/attachments/commit-dialog/commit-dialog-disk-changes.png
  content/refguide7/attachments/commit-dialog/commit-dialog-model-changes.png
  content/refguide7/attachments/commit-dialog/commit-dialog-stories.png
  content/refguide7/attachments/commit-dialog/commit-main.png
  content/refguide7/attachments/create-branch-line-dialog/create-branch-line-dialog.png
  content/refguide7/attachments/create-deployment-package-dialog/create-deployment-package-dialog.png
  content/refguide7/attachments/download-from-version-control-server-dialog/download-from-private-server.png
  content/refguide7/attachments/download-from-version-control-server-dialog/download-from-version-control-server-dialog-original.png
  content/refguide7/attachments/download-from-version-control-server-dialog/download-from-version-control-server.png
  content/refguide7/attachments/export-a-project-package/export-project-package-dialog.png
  content/refguide7/attachments/import-project-package-dialog/import-project-package.png
  content/refguide7/attachments/preferences-dialog/preferences-dialog-box.png
  content/refguide7/attachments/upload-to-version-control-dialog/project-more-versioning-upload-to-version-control-server.png
  content/refguide7/attachments/upload-to-version-control-dialog/upload-to-version-control-server-dialog.png
  content/refguide7/branch-line-manager-dialog.md
  content/refguide7/commit-dialog.md
  content/refguide7/create-branch-line-dialog.md
  content/refguide7/create-deployment-package-dialog.md
  content/refguide7/deploy-to-the-cloud-dialog.md
  content/refguide7/dialogs.md
  content/refguide7/download-from-version-control-dialog.md
  content/refguide7/edit-cloud-foundry-settings-dialog.md
  content/refguide7/export-project-package-dialog.md
  content/refguide7/history-dialog.md
  content/refguide7/import-project-package-dialog.md
  content/refguide7/merge-dialog.md
  content/refguide7/open-app-dialog.md
  content/refguide7/preferences-dialog.md
  content/refguide7/sign-in-dialog.md
  content/refguide7/upload-to-version-control-dialog.md
  content/refguide7/version-control.md
  content/refguide8/preferences-dialog.md
Labels: Internal WIP

#3408 docs: Mendix Buildpack is now automatically updated on resume for Free Tier
  content/releasenotes/developer-portal/mendix-cloud.md
Labels: Future release, Update RN/featured date

#3414 Added basic document topics
  content/developerportal/deploy/local-users-in-studio.md
Labels: Internal WIP

#3413 7.23.22 RN
  content/releasenotes/studio-pro/7.23.md
Labels: Future release

#3418 Release notes for Data Hub Catalog version 1.33 on Thursday, June 10.
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3406 8.18.7 RN
  content/releasenotes/studio-pro/8.18.md
Labels: Future release

#3411 Remove Uniqueness Validation type in Mx9
  content/refguide/attachments/datastorage/attr-uniq-validation-rule.PNG
  content/refguide/attachments/datastorage/deprecation-warning.PNG
  content/refguide/attachments/datastorage/uniqueness-validation-setting.PNG
  content/refguide/project-settings.md
  content/refguide/uniqueness-constraint-migration.md
  content/refguide/validation-rules.md
Labels: Needs technical verification

#3421 Mendix Cloud release note 11 June
  content/releasenotes/developer-portal/deployment.md
  content/releasenotes/developer-portal/mendix-cloud.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3405 Proofread datasets and oql pages
  content/refguide/data-sets.md
  content/refguide/oql-aggregation.md
  content/refguide/oql-case-expression.md
  content/refguide/oql-cast.md
  content/refguide/oql-coalesce.md
  content/refguide/oql-datediff.md
  content/refguide/oql-datepart.md
  content/refguide/oql-expressions.md
  content/refguide/oql-from-clause.md
  content/refguide/oql-functions.md
  content/refguide/oql-group-by-clause.md
  content/refguide/oql-length.md
  content/refguide/oql-limit-clause.md
  content/refguide/oql-operators.md
  content/refguide/oql-order-by-clause.md
  content/refguide/oql-parameters.md
  content/refguide/oql-rangebegin.md
  content/refguide/oql-rangeend.md
  content/refguide/oql-round.md
  content/refguide/oql-select-clause.md
  content/refguide/oql-where-clause.md
  content/refguide/oql.md
Labels: Internal WIP

#3404 Fix style issues
  content/refguide7/app-settings-dialog.md
  content/refguide7/attachments/app-settings-dialog/app-settings-dialg-box.png
  content/refguide7/branch-line-manager-dialog.md
  content/refguide7/consistency-errors-pages.md
  content/refguide7/create-branch-line-dialog.md
  content/refguide7/download-from-version-control-dialog.md
  content/refguide7/edit-cloud-foundry-settings-dialog.md
  content/refguide7/export-project-package-dialog.md
  content/refguide7/import-project-package-dialog.md
  content/refguide7/open-app-dialog.md
  content/refguide7/preferences-dialog.md
  content/refguide7/upload-to-version-control-dialog.md
Labels: Internal WIP

#3426 Change page structure to mimic 404 page
  themes/mendix/layouts/search/single.html
Labels: Internal WIP

#3419 Fix broken links
  content/partners/siemens/mindsphere-asset-management-connector.md
Labels: Internal WIP

#3427 16 June - SAP connectors support for OData V4
  content/partners/sap/sap-cloud-connector.md
  content/partners/sap/sap-data-models.md
  content/partners/sap/sap-odata-connector.md
  content/partners/sap/use-sap-odata-connector.md
  content/partners/sap/use-sap-odata-model-creator.md
  content/releasenotes/developer-portal/deployment.md
  content/releasenotes/developer-portal/sap-cloud-platform.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3444 Improve deploy-api documentation
  content/apidocs-mxsdk/apidocs/deploy-api.md
Labels: Needs technical verification

#3415 Proofreading Collaboration in Studio Pro 9 How-to's
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/batch-replace-russian-capitals.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/batch-replace-russian-initial.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/batch-translate-cancel-delete-edit.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/batch-translate-initial.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/batch-translate-myfirstmodule.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/batch-translate-order-2-translations.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/batch-translate-order-split.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/batch-translate-order.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/change-language.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/domain-model.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/generate-pages.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/home-page-russian.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/home-page-text.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/language-settings-belarusian.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/language-settings.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/order-button.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/product-new-edit-order-russian.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/product-new-edit-order.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/product-new-edit-partial-translation.png
  content/howto/collaboration-requirements-management/attachments/translate-your-app-content/untranslated-texts.png
  content/howto/collaboration-requirements-management/contribute-to-a-github-repository.md
  content/howto/collaboration-requirements-management/sharing-the-development-database.md
  content/howto/collaboration-requirements-management/starting-your-own-repository.md
  content/howto/collaboration-requirements-management/translate-your-app-content.md
  content/howto/collaboration-requirements-management/troubleshoot-network-issues-for-team-server.md
  content/howto/collaboration-requirements-management/troubleshoot-version-control-issues.md
Labels: Internal WIP

#3453 Added a useful example for CAST
  content/refguide/oql-cast.md
Labels: Needs language review

#3458 Add warnings to deprecated components in Marketplace
  content/appstore/connectors/box.md
  content/appstore/connectors/ibm-app-launch.md
  content/appstore/modules/google-maps.md
  content/appstore/widgets/barcode-scanner.md
  content/appstore/widgets/contacts-for-hybrid.md
  content/appstore/widgets/mobile-device.md
  content/appstore/widgets/mobile-features.md
  content/appstore/widgets/pull-to-refresh.md
  content/appstore/widgets/radio-button-list.md
  content/appstore/widgets/url-redirector.md
Labels: Internal WIP

#3464 Remove deprecation warning in barcode scanner docs
  content/appstore/widgets/barcode-scanner.md
Labels: Internal WIP

#3469 Data Hub Catalog release 1.35 June 24
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3439 Restructure with new examples
  content/appstore/general/app-store-content.md
  content/appstore/general/attachments/app-store-content/add-widget.png
  content/appstore/general/attachments/app-store-content/data-grid-app-explorer.png
  content/appstore/general/attachments/app-store-content/edit-rating.png
  content/appstore/general/attachments/app-store-content/email-template-app-explorer.png
  content/appstore/general/attachments/app-store-content/import-module.png
  content/appstore/general/attachments/app-store-content/item-details.png
  content/appstore/general/attachments/app-store-content/item_details.png
  content/appstore/general/attachments/app-store-content/marketplace.png
  content/appstore/general/attachments/app-store-content/select-attribute.png
  content/appstore/general/attachments/app-store-content/select-widget.png
  content/appstore/general/attachments/app-store-content/versions.png
  content/appstore/general/attachments/app-store-content/widget-documentation.png
  content/appstore/general/attachments/app-store-content/widget-dropped-in-page.png
  content/appstore/general/attachments/app-store-content/widget-errors.png
  content/appstore/modules/attachments/web-actions/properties.png
  content/appstore/modules/web-actions.md
  content/partners/siemens/mindsphere-app-service.md
Labels: Internal WIP

#3465 7.23.23 RN
  content/releasenotes/studio-pro/7.23.md
Labels: 7.23.23

#3437 Removed unsupported databases.
  content/refguide7/system-requirements.md
Labels: 7.23.23

#3468 Add scaling to connection pooling
  content/refguide/custom-settings.md
  content/refguide/tricky-custom-runtime-settings.md
  content/refguide7/custom-settings.md
  content/refguide7/tricky-custom-runtime-settings.md
  content/refguide8/custom-settings.md
  content/refguide8/tricky-custom-runtime-settings.md
Labels: Needs language review

#3445 9.3 RN
  content/releasenotes/studio-pro/9.3.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 9.3.0

#3432 Remove unsupported databases
  content/refguide/system-requirements.md
Labels: 9.3.0, Internal WIP

#3398 [IN-4444] MaxLength can be set for String key attributes of unlimited length
  content/refguide/consumed-odata-service-requirements.md
Labels: 9.3.0

#3459 Front-end styling: UI Resources modules and ordering
  content/howto/front-end/attachments/customize-styling/app-theme-settings.png
  content/howto/front-end/attachments/customize-styling/green-module.png
  content/howto/front-end/customize-styling-new.md
  content/refguide/attachments/project-settings/app-theme-settings.png
  content/refguide/attachments/project-settings/green-module.png
  content/refguide/project-settings.md
Labels: 9.3.0

#3455 Add 9.3 redesign changes
  content/howto/mobile/native-debug.md
  content/refguide/app-menu.md
  content/refguide/attachments/app-menu/app-menu.png
  content/refguide/attachments/app-menu/create-deployment-package.png
  content/refguide/attachments/app-menu/deploy-to-the-cloud.png
  content/refguide/attachments/edit-menu/edit-menu.png
  content/refguide/attachments/file-menu/file-menu.png
  content/refguide/attachments/find-and-find-advanced/find-options.jpg
  content/refguide/attachments/language/language-menu.png
  content/refguide/attachments/mx-assist-logic-bot/mendix-assist-icon.png
  content/refguide/attachments/mx-assist-logic-bot/mendix-assist-salutation.png
  content/refguide/attachments/mx-assist-logic-bot/mx-assist-add-check.png
  content/refguide/attachments/mx-assist-logic-bot/mx-assist-add-other-element.png
  content/refguide/attachments/mx-assist-logic-bot/mx-assist-recommendations.png
  content/refguide/attachments/mx-assist-logic-bot/mx-assist-system-variables.png
  content/refguide/attachments/progressive-web-app/view-menu.png
  content/refguide/attachments/project-menu/project-menu.png
  content/refguide/attachments/project-menu/tools.png
  content/refguide/attachments/run-menu/run-menu.png
  content/refguide/attachments/upload-to-version-control/upload-to-version-control-server.png
  content/refguide/attachments/version-control-menu/version-control-menu.png
  content/refguide/attachments/view-menu/changes.mp4
  content/refguide/attachments/view-menu/view-menu.png
  content/refguide/create-deployment-package-dialog.md
  content/refguide/deploy-to-the-cloud-dialog.md
  content/refguide/find-and-find-advanced.md
  content/refguide/menus.md
  content/refguide/mx-assist-logic-bot.md
  content/refguide/preferences-dialog.md
  content/refguide/progressive-web-app.md
  content/refguide/run-menu.md
  content/refguide/version-control-menu.md
  content/releasenotes/developer-portal/mendix-cloud.md
  content/releasenotes/studio-pro/8.18.md
  content/releasenotes/studio-pro/9.2.md
Labels: 9.3.0

#3409 The api-doc endpoint is only available when there is at least one service
  content/refguide/runtime.md
Labels: 9.3.0

#3395 Add newly supported languages in 9.x
  content/refguide/language-settings.md
Labels: 9.3.0

#3476 Private Cloud release notes June 29
  content/developerportal/deploy/private-cloud-cluster.md
  content/developerportal/deploy/private-cloud-deploy.md
  content/developerportal/deploy/private-cloud-operator.md
  content/developerportal/deploy/private-cloud-supported-environments.md
  content/developerportal/deploy/private-cloud.md
  content/releasenotes/developer-portal/deployment.md
  content/releasenotes/developer-portal/mendix-for-private-cloud.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3488 Sprintr release 11.3.0
  content/developerportal/collaborate/api-key.md
  content/developerportal/collaborate/attachments/general-settings/general-settings.png
  content/developerportal/collaborate/attachments/stories/new-story.jpg
  content/developerportal/collaborate/attachments/team/team.png
  content/developerportal/collaborate/general-settings.md
  content/developerportal/collaborate/stories.md
  content/developerportal/collaborate/team.md
  content/releasenotes/developer-portal/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#3466 8.18.8 RN
  content/releasenotes/studio-pro/8.18.md
Labels: 8.18.8

#3433 Remove unsupported databases
  content/refguide8/system-requirements.md
Labels: 8.18.8

#3493 Add borders to a screenshot and apply bold to UI text
  content/developerportal/collaborate/attachments/general-settings/general-settings.png
  content/developerportal/collaborate/general-settings.md
Labels: Internal WIP
