Repository mendix/docs, pull requests merged in 2022-06, with the labels that each got.

#4621 7.23.31 RN
  content/en/docs/releasenotes/studio-pro/7/7.23.md
Labels: Future release

#4641 Catalog 2.35
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4643 Mendix Cloud Release Notes - 2 June 2022
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
Labels: Future release, Update release and/or featured date

#4602 9.14 RN
  content/en/docs/releasenotes/studio-pro/9/9.14.md
  layouts/partials/landingpage/latest-releases.html
Labels: 9.14

#4525 Adoptium java11
  content/en/docs/refguide/general/system-requirements.md
  content/en/docs/refguide7/general/system-requirements.md
  content/en/docs/refguide8/general/system-requirements.md
Labels: 9.14

#4487 [NC-675] add onchange behavior to text area native widget
  content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
Labels: 9.14

#4551 Published OData metrics
  content/en/docs/refguide/runtime/metrics.md
Labels: 9.14

#4461 Update the list of available languages
  content/en/docs/refguide/modeling/menus/translatable-texts/language-settings.md
Labels: 9.14

#4649 Security implementation - changes from Jasper
  content/en/docs/data-hub/data-hub-catalog/security.md
  static/attachments/data-hub/data-hub-catalog/security/federation-with-ADFS-SAML-schematic.png
Labels: Internal WIP

#4652 Correct misleading information about restoring S3 files
  content/en/docs/developerportal/operate/backups/restore-backup.md
Labels: Needs R&D technical verification

#4625 Update the Apps Section in Control Center
  content/en/docs/developerportal/control-center/_index.md
  static/attachments/developerportal/control-center/check-mark.svg
  static/attachments/developerportal/control-center/cross-mark.svg
Labels: Internal WIP

#4670 Add policy
  content/en/docs/appstore/general/share-app-store-content.md
Labels: Internal WIP

#4671 Lead generation details section added
  content/en/docs/appstore/general/share-app-store-content.md
  static/attachments/appstore/general/share-app-store-content/general.jpg
Labels: Edit images after merging

#4636 Fix Google Font calls for different font weights
  assets/scss/_alerts.scss
  assets/scss/_content.scss
  assets/scss/_front-page.scss
  assets/scss/_nav.scss
  assets/scss/_sidebar-toc.scss
  assets/scss/_sidebar-tree.scss
  assets/scss/_variables_project.scss
  layouts/partials/sidebar-tree.html
Labels: Internal WIP

#4640 9.6.12 RN
  content/en/docs/releasenotes/studio-pro/9/9.6.md
Labels: Future release

#4682 Update
  content/en/docs/releasenotes/security-advisories/_index.md
Labels: Future release

#4673 9.14.1 RN
  content/en/docs/releasenotes/studio-pro/9/9.14.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Update release and/or featured date

#4687 DataHub Release 2.36
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4696 Update settings-languages.md
  content/en/docs/studio/settings/settings-languages.md
Labels: Needs language review

#4694 Update versions of SAP Fiori themes for Mendix 9
  content/en/docs/partners/sap/sap-fiori-3-0/_index.md
  content/en/docs/partners/sap/sap-fiori-3-0/sap-fiori-building-blocks.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/sap-cloud-platform.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/partners/sap/sap-fiori-3-0/theme-order.png
Labels: Future release, Needs R&D technical verification, Update release and/or featured date

#4695 Clarify Statsd Filters
  content/en/docs/refguide/runtime/metrics.md
Labels: Needs R&D technical verification

#4703 Add link to figure
  content/en/docs/howto/general/install.md
  content/en/docs/howto/integration/importing-excel-documents/_index.md
  content/en/docs/howto7/general/install-the-mendix-desktop-modeler.md
  content/en/docs/howto7/integration/importing-excel-documents/_index.md
  content/en/docs/howto8/integration/importing-excel-documents/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md
  content/en/docs/refguide7/desktop-modeler/application-logic/common-elements/activities/_index.md
  content/en/docs/refguide7/desktop-modeler/application-logic/microflows/_index.md
  content/en/docs/refguide7/desktop-modeler/application-logic/nanoflows/_index.md
  content/en/docs/refguide7/desktop-modeler/document-templates/data-grid-document-template/_index.md
  content/en/docs/refguide7/desktop-modeler/pages/_index.md
  content/en/docs/refguide7/desktop-modeler/pages/data-widgets/_index.md
  content/en/docs/refguide8/modeling/application-logic/activities/_index.md
  content/en/docs/refguide8/modeling/application-logic/microflows/_index.md
  content/en/docs/refguide8/modeling/application-logic/nanoflows/_index.md
Labels: Internal WIP

#4657 Updated Mobile Structure
  content/en/docs/refguide/mobile/_index.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/_index.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/building-native-apps/_index.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/building-native-apps/deploying-native-app.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/distributing-native-apps.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/native-debug.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/overtheair-updates.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/testing-mobile-apps.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/_index.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/augmented-reality/_index.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/deep-links.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/local-notifications/_index.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/location-&-maps.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/_index.md
Labels: Needs language review

#4719 release notes added
  content/en/docs/apidocs-mxsdk/apidocs/data-hub-apis.md
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4721 Document mx check and mx show-version
  content/en/docs/refguide/general/mx-command-line-tool.md
Labels: Needs language review

#4724 Proofread metrics.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/refguide/runtime/metrics.md
Labels: Needs R&D technical verification, Needs language review

#4739 Release Note - update to TLS certificates
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Update release and/or featured date

#4720 9.15 Release Notes
  content/en/docs/releasenotes/studio-pro/9/9.15.md
  layouts/partials/landingpage/latest-releases.html
Labels: 9.15

#4715 Add annotation description to Studios
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
  content/en/docs/studio/workflows/_index.md
  content/en/docs/studio/workflows/workflows-general-activities.md
  static/attachments/refguide/modeling/application-logic/workflows/annotation.png
  static/attachments/studio/workflows/workflows-general-activities/annotation.jpg
Labels: 9.15

#4707 Add New Expressions
  content/en/docs/refguide/modeling/application-logic/expressions/_index.md
  content/en/docs/refguide/modeling/application-logic/expressions/add-date-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/subtract-date-function-calls.md
  content/en/docs/studio/expressions/_index.md
Labels: 9.15

#4499 [NC-591] Add autofocus option to TextBox and TextArea native widgets
  content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
  content/en/docs/refguide/modeling/pages/input-widgets/text-box.md
Labels: 9.15

#4601 Send and Delete set $latestHttpResponse in 9.15.0
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/external-object-activities/delete-external-object.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/external-object-activities/send-external-object.md
Labels: 9.15

#4623 Update external entities
  content/en/docs/refguide/modeling/domain-model/associations/association-properties.md
  content/en/docs/refguide/modeling/domain-model/external-entities.md
  static/attachments/refguide/modeling/domain-model/external-entities/association-properties-one-way-navigable.png
  static/attachments/refguide/modeling/domain-model/external-entities/association-properties.png
  static/attachments/refguide/modeling/domain-model/external-entities/external-entity-associations.png
Labels: 9.15

#4747 REG-248 catalog release 2.38.0
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4757 Update Email Connector screenshots
  static/attachments/appstore/connectors/email-connector/digital-signature.png
  static/attachments/appstore/connectors/email-connector/email-encryption.png
  static/attachments/appstore/connectors/email-connector/other-account-settings.png
  static/attachments/appstore/connectors/email-connector/sign-encrypt-domain-model.png
Labels: Internal WIP

#4756 9.15 RN
  content/en/docs/releasenotes/studio-pro/9/9.15.md
  content/en/docs/releasenotes/studio/9.7-and-above.md
  layouts/partials/landingpage/latest-releases.html
Labels: 9.15
