Repository mendix/docs, pull requests merged in 2022-09, with the labels that each got.

#4990 Datahub catalog Release 2.47
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4953 Kk proofreading deployment2
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
  static/attachments/developerportal/deploy/mendix-cloud-deploy/environments/deploy-environments.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/environments/deployment-package.png
Labels: Internal WIP

#4993 modify preference widget doc
  content/en/docs/appstore/app-services/3d-viewer/_index.md
  static/attachments/appstore/app-services/3d-viewer/preferences-general.png
Labels: Needs R&D technical verification

#5002 Corrected the capitalization of sleep mode
  content/en/docs/studio/publishing-app/_index.md
  content/en/docs/studio7/publishing-app/_index.md
  content/en/docs/studio8/publishing-app/_index.md
Labels: Internal WIP

#4964 Troubleshooting BYOIDP
  content/en/docs/developerportal/control-center/set-up-sso-byoidp.md
Labels: Internal WIP

#5007 Delete Error Event from the Events section of Nanoflows
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md
Labels: Changes requested

#5012 Update Marketplace deprecation definition
  content/en/docs/appstore/general/app-store-content-support.md
Labels: Internal WIP

#5014 Kk canvas
  content/en/docs/apidocs-mxsdk/mxsdk/sdk-howtos/manipulating-existing-models/changing-things-in-the-model.md
  content/en/docs/appstore/app-services/text-analytics.md
  content/en/docs/appstore/app-services/text-to-speech.md
  content/en/docs/appstore/app-services/translation.md
  content/en/docs/appstore/creating-content/connector-guide-build/connector-guide-best-practices.md
  content/en/docs/refguide/modeling/pages/page-resources/page-templates.md
  content/en/docs/refguide7/desktop-modeler/pages/layout.md
  content/en/docs/refguide7/desktop-modeler/pages/page-templates.md
  content/en/docs/refguide8/modeling/pages/page-resources/layout/_index.md
  content/en/docs/refguide8/modeling/pages/page-resources/layout/placeholder.md
  content/en/docs/refguide8/modeling/pages/page-resources/page-templates.md
  content/en/docs/releasenotes/studio-pro/7/7.14.md
  content/en/docs/releasenotes/studio-pro/8/8.3.md
  content/en/docs/releasenotes/studio-pro/9/9.17.md
  content/en/docs/releasenotes/studio/7.11-7.23.md
Labels: Internal WIP

#4992 Proofreading - Filter Data on an Overview Page
  content/en/docs/howto/general/setting-up-the-navigation-structure.md
  content/en/docs/howto/logic-business-rules/filtering-data-on-an-overview-page.md
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581350.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581351.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581353.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581354.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581355.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581359.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581362.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581363.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581364.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581365.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581366.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581367.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581368.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581370.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581371.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/18581372.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/XPath-constraint-Rotterdam-customers.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/XPath-constraint-minimun-price-50.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/XPath-constraint-open-status-and-minimum-price-50.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/XPath-constraint-open-status-or-minimum-price-50.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/XPath-constraint-open-status.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/create-search-field-minimum-total-price.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/create-search-field-order-status.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/empty-search-bar-section.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/example-customers-data.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/example-orders-data.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/open-XPath-constraint.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/order-list-Rotterdam-customers.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/order-list-minimum-price-50-using-XPath.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/order-list-minimum-price-50.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/order-list-open-status-and-minimum-price-50.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/order-list-open-status-using-XPath.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/order-list-open-status.png
  static/attachments/howto/logic-business-rules/filtering-data-on-an-overview-page/order-status-search-field.png
Labels: Internal WIP

#5026 Hide feedback widget on old content
  content/en/docs/howto7/_index.md
  content/en/docs/howto8/_index.md
  content/en/docs/refguide7/_index.md
  content/en/docs/refguide8/_index.md
  content/en/docs/studio-how-to8/_index.md
  content/en/docs/studio7/_index.md
  content/en/docs/studio8/_index.md
Labels: Internal WIP

#5015 9.17.1 RN
  content/en/docs/releasenotes/studio-pro/9/9.17.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5041 Catalog Release 2.49
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5066 Update language example
  content/en/docs/refguide/modeling/menus/translatable-texts/language-settings.md
  static/attachments/refguide/modeling/menus/translatable-texts/language-settings/01_app_settings.png
  static/attachments/refguide/modeling/menus/translatable-texts/language-settings/add-language.png
  static/attachments/refguide/modeling/menus/translatable-texts/language-settings/app-settings.png
  static/attachments/refguide/modeling/menus/translatable-texts/language-settings/date-format.png
  static/attachments/refguide/modeling/menus/translatable-texts/language-settings/edit-language.png
Labels: Internal WIP

#5000 Kk proofreading deployment3
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
Labels: Internal WIP

#5031 Proofread second runtime file
  content/en/docs/refguide/runtime/runtime-server.md
Labels: Internal WIP

#5075 Update to feature release calendar
  content/en/docs/releasenotes/mx-world-2021/_index.md
Labels: Internal WIP

#5022 Proofread first file in the runtime batch
  content/en/docs/refguide/runtime/_index.md
  static/attachments/refguide/runtime/runtime-overview.png
Labels: Internal WIP

#5003 Describe database-specific limitations on unlimited string uniqueness
  content/en/docs/refguide/runtime/data-storage/case-sensitive-database-behavior.md
  content/en/docs/refguide/runtime/data-storage/unlimited-string-behavior.md
Labels: Needs R&D technical verification, Needs language review

#5080 Catalog 2.50.0 release notes
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5072 9.12.6 RN
  content/en/docs/releasenotes/studio-pro/9/9.12.md
Labels: Future release, Update release and/or featured date

#5055 add documentation for language selector widget
  content/en/docs/appstore/widgets/language-selector.md
  content/en/docs/appstore/widgets/popup-menu.md
Labels: Future release

#5086 Add business events info to 9.18 RN
  content/en/docs/releasenotes/studio-pro/9/9.18.md
Labels: 9.18

#5058 Add descriptions to children docs-Studio Pro guide
  content/en/docs/refguide/general/_index.md
  content/en/docs/refguide/general/mx-command-line-tool.md
  content/en/docs/refguide/general/mxbuild.md
  content/en/docs/refguide/general/third-party-licenses.md
  content/en/docs/refguide/java-programming/troubleshooting.md
  content/en/docs/refguide/java-programming/using-eclipse.md
  content/en/docs/refguide/mobile/_index.md
  content/en/docs/refguide/modeling/_index.md
  content/en/docs/refguide/modeling/data-types.md
  content/en/docs/refguide/modeling/domain-model/_index.md
  content/en/docs/refguide/modeling/images.md
  content/en/docs/refguide/modeling/import-and-export/_index.md
  content/en/docs/refguide/modeling/integration/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/_index.md
  content/en/docs/refguide/modeling/pages/_index.md
  content/en/docs/refguide/modeling/resources/_index.md
  content/en/docs/refguide/modeling/studio-pro-overview/_index.md
  content/en/docs/refguide/quickstart-guide/_index.md
  content/en/docs/refguide/runtime/_index.md
  content/en/docs/refguide/runtime/clustered-mendix-runtime.md
  content/en/docs/refguide/runtime/communication-patterns.md
  content/en/docs/refguide/runtime/data-storage/_index.md
  content/en/docs/refguide/runtime/date-and-time-handling/_index.md
  content/en/docs/refguide/runtime/logging.md
  content/en/docs/refguide/runtime/login-behavior.md
  content/en/docs/refguide/runtime/mendix-client.md
  content/en/docs/refguide/runtime/metrics.md
  content/en/docs/refguide/runtime/monitoring-client-state.md
  content/en/docs/refguide/runtime/objects-and-caching.md
  content/en/docs/refguide/runtime/runtime-deployment.md
  content/en/docs/refguide/runtime/runtime-java/_index.md
  content/en/docs/refguide/runtime/runtime-server.md
  content/en/docs/refguide/runtime/websockets-in-runtime.md
  content/en/docs/refguide/version-control/_index.md
  content/en/docs/refguide/version-control/collaborative-development/_index.md
  content/en/docs/refguide/version-control/collaborative-development/collaborative-development-troubleshooting.md
  content/en/docs/refguide/version-control/new-merge-algorithm.md
  content/en/docs/refguide/version-control/on-premises-git.md
  content/en/docs/refguide/version-control/on-premises-svn.md
  content/en/docs/refguide/version-control/troubleshoot-git-issues.md
  content/en/docs/refguide/version-control/troubleshoot-version-control-issues.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro.md
  content/en/docs/refguide/version-control/version-control-faq.md
Labels: Internal WIP

#5047 Windows Cmdlets for CI/CD
  content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
Labels: Needs R&D technical verification

#5017 Proofreading - Set Up Error Handling -and- Error Event
  content/en/docs/appstore/connectors/aws-s3-connector.md
  content/en/docs/howto/general/dev-best-practices.md
  content/en/docs/howto/logic-business-rules/create-a-custom-save-button.md
  content/en/docs/howto/logic-business-rules/define-access-rules-using-xpath.md
  content/en/docs/howto/logic-business-rules/extending-your-application-with-custom-java.md
  content/en/docs/howto/logic-business-rules/java-api-tutorial.md
  content/en/docs/howto/logic-business-rules/optimizing-microflow-aggregates.md
  content/en/docs/howto/logic-business-rules/optimizing-retrieve-activities.md
  content/en/docs/howto/logic-business-rules/set-up-error-handling.md
  content/en/docs/howto/logic-business-rules/trigger-microflow-from-menu-item.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/synchronize.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/call-rest-action.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/committing-objects.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/rollback-object.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/events/error-event.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflow-element-common-properties.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/error-handling-in-nanoflows.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/nanoflow.md
  content/en/docs/refguide/modeling/integration/consumed-odata-services/consumed-odata-service.md
  static/attachments/howto/logic-business-rules/set-up-error-handling/18580962.png
  static/attachments/howto/logic-business-rules/set-up-error-handling/18580963.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/blue.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/continue-and-continue.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/continue-and-rollback.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/continue-option.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/custom-with-rollback-diagram.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/custom-with-rollback-microflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/custom-with-rollback-option.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/custom-without-rollback-diagram.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/custom-without-rollback-microflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/custom-without-rollback-option.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/default-error-handling-diagram.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/default-error-handling-microflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/green.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/orange.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/rollback-and-continue.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/rollback-and-rollback.png
Labels: Internal WIP

#5092 Extend warning about usage of OpenSSL 3 on Windows
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/certificates.md
Labels: Needs Support verification

#5103 #CAT-2382: release notes for Catalog 2.51.0
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5056 AWS Authentication Connector
  content/en/docs/appstore/connectors/aws-authentication.md
  static/attachments/appstore/connectors/aws-authentication/certificate-currently-enabled.png
  static/attachments/appstore/connectors/aws-authentication/client-certificate-id.png
  static/attachments/appstore/connectors/aws-authentication/custom-settings.png
  static/attachments/appstore/connectors/aws-authentication/get-static-credentials.png
  static/attachments/appstore/connectors/aws-authentication/iam-user-keys.png
  static/attachments/appstore/connectors/aws-authentication/identifier.png
  static/attachments/appstore/connectors/aws-authentication/microflow-get-session-credentials.png
  static/attachments/appstore/connectors/aws-authentication/microflow-get-static-credentials.png
  static/attachments/appstore/connectors/aws-authentication/ongoing-connections-certificate.png
Labels: Future release

#5113 Private Cloud Operator Release Notes
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs R&D technical verification, Update release and/or featured date

#5060 9.18 RN
  content/en/docs/releasenotes/studio-pro/9/9.18.md
  content/en/docs/releasenotes/studio-pro/lts-mts.md
  layouts/partials/landingpage/latest-releases.html
Labels: 9.18

#4955 Add docs for new sqrt function
  content/en/docs/refguide/modeling/application-logic/expressions/mathematical-function-calls.md
Labels: 9.18

#4819 [SCR-3679] add documentation for begin-of and end-of date functions
  content/en/docs/refguide/modeling/application-logic/expressions/_index.md
  content/en/docs/refguide/modeling/application-logic/expressions/begin-of-date-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/end-of-date-function-calls.md
  content/en/docs/studio/expressions/_index.md
Labels: 9.18

#5062 new pluggable widgets config api doc
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/_index.md
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-config-api.md
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-studio-apis.md
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/structure-preview-example-container.png
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/structure-preview-example-datasource.png
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/structure-preview-example-drop-zone.png
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/structure-preview-example-image.png
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/structure-preview-example-row-layout-fixed.png
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/structure-preview-example-row-layout-grow-2.png
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/structure-preview-example-row-layout-grow.png
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/structure-preview-example-selectable.png
Labels: 9.18

#4668 Data Broker Business Events - Docs for GA
  content/en/docs/appstore/modules/business-events.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
  content/en/docs/refguide/modeling/integration/business-event-services/_index.md
  static/attachments/appstore/modules/business-events/four-entities-in-domain-model.png
  static/attachments/appstore/modules/business-events/payload-event-entity-2.png
  static/attachments/appstore/modules/business-events/payload-event-entity-3.png
  static/attachments/appstore/modules/business-events/postgres.png
  static/attachments/appstore/modules/business-events/specialized-entity.png
  static/attachments/appstore/modules/business-events/subscriptions-available-2.png
Labels: 9.18

#5073 Add Page Explorer section
  content/en/docs/refguide/modeling/menus/view-menu/_index.md
  content/en/docs/refguide/modeling/menus/view-menu/app-explorer/_index.md
  content/en/docs/refguide/modeling/menus/view-menu/changes-pane.md
  content/en/docs/refguide/modeling/menus/view-menu/data-hub-pane.md
  content/en/docs/refguide/modeling/menus/view-menu/errors-pane/_index.md
  content/en/docs/refguide/modeling/menus/view-menu/page-explorer.md
  content/en/docs/refguide/modeling/pages/page/_index.md
  static/attachments/refguide/modeling/menus/view-menu/page-explorer.png
  static/attachments/refguide/modeling/menus/view-menu/view-menu.png
Labels: 9.18

#5083 Update Mx9 dependencies
  content/en/docs/howto/general/install.md
  content/en/docs/refguide/general/system-requirements.md
Labels: 9.18

#5076 Update preferences-dialog.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
Labels: 9.18

#5045 Page Parameters in Studio
  content/en/docs/studio-how-to/microflows/microflows-how-to-configure-decision/microflows-how-to-configure-decision-p1.md
  content/en/docs/studio-how-to/pages/pages-how-to-attach-files.md
  content/en/docs/studio-how-to/pages/pages-how-to-attach-images.md
  content/en/docs/studio-how-to/pages/pages-how-to-configure-form.md
  content/en/docs/studio-how-to/pages/pages-how-to-configure-list/pages-how-to-configure-list-and-details-on-one-page.md
  content/en/docs/studio-how-to/pages/pages-how-to-configure-list/pages-how-to-configure-list-and-pop-up-page.md
  content/en/docs/studio-how-to/pages/pages-how-to-set-visibility.md
  content/en/docs/studio/page-editor/_index.md
  content/en/docs/studio/page-editor/page-editor-widgets/page-editor-data-view-list-view.md
  content/en/docs/studio/page-editor/page-editor-widgets/page-editor-widgets-input-elements.md
  content/en/docs/studio/page-editor/page-parameter/_index.md
  static/attachments/studio-how-to/microflows/microflows-how-to-configure-decision/microflows-how-to-configure-decision-p1/configure-condition-grade.png
  static/attachments/studio-how-to/microflows/microflows-how-to-configure-decision/microflows-how-to-configure-decision-p1/configure-condition-pop-up.png
  static/attachments/studio-how-to/microflows/microflows-how-to-configure-decision/microflows-how-to-configure-decision-p1/parameter-properties.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-files/column-list.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-files/create-attach-file-page.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-files/create-object-button.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-files/create-object-property.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-files/list-4.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-files/list-view-configured.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-files/open-page-button.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-files/select-attribute.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-files/select-file-entity.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-images/button-style-change.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-images/create-new-page-images.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-images/form-example.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-images/image-report-association.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-images/new-button.png
  static/attachments/studio-how-to/pages/pages-how-to-attach-images/open-page-button.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-form/create-new-page.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-form/data-grid-over-association.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-form/data-view-source.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-form/manage-checklist.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-list-and-pop-up-page/create-page.jpg
  static/attachments/studio-how-to/pages/pages-how-to-configure-list/button-properties.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-list/create-master-detail.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-list/job-title-text-box.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-list/new-parameter.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-list/parameter-properties.png
  static/attachments/studio-how-to/pages/pages-how-to-configure-list/title.png
  static/attachments/studio-how-to/pages/pages-how-to-set-visibility/eye-icon.png
  static/attachments/studio/page-editor/page-parameter/page-parameters.png
  static/attachments/studio/page-editor/pages-icon.png
Labels: 9.18

#5042 Document native database encryption [9.18]
  content/en/docs/refguide/mobile/distributing-mobile-apps/logging.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/_index.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
  static/attachments/refguide/mobile/offline-first/enable-native-db-encryption.png
Labels: 9.18

#4973 Update pluggable-widgets-studio-apis.md
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-studio-apis.md
Labels: 9.18

#4892 Document offline-first apps and auto-committed objects
  content/en/docs/refguide/mobile/introduction-to-mobile-technologies/progressive-web-app.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/auto-committed-objects.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/committing-objects.md
  content/en/docs/refguide/runtime/custom-settings/tricky-custom-runtime-settings.md
  static/attachments/refguide/mobile/offline-first/example-domain-model.png
  static/attachments/refguide/mobile/offline-first/flow-creating-invalid-customer-reference.png
  static/attachments/refguide/mobile/offline-first/nanoflow-causing-auto-committed-object.png
Labels: 9.18

#5104 Clarify Data Hub info in guide
  content/en/docs/data-hub/_index.md
Labels: Internal WIP

#5065 Update Studio Pro refguide for Multiple Page Parameters (9.18)
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/show-page.md
  content/en/docs/refguide/modeling/menus/view-menu/errors-pane/consistency-errors/consistency-errors-pages.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-sources/context-source.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-view.md
  content/en/docs/refguide/modeling/pages/on-click-event.md
  content/en/docs/refguide/modeling/pages/page/page-properties.md
  static/attachments/refguide/modeling/pages/on-click-event/page-title-property.png
Labels: 9.18

#4919 Add a draft on Validation Assist
  content/en/docs/refguide/modeling/mx-assist-studio-pro/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/performance-best-practices.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-validation-assist.md
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/mendix-assist-icon.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/mx-assist-on-off-button.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/mx-assist-recommendations.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/mx-assist-system-variables.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/anti-pattern-overview.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/app-model.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/auto-fixable.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/best-practice.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/drop-down-menu.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/fix-performance-issue.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/indicator-in-editor.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/performance-bot-pane.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/performance-recommendation.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/viewing-anti-pattern.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-validation-assist/extract-sub-microflow-dialog.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-validation-assist/extract-sub-microflow.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-validation-assist/generate-validation-microflow-dialog.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-validation-assist/generate-validation-microflow-option.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-validation-assist/select-microflow.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-validation-assist/validation-microflow.png
Labels: 9.18

#5081 Studio release notes
  content/en/docs/releasenotes/studio/9.7-and-above.md
  content/en/docs/studio/microflows/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Update release and/or featured date, 9.18

#5115 Small changes to email connector
  content/en/docs/appstore/connectors/email-connector.md
Labels: Internal WIP
