Repository mendix/docs, pull requests merged in 2022-08, with the labels that each got.

#4864 Email Connector updates
  content/en/docs/appstore/connectors/email-connector.md
Labels: Internal WIP

#4863 Kk proofreading logic
  content/en/docs/appstore/modules/unit-testing.md
  content/en/docs/howto/data-models/create-a-basic-data-layer.md
  content/en/docs/howto/logic-business-rules/extract-and-use-sub-microflows.md
  content/en/docs/howto/testing/testing-microflows-using-the-unittesting-module.md
Labels: Internal WIP

#4877 Datahub 2.43.0 external release notes
  content/en/docs/data-hub/data-hub-catalog/search.md
  content/en/docs/data-hub/write-data/_index.md
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4885 9.16.1 RN
  content/en/docs/releasenotes/studio-pro/9/9.16.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Update release and/or featured date

#4882 Update modelerdownload button link
  layouts/shortcodes/modelerdownloadlink.html
Labels: Internal WIP

#4854 Notifications in the Dev Portal + Release Notes
  content/en/docs/developerportal/_index.md
  content/en/docs/developerportal/collaborate/feedback.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/developerportal/notification-settings-icon.png
  static/attachments/developerportal/notifications-icon.png
Labels: Future release

#4896 Update _index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mxcloudv4/_index.md
Labels: Awaiting Response

#4888 Kk proofreading logic2
  content/en/docs/howto/logic-business-rules/working-with-lists-in-a-microflow.md
Labels: Internal WIP

#4901 Updated according to latest development
  content/en/docs/appstore/modules/email-with-templates.md
Labels: Future release

#4899 Catalog 2.44
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4443 Advanced Audit Trail doc
  content/en/docs/appstore/app-services/advanced-audit-trail.md
  content/en/docs/appstore/modules/advanced-audit-trail-ui.md
  static/attachments/appstore/app-services/advanced-audit-trail/integration-diagram.png
Labels: Future release, Internal WIP

#4886 9.12.5 RN
  content/en/docs/releasenotes/studio-pro/9/9.12.md
Labels: Future release

#4910 Tekton documentation updates.
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-tekton/_index.md
Labels: Needs R&D technical verification, Waiting for CLA

#4920 7.23.32 RN
  content/en/docs/releasenotes/studio-pro/7/7.23.md
Labels: Future release

#4930 Remove unwanted files from Private Cloud PR.
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-cli-non-interactive.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-migrating.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/choose-operating-system.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/cluster-details.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/download-executable.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/download-operator-version.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/image2.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/image3.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/image4.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/image6.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/installation-command.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/installer-options.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/post-install-landing-page.png
Labels: Internal WIP

#4929 cat-2350 catalog release 2.45
  content/en/docs/developerportal/control-center/data-hub-admin.md
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4922 Remove PostgreSQL on AWS for SAP deployments
  content/en/docs/developerportal/deploy/sap-cloud-platform.md
  content/en/docs/partners/sap/sap-postgresql-on-aws.md
  content/en/docs/releasenotes/deployment/sap-cloud-platform.md
  static/attachments/developerportal/deploy/sap-cloud-platform/aws-rds.png
  static/attachments/partners/sap/sap-postgresql-on-aws/database-new-app.png
  static/attachments/partners/sap/sap-postgresql-on-aws/database-new-environment.png
  static/attachments/partners/sap/sap-postgresql-on-aws/database-service.png
  static/attachments/partners/sap/sap-postgresql-on-aws/postgresql-for-aws.png
Labels: Needs R&D technical verification

#4947 Test commit
  content/en/docs/appstore/widgets/list-view-controls.md
Labels: Internal WIP

#4949 Test
  content/en/docs/addons/ats-addon/ht/ht-one/ht-one-create-a-test-case.md
Labels: Internal WIP

#4911 WIP: Add examples to clarify behavior of absent associated objects
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
Labels: Needs R&D technical verification

#4939 Development workflow ad hoc jump to
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/apply-jump-to-option.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/generate-jump-to-options.md
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
  content/en/docs/refguide/modeling/application-logic/workflows/jump-to.md
  static/attachments/refguide/modeling/application-logic/workflows/jump-to/jump-to-entities.jpg
Labels: Needs language review, 9.17

#4948 Mx Platform Security Release Note
  content/en/docs/releasenotes/developer-portal/_index.md
Labels: Needs R&D technical verification, Internal WIP

#4959 Add "connector kit 2" section (expansion of OData capabilities) to 9.17 RN
  content/en/docs/releasenotes/studio-pro/9/9.17.md
Labels: 9.17

#4884 Adjust code fence styling
  assets/scss/_code.scss
Labels: Internal WIP

#4868 External Entities Sans Catalog
  content/en/docs/data-hub/_index.md
  content/en/docs/data-hub/data-hub-catalog/_index.md
  content/en/docs/data-hub/data-hub-catalog/register-data.md
  content/en/docs/data-hub/without-mendix-cloud/_index.md
  content/en/docs/refguide/modeling/domain-model/external-entities.md
  content/en/docs/refguide/modeling/integration/consumed-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/consumed-odata-services/consumed-odata-service-requirements.md
  content/en/docs/refguide/modeling/integration/consumed-odata-services/consumed-odata-service.md
  content/en/docs/refguide/modeling/menus/view-menu/data-hub-pane.md
  content/en/docs/refguide8/modeling/integration/consumed-odata-services/consumed-odata-service-requirements.md
  content/en/docs/refguide8/modeling/menus/view-menu/data-hub-pane.md
  content/en/docs/releasenotes/studio-pro/8/8.14.md
  content/en/docs/releasenotes/studio/8.7-8.18.md
  content/en/docs/studio/work-with-data/_index.md
  content/en/docs/studio/work-with-data/data-hub-in-studio.md
  content/en/docs/studio8/work-with-data/_index.md
  content/en/docs/studio8/work-with-data/data-hub-in-studio.md
Labels: Needs R&D technical verification, Internal WIP

#4970 REG-287 Catalog release 2.46.0
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4969 Release notes for Private cloud portal 2.15.0
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Update release and/or featured date

#4954 Operator 2.7.0 release notes and documentation update
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-operator.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/cloudSelectionPage.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/generalPage.png
Labels: Update release and/or featured date

#4977 Update _index.md
  content/en/docs/releasenotes/app-store/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4974 Draft Management Release changes. My Drafts Page added.
  content/en/docs/appstore/general/app-store-overview.md
  content/en/docs/appstore/general/share-app-store-content.md
  static/attachments/appstore/general/app-store-overview/company-content.png
  static/attachments/appstore/general/app-store-overview/my-content.png
  static/attachments/appstore/general/app-store-overview/my-draft-menu-options.png
  static/attachments/appstore/general/app-store-overview/my-draft.png
Labels: Future release, Edit images after merging

#4976 File document in REST operation
  content/en/docs/refguide/modeling/integration/published-rest-services/published-rest-service/published-rest-operation.md
Labels: Internal WIP

#4984 Reviewed the occurrences of ampersands in bold and italics formatting…
  content/en/docs/apidocs-mxsdk/_index.md
  content/en/docs/appstore/general/share-app-store-content.md
  content/en/docs/developerportal/collaborate/general-settings/_index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/_index.md
  content/en/docs/developerportal/operate/backups/_index.md
  content/en/docs/howto/extensibility/best-practices-javascript-actions.md
  content/en/docs/howto/front-end/use-navigation-layouts.md
  content/en/docs/howto8/extensibility/best-practices-javascript-actions.md
  content/en/docs/howto8/front-end/use-navigation-layouts.md
  content/en/docs/refguide/modeling/menus/view-menu/app-explorer/security/studio-security-enabled.md
  content/en/docs/refguide/modeling/pages/input-widgets/input-reference-set-selector.md
  content/en/docs/refguide/modeling/pages/input-widgets/reference-selector.md
  content/en/docs/refguide8/modeling/menus/view-menu/project-explorer/security/studio-security-enabled.md
  content/en/docs/refguide8/modeling/pages/input-widgets/input-reference-set-selector.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  content/en/docs/releasenotes/studio/7.11-7.23.md
  content/en/docs/releasenotes/studio/8.0-8.6.md
  content/en/docs/releasenotes/studio/8.7-8.18.md
  content/en/docs/releasenotes/studio/9.0-9.6.md
  content/en/docs/studio-how-to/security-how-to-configure-roles/_index.md
  content/en/docs/studio/general/general-versions.md
  content/en/docs/studio/page-editor/page-editor-widgets/page-editor-widgets-images-and-files.md
  content/en/docs/studio/publishing-app/_index.md
  content/en/docs/studio7/navigation/_index.md
  content/en/docs/studio7/publishing-app/_index.md
  content/en/docs/studio8/page-editor/page-editor-widgets/page-editor-widgets-images-and-files.md
  content/en/docs/studio8/publishing-app/_index.md
Labels: Internal WIP

#4837 Studio Pro 9.17.0 introduces export of OpenApi
  content/en/docs/refguide/modeling/integration/published-odata-services/_index.md
Labels: 9.17

#4862 Connector Kit 2 - Docs for GA
  content/en/docs/appstore/creating-content/connector-guide-build/_index.md
  content/en/docs/howto/integration/consume-a-rest-service.md
  content/en/docs/refguide/modeling/integration/published-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/published-odata-services/odata-representation.md
  content/en/docs/refguide/modeling/integration/published-odata-services/published-odata-resource.md
  content/en/docs/refguide/modeling/integration/wrap-services-odata.md
  static/attachments/refguide/modeling/integration/wrap-services-odata/call-microflow-implementation.png
  static/attachments/refguide/modeling/integration/wrap-services-odata/newtwitterinput-microflow.png
  static/attachments/refguide/modeling/integration/wrap-services-odata/query-followers-microflow.png
  static/attachments/refguide/modeling/integration/wrap-services-odata/read-uri-data.png
  static/attachments/refguide/modeling/integration/wrap-services-odata/showuserpage-microflow.png
  static/attachments/refguide/modeling/integration/wrap-services-odata/twitter-client-domain-model.png
  static/attachments/refguide/modeling/integration/wrap-services-odata/twitter-connector-domain-model.png
Labels: 9.17

#4858 Document graceful handling for failed file downloads (9.17)
  content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/synchronization.md
Labels: 9.17

#4945 [WTF-1126] Add documentation for linked association properties (9.17)
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
Labels: 9.17

#4918 Update version control guide with MxToolSet
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro.md
Labels: 9.17

#4941 Update for mx check to add option to specify a suppress warnings file
  content/en/docs/refguide/general/mx-command-line-tool.md
Labels: 9.17

#4952 Add Studio RN for 9.17
  content/en/docs/releasenotes/studio/9.7-and-above.md
Labels: Update release and/or featured date, 9.17

#4936 Workflow jump-to activities review
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/apply-jump-to-option.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/generate-jump-to-options.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/retrieve-workflow-context.md
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
  content/en/docs/refguide/modeling/application-logic/workflows/jump-to.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/apply-jump-to-option/apply-jump-to-option-properties.jpg
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/apply-jump-to-option/apply-jump-to-option.jpg
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/generate-jump-to-options/generate-jump-to-options-properties.jpg
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/generate-jump-to-options/generate-jump-to-options.jpg
  static/attachments/refguide/modeling/application-logic/workflows/jump-to/jump-to-entities.jpg
Labels: 9.17

#4986 Add Custom Settings to SAP Environments Runtime tab
  content/en/docs/developerportal/deploy/sap-cloud-platform.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/releasenotes/deployment/sap-cloud-platform.md
Labels: Needs R&D technical verification

#4738 Add additional info to connector guide best practices
  content/en/docs/appstore/creating-content/connector-guide-build/connector-guide-best-practices.md
Labels: Internal WIP
