Repository mendix/docs, pull requests merged in 2022-12, with the labels that each got.

#5367 Epics update
  content/en/docs/developerportal/collaborate/epics.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/developerportal/collaborate/epics/archive.png
  static/attachments/developerportal/collaborate/epics/data-migration-content.png
  static/attachments/developerportal/collaborate/epics/data-migration-example-epics.png
  static/attachments/developerportal/collaborate/epics/data-migration-example-stories.png
  static/attachments/developerportal/collaborate/epics/data-migration-info.png
  static/attachments/developerportal/collaborate/epics/migration-report-buttons.png
  static/attachments/developerportal/collaborate/epics/migration-report.png
  static/attachments/developerportal/collaborate/epics/switch-scrum-kanban.png
  static/attachments/developerportal/collaborate/epics/toast-notification.png
Labels: Future release

#5376 Add XSS recommendation
  content/en/docs/appstore/connectors/email-connector.md
Labels: Internal WIP

#5370 Merge how-to Optimize Retrieve Activities with refguide Retrieve
  content/en/docs/howto/logic-business-rules/define-access-rules-using-xpath.md
  content/en/docs/howto/logic-business-rules/extending-your-application-with-custom-java.md
  content/en/docs/howto/logic-business-rules/java-api-tutorial.md
  content/en/docs/howto/logic-business-rules/optimizing-retrieve-activities.md
  content/en/docs/howto/logic-business-rules/trigger-microflow-from-menu-item.md
  content/en/docs/howto/logic-business-rules/working-with-lists-in-a-microflow.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/retrieve.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/retrieve/example-create-order.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/retrieve/example-solution-one.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/retrieve/example-solution-two.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/retrieve/get-address-sub-microflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/retrieve/retrieve-one-object-instance.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/retrieve/retrieve-properties.png
Labels: Internal WIP

#5379 Evaluate doc Commit Object(s)
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/committing-objects.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/committing-objects/commit-properties.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/committing-objects/during-commits.png
Labels: Internal WIP

#5383 Evaluate doc Create Object
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/create-object.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/create-object/during-creates.png
Labels: Internal WIP

#5386 More email connector updates
  content/en/docs/appstore/connectors/email-connector.md
Labels: Internal WIP

#5387 Add Swagger page types to Algolia index
  layouts/_default/list.mxdocsalgolia.json
Labels: Internal WIP

#5391 Add backup and restore information for Private Cloud
  content/en/docs/developerportal/deploy/private-cloud/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-data-transfer.md
Labels: Needs R&D technical verification, Internal WIP

#5392 Improve the info on solving upload speed issue- Configuring Parallels
  content/en/docs/refguide/general/using-mendix-studio-pro-on-a-mac.md
Labels: Internal WIP

#5354 9.18.3 RN
  content/en/docs/releasenotes/studio-pro/9/9.18.md
Labels: Future release

#5402 Replace image
  static/attachments/data-hub/data-hub-catalog/curate/curate-list.png
Labels: Future release

#5400 Catalog Release2.61
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5406 Kk secrets corrections
  content/en/docs/developerportal/deploy/private-cloud/secret-store-credentials.md
Labels: Changes requested

#5358 BAPI using SNC Connection
  content/en/docs/partners/sap/sap-bapi-connector.md
Labels: Future release

#5409 AWS minor edits
  content/en/docs/appstore/connectors/aws/amazon-polly.md
  content/en/docs/appstore/connectors/aws/amazon-rekognition.md
  content/en/docs/appstore/connectors/aws/amazon-translate.md
  content/en/docs/appstore/connectors/aws/aws-authentication.md
  content/en/docs/appstore/connectors/aws/aws-dynamodb.md
  content/en/docs/appstore/connectors/aws/aws-lambda-connector.md
  content/en/docs/appstore/connectors/aws/aws-s3-connector.md
  content/en/docs/appstore/connectors/aws/aws-sns.md
  content/en/docs/partners/aws/_index.md
Labels: Internal WIP

#5378 Update mendix-feedback.md
  content/en/docs/appstore/modules/mendix-feedback.md
  content/en/docs/appstore/widgets/mendix-feedback.md
  content/en/docs/developerportal/collaborate/feedback.md
  content/en/docs/developerportal/deploy/deploying-to-mindsphere.md
  content/en/docs/howto8/mobile/hybrid-mobile/feedback-widget-ios.md
  content/en/docs/releasenotes/developer-portal/_index.md
  content/en/docs/releasenotes/studio/7.11-7.23.md
  static/attachments/appstore/modules/mendix-feedback/Toolbox-feedback.png
  static/attachments/appstore/modules/mendix-feedback/custom-authentication.png
  static/attachments/appstore/modules/mendix-feedback/feedback-form.png
  static/attachments/appstore/modules/mendix-feedback/feedback-in-app.png
  static/attachments/appstore/modules/mendix-feedback/feedback-on-layout.png
  static/attachments/appstore/modules/mendix-feedback/feedback-submit-button.png
  static/attachments/appstore/modules/mendix-feedback/install-error.png
  static/attachments/appstore/modules/mendix-feedback/mendixsso-authentication.png
  static/attachments/appstore/modules/mendix-feedback/widget-error.png
Labels: Future release

#5423 Evaluate doc - Rollback Object
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/change-object.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/committing-objects.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/rollback-object.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/rollback-object/during-rollback.png
Labels: Internal WIP

#5424 Preparing the SES email connector doc for publication
  content/en/docs/partners/aws/amazon-ses-email-connector.md
Labels: Changes requested

#5433 Update advanced-audit-trail.md
  content/en/docs/appstore/app-services/advanced-audit-trail.md
Labels: Needs R&D technical verification, Internal WIP

#5421 Remove Expectations for when Garbage Collector runs
  content/en/docs/refguide/runtime/runtime-java/_index.md
  content/en/docs/refguide/runtime/runtime-java/java-memory-usage.md
Labels: Needs R&D technical verification

#5405 9.21.0 RN
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.15.md
  content/en/docs/releasenotes/studio-pro/9/9.16.md
  content/en/docs/releasenotes/studio-pro/9/9.17.md
  content/en/docs/releasenotes/studio-pro/9/9.18.md
  content/en/docs/releasenotes/studio-pro/9/9.19.md
  content/en/docs/releasenotes/studio-pro/9/9.20.md
  content/en/docs/releasenotes/studio-pro/9/9.21.md
Labels: 9.21

#5432 Studio notifications and changes
  content/en/docs/refguide/version-control/_index.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/collaborative-development.md
  content/en/docs/releasenotes/studio/8.0-8.6.md
  content/en/docs/releasenotes/studio/8.7-8.18.md
  content/en/docs/releasenotes/studio/9.0-9.6.md
  content/en/docs/releasenotes/studio/9.7-9.20.md
  content/en/docs/releasenotes/studio/_index.md
  content/en/docs/studio-how-to/_index.md
  content/en/docs/studio/_index.md
  content/en/docs/studio/general/general-versions.md
  layouts/partials/landingpage/latest-releases.html
Labels: 9.21

#5329 Optimization App Setting (Workflows), Mx 9.21
  content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
Labels: 9.21

#5324 Include mitigation options for Context Entity Replaced and for Context Object Not Found conflicts
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-versioning.md
Labels: 9.21

#5436 Update user task properties
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/show-task-page.md
  content/en/docs/refguide/modeling/pages/on-click-event.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/show-task-page/open-task-page-properties.jpg
Labels: 9.21

#5427 Widget Styling Copy/Paste Update
  content/en/docs/refguide/modeling/studio-pro-overview/_index.md
Labels: 9.21

#5403 Add reference documentation for snippet parameters
  content/en/docs/refguide/modeling/menus/view-menu/errors-pane/consistency-errors/consistency-errors-pages.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-view.md
  content/en/docs/refguide/modeling/pages/page-resources/snippet.md
  content/en/docs/refguide/modeling/pages/structure-widgets/snippet-call.md
  static/attachments/refguide/modeling/pages/page-resources/snippet/snippet-properties.png
  static/attachments/refguide/modeling/pages/page-resources/snippet/snippet.png
  static/attachments/refguide/modeling/pages/structure-widgets/snippet-call/snippet-call-example.png
  static/attachments/refguide/modeling/pages/structure-widgets/snippet-call/snippet-call-properties.png
Labels: 9.21

#5416 Update docs to the latest 9.21 Git changes
  content/en/docs/refguide/modeling/menus/version-control-menu/_index.md
  content/en/docs/refguide/modeling/menus/version-control-menu/branch-line-manager-dialog/_index.md
  content/en/docs/refguide/version-control/_index.md
  content/en/docs/refguide/version-control/svn-git-differences.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  static/attachments/refguide/modeling/menus/version-control-menu/branch-line-manager-dialog/branch-line-manager.png
Labels: 9.21

#5397 Add new OQL String functions
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/_index.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-lower.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-replace.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-upper.md
Labels: 9.21

#5428 Kk aws textract
  content/en/docs/appstore/connectors/aws/aws-textract.md
  content/en/docs/refguide/modeling/pages/page/page-properties.md
  static/attachments/appstore/connectors/aws-textract/6-completed-access-rules.png
  static/attachments/appstore/connectors/aws-textract/analyze-document-configure-microflow.png
  static/attachments/appstore/connectors/aws-textract/analyze-document-properties.png
  static/attachments/appstore/connectors/aws-textract/block-item-page.png
  static/attachments/appstore/connectors/aws-textract/create-object-properties.png
  static/attachments/appstore/connectors/aws-textract/input-parameter-microflow.png
Labels: Future release

#5446 Sprintr release 2022.12.21 hotfix
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5458 Update curate.md for Catalog release
  content/en/docs/data-hub/data-hub-catalog/curate.md
Labels: Future release

#5422 Review and Merge how-to - Custom Save Button
  content/en/docs/appstore/connectors/aws/amazon-polly.md
  content/en/docs/appstore/connectors/aws/amazon-rekognition.md
  content/en/docs/appstore/connectors/aws/aws-dynamodb.md
  content/en/docs/appstore/connectors/aws/aws-sns.md
  content/en/docs/howto/logic-business-rules/create-a-custom-save-button.md
  content/en/docs/howto/logic-business-rules/define-access-rules-using-xpath.md
  content/en/docs/howto/logic-business-rules/extending-your-application-with-custom-java.md
  content/en/docs/howto/logic-business-rules/java-api-tutorial.md
  content/en/docs/howto/logic-business-rules/trigger-microflow-from-menu-item.md
  content/en/docs/refguide/modeling/pages/button-widgets/create-a-custom-save-button.md
  static/attachments/howto/logic-business-rules/create-a-custom-save-button/commit-object-properties.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/button-properties.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/close-page-activity.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/commit-object-properties.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/created-microflow.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/customer-detail.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/customer-save.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/detail-page-customer.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/entity-customer.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/icon.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/microflow.png
  static/attachments/refguide/modeling/pages/button-widgets/create-a-custom-save-button/show-message-properties.png
Labels: Internal WIP

#5453 Add linter GH action
  .github/workflows/lint-action.yml
Labels: Internal WIP

#5460 KI
  content/en/docs/releasenotes/studio-pro/9/9.10.md
  content/en/docs/releasenotes/studio-pro/9/9.11.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.13.md
  content/en/docs/releasenotes/studio-pro/9/9.14.md
  content/en/docs/releasenotes/studio-pro/9/9.15.md
  content/en/docs/releasenotes/studio-pro/9/9.16.md
  content/en/docs/releasenotes/studio-pro/9/9.17.md
  content/en/docs/releasenotes/studio-pro/9/9.18.md
  content/en/docs/releasenotes/studio-pro/9/9.19.md
  content/en/docs/releasenotes/studio-pro/9/9.20.md
  content/en/docs/releasenotes/studio-pro/9/9.21.md
  content/en/docs/releasenotes/studio-pro/9/9.5.md
  content/en/docs/releasenotes/studio-pro/9/9.6.md
  content/en/docs/releasenotes/studio-pro/9/9.7.md
  content/en/docs/releasenotes/studio-pro/9/9.8.md
  content/en/docs/releasenotes/studio-pro/9/9.9.md
Labels: Internal WIP

#5435 Review and relocate how-to - Extract and Use Sub-Microflows
  content/en/docs/appstore/modules/deep-link.md
  content/en/docs/howto/logic-business-rules/define-access-rules-using-xpath.md
  content/en/docs/howto/logic-business-rules/extending-your-application-with-custom-java.md
  content/en/docs/howto/logic-business-rules/extract-and-use-sub-microflows.md
  content/en/docs/howto/logic-business-rules/java-api-tutorial.md
  content/en/docs/howto/logic-business-rules/trigger-microflow-from-menu-item.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/retrieve.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extract-and-use-sub-microflows.md
  content/en/docs/refguide/modeling/pages/button-widgets/create-a-custom-save-button.md
  static/attachments/howto/logic-business-rules/extract-and-use-sub-microflows/18581017.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extracting-and-using-sub-microflows/example-complex-microflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extracting-and-using-sub-microflows/example-submicroflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extracting-and-using-sub-microflows/reuse-microflow.gif
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extracting-and-using-sub-microflows/select-Extract-submicroflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extracting-and-using-sub-microflows/select-an-area.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extracting-and-using-sub-microflows/submicroflow-in-parent-microflow.png
Labels: Internal WIP

#5100 Update Transporting a Deployment Package error messages
  content/en/docs/apidocs-mxsdk/apidocs/deploy-api/_index.md
Labels: Future release

#5469 Add link to Email with Templates doc
  content/en/docs/appstore/connectors/email-connector.md
  content/en/docs/appstore/modules/email-with-templates.md
Labels: Internal WIP

#5291 Improve Execute an SQL Statement on an External Database
  content/en/docs/appstore/connectors/database-connector.md
  content/en/docs/howto/integration/execute-an-sql-statement-on-an-external-database.md
Labels: Internal WIP

#5468 Business events updates
  content/en/docs/appstore/modules/business-events.md
Labels: Internal WIP

#5456 Updates to Call REST Service
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/call-rest-action.md
Labels: Internal WIP
