Repository mendix/docs, pull requests merged in 2022-07, with the labels that each got.

#4700 Update query-over.md
  content/en/docs/refguide/modeling/domain-model/associations/query-over.md
Labels: Needs R&D technical verification

#4777 Update section on Catalog filters
  content/en/docs/data-hub/data-hub-catalog/search.md
  content/en/docs/data-hub/write-data/_index.md
  static/attachments/data-hub/data-hub-catalog/search/dh-filter-box.png
Labels: Internal WIP

#4745 Update published-rest-service
  content/en/docs/howto/integration/publish-rest-service.md
Labels: Internal WIP

#4782 Mendix Cloud Deployment Release Notes and Documentation
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs R&D technical verification, Update release and/or featured date

#4794 Add release notes (9.14.2)
  content/en/docs/releasenotes/studio-pro/9/9.14.md
Labels: Future release

#4797 Remove (page).URL from our layouts as it is deprecated
  layouts/_default/list.mxdocsalgolia.json
  layouts/partials/navbar.html
Labels: Internal WIP

#4798 Update sending email settings to include MS Office 365
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/sending-email.md
Labels: Internal WIP

#4793 Mendix for Private Cloud Release Note
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs R&D technical verification

#4799 Update explanation of app metrics
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
Labels: Internal WIP

#4740 Notice about module deprecation
  content/en/docs/appstore/modules/email-with-templates.md
  content/en/docs/appstore/modules/imap.md
Labels: Internal WIP

#4804 Update sec vuln
  content/en/docs/releasenotes/security-advisories/_index.md
  content/en/docs/releasenotes/studio-pro/7/7.23.md
  content/en/docs/releasenotes/studio-pro/8/8.18.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.14.md
  content/en/docs/releasenotes/studio-pro/9/9.15.md
  content/en/docs/releasenotes/studio-pro/9/9.6.md
Labels: Needs R&D technical verification

#4770 Added release notes for new operator release and updated the document…
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Future release, Needs R&D technical verification, Update release and/or featured date

#4802 9.15.1 RN
  content/en/docs/releasenotes/studio-pro/9/9.15.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4809 Data Hub release notes for release 2.40.0
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4816 make the list of Data Set parameter types up to date
  content/en/docs/refguide/modeling/resources/data-sets/_index.md
Labels: Waiting for CLA

#4806 Support for OAuth 2.0 in IMAP/POP3 connector
  content/en/docs/appstore/modules/imap.md
  static/attachments/appstore/modules/imap/azure-permissions.png
Labels: Future release

#4817 Add information on exposed actions and Studio release notes
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
  content/en/docs/releasenotes/studio/9.7-and-above.md
  content/en/docs/studio/microflows/_index.md
  content/en/docs/studio/workflows/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4674 Add support for Splunk to Mendix Cloud V4
  content/en/docs/developerportal/operate/metrics/monitoring-with-apm/_index.md
  content/en/docs/developerportal/operate/metrics/monitoring-with-apm/splunk-metrics.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Update release and/or featured date

#4843 Add 9.9.3 RN
  content/en/docs/releasenotes/studio-pro/9/9.9.md
Labels: Future release, Update release and/or featured date

#4856 ba-dh-2.42.0-Datahub 2.42.0 release external release notes
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4823 9.16 RN
  content/en/docs/releasenotes/studio-pro/9/9.16.md
  layouts/partials/landingpage/latest-releases.html
Labels: 9.16

#4667 Add documentation for PB BP MXP015
  content/en/docs/refguide/modeling/menus/view-menu/mx-assist-performance-bot/performance-best-practices.md
Labels: 9.16

#4727 mx check add performance
  content/en/docs/refguide/general/mx-command-line-tool.md
  content/en/docs/refguide/modeling/menus/view-menu/mx-assist-performance-bot/_index.md
Labels: 9.16

#4820 Add native mobile logging docs
  content/en/docs/refguide/mobile/_index.md
  content/en/docs/refguide/mobile/logging.md
  content/en/docs/refguide/runtime/logging.md
  static/attachments/refguide/mobile/native-mobile/logging/enable-logging.png
Labels: 9.16
