Repository mendix/docs, pull requests merged in 2022-11, with the labels that each got.

#5239 Updates to integration landing page
  content/en/docs/refguide/modeling/integration/_index.md
Labels: Internal WIP

#5233 Added integrated security to main database runtime settings
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/refguide7/runtime/custom-settings/_index.md
  content/en/docs/refguide8/runtime/custom-settings/_index.md
Labels: Needs R&D technical verification

#5238 Clarify product name
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Internal WIP

#5244 Clarify DH API page
  content/en/docs/apidocs-mxsdk/apidocs/data-hub-apis.md
Labels: Internal WIP

#5240 9.6.14 RN
  content/en/docs/releasenotes/studio-pro/9/9.6.md
Labels: Future release

#5248 Release notes for Data Hub Catalog Release 2.56.0
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5260 Change to examples that do not reveal personal identifiable infor…
  content/en/docs/howto/monitoring-troubleshooting/log-levels.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/log-message.md
  static/attachments/howto/monitoring-troubleshooting/log-levels/18580031.png
  static/attachments/howto/monitoring-troubleshooting/log-levels/critical.png
  static/attachments/howto/monitoring-troubleshooting/log-levels/custom-log-messages.png
  static/attachments/howto/monitoring-troubleshooting/log-levels/error.png
  static/attachments/howto/monitoring-troubleshooting/log-levels/log-message-template.png
  static/attachments/howto/monitoring-troubleshooting/log-levels/set-log-levels.png
  static/attachments/howto/monitoring-troubleshooting/log-levels/warning.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/log-message/log-message-properties.png
Labels: Internal WIP

#5259 Updated Mx4PC supported environments (no release date).
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
Labels: Needs language review

#5253 Kk authentication
  content/en/docs/appstore/connectors/aws-authentication.md
  static/attachments/appstore/connectors/aws-authentication/microflow-get-static-credentials.png
  static/attachments/appstore/connectors/aws-authentication/sigv4action.png
  static/attachments/appstore/connectors/aws-authentication/sigv4builder.png
  static/attachments/appstore/connectors/aws-authentication/sigv4headers.png
  static/attachments/appstore/connectors/aws-authentication/sigv4microflow.png
  static/attachments/appstore/connectors/aws-authentication/sigv4parameters.png
Labels: Needs R&D technical verification

#5258 Email Connector Doc Updates
  content/en/docs/appstore/connectors/email-connector.md
Labels: Internal WIP

#5267 Improvements to the demo update script
  content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
Labels: Internal WIP

#5268 AWS Authentication - clarification for sig v4 use case
  content/en/docs/appstore/connectors/aws-authentication.md
Labels: Changes requested

#5265 Extend
  content/en/docs/developerportal/support/_index.md
  content/en/docs/howto7/_index.md
  content/en/docs/refguide7/_index.md
  content/en/docs/releasenotes/studio-pro/7/7.23.md
  content/en/docs/releasenotes/studio-pro/lts-mts.md
  content/en/docs/studio7/_index.md
Labels: Future release

#5271 Update screenshots for the doc Access Rules
  content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
  static/attachments/refguide/modeling/domain-model/entities/access-rules/access-rule-order-xpath.png
  static/attachments/refguide/modeling/domain-model/entities/access-rules/access-rules-properties.png
  static/attachments/refguide/modeling/domain-model/entities/access-rules/access-rules-section.png
  static/attachments/refguide/modeling/domain-model/entities/access-rules/access-rules-tab.png
Labels: Internal WIP

#5274 Data Hub Catalog 2.57.0 Release Notes
  content/en/docs/data-hub/data-hub-catalog/curate.md
  content/en/docs/data-hub/data-hub-catalog/search.md
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5281 Mendix Cloud Release Notes 10 November 2022
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs R&D technical verification, Update release and/or featured date

#5252 Updated/refined the technical part of the documentation.
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-secrets.md
Labels: Internal WIP

#5296 A note about mapping user roles
  content/en/docs/appstore/general/app-store-content.md
Labels: Internal WIP

#5283 Kk s3
  content/en/docs/appstore/connectors/aws-s3-connector.md
Labels: Needs R&D technical verification

#5216 Fixes in tekton documentation for standalone Private Cloud.
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-tekton/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-tekton/private-cloud-tekton-airgap.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-tekton/tekton-architecture-example.png
Labels: Needs language review

#5297 Update aws-authentication.md
  content/en/docs/appstore/connectors/aws-authentication.md
Labels: Needs R&D technical verification

#5251 Adjust XPath docs
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/retrieve.md
  content/en/docs/refguide/modeling/xpath/_index.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/_index.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-avg.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-count.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-max.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-min.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-sum.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/_index.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-day-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-day-of-year-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-false.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-hours-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-length.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-minutes-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-month-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-quarter-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-seconds-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-starts-with.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-string-length.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-week-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-weekday-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-year-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-query-functions/_index.md
  content/en/docs/refguide/modeling/xpath/xpath-tokens.md
  static/attachments/refguide/modeling/xpath/XPath-constraint-example.png
Labels: Internal WIP

#5237 External Kubernetes secrets storage - best practices
  content/en/docs/developerportal/deploy/private-cloud/secret-store-credentials.md
Labels: Needs R&D technical verification

#5317 Evaluate the doc Optimize Microflow Aggregates (including the screens…
  content/en/docs/howto/logic-business-rules/optimizing-microflow-aggregates.md
  static/attachments/howto/logic-business-rules/optimizing-microflow-aggregates/not-merged-activities.png
  static/attachments/howto/logic-business-rules/optimizing-microflow-aggregates/one-single-retrieve-query.png
  static/attachments/howto/logic-business-rules/optimizing-microflow-aggregates/two-separate-retrieves.png
Labels: Internal WIP

#5020 Amazon Rekognition connector
  content/en/docs/appstore/connectors/amazon-rekognition.md
Labels: Future release

#5299 Added self-service SVN-Git migration
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Update release and/or featured date

#4925 Migration from SVN to Git
  content/en/docs/developerportal/collaborate/team-server/_index.md
  content/en/docs/developerportal/collaborate/team-server/migrate-to-git.md
  content/en/docs/refguide/version-control/svn-git-differences.md
  content/en/docs/refguide/version-control/version-control-faq.md
Labels: Future release

#5330 Inline date format tokens (2)
  content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
Labels: Needs R&D technical verification

#5322 AWS Lambda connector first doc draft
  content/en/docs/appstore/connectors/aws-lambda-connector.md
Labels: Needs R&D technical verification

#5328 Nidhi251289 secretstorefeedback
  content/en/docs/developerportal/deploy/private-cloud/secret-store-credentials.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/awsserviceaccountlinktorole.png
Labels: Needs R&D technical verification

#5340 Release notes for Data Hub Catalog 2.59
  content/en/docs/data-hub/data-hub-catalog/search.md
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5310 AWS SNS connector
  content/en/docs/appstore/connectors/aws-sns.md
Labels: Needs R&D technical verification

#5342 Moving AWS IoT to community supported
  content/en/docs/appstore/connectors/aws-iot.md
  content/en/docs/appstore/creating-content/connector-guide-build/_index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mxcloudv4/_index.md
Labels: Awaiting Response

#5341 [WC-1512]: add htmlelement documentation
  content/en/docs/appstore/widgets/htmlelement.md
  static/attachments/appstore/widgets/htmlelement/sample-custom-ui.png
  static/attachments/appstore/widgets/htmlelement/sample-embedded-html.png
  static/attachments/appstore/widgets/htmlelement/sample-formatting-text.png
  static/attachments/appstore/widgets/htmlelement/sample-tailored-html.png
Labels: Future release

#5344 Adding AWS in the Strategic Partners guide
  content/en/docs/partners/_index.md
  content/en/docs/partners/aws/_index.md
Labels: Awaiting Response

#5332 Error Handling in Microflows - create a new document
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/combination-without-roll-back-error-event.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/continue.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/default-roll-back.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/with-roll-back-end-event.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/with-roll-back-error-event.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/without-roll-back-end-event.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows/without-roll-back-error-event.png
Labels: Needs R&D technical verification, Internal WIP

#5245 Improve MQTT connector doc
  content/en/docs/appstore/connectors/mqtt.md
Labels: Internal WIP

#5356 XSD updates
  content/en/docs/refguide/modeling/integration/consumed-web-services/_index.md
  content/en/docs/refguide/modeling/integration/xml-schemas/_index.md
  content/en/docs/refguide/modeling/integration/xml-schemas/xml-schema-support.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
Labels: Internal WIP

#5361 Add Studio Pro version information for two functions
  content/en/docs/refguide/modeling/application-logic/expressions/begin-of-date-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/end-of-date-function-calls.md
Labels: Internal WIP

#5362 aws cognitive polly
  content/en/docs/appstore/connectors/aws-polly.md
Labels: Needs R&D technical verification

#5326 9.20 RN
  content/en/docs/releasenotes/studio-pro/9/9.20.md
  layouts/partials/landingpage/latest-releases.html
Labels: 9.20

#5316 Extend configuration module api for pluggable widgets
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-config-api.md
Labels: 9.20

#5181 [WTF-1175] Add reference documentation for return type depending on another property (9.20)
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
Labels: 9.20

#5212 [SP 9.20] Update description of Performance Bot settings under Edit|Preferences
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
Labels: 9.20

#5348 [WTF-1312] Update docs for Page to include the parameters button (9.20)
  content/en/docs/refguide/modeling/pages/page/_index.md
  static/attachments/refguide/modeling/pages/page/design-mode-example.png
  static/attachments/refguide/modeling/pages/page/structure-mode-info.png
  static/attachments/refguide/modeling/pages/page/top-menu.png
Labels: 9.20

#5364 amazon polly
  content/en/docs/appstore/connectors/amazon-polly.md
Labels: Needs R&D technical verification

#5300 Add 'Disk location' setting to the Preferences dialog
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/menus/file-menu/new-app.md
  static/attachments/refguide/modeling/menus/edit-menu/preferences-dialog/preferences.png
Labels: 9.20

#5357 Evaluate the doc - Cast Object
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/cast-object.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/cast-object/cast-properties.png
Labels: Internal WIP

#4303 Portfolio Management Tool doc
  content/en/docs/developerportal/_index.md
  content/en/docs/developerportal/community-tools/_index.md
  content/en/docs/developerportal/control-center/data-hub-admin.md
  content/en/docs/developerportal/portfolio-management/_index.md
  content/en/docs/developerportal/portfolio-management/prioritization-models.md
  content/en/docs/developerportal/support/_index.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  layouts/partials/landingpage/product-cards.html
  static/attachments/developerportal/portfolio-management/access-management.png
  static/attachments/developerportal/portfolio-management/archive-dialog-box.png
  static/attachments/developerportal/portfolio-management/archived-projects.png
  static/attachments/developerportal/portfolio-management/check-mark.svg
  static/attachments/developerportal/portfolio-management/cross-mark.svg
  static/attachments/developerportal/portfolio-management/delete-edit-stage.png
  static/attachments/developerportal/portfolio-management/edit-delete-user.png
  static/attachments/developerportal/portfolio-management/edit-project-list-view.png
  static/attachments/developerportal/portfolio-management/landing-page.png
  static/attachments/developerportal/portfolio-management/list-view.png
  static/attachments/developerportal/portfolio-management/manage-tags-dialog-box.png
  static/attachments/developerportal/portfolio-management/manage-tags.png
  static/attachments/developerportal/portfolio-management/move-upwards-downwards.png
  static/attachments/developerportal/portfolio-management/project-card.png
  static/attachments/developerportal/portfolio-management/projects-overview.png
  static/attachments/developerportal/portfolio-management/side-pane.png
  static/attachments/developerportal/portfolio-management/switch-view.png
  static/attachments/developerportal/switcher.png
Labels: Future release, Internal WIP, Verify formatting

#5363 Merge how-to Optimize Microflow Aggregates with the refguide Aggregat…
  content/en/docs/howto/logic-business-rules/create-a-custom-save-button.md
  content/en/docs/howto/logic-business-rules/define-access-rules-using-xpath.md
  content/en/docs/howto/logic-business-rules/extending-your-application-with-custom-java.md
  content/en/docs/howto/logic-business-rules/java-api-tutorial.md
  content/en/docs/howto/logic-business-rules/optimizing-microflow-aggregates.md
  content/en/docs/howto/logic-business-rules/trigger-microflow-from-menu-item.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
  static/attachments/howto/logic-business-rules/optimizing-microflow-aggregates/18580944.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list/not-merged-activities.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list/one-single-retrieve-query.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list/two-separate-retrieves.png
Labels: Internal WIP
