Repository mendix/docs, pull requests merged in 2022-04, with the labels that each got.

#4391 Upate Creating Solutions
  content/en/docs/appstore/creating-content/prepare.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/_index.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-development/_index.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-development/sol-architecting.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-development/sol-ip-protection.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-general/_index.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-general/sol-vendor-programs.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-vendor-programs.md
  content/en/docs/appstore/creating-content/vendor-program.md
Labels: Internal WIP

#4393 Note issue with integer attributes
  content/en/docs/refguide/modeling/domain-model/entities/attributes.md
Labels: Needs R&D technical verification

#4399 Add menu scrolling
  assets/scss/_sidebar-toc.scss
  assets/scss/_sidebar-tree.scss
  layouts/partials/sidebar-tree.html
  layouts/partials/toc.html
Labels: Internal WIP

#4402 Between dates is always positive
  content/en/docs/refguide/modeling/application-logic/expressions/between-date-function-calls.md
Labels: Needs R&D technical verification

#4413 Update imap.md
  content/en/docs/appstore/modules/imap.md
Labels: Internal WIP

#4300 Email service doc
  content/en/docs/appstore/app-services/email-service.md
  static/attachments/appstore/app-services/email-service/binding-key-generation.png
  static/attachments/appstore/app-services/email-service/console-domain-text-input.png
  static/attachments/appstore/app-services/email-service/console-domain-verification.png
  static/attachments/appstore/app-services/email-service/console-domain.png
  static/attachments/appstore/app-services/email-service/console-email-verification.png
  static/attachments/appstore/app-services/email-service/console-mail-from-domain-text-input.png
  static/attachments/appstore/app-services/email-service/console.png
  static/attachments/appstore/app-services/email-service/dkim-and-domain-verification-record.png
  static/attachments/appstore/app-services/email-service/domain-verification-in-progress.png
  static/attachments/appstore/app-services/email-service/domain-verification-pending.png
  static/attachments/appstore/app-services/email-service/email-identities.png
  static/attachments/appstore/app-services/email-service/email-verification-in-progress.png
  static/attachments/appstore/app-services/email-service/email-verification-pending.png
  static/attachments/appstore/app-services/email-service/email-verification.png
  static/attachments/appstore/app-services/email-service/file-attachment-entity.png
  static/attachments/appstore/app-services/email-service/generate-document-dialog-box.png
  static/attachments/appstore/app-services/email-service/generate-html-body-content-microflow.png
  static/attachments/appstore/app-services/email-service/java-action.png
  static/attachments/appstore/app-services/email-service/send-email-dialog-box.png
  static/attachments/appstore/app-services/email-service/spf-dns-records.png
  static/attachments/appstore/app-services/email-service/string-from-file-dialog-box.png
  static/attachments/appstore/app-services/email-service/verification-type-domain.png
  static/attachments/appstore/app-services/email-service/view-details-edit.png
Labels: Internal WIP

#4411 Update forum doc and release note
  content/en/docs/developerportal/community-tools/mendix-forum.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/developerportal/community-tools/mendix-forum/ideas_example.png
  static/attachments/developerportal/community-tools/mendix-forum/ideas_sort_by.jpg
  static/attachments/developerportal/community-tools/mendix-forum/ideas_sort_by.png
  static/attachments/developerportal/community-tools/mendix-forum/questions_example.png
  static/attachments/developerportal/community-tools/mendix-forum/questions_sort_by.jpg
  static/attachments/developerportal/community-tools/mendix-forum/questions_sort_by.png
Labels: Future release, Post-publish edit images

#4415 Data Hub Release Notes for Release 2.28.0
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4406 7.23.30 RN
  content/en/docs/releasenotes/studio-pro/7/7.23.md
Labels: Future release, Update release and/or featured date

#4408 9.6.11 RN
  content/en/docs/releasenotes/studio-pro/9/9.6.md
Labels: Future release, Update release and/or featured date

#4420 Headings overlap with MxDock
  assets/scss/_tables.scss
  assets/scss/main.scss
  content/en/docs/developerportal/community-tools/contribute-to-the-mendix-documentation/indentation-spacing-test.md
Labels: Internal WIP

#4378 9.12.1 RN
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  layouts/partials/landingpage/latest-releases.html
Labels: Update release and/or featured date, 9.12.1

#4369 9.12.1 support for scheduled events conversion
  content/en/docs/refguide/modeling/resources/scheduled-events/_index.md
Labels: 9.12.1

#4398 Create best practices for connectors doc, update building connectors doc
  content/en/docs/appstore/creating-content/connector-guide-build/_index.md
  content/en/docs/appstore/creating-content/connector-guide-build/connector-guide-best-practices.md
  content/en/docs/refguide/modeling/resources/java-actions.md
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/app-initial-setup.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/app-post-setup.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/complex-config-create-microflow.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/complex-config-entity.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/complex-config-security-2.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/complex-config-security.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/gradle-library.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/implementation-folder.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/microflow-action.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-change-value.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-constant.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-new-constants.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-select-constant.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-settings.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-value.png
Labels: Internal WIP, Needs language review

#4430 Front page image size fix
  images/docs-extended.png
  images/most-popular-development-best-practices.png
  images/most-popular-expressions.png
  images/most-popular-string-function-calls.png
  images/most-popular-system-requirements.png
  layouts/docs/landingpage.html
  layouts/partials/landingpage/most-popular.html
  static/images/docs-extended-small.png
  static/images/most-popular-development-best-practices-small.png
  static/images/most-popular-expressions-small.png
  static/images/most-popular-string-function-calls-small.png
  templates/image-originals/docs-extended.png
  templates/image-originals/most-popular-development-best-practices.png
  templates/image-originals/most-popular-expressions.png
  templates/image-originals/most-popular-string-function-calls.png
  templates/image-originals/most-popular-system-requirements.png
Labels: Internal WIP

#4427 Revert google tag code to reference dataLayer
  layouts/partials/hooks/body-end.html
Labels: Internal WIP

#4428 Adjust code block line height and button location
  assets/scss/_code.scss
  static/css/prism.css
Labels: Internal WIP

#4424 Document comparison with empty values
  content/en/docs/refguide/modeling/application-logic/expressions/relational-expressions.md
Labels: Needs language review

#4435 Added Database Connection Pool Metrics
  content/en/docs/refguide/runtime/metrics.md
Labels: Needs language review

#4449 Add Creating Content Link
  content/en/docs/appstore/creating-content/_index.md
Labels: Internal WIP

#4452 Data hub release notes for 2.29.0
  content/en/docs/apidocs-mxsdk/apidocs/data-hub-apis.md
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#4438 Make Performance Bot docs easier to find
  content/en/docs/howto/general/community-best-practices-for-app-performance.md
  content/en/docs/howto/monitoring-troubleshooting/detect-and-resolve-performance-issues.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/_index.md
Labels: Needs language review

#4326 Workflows re-enabled in Studio
  content/en/docs/releasenotes/studio/9.0-9.6.md
  content/en/docs/releasenotes/studio/9.7-and-above.md
  content/en/docs/studio-how-to/_index.md
  content/en/docs/studio-how-to/workflow-how-to-configure/_index.md
  content/en/docs/studio/checks/consistency-errors/consistency-errors-microflows.md
  content/en/docs/studio/microflows/_index.md
  content/en/docs/studio/work-with-data/domain-models/_index.md
  content/en/docs/studio/workflows/_index.md
  content/en/docs/studio/workflows/workflow-parameter.md
  content/en/docs/studio/workflows/workflow-properties.md
  content/en/docs/studio/workflows/workflow-system-actions.md
  content/en/docs/studio/workflows/workflows-9.6.md
  content/en/docs/studio/workflows/workflows-general-activities.md
  content/en/docs/studio/workflows/workflows-user-task.md
  static/attachments/studio-how-to/workflow-how-to-configure/create-employee-details-page.png
  static/attachments/studio-how-to/workflow-how-to-configure/create-new-page.png
  static/attachments/studio-how-to/workflow-how-to-configure/demo_hr.png
  static/attachments/studio-how-to/workflow-how-to-configure/domain-model.png
  static/attachments/studio-how-to/workflow-how-to-configure/enable-security.png
  static/attachments/studio-how-to/workflow-how-to-configure/select-page-for-navigation.png
  static/attachments/studio-how-to/workflow-how-to-configure/set-up-manually.jpg
  static/attachments/studio/microflows/workflow-activities.jpg
  static/attachments/studio/microflows/workflow-administration.jpg
  static/attachments/studio/workflows/copy.jpg
  static/attachments/studio/workflows/create-new-workflow.jpg
  static/attachments/studio/workflows/create-request-form.jpg
  static/attachments/studio/workflows/delete-workflow.jpg
  static/attachments/studio/workflows/duplicate.jpg
  static/attachments/studio/workflows/general.jpg
  static/attachments/studio/workflows/new-workflow.jpg
  static/attachments/studio/workflows/parameter.jpg
  static/attachments/studio/workflows/workflow-page.jpg
  static/attachments/studio/workflows/workflow-parameter/parameter.jpg
  static/attachments/studio/workflows/workflow-properties/data.jpg
  static/attachments/studio/workflows/workflow-properties/permissions.jpg
  static/attachments/studio/workflows/workflows-user-task/permissions.jpg
  static/attachments/studio/workflows/workflows-user-task/user-assignment.jpg
Labels: Future release

#4446 8.18.17 RN
  content/en/docs/releasenotes/studio-pro/8/8.18.md
Labels: Future release

#4456 Add notice
  content/en/docs/releasenotes/studio-pro/9/9.11.md
Labels: Internal WIP

#4460 Add data to feedback link to prefill issue form
  layouts/partials/page-meta-links.html
Labels: Internal WIP

#4379 FAQ about version control and team server
  content/en/docs/refguide/version-control/_index.md
  content/en/docs/refguide/version-control/version-control-faq.md
Labels: Needs language review

#4465 Update intelligent-document-service.md
  content/en/docs/appstore/app-services/intelligent-document-service.md
Labels: Internal WIP

#4437 Correct bad external links
  .htmltest.yml
  content/en/docs/appstore/app-services/3d-viewer/3d-viewer-api.md
  content/en/docs/appstore/app-services/3d-viewer/_index.md
  content/en/docs/appstore/general/app-store-content-support.md
  content/en/docs/appstore/modules/excel-importer.md
  content/en/docs/appstore/modules/mendix-sso.md
  content/en/docs/developerportal/_index.md
  content/en/docs/developerportal/collaborate/team-server.md
  content/en/docs/developerportal/community-tools/mendix-profile/_index.md
  content/en/docs/developerportal/deploy/deploying-to-mindsphere.md
  content/en/docs/developerportal/deploy/general/two-factor-authentication.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/sending-email.md
  content/en/docs/developerportal/deploy/on-premises-design/deploy-mendix-on-microsoft-windows/mendix-on-windows-microsoft-sql-server/setting-up-the-database-user.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-monitor.md
  content/en/docs/developerportal/support/_index.md
  content/en/docs/developerportal/support/escalation-management-process.md
  content/en/docs/developerportal/support/prepare-your-project.md
  content/en/docs/developerportal/support/submit-support-request.md
  content/en/docs/howto/collaboration-requirements-management/on-premises-howto/on-premises-svn-howto.md
  content/en/docs/howto7/collaboration-requirements-management/on-premises-svn-howto.md
  content/en/docs/howto8/collaboration-requirements-management/on-premises-svn-howto.md
  content/en/docs/partners/siemens/mindsphere/mendix-on-mindsphere/mindsphere-development-considerations.md
  content/en/docs/partners/siemens/mindsphere/mendix-on-mindsphere/mindsphere-mobile-native.md
  content/en/docs/refguide/general/system-requirements.md
  content/en/docs/refguide/runtime/custom-settings/tricky-custom-runtime-settings.md
  content/en/docs/refguide7/general/system-requirements.md
  content/en/docs/refguide7/runtime/custom-settings/tricky-custom-runtime-settings.md
  content/en/docs/refguide8/general/system-requirements.md
  content/en/docs/refguide8/runtime/custom-settings/tricky-custom-runtime-settings.md
  content/en/docs/releasenotes/studio-pro/8/8.14.md
  content/en/docs/releasenotes/studio/7.11-7.23.md
  content/en/docs/studio/general/_index.md
  content/en/docs/studio7/general/_index.md
  content/en/docs/studio8/general/_index.md
Labels: Needs language review

#4475 Added release notes for catalog 2.30 release
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs language review

#4472 Update _index.md
  content/en/docs/developerportal/control-center/_index.md
  content/en/docs/releasenotes/developer-portal/_index.md
Labels: Future release

#4440 Removed NotRunning text
  content/en/docs/apidocs-mxsdk/apidocs/deploy-api/_index.md
Labels: Needs R&D technical verification

#4485 Release notes for LM-134, LM-752 & LM-449
  content/en/docs/releasenotes/deployment/mendix-cloud.md
Labels: Update release and/or featured date

#4343 Copy information on Studio multi-language support
  content/en/docs/studio/general/_index.md
  content/en/docs/studio/general/attachments/language-support/language-diagram.png
  content/en/docs/studio/general/attachments/language-support/selected-language.png
  content/en/docs/studio/general/attachments/language-support/translations-drop-down.png
  content/en/docs/studio/general/language-support.md
  content/en/docs/studio/navigation/_index.md
  content/en/docs/studio/page-editor/page-editor-widgets/page-editor-data-grid.md
  content/en/docs/studio/page-editor/page-editor-widgets/page-editor-widgets-buttons.md
  content/en/docs/studio/page-editor/page-editor-widgets/page-editor-widgets-text.md
  static/attachments/studio/general/language-support/language-diagram.png
  static/attachments/studio/general/language-support/selected-language.png
  static/attachments/studio/general/language-support/translations-drop-down.png
  static/attachments/studio/general/top-bar.png
  static/attachments/studio/navigation/navigation-properties.png
Labels: Future release

#4470 9.13 RN
  content/en/docs/releasenotes/studio-pro/9/9.11.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.13.md
  layouts/partials/landingpage/latest-releases.html
Labels: 9.13

#4444 Introducing the deletable capability
  content/en/docs/refguide/modeling/integration/published-odata-services/odata-query-options.md
  content/en/docs/refguide/modeling/integration/published-odata-services/published-odata-resource.md
Labels: 9.13

#4451 [WTF-1088] Add documentation for PW association property [9.13]
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types/association.png
Labels: 9.13

#4457 Studio Pro 9.13 now completely supports CRUD in published OData services
  content/en/docs/data-hub/write-data/_index.md
  content/en/docs/refguide/modeling/domain-model/external-entities.md
Labels: 9.13

#4488 Doc tab location change for 9.13
  content/en/docs/refguide/modeling/integration/published-odata-services/_index.md
Labels: Future release, 9.13

#4404 Add support for ISO 8601/HOCON Durations
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: 9.13

#4441 [RTI-466] More information about session configurations
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/refguide/runtime/custom-settings/tricky-custom-runtime-settings.md
Labels: 9.13

#4482 Update 9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
Labels: 9.13

#4469 Update documentation about exposed actions
  content/en/docs/howto/extensibility/best-practices-javascript-actions.md
  content/en/docs/howto/logic-business-rules/add-action-to-workflow-toolbox.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
  content/en/docs/refguide/modeling/resources/java-actions.md
  content/en/docs/refguide/modeling/resources/javascript-actions.md
  static/attachments/howto/extensibility/best-practices-javascript-actions/narrow-expose.png
  static/attachments/howto/logic-business-rules/add-action-to-workflow-toolbox/expose-as-workflow-action-properties.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow/microflow-expose.jpg
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow/workflow-expose.jpg
  static/attachments/refguide/modeling/resources/javascript-actions/expose-jsaction.png
Labels: 9.13

#4454 Add 'new add-on imported/deleted' dialog
  content/en/docs/howto/integration/importing-and-exporting-objects.md
  static/attachments/howto/integration/importing-and-exporting-objects/mxmodule-notification.png
Labels: 9.13

#4506 Feedback on MendixSSO setup
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-sso.md
Labels: Internal WIP
