Repository mendix/docs, pull requests merged in 2022-01, with the labels that each got.

#3829 Studio module management
  content/releasenotes/studio/9.7-and-above.md
  content/studio/attachments/settings-version-and-add-ons/dependencies-found.png
  content/studio/attachments/settings-version-and-add-ons/upgrade-now-button.png
  content/studio/attachments/settings-version-and-add-ons/version-and-add-ons-screen.png
  content/studio/settings-version-and-add-ons.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#4041 Add a note about Japanese translation to the landing page
  themes/mendix/layouts/index.html
  themes/mendix/layouts/partials/frontpage/note.html
Labels: Internal WIP

#4037 Catalog 2.15 release notes
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#4027 Excel exporter
  content/howto/integration/attachments/using-the-excel-exporter/18581165.png
  content/howto/integration/attachments/using-the-excel-exporter/18581909.png
  content/howto/integration/attachments/using-the-excel-exporter/java-action.png
  content/howto/integration/attachments/using-the-excel-exporter/microflow-for-generate.png
  content/howto/integration/attachments/using-the-excel-exporter/new-menu-item-excel-exporter.png
  content/howto/integration/attachments/using-the-excel-exporter/new-menu-item-mxreflection.png
  content/howto/integration/attachments/using-the-excel-exporter/retrieve-template.png
  content/howto/integration/attachments/using-the-excel-exporter/security.png
  content/howto/integration/attachments/using-the-excel-exporter/upload-excel-file.png
  content/howto/integration/using-the-excel-exporter.md
Labels: Internal WIP

#4044 Update info about REST services authentication
  content/howto/security/best-practices-security.md
Labels: Internal WIP

#4046 Fix anchors in Excel Exporter
  content/howto/integration/using-the-excel-exporter.md
Labels: Internal WIP

#4043 MX world calendar update for marketplace component
  content/releasenotes/mx-world-2021/index.md
Labels: Internal WIP

#4057 Marketplace approval guidelines
  content/appstore/creating-content/as-sell.md
  content/appstore/general/share-app-store-content.md
Labels: Internal WIP

#3952 3dviewer api doc
  content/appstore/app-services/3d-viewer-api.md
  content/appstore/app-services/3d-viewer.md
  content/appstore/app-services/attachments/3d-viewer-api/show-properties.jpg
Labels: Internal WIP

#4062 Data Hub notes for Release 2.16
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#4055 added release note for 13th january release for operator and private portal
  content/developerportal/deploy/private-cloud-cluster.md
  content/releasenotes/developer-portal/mendix-for-private-cloud.md
Labels: Future release, Update RN & featured date

#4069 Proofread
  content/data-hub/index.md
Labels: Internal WIP

#4077 Proofread
  content/howto7/logic-business-rules/finding-object-activities.md
Labels: Internal WIP

#4078 Proofread
  content/howto7/collaboration-requirements-management/translate-your-app-content.md
Labels: Internal WIP

#4079 Proofread
  content/refguide7/attachments/819203/917756.png
  content/refguide7/cast-object.md
Labels: Internal WIP

#4059 9.9.2 RN
  content/releasenotes/studio-pro/9.9.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#4081 Update yarn.lock
  yarn.lock
Labels: Internal WIP

#4071 COA-733: Add Free Apps Archival documentation
  content/developerportal/deploy/mendix-cloud-deploy.md
Labels: Needs language review

#4052 9.6.7 RN
  content/releasenotes/studio-pro/9.6.md
Labels: Future release

#4085 Corrected time limitation for Unlicensed Apps.
  content/developerportal/deploy/licensing-apps-outside-mxcloud.md
Labels: Needs language review

#4089 Add more info on missing alerts
  content/developerportal/operate/monitoring-application-health.md
Labels: Needs R&D technical verification

#4098 Update for Workflow Commons 2.0.0
  content/appstore/modules/workflow-commons.md
  content/refguide/workflow-setting-up-app.md
Labels: 9.10.0

#4088 DataHub release 2.17.0 Release Notes
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#4095 Add MQTT file
  content/appstore/connectors/mqtt.md
Labels: Future release

#4104 Update QOS links and some punctuation
  content/appstore/connectors/mqtt.md
Labels: Verify formatting after merge

#4084 9.10 RN
  content/releasenotes/studio-pro/9.10.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: 9.10.0

#4014 Add Kazakh language into the List of Supported Languages
  content/refguide/language-settings.md
Labels: 9.10.0

#4101 Git Changes for 9.10
  content/refguide/attachments/merge-dialog/merge-dialog-git.png
  content/refguide/merge-dialog.md
  content/refguide/using-version-control-in-studio-pro.md
Labels: 9.10.0

#3976 Add Performance Bot Best Practice MXP012 - Repeatedly Committed Variable
  content/refguide/performance-best-practices.md
Labels: 9.10.0

#4099 Describe XPath variable feature 9.10
  content/refguide/attachments/xpath-source/xpath-variable-constraint.png
  content/refguide/xpath-source.md
Labels: 9.10.0

#4106 Add Studio release notes
  content/releasenotes/studio/9.7-and-above.md
Labels: 9.10.0

#4068 [MOO-494] Add docs for dangling references
  content/refguide/offline-first.md
Labels: 9.10.0

#4092 Workflows Changes in 9.10
  content/appstore/modules/workflow-commons.md
  content/refguide/attachments/complete-task/complete-task-properties.jpg
  content/refguide/attachments/complete-task/complete-task.jpg
  content/refguide/attachments/complete-task/desktop.ini
  content/refguide/attachments/open-user-task/open-task-page-properties.jpg
  content/refguide/attachments/retrieve-workflow-context/retrieve-workflow-context-properties.png
  content/refguide/attachments/retrieve-workflow-context/retrieve-workflow-context.png
  content/refguide/attachments/set-task-outcome/complete-task-properties.jpg
  content/refguide/attachments/workflow-parameters/workflow-parameters.png
  content/refguide/change-workflow-state.md
  content/refguide/complete-task.md
  content/refguide/retrieve-workflow-context.md
  content/refguide/show-task-page.md
  content/refguide/show-workflow-page.md
  content/refguide/user-task.md
  content/refguide/workflow-activities.md
  content/refguide/workflow-call.md
  content/refguide/workflow-parameters.md
  content/refguide/workflow-setting-up-app.md
  content/refguide/workflows.md
  content/studio-how-to/workflow-how-to-configure.md
  content/studio/workflows-9.6.md
  content/studio/workflows.md
Labels: 9.10.0

#3968 Add naming constraint on metrics (Mendix 9.10)
  content/developerportal/operate/datadog-metrics.md
  content/refguide/metrics-counter.md
  content/refguide/metrics-gauge.md
  content/refguide/metrics-increment-counter.md
  content/refguide/metrics.md
Labels: Needs R&D technical verification, 9.10.0

#4007 [UFC-403] Update documentation with adding platform selection in javascript actions
  content/refguide/attachments/javascript-actions/javascript-action-settings-no-para.png
  content/refguide/javascript-actions.md
Labels: 9.10.0

#3942 [RTI-338] Add Task Queue Retry to docs
  content/refguide/java-action-call.md
  content/refguide/microflow-call.md
  content/refguide/task-queue.md
Labels: 9.10.0

#3944 Nk data grid widgets
  content/appstore/modules/data-grid-2.md
  content/refguide/attachments/common-widget-properties/visibility-example.png
  content/refguide/attachments/data-widgets/control-bar-add-button.png
  content/refguide/common-widget-properties.md
  content/refguide/control-bar.md
  content/refguide/grids.md
Labels: Internal WIP

#4113 ba-dh-2.18.0 - Document update for DataHub 2.18.0 release
  content/releasenotes/data-hub/index.md
  themes/mendix/layouts/partials/frontpage/featured.html
Labels: Future release

#4108 Add hyperlink to team server API doc
  content/apidocs-mxsdk/apidocs/build-api.md
Labels: Internal WIP

#4124 Clarify once license per environment
  content/developerportal/deploy/activate-a-mendix-license-on-microsoft-windows.md
  content/developerportal/deploy/licensing-apps-outside-mxcloud.md
Labels: Needs Support verification

#4097 Hidden attributes and stateless transactions
  content/refguide/access-rules.md
  content/refguide/attachments/communication-patterns/attribute-security.png
  content/refguide/communication-patterns.md
Labels: Needs R&D technical verification
