Repository mendix/docs, pull requests merged in 2023-10, with the labels that each got.

#6534 Proofread and update SP Integration docs
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/odata-query-options.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-microflow.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/publish-rest-service.md
  static/attachments/refguide/modeling/integration/publish-rest-service/AddOperation.png
  static/attachments/refguide/modeling/integration/publish-rest-service/AddRestResource.png
  static/attachments/refguide/modeling/integration/publish-rest-service/CompleteMFNoErrorHandling.png
  static/attachments/refguide/modeling/integration/publish-rest-service/CompleteMFWithErrorHandling.png
  static/attachments/refguide/modeling/integration/publish-rest-service/ConvertOrderID.png
  static/attachments/refguide/modeling/integration/publish-rest-service/DataGridSettings.png
  static/attachments/refguide/modeling/integration/publish-rest-service/MD_SelectedAttributes.png
  static/attachments/refguide/modeling/integration/publish-rest-service/MFExportWithMapping.png
  static/attachments/refguide/modeling/integration/publish-rest-service/OperationsDialogSettings.png
  static/attachments/refguide/modeling/integration/publish-rest-service/OrderNotFoundHeader.png
  static/attachments/refguide/modeling/integration/publish-rest-service/OrderNotFoundResponse.png
  static/attachments/refguide/modeling/integration/publish-rest-service/ParsingErrorMicroflow.png
  static/attachments/refguide/modeling/integration/publish-rest-service/ParsingErrorRESTResult.png
  static/attachments/refguide/modeling/integration/publish-rest-service/ParsingErrorResponse.png
  static/attachments/refguide/modeling/integration/publish-rest-service/ParsingErrorResponseHeader.png
  static/attachments/refguide/modeling/integration/publish-rest-service/RESTTestDetails.png
  static/attachments/refguide/modeling/integration/publish-rest-service/RESTTestExceute.png
  static/attachments/refguide/modeling/integration/publish-rest-service/RESTTestExecute.png
  static/attachments/refguide/modeling/integration/publish-rest-service/RESTTestOverview.png
  static/attachments/refguide/modeling/integration/publish-rest-service/RESTTestResponse.png
  static/attachments/refguide/modeling/integration/publish-rest-service/RetrieveOrder.png
  static/attachments/refguide/modeling/integration/publish-rest-service/httpResponse.png
  static/attachments/refguide/modeling/integration/publish-rest-service/httpResponseHeader.png
  static/attachments/refguide/modeling/integration/publish-rest-service/order_NewEdit_Page.png
Labels: Internal WIP

#6585 Qt build o data ap is resized
  content/en/docs/refguide/modeling/integration/odata-services/build-odata-apis.md
Labels: Internal WIP

#6549 sap UI themes
  content/en/docs/appstore/modules/sap-ui-resources/_index.md
Labels: Future release

#6586 Revised wording
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
Labels: Internal WIP

#6407 Patch 1
  content/en/docs/appstore/connectors/aws/amazon-bedrock.md
  content/en/docs/appstore/connectors/aws/aws-lambda-connector.md
Labels: Internal WIP, Needs language review

#6589 Update MG for Use in SP
  content/en/docs/appstore/general/app-store-content.md
  content/en/docs/appstore/general/app-store-overview.md
  content/en/docs/releasenotes/marketplace/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/appstore/general/app-store-overview/component-details.png
Labels: Internal WIP, Awaiting response

#6401 AWS Bdoc draft
  content/en/docs/appstore/connectors/aws/amazon-bedrock.md
  content/en/docs/appstore/connectors/aws/aws-lambda-connector.md
Labels: Internal WIP

#6592 Update MG for share
  content/en/docs/appstore/general/share-app-store-content.md
  static/attachments/appstore/general/share-app-store-content/capabilities.jpg
  static/attachments/appstore/general/share-app-store-content/capabilities.png
  static/attachments/appstore/general/share-app-store-content/enable.jpg
  static/attachments/appstore/general/share-app-store-content/enable.png
  static/attachments/appstore/general/share-app-store-content/general.jpg
  static/attachments/appstore/general/share-app-store-content/general.png
  static/attachments/appstore/general/share-app-store-content/package.jpg
  static/attachments/appstore/general/share-app-store-content/package.png
  static/attachments/appstore/general/share-app-store-content/publish.png
Labels: Internal WIP

#6590 Docs Mx Blue color exploration
  assets/scss/_styles_project.scss
  assets/scss/_variables_project.scss
  layouts/partials/feedback.html
  static/icons/content-paper-edit.svg
  static/icons/handshake.png
  static/icons/messages-bubble-text-1.svg
  static/icons/mx-data-hub.png
  static/icons/mx-dev-portal.png
  static/icons/print-text.svg
  static/icons/shopping-cart-1.png
  static/icons/sp-logo.png
  static/icons/translate.svg
Labels: Internal WIP

#6559 Proofread and update Connector docs
  content/en/docs/appstore/connectors/database-connector.md
  content/en/docs/appstore/connectors/email-connector.md
Labels: Internal WIP

#6602 [Snyk] Upgrade @fortawesome/fontawesome-free from 6.2.0 to 6.4.2
  package-lock.json
  package.json
Labels: Dependencies

#6616 Language review for Mendix Public Cloud (part 2)
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/_index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/access-restrictions.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mxcloudv4/_index.md
  static/attachments/developerportal/deploy/mendix-cloud-deploy/deployment-started.png
Labels: Internal WIP

#6631 Update Cloud release notes
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#6604 8.18.27 RN
  content/en/docs/releasenotes/studio-pro/8/8.18.md
Labels: Update release and/or featured date

#6606 7.23.37 RN
  content/en/docs/releasenotes/studio-pro/7/7.23.md
Labels: Update release and/or featured date

#6633 Update scheduled-events.md
  content/en/docs/refguide/modeling/resources/scheduled-events.md
  content/en/docs/refguide/modeling/resources/task-queue.md
Labels: Needs Support verification

#6646 github issue 6641
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-registry.md
Labels: Changes requested

#6659 Portnus 2 3 0 release
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-operator.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/customPlan.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/customPlanDetails.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/customPlanEnable.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/savedCustomPlan.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/configureEnvResources.png
Labels: Future release

#6595 Kv proofreading1
  content/en/docs/appstore/modules/forgot-password.md
Labels: Internal WIP

#6639 Running Now rework
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/licensing-apps/basic-package.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/scale-environment.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/troubleshooting-mxcloud-runningnow.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-monitor.md
  content/en/docs/developerportal/operate/metrics.md
  content/en/docs/developerportal/operate/metrics/_index.md
  content/en/docs/developerportal/operate/metrics/trends-v4.md
  content/en/docs/developerportal/operate/metrics/troubleshooting-mxcloud-runningnow.md
  content/en/docs/developerportal/operate/monitoring-application-health/_index.md
  content/en/docs/developerportal/operate/monitoring-application-health/receive-alerts.md
  content/en/docs/developerportal/operate/monitoring-with-apm/_index.md
  content/en/docs/howto/monitoring-troubleshooting/manage-app-performance/_index.md
  content/en/docs/howto9/monitoring-troubleshooting/manage-app-performance/_index.md
  content/en/docs/refguide/runtime/monitoring-mendix-runtime.md
  content/en/docs/refguide8/runtime/monitoring-mendix-runtime.md
  content/en/docs/refguide9/runtime/monitoring-mendix-runtime.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  content/en/docs/releasenotes/studio-pro/9/9.3.md
  content/en/docs/releasenotes/studio-pro/9/9.4.md
  content/en/docs/releasenotes/studio-pro/9/9.5.md
  content/en/docs/releasenotes/studio-pro/9/9.6.md
  static/attachments/developerportal/deploy/mendix-cloud-deploy/environments-details/actions-v4.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/environments-details/actions-v5.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/troubleshooting-mxcloud-runningnow/dialog-box.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/troubleshooting-mxcloud-runningnow/running-request-details.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/troubleshooting-mxcloud-runningnow/stack.png
  static/attachments/developerportal/operate/metrics/app-cpu.png
  static/attachments/developerportal/operate/metrics/app-disk-usage-pct.png
  static/attachments/developerportal/operate/metrics/app-number-of-files.png
  static/attachments/developerportal/operate/metrics/app-size-of-files.png
  static/attachments/developerportal/operate/metrics/db-burst-balance.png
  static/attachments/developerportal/operate/metrics/db-cpu-usage.png
  static/attachments/developerportal/operate/metrics/db-disk-ios.png
  static/attachments/developerportal/operate/metrics/db-disk-latency.png
  static/attachments/developerportal/operate/metrics/db-disk-throughput.png
  static/attachments/developerportal/operate/metrics/db-disk-usage-bytes.png
  static/attachments/developerportal/operate/metrics/db-mutations.png
  static/attachments/developerportal/operate/metrics/db-os-memory.png
  static/attachments/developerportal/operate/metrics/db-table-vs-index.png
  static/attachments/developerportal/operate/metrics/jvm-heap.png
  static/attachments/developerportal/operate/metrics/jvm-process-memory.png
  static/attachments/developerportal/operate/metrics/jvm-thread-count.png
  static/attachments/developerportal/operate/metrics/no-db-connections.png
  static/attachments/developerportal/operate/metrics/no-db-queries.png
  static/attachments/developerportal/operate/metrics/no-ext-reqs.png
  static/attachments/developerportal/operate/metrics/node-os-memory.png
  static/attachments/developerportal/operate/metrics/nodepermission.jpg
  static/attachments/developerportal/operate/metrics/threadpool-external-reqs.png
  static/attachments/developerportal/operate/metrics/trends-v4/environment.png
  static/attachments/developerportal/operate/metrics/troubleshooting-mxcloud-runningnow/troubleshooting-mxcloud-runningnow-img1.png
  static/attachments/developerportal/operate/metrics/troubleshooting-mxcloud-runningnow/troubleshooting-mxcloud-runningnow-img2.png
  static/attachments/developerportal/operate/metrics/user-accounts-logins.png
Labels: Needs R&D technical verification

#6680 Remove "the" from "the Mendix Cloud"
  content/en/docs/developerportal/control-center/_index.md
  content/en/docs/developerportal/control-center/set-up-sso-byoidp.md
  content/en/docs/developerportal/deploy/_index.md
  content/en/docs/developerportal/deploy/deploying-to-mindsphere.md
  content/en/docs/developerportal/deploy/general/deployment-location.md
  content/en/docs/developerportal/deploy/general/licensing-apps-outside-mxcloud.md
  content/en/docs/developerportal/deploy/general/running-in-iframe.md
  content/en/docs/developerportal/deploy/general/securing-outgoing-connections-from-your-application.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/cloud-version-region.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/custom-domains.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/licensing-apps/_index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/licensing-apps/basic-package.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-cloud-request-headers.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-sso.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/node-permissions.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/scale-environment.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/sending-email.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/studio-deployment-settings.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/webhooks.md
  content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
  content/en/docs/developerportal/deploy/on-premises-design/_index.md
  content/en/docs/developerportal/deploy/on-premises-design/ms-windows/_index.md
  content/en/docs/developerportal/deploy/on-premises-design/security-checklist-for-your-on-premises-installation.md
  content/en/docs/developerportal/deploy/on-premises-design/setting-up-monitoring-with-new-relic.md
  content/en/docs/developerportal/deploy/private-cloud/_index.md
  content/en/docs/developerportal/general/settings/_index.md
  content/en/docs/developerportal/general/team/app-roles.md
  content/en/docs/developerportal/operate/_index.md
  content/en/docs/developerportal/operate/backups/_index.md
  content/en/docs/developerportal/operate/backups/create-backup.md
  content/en/docs/developerportal/operate/backups/database-size-reduction.md
  content/en/docs/developerportal/operate/backups/restore-backup-locally.md
  content/en/docs/developerportal/operate/backups/restore-backup.md
  content/en/docs/developerportal/operate/logs.md
  content/en/docs/developerportal/operate/monitoring-application-health/_index.md
  content/en/docs/developerportal/operate/monitoring-application-health/receive-alerts.md
  content/en/docs/developerportal/operate/monitoring-with-apm/appdynamics-metrics.md
  content/en/docs/developerportal/operate/monitoring-with-apm/datadog-metrics.md
  content/en/docs/developerportal/operate/monitoring-with-apm/dynatrace-metrics.md
  content/en/docs/developerportal/operate/monitoring-with-apm/splunk-metrics.md
  content/en/docs/developerportal/support/new-app-node-request-template.md
  content/en/docs/developerportal/support/security-findings-faq.md
  content/en/docs/howto/data-models/migrating-your-mendix-database.md
  content/en/docs/howto/front-end/custom-error-page.md
  content/en/docs/howto/integration/access-a-samba-share-from-the-mxcloud.md
  content/en/docs/howto/monitoring-troubleshooting/log-levels.md
  content/en/docs/howto/security/create-a-secure-app.md
  content/en/docs/howto7/data-models/migrating-your-mendix-database.md
  content/en/docs/howto7/extensibility/access-a-samba-share-from-the-mxcloud.md
Labels: Internal WIP

#6684 Correct links
  content/en/docs/developerportal/operate/metrics.md
  content/en/docs/refguide8/runtime/monitoring-mendix-runtime.md
  content/en/docs/refguide9/runtime/monitoring-mendix-runtime.md
Labels: Internal WIP

#6690 Proofread Cloud docs
  content/en/docs/developerportal/deploy/general/deployment-location.md
  content/en/docs/developerportal/deploy/general/two-factor-authentication.md
  static/attachments/developerportal/deploy/general/two-factor-authentication/authentication-sms.png
  static/attachments/developerportal/deploy/general/two-factor-authentication/please-authenticate.png
Labels: Internal WIP

#6507 Continuation URL parameter for Mendix SSO
  content/en/docs/appstore/modules/mendix-sso.md
  static/attachments/appstore/modules/mendix-sso/continuation.png
Labels: Future release

#6693 Update _index.md
  content/en/docs/developerportal/control-center/_index.md
  content/en/docs/releasenotes/developer-portal/_index.md
Labels: Future release, Needs language review, Update release and/or featured date

#6689 AppInsights Developer Release Notes
  content/en/docs/developerportal/app-insights/feedback.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/developerportal/app-insights/feedback/tag-management-settings.png
Labels: Future release, Needs language review, Update release and/or featured date

#6691 Remove temp note
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/troubleshooting-mxcloud-runningnow.md
Labels: Future release

#6674 Add Origin-Trial header
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#6705 Language review: Licensing Mendix Cloud
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/licensing-apps/_index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/licensing-apps/basic-package.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/licensing-apps/migrate-free-app-to-basic.md
  static/attachments/developerportal/deploy/mendix-cloud-deploy/licensing-apps/basic-package/configure-basic-package.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/licensing-apps/basic-package/free-app-message.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/licensing-apps/basic-package/invoice-details.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/licensing-apps/confirm-unlink.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/licensing-apps/migrate-free-app-to-basic/confirm-unlink.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/licensing-apps/migrate-free-app-to-basic/download-backup.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/licensing-apps/migrate-free-app-to-basic/unlink-free-app.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/licensing-apps/unlink-free-app.png
Labels: Internal WIP

#6703 9.24.11 RN
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Update release and/or featured date

#6713 Documentation updates
  content/en/docs/developerportal/deploy/private-cloud/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-registry.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-operator.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
Labels: Needs language review

#6724 Proofread Backup docs
  content/en/docs/developerportal/operate/backups/_index.md
  content/en/docs/developerportal/operate/backups/create-backup.md
  content/en/docs/developerportal/operate/backups/database-size-reduction.md
  content/en/docs/developerportal/operate/backups/download-backup.md
  content/en/docs/developerportal/operate/backups/restore-backup-locally.md
  content/en/docs/developerportal/operate/backups/restore-backup.md
  static/attachments/developerportal/operate/backups/create-backup/backupoptions.jpg
  static/attachments/developerportal/operate/backups/create-backup/backupoptions.png
  static/attachments/developerportal/operate/backups/create-backup/environment.png
  static/attachments/developerportal/operate/backups/download-backup/backupoptions-free.png
  static/attachments/developerportal/operate/backups/download-backup/backupoptions.jpg
  static/attachments/developerportal/operate/backups/download-backup/backupoptions.png
  static/attachments/developerportal/operate/backups/download-backup/environment.png
  static/attachments/developerportal/operate/backups/restore-backup-locally/postgres-password.png
  static/attachments/developerportal/operate/backups/restore-backup/backupoptions.png
  static/attachments/developerportal/operate/backups/restore-backup/environment.png
  static/attachments/developerportal/operate/backups/restore-backup/free-backup-options.png
Labels: Internal WIP

#6736 Qt external entities review
  content/en/docs/refguide/modeling/domain-model/external-entities.md
Labels: Internal WIP

#6688 10.4 RN
  content/en/docs/releasenotes/studio-pro/10/10.1.md
  content/en/docs/releasenotes/studio-pro/10/10.2.md
  content/en/docs/releasenotes/studio-pro/10/10.3.md
  content/en/docs/releasenotes/studio-pro/10/10.4.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.4

#6707 Mention support of Postgres 16
  content/en/docs/refguide/installation/system-requirements.md
  content/en/docs/refguide7/general/system-requirements.md
  content/en/docs/refguide8/general/system-requirements.md
Labels: 10.4

#6679 Add page for beta logic editors
  content/en/docs/refguide/general/studio-pro-overview.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/logic-editors-beta.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot.md
  content/en/docs/refguide9/modeling/mx-assist-studio-pro/mx-assist-logic-bot.md
  content/en/docs/refguide9/modeling/mx-assist-studio-pro/mx-assist-performance-bot/_index.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/logic-editors-beta/assist-bulb.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/logic-editors-beta/beta-toggle.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/logic-editors-beta/initial-recommendations.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/logic-editors-beta/search-microflows-nanoflows.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/logic-editors-beta/search-sub-actions.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/logic-editors-beta/search-toolbox.png
  static/attachments/refguide/modeling/menus/edit-menu/preferences-dialog/preferences.png
Labels: 10.4

#6718 Add or move elements in workflows
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
Labels: 10.4

#6711 Select parameters when call a new micro/nanoflow
  content/en/docs/refguide/modeling/pages/on-click-event.md
  static/attachments/refguide/modeling/pages/on-click-event/configure-new-microflow-no-parameter.png
  static/attachments/refguide/modeling/pages/on-click-event/configure-new-microflow-with-parameter.png
  static/attachments/refguide/modeling/pages/on-click-event/microflow-settings.png
Labels: 10.4

#6608 Updating history view to add changes info
  content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
  static/attachments/refguide/modeling/menus/version-control-menu/history-dialog/MergeRevision.png
  static/attachments/refguide/modeling/menus/version-control-menu/history-dialog/RevChangesDisk.png
  static/attachments/refguide/modeling/menus/version-control-menu/history-dialog/RevChangesModel.png
  static/attachments/refguide/modeling/menus/version-control-menu/history-dialog/RevChangesVersion.png
  static/attachments/refguide/modeling/menus/version-control-menu/history-dialog/Solution.png
  static/attachments/refguide/modeling/menus/version-control-menu/history-dialog/revisions.png
Labels: 10.4

#6699 Upgraded information about BYOK
  content/en/docs/appstore/modules/business-events.md
Labels: Needs language review, 10.4

#6654 Add South African languages to the list of supported languages
  content/en/docs/refguide/modeling/menus/translatable-texts/language-settings.md
Labels: 10.4

#6728 DataGrid 2 autofill improvement info
  content/en/docs/appstore/modules/data-widgets/data-grid-2.md
Labels: 10.4

#6709 [WTF-1651] Document "Support configuring arguments for delete client action"
  content/en/docs/refguide/modeling/pages/on-click-event.md
Labels: 10.4

#6685 Add note on ignoring read-only attributes
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/odata-query-options.md
Labels: Needs language review, 10.4

#6687 Update oidc.md
  content/en/docs/appstore/modules/oidc.md
Labels: Needs language review

#6681 Add note about on delete behaviour of external entities
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/auto-committed-objects.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/deleting-objects.md
  content/en/docs/refguide/modeling/domain-model/associations/association-properties.md
  content/en/docs/refguide/modeling/domain-model/create-a-basic-data-layer.md
  content/en/docs/refguide/modeling/domain-model/generalization-and-association.md
Labels: 10.4
