Repository mendix/docs, pull requests merged in 2023-01, with the labels that each got.

#5473 Update info on M and L pattern letters
  content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
Labels: Needs R&D technical verification

#5471 Review and Relocate how-to - Work with Lists in a Microflow
  content/en/docs/appstore/app-services/email-service.md
  content/en/docs/howto/logic-business-rules/define-access-rules-using-xpath.md
  content/en/docs/howto/logic-business-rules/extending-your-application-with-custom-java.md
  content/en/docs/howto/logic-business-rules/java-api-tutorial.md
  content/en/docs/howto/logic-business-rules/trigger-microflow-from-menu-item.md
  content/en/docs/howto/logic-business-rules/working-with-lists-in-a-microflow.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow.md
  content/en/docs/refguide/modeling/pages/button-widgets/create-a-custom-save-button.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581054.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581055.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581058.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581059.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581061.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581063.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581064.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581067.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581069.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581073.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581076.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581078.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581080.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581084.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581085.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581086.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581087.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581088.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581091.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581093.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581103.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581106.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581110.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581111.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581113.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/18581118.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/8946316.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/variable.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow/working-with-lists-optimization.jpg
Labels: Internal WIP

#5478 XSUAA Workaround for Mendix 9.20 [MCDEP-1294]
  content/en/docs/partners/sap/sap-xsuaa-connector.md
  content/en/docs/partners/sap/use-sap-xsuaa-connector.md
Labels: Needs R&D technical verification

#5467 Add top/skip info to OData doc
  content/en/docs/refguide/modeling/integration/published-odata-services/odata-query-options.md
  content/en/docs/refguide/modeling/integration/published-odata-services/published-odata-resource.md
Labels: Internal WIP

#5449 OIDC - add Azure processing information.
  content/en/docs/appstore/modules/oidc.md
  static/attachments/appstore/modules/oidc/enable-sam-parsing.png
Labels: Future release, Needs R&D technical verification

#5481 Move and review how-to - Trigger a Microflow from a Menu Item
  content/en/docs/howto/integration/expose-a-web-service.md
  content/en/docs/howto/integration/importing-excel-documents/_index.md
  content/en/docs/howto/integration/integrating-a-legacy-system-into-a-mendix-app.md
  content/en/docs/howto/logic-business-rules/java-api-tutorial.md
  content/en/docs/howto/logic-business-rules/trigger-microflow-from-menu-item.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extract-and-use-sub-microflows.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/trigger-microflow-from-menu-item.md
  content/en/docs/refguide/modeling/pages/page-resources/menu.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/call-microflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/caption.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/created-microflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/go-to-target.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/hello-world-message.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/new-menu-item.jpg
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/new-microflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/show-message-activity.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/show-message-properties.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/triggering-microflow-from-menu-item/toolbox.png
Labels: Internal WIP

#5487 Move and review how-to - Extend App with Custom Java
  content/en/docs/howto/logic-business-rules/define-access-rules-using-xpath.md
  content/en/docs/howto/logic-business-rules/java-api-tutorial.md
  content/en/docs/howto/monitoring-troubleshooting/debug-java-actions/_index.md
  content/en/docs/refguide/java-programming/extending-your-application-with-custom-java.md
  content/en/docs/refguide/java-programming/troubleshooting.md
  content/en/docs/refguide/java-programming/using-eclipse.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-versioning.md
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/add-widget.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/add.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/app1.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/app2.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/argument.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/call1.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/call2.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/import3.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/microflow2.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/microflow3.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/microflow4.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/package-explorer.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/return.png
  static/attachments/refguide/java-programming/extending-your-application-with-custom-java/show-message.png
Labels: Internal WIP

#5492 Kk aws ses feedback
  content/en/docs/appstore/connectors/aws/amazon-ses-email-connector.md
Labels: Changes requested

#5495 Changing the navtitle
  content/en/docs/appstore/connectors/aws/amazon-ses-email-connector.md
Labels: Internal WIP

#5483 Release notes and updates for Mx4PC 2.10.0 (expected to be released on January 5)
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/developerportal/deploy/private-cloud/secret-store-credentials.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Update release and/or featured date

#5497 fix for the year
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Internal WIP

#5499 DD_LOG_LEVEL clarification
  content/en/docs/developerportal/operate/metrics/monitoring-with-apm/datadog-metrics.md
Labels: Needs language review

#5353 Solution upgrade documentation
  content/en/docs/appstore/creating-content/connector-guide-build/_index.md
  content/en/docs/appstore/creating-content/sol-solutions-impl-guide/_index.md
  content/en/docs/appstore/creating-content/sol-solutions-impl-guide/sol-set-up.md
  content/en/docs/appstore/creating-content/sol-solutions-impl-guide/sol-upgrade.md
  content/en/docs/refguide/modeling/import-and-export/_index.md
  static/attachments/appstore/creating-content/sol-solutions-impl-guide/solution-import.png
  static/attachments/appstore/creating-content/sol-solutions-impl-guide/solution-lifecycle.png
  static/attachments/appstore/creating-content/sol-solutions-impl-guide/solution-upgrade.png
Labels: Future release, Edit images after merging

#5502 Add redirect to Error Handling document
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/_MAPPING.txt
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extract-and-use-sub-microflows.md
Labels: Internal WIP

#5419 ibm cloud deprecate docs
  content/en/docs/appstore/connectors/ibm-watson-connector.md
  content/en/docs/developerportal/collaborate/general-settings/_index.md
  content/en/docs/developerportal/community-tools/oauth-scopes.md
  content/en/docs/developerportal/deploy/_index.md
  content/en/docs/developerportal/deploy/cloud-foundry-deploy.md
  content/en/docs/developerportal/deploy/general/_index.md
  content/en/docs/developerportal/deploy/general/licensing-apps-outside-mxcloud.md
  content/en/docs/developerportal/deploy/ibm-cloud.md
  content/en/docs/developerportal/operate/_index.md
  content/en/docs/developerportal/support/_index.md
  content/en/docs/developerportal/support/new-app-node-request-template.md
  content/en/docs/refguide/modeling/resources/constants.md
  content/en/docs/refguide7/desktop-modeler/constants.md
  content/en/docs/refguide8/modeling/resources/constants.md
  content/en/docs/releasenotes/app-store/_index.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/on-premises.md
Labels: Changes requested

#5518 DynamoDB more info
  content/en/docs/appstore/connectors/aws/aws-dynamodb.md
Labels: Changes requested

#5516 SAML sec vuln
  content/en/docs/releasenotes/security-advisories/_index.md
Labels: Needs R&D technical verification

#5522 Adding more in-depth authentication instructions
  content/en/docs/appstore/connectors/aws/amazon-polly.md
  static/attachments/appstore/connectors/aws-dynamodb/appsettings.png
  static/attachments/appstore/connectors/aws-dynamodb/credentials.png
Labels: Internal WIP

#5505 Add information about SAML versions
  content/en/docs/appstore/modules/saml.md
Labels: Needs R&D technical verification

#5508 Note space taken by transaction logs.
  content/en/docs/developerportal/operate/metrics/trends-v4.md
Labels: Needs R&D technical verification

#5528 kk-aws-fixes-dynamodb2
  content/en/docs/appstore/connectors/aws/aws-dynamodb.md
Labels: Changes requested

#5527 Mendix Cloud replaces custom HTTP Reason Codes
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mxcloudv4/_index.md
  content/en/docs/refguide/modeling/integration/http-request-and-response-entities.md
Labels: Needs Support verification

#5533 Revert "Data Broker Milestone 23 - Outbox"
  content/en/docs/appstore/modules/business-events.md
Labels: Future release

#5513 Update amazon-polly.md
  content/en/docs/appstore/connectors/aws/amazon-polly.md
Labels: Internal WIP

#5532 Creating AWS connectors
  content/en/docs/appstore/connectors/aws/aws-create-new.md
  static/attachments/appstore/connectors/aws-create-new/sampleentities.png
  static/attachments/appstore/connectors/aws-create-new/samplefolders.png
Labels: Needs R&D technical verification

#5536 Move and review how-to - Configure String Concatenation
  content/en/docs/howto/logic-business-rules/string-concatenation.md
  content/en/docs/refguide/modeling/application-logic/string-concatenation.md
  static/attachments/refguide/modeling/application-logic/string-concatenation/bco_contactperson_createfullname.jpg
  static/attachments/refguide/modeling/application-logic/string-concatenation/bco_contactperson_createfullname_hardtoread.jpg
  static/attachments/refguide/modeling/application-logic/string-concatenation/bco_contactperson_createfullname_inefficient.jpg
Labels: Internal WIP

#5548 A few small changes per peer review
  content/en/docs/appstore/connectors/aws/aws-create-new.md
Labels: Internal WIP

#5544 Private cloud portal release 2 20
  content/en/docs/apidocs-mxsdk/apidocs/private-cloud-deploy-api.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/Customization.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/SetupButton.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/image2.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/image3.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/image4.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/runtime-tab.png
Labels: Future release, Needs language review

#5514 9.12.9 RN
  content/en/docs/releasenotes/studio-pro/7/7.23.md
  content/en/docs/releasenotes/studio-pro/8/8.18.md
  content/en/docs/releasenotes/studio-pro/9/9.10.md
  content/en/docs/releasenotes/studio-pro/9/9.11.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.18.md
  content/en/docs/releasenotes/studio-pro/9/9.2.md
  content/en/docs/releasenotes/studio-pro/9/9.20.md
  content/en/docs/releasenotes/studio-pro/9/9.3.md
  content/en/docs/releasenotes/studio-pro/9/9.5.md
  content/en/docs/releasenotes/studio-pro/9/9.6.md
  content/en/docs/releasenotes/studio-pro/9/9.7.md
  content/en/docs/releasenotes/studio-pro/9/9.8.md
  content/en/docs/releasenotes/studio-pro/9/9.9.md
Labels: 9.12.9

#5552 Move workflow how-tos to refguide
  content/en/docs/refguide/modeling/application-logic/workflows/add-action-to-workflow-toolbox.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-how-to-configure.md
  content/en/docs/studio/workflows/_index.md
  static/attachments/refguide/modeling/application-logic/workflows/add-action-to-workflow-toolbox/expose-as-workflow-action-properties.png
  static/attachments/refguide/modeling/application-logic/workflows/add-action-to-workflow-toolbox/expose-as-workflow-action.png
  static/attachments/refguide/modeling/application-logic/workflows/add-action-to-workflow-toolbox/microflow-call.png
  static/attachments/refguide/modeling/application-logic/workflows/add-action-to-workflow-toolbox/workflow-toolbox.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/access-rules-facilities-and-user.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/access-rules-hr.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/access-rules-manager.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/add-workflow.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/admin-role.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/call-microflow.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/decision-outcomes.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/decision-properties.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/demo_hr.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/domain-model.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/edit-module-roles.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/employees-page-configured.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/employees-page.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/entity-properties.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/enumeration-laptop-model.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/enumeration-phone-model.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/manager-form.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/microflow-example.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/modules-roles.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/newly-created-workflow.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/page-access-hr.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/prepare-desk.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/read-only-form.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/select-module-roles.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/select-workflowcontext-entity.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/specify-device-and-location-properties.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/task-inbox.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/user-icon.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/workflow-admin-center.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/workflow-commons-admin.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-how-to-configure/workflow-with-task.png
Labels: Internal WIP

#5541 Move and review how-to - Use Translatable Validation Messages
  content/en/docs/howto/logic-business-rules/translatable-validation-messages.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/native-language-change.md
  content/en/docs/refguide/modeling/menus/translatable-texts/_index.md
  content/en/docs/refguide/modeling/menus/translatable-texts/translatable-validation-messages.md
  static/attachments/refguide/modeling/menus/translatable-texts/translatable-validation-messages/alternative-validation.png
  static/attachments/refguide/modeling/menus/translatable-texts/translatable-validation-messages/classic-validation.png
  static/attachments/refguide/modeling/menus/translatable-texts/translatable-validation-messages/model1.jpg
  static/attachments/refguide/modeling/menus/translatable-texts/translatable-validation-messages/model2.jpg
  static/attachments/refguide/modeling/menus/translatable-texts/translatable-validation-messages/model3.jpg
  static/attachments/refguide/modeling/menus/translatable-texts/translatable-validation-messages/model4.jpg
  static/attachments/refguide/modeling/menus/translatable-texts/translatable-validation-messages/validation-entity.png
  static/attachments/refguide/modeling/menus/translatable-texts/translatable-validation-messages/validation-enumeration.png
  static/attachments/refguide/modeling/menus/translatable-texts/translatable-validation-messages/validation-second-option.png
Labels: Internal WIP

#5556 Remove SP logic how-tos category
  content/en/docs/howto/logic-business-rules/_index.md
  content/en/docs/refguide/modeling/pages/button-widgets/create-a-custom-save-button.md
Labels: Internal WIP

#5555 RDS SME review
  content/en/docs/appstore/connectors/aws/amazon-rds-database-connector.md
Labels: Internal WIP

#5557 Update URL names in Mendix Cloud
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/_index.md
Labels: Needs R&D technical verification

#5562 Add 4XL resource Packs
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/_index.md
Labels: Needs R&D technical verification

#5564 9.12.10 RN
  content/en/docs/releasenotes/studio-pro/9/9.12.md
Labels: Future release, Update release and/or featured date

#5412 Add information about internal vs external end-users
  content/en/docs/developerportal/deploy/general/licensing-apps-outside-mxcloud.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/_index.md
Labels: Needs R&D technical verification, Internal WIP

#5574 Update Release Notes - Developer Portal
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5580 Improved documentation for published OData resource key
  content/en/docs/refguide/modeling/integration/published-odata-services/published-odata-resource.md
  content/en/docs/refguide/modeling/integration/wrap-services-odata.md
  content/en/docs/releasenotes/studio-pro/9/9.19.md
Labels: Needs language review

#5509 9.18.4 RN
  content/en/docs/releasenotes/studio-pro/9/9.10.md
  content/en/docs/releasenotes/studio-pro/9/9.11.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.13.md
  content/en/docs/releasenotes/studio-pro/9/9.14.md
  content/en/docs/releasenotes/studio-pro/9/9.15.md
  content/en/docs/releasenotes/studio-pro/9/9.16.md
  content/en/docs/releasenotes/studio-pro/9/9.17.md
  content/en/docs/releasenotes/studio-pro/9/9.18.md
  content/en/docs/releasenotes/studio-pro/9/9.19.md
  content/en/docs/releasenotes/studio-pro/9/9.20.md
  content/en/docs/releasenotes/studio-pro/9/9.21.md
  content/en/docs/releasenotes/studio-pro/9/9.5.md
  content/en/docs/releasenotes/studio-pro/9/9.6.md
  content/en/docs/releasenotes/studio-pro/9/9.7.md
  content/en/docs/releasenotes/studio-pro/9/9.8.md
  content/en/docs/releasenotes/studio-pro/9/9.9.md
Labels: Future release, Update release and/or featured date

#5359 Authentication for external entities
  content/en/docs/refguide/modeling/domain-model/external-entities.md
  content/en/docs/refguide/modeling/integration/consumed-odata-services/consumed-odata-service.md
  content/en/docs/refguide/modeling/integration/published-odata-services/_index.md
Labels: Internal WIP

#5547 9.22 RN
  content/en/docs/releasenotes/studio-pro/9/9.10.md
  content/en/docs/releasenotes/studio-pro/9/9.11.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.13.md
  content/en/docs/releasenotes/studio-pro/9/9.14.md
  content/en/docs/releasenotes/studio-pro/9/9.15.md
  content/en/docs/releasenotes/studio-pro/9/9.16.md
  content/en/docs/releasenotes/studio-pro/9/9.17.md
  content/en/docs/releasenotes/studio-pro/9/9.18.md
  content/en/docs/releasenotes/studio-pro/9/9.19.md
  content/en/docs/releasenotes/studio-pro/9/9.20.md
  content/en/docs/releasenotes/studio-pro/9/9.21.md
  content/en/docs/releasenotes/studio-pro/9/9.22.md
  content/en/docs/releasenotes/studio-pro/9/9.5.md
  content/en/docs/releasenotes/studio-pro/9/9.6.md
  content/en/docs/releasenotes/studio-pro/9/9.7.md
  content/en/docs/releasenotes/studio-pro/9/9.8.md
  content/en/docs/releasenotes/studio-pro/9/9.9.md
  layouts/partials/landingpage/latest-releases.html
Labels: 9.22

#5420 Update offline-first docs with startup sync optimizations
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/synchronization.md
Labels: 9.22

#5431 Document Native User File Encryption
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/local-data-security.md
  static/attachments/refguide/mobile/offline-first/enable-native-file-encryption.png
Labels: 9.22

#5546 Add new preference settings section about disabling sending data usage
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
Labels: 9.22

#5462 Add optional timezone parameter to date functions
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-datediff.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-datepart.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-avg.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-count.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-max.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-min.md
  content/en/docs/refguide/modeling/xpath/xpath-aggregate-functions/xpath-sum.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-contains.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-day-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-day-of-year-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-ends-with.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-false.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-hours-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-length.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-minutes-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-month-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-not.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-quarter-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-seconds-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-starts-with.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-string-length.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-true.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-week-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-weekday-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-year-from-datetime.md
Labels: 9.22

#5578 AWS S3 - authentication, access points
  content/en/docs/appstore/connectors/aws/aws-authentication.md
  content/en/docs/appstore/connectors/aws/aws-s3-connector.md
Labels: Needs R&D technical verification
