Repository mendix/docs, pull requests merged in 2023-06, with the labels that each got.

#6110 Release notes for Catalog 2.81
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#6109 Portunus 4 2 0
  content/en/docs/apidocs-mxsdk/apidocs/private-cloud-deploy-api.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/image18.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/image22.png
  static/openapi-spec/private-cloud-deploy-api.yaml
Labels: Future release

#6055 10.0.0 Beta 2 RN
  content/en/docs/releasenotes/studio-pro/10/10.0.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.0.0 Beta 2

#6007 Add business events enum documentation
  content/en/docs/appstore/modules/business-events.md
Labels: 10.0.0 Beta 2

#6083 Update Open App
  static/attachments/refguide/modeling/menus/file-menu/open-app-dialog/open-app.png
  static/attachments/refguide/modeling/menus/file-menu/open-app-dialog/select-app.png
Labels: 10.0.0 Beta 2

#6030 Update docs for new page URL features
  content/en/docs/refguide/modeling/pages/page/page-properties.md
  static/attachments/refguide/modeling/pages/page/page-url-dialog.png
Labels: 10.0.0 Beta 2

#6063 [WTF-1509] Remove Reporting Widgets from Mendix Docs (10.0.0 Beta 2)
  content/en/docs/refguide/modeling/pages/_index.md
  content/en/docs/refguide/modeling/pages/report-widgets/_index.md
  content/en/docs/refguide/modeling/pages/report-widgets/report-button.md
  content/en/docs/refguide/modeling/pages/report-widgets/report-date-parameter/_index.md
  content/en/docs/refguide/modeling/pages/report-widgets/report-date-parameter/date-range-field.md
  content/en/docs/refguide/modeling/pages/report-widgets/report-grid.md
  content/en/docs/refguide/modeling/pages/report-widgets/report-parameter.md
  content/en/docs/refguide/modeling/resources/data-sets/_index.md
Labels: 10.0.0 Beta 2

#6080 Add the option to expose as action
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
Labels: 10.0.0 Beta 2

#6066 Wait for notification
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/apply-jump-to-option.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/notify-workflow.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/unlock-workflow.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/wait-for-notification.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/notify-workflow/notify-workflow-properties.jpg
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/notify-workflow/notify-workflow.jpg
  static/attachments/refguide/modeling/application-logic/workflows/workflow-elements/wait-for-notification/wait-for-notification-example.jpg
Labels: 10.0.0 Beta 2

#6044 Update docs for new list aggregation functions
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list/aggregate-list-reduce-example.png
Labels: 10.0.0 Beta 2

#5979 Update workflow lock and unlock with input type selection
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/lock-workflow.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/unlock-workflow.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/lock-workflow/lock-workflow-properties.jpg
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/unlock-workflow/unlock-workflow-properties.jpg
Labels: 10.0.0 Beta 2

#6074 Performance bot rename and docs restructure
  content/en/docs/howto/monitoring-troubleshooting/detect-and-resolve-performance-issues.md
  content/en/docs/refguide/modeling/community-best-practices-for-app-performance.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/menus/view-menu/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/performance-best-practices.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-validation-assist.md
  content/en/docs/refguide/modeling/studio-pro-overview/_index.md
  content/en/docs/refguide/quickstart-guide/quickstart-part1.md
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/app-model.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/auto-fixable.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/best-practice-bot-pane.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/best-practice-recommendation.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/best-practice.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/drop-down-menu.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/fix-issue.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/indicator-in-editor.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/viewing-anti-pattern.jpg
Labels: 10.0.0 Beta 2

#5982 Public add clear from device nanoflow activity
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/clear-from-device.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/clear-from-device/clear-from-device-properties.png
Labels: 10.0.0 Beta 2

#5980 Modify docs for adding a new workflow
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
  static/attachments/refguide/modeling/application-logic/workflows/add-workflow-dialog.jpg
  static/attachments/refguide/modeling/application-logic/workflows/add-workflow-dialog.png
Labels: 10.0.0 Beta 2

#6038 [RUN-3527][RUN-3349] Remove Mx10 Metrics removed features
  content/en/docs/refguide/runtime/metrics.md
Labels: 10.0.0 Beta 2

#6013 Add new runtime configuration setting description
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: 10.0.0 Beta 2

#5944 Update DatabaseUseSsl runtime setting to tri-state use
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: 10.0.0 Beta 2

#5983 Remove SVN from Mx10 docs
  content/en/docs/appstore/creating-content/connector-guide-build/connector-guide-best-practices.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-installation-steps/_index.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-uninstall-steps.md
  content/en/docs/developerportal/collaborate/team-server/migrate-to-git.md
  content/en/docs/refguide/general/system-requirements.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/building-native-apps/native-template.md
  content/en/docs/refguide/modeling/dev-best-practices.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/menus/file-menu/import-app-package-dialog.md
  content/en/docs/refguide/modeling/menus/file-menu/open-app-dialog.md
  content/en/docs/refguide/modeling/menus/version-control-menu/_index.md
  content/en/docs/refguide/modeling/menus/version-control-menu/branch-line-manager-dialog/_index.md
  content/en/docs/refguide/modeling/menus/version-control-menu/commit-dialog.md
  content/en/docs/refguide/modeling/menus/version-control-menu/download-from-version-control-dialog.md
  content/en/docs/refguide/modeling/menus/version-control-menu/merge-dialog.md
  content/en/docs/refguide/modeling/menus/version-control-menu/upload-to-version-control-dialog.md
  content/en/docs/refguide/modeling/menus/view-menu/_index.md
  content/en/docs/refguide/modeling/menus/view-menu/changes-pane.md
  content/en/docs/refguide/modeling/menus/view-menu/stories-pane.md
  content/en/docs/refguide/version-control/_index.md
  content/en/docs/refguide/version-control/on-premises-git.md
  content/en/docs/refguide/version-control/on-premises-svn.md
  content/en/docs/refguide/version-control/svn-git-differences.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  content/en/docs/refguide/version-control/version-control-faq.md
  content/en/docs/refguide/version-control/version-control-troubleshooting/_index.md
  content/en/docs/refguide/version-control/version-control-troubleshooting/troubleshoot-git-issues.md
  content/en/docs/refguide/version-control/version-control-troubleshooting/troubleshoot-team-server-issues.md
  content/en/docs/refguide9/version-control/using-version-control-in-studio-pro/collaborative-development.md
  static/attachments/refguide/modeling/menus/view-menu/changes-pane/changes-top-bar.png
  static/attachments/refguide/modeling/menus/view-menu/changes-pane/changes-top-level.png
  static/attachments/refguide/modeling/menus/view-menu/changes-pane/element-added.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/incoming-changes.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/local-repo-and-team-server.png
  static/attachments/refguide8/modeling/menus/version-control-menu/merge-dialog/merge-dialog.png
Labels: 10.0.0 Beta 2

#6113 Release documentation for metamodel & Model SDK 10.0.0-beta.2
  content/en/docs/releasenotes/sdk/metamodel/metamodel-10/metamodel-10.0.md
  content/en/docs/releasenotes/sdk/model-sdk/model-sdk-4.md
  layouts/partials/landingpage/latest-releases.html
Labels: Awaiting Response

#6115 Banner and notes
  content/en/docs/howto/_index.md
  content/en/docs/refguide/_index.md
Labels: Internal WIP

#6126 Fix snippet links
  static/_includes/refguide9/common-section-link.md
  static/_includes/refguide9/data-source-section-link.md
  static/_includes/refguide9/editability-section-link.md
  static/_includes/refguide9/events-section-link.md
  static/_includes/refguide9/label-section-link.md
  static/_includes/refguide9/microflow-common-section-link.md
  static/_includes/refguide9/numeric-formatting-link.md
  static/_includes/refguide9/performing-basic-functions-widgets.md
  static/_includes/refguide9/visibility-section-link.md
  static/_includes/refguide9/widget-validation-link.md
Labels: Internal WIP

#6123 Cards
  layouts/partials/landingpage/product-cards.html
Labels: Internal WIP

#6127 Fix the namespace member accept invite
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Future release

#6132 Replace instances of Company Admin
  content/en/docs/data-hub/data-hub-catalog/manage-data-sources/search.md
  content/en/docs/developerportal/control-center/data-hub-admin.md
  content/en/docs/releasenotes/data-hub/_index.md
Labels: Internal WIP

#6133 Add sec vuln
  content/en/docs/releasenotes/security-advisories/_index.md
Labels: Internal WIP

#6093 9.24.3 RN
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Future release

#6136 SAP XSUAA updates
  content/en/docs/partners/sap/sap-xsuaa-connector.md
  content/en/docs/partners/sap/use-sap-xsuaa-connector.md
Labels: Changes requested

#6046 S3 updates
  content/en/docs/appstore/connectors/aws/aws-s3-connector.md
  static/attachments/appstore/connectors/aws-s3-connector/awsregions.png
  static/attachments/appstore/connectors/aws-s3-connector/constants.png
  static/attachments/appstore/connectors/aws-s3-connector/microflow.png
  static/attachments/appstore/connectors/aws-s3-connector/settings.png
Labels: Internal WIP

#6138 Restructure
  content/en/docs/developerportal/community-tools/contribute-to-the-mendix-documentation/indentation-spacing-test.md
  content/en/docs/refguide/_index.md
  content/en/docs/refguide/general/_index.md
  content/en/docs/refguide/general/developer-tools.md
  content/en/docs/refguide/general/mx-command-line-tool.md
  content/en/docs/refguide/general/mxbuild.md
  content/en/docs/refguide/general/studio-pro-overview.md
  content/en/docs/refguide/general/third-party-licenses.md
  content/en/docs/refguide/installation/_index.md
  content/en/docs/refguide/installation/install.md
  content/en/docs/refguide/installation/system-requirements.md
  content/en/docs/refguide/installation/upgrading-from-9-to-10.md
  content/en/docs/refguide/installation/using-mendix-studio-pro-on-a-mac.md
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/10-edge.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/2-rename.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/3-import.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/4-errors.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/5-nav.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/6-hybrid-phone.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/7-errors.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/8-errors-background.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/9-set-prop.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/atlas-native-content-folder.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/atlas-web-content-folder-structure.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/atlas2-themefolder.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/atlas3-change-summary/atlas-native-content-marketplace.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/atlas3-change-summary/atlas-web-content-marketplace.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/atlas3-themefolder.png
  static/attachments/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/set-hybrid-nav.png
  static/attachments/refguide/installation/install/select-folder.png
  static/attachments/refguide/installation/install/setup-wizard.png
  static/attachments/refguide/installation/install/shortcut-folder.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/ip-in-dev-app.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/mapped-drive.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/network-drive.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/parallels-preferences-no-ports.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/parallels-preferences-ports.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/port-setup.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/preferences-dropdown.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/view-mobile-app.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/windows-configuration.png
  static/attachments/refguide/installation/using-mendix-studio-pro-on-a-mac/windows-control-center.png
  static/attachments/refguide/studio-pro-overview/ctrl-tab-navigation.png
  static/attachments/refguide/studio-pro-overview/pane-example.png
  static/attachments/refguide/studio-pro-overview/status-bar.png
  static/attachments/refguide/studio-pro-overview/studio-pro-diagram.png
  static/attachments/refguide/studio-pro-overview/view-and-publish.png
Labels: Internal WIP

#6078 Restructured Private Cloud storage documentation (planned for release in the second week of June)
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-migrating.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-storage-plans.md
  content/en/docs/developerportal/deploy/private-cloud/secret-store-credentials.md
Labels: Future release

#6156 Email connector images
  static/attachments/appstore/connectors/email-connector/app-permissions.png
  static/attachments/appstore/connectors/email-connector/app_permissions.png
  static/attachments/appstore/connectors/email-connector/client-cred-api-permissions.png
Labels: Internal WIP

#5695 Update Docsy to v0.6.0 as npm package
  .gitmodules
  .travis.yml
  README.md
  assets/scss/_alerts.scss
  assets/scss/_code.scss
  assets/scss/_content.scss
  assets/scss/_front-page.scss
  assets/scss/_main-container.scss
  assets/scss/_nav.scss
  assets/scss/_sidebar-toc.scss
  assets/scss/_sidebar-tree.scss
  assets/scss/_styles_project.scss
  assets/scss/_tables.scss
  assets/scss/_variables_project.scss
  assets/scss/main.scss
  assets/scss/section-index.scss
  assets/scss/support/_utilities.scss
  config/_default/config.toml
  content/en/docs/_index.md
  content/en/docs/appstore/widgets/charts/charts-plotly-images-rest.md
  content/en/docs/howto7/extensibility/charts-tutorials/charts-plotly-images-rest.md
  content/en/docs/howto8/front-end/charts-tutorials/charts-plotly-images-rest.md
  layouts/404.html
  layouts/_default/content.html
  layouts/docs/baseof.html
  layouts/docs/baseof.print.html
  layouts/docs/list.html
  layouts/index.html
  layouts/landingpage/landingpage.html
  layouts/partials/breadcrumb.html
  layouts/partials/navbar.html
  layouts/partials/page-meta-links.html
  layouts/partials/scripts.html
  layouts/partials/sidebar-tree.html
  layouts/partials/toc.html
  layouts/swagger/baseof.html
  package-lock.json
  package.json
  static/_includes/refguide7/Is+default+button+Property.md
Labels: Future release, Internal WIP

#5581 updated the PCLM with more information on operator and ingress configuration
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
Labels: Future release

#6047 Kk aws textract feedback
  content/en/docs/appstore/connectors/aws/aws-textract.md
Labels: Needs R&D technical verification

#6172 Folder_SubFolder association should be SubFolder_Folder
  content/en/docs/refguide/modeling/domain-model/associations/query-over.md
  static/attachments/refguide/modeling/domain-model/associations/query-over/query-over-association.png
  static/attachments/refguide/modeling/domain-model/associations/query-over/query-over-example-database.png
  static/attachments/refguide/modeling/domain-model/associations/query-over/query-over-extended-domain-model.png
  static/attachments/refguide/modeling/domain-model/associations/query-over/query-over-retrieve-complex.png
  static/attachments/refguide/modeling/domain-model/associations/query-over/query-over-retrieve-normal-tables.png
  static/attachments/refguide/modeling/domain-model/associations/query-over/query-over-retrieve-normal.png
  static/attachments/refguide/modeling/domain-model/associations/query-over/query-over-retrieve-reversed-tables.png
  static/attachments/refguide/modeling/domain-model/associations/query-over/query-over-retrieve-reversed.png
  static/attachments/refguide/modeling/domain-model/associations/query-over/self-reference-domain-model.png
  static/originals/refguide/query-over-example-database.xlsx
Labels: Internal WIP

#6181 Webhooks relnote and removal of beta tag
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/webhooks.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Needs R&D technical verification

#6134 Filtering capability for runtime metrics to APMs
  content/en/docs/developerportal/operate/metrics/monitoring-with-apm/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
Labels: Future release, Needs R&D technical verification, Update release and/or featured date

#6195 Add one more alias
  content/en/docs/catalog/integrate-with-catalog/share-data/_index.md
Labels: Internal WIP

#6189 Remove icons from activities children docs
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/action-call-activities/java-action-call.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/action-call-activities/javascript-action-call.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/action-call-activities/microflow-call.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/download-file.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/nanoflow-call.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/synchronize-to-device.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/validation-feedback.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/generate-document.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/log-message.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/metrics-activities/metrics-counter.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/metrics-activities/metrics-gauge.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/metrics-activities/metrics-increment-counter.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/call-ml-model.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/variable-activities/change-variable.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/variable-activities/create-variable.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/apply-jump-to-option.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/complete-task.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/generate-jump-to-options.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/lock-workflow.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/notify-workflow.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/retrieve-workflow-context.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/show-task-page.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/show-workflow-page.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/unlock-workflow.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/workflow-call.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/synchronize/synchronize-objects-selection.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/synchronize/synchronize-objects.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/synchronize/synchronize-unsynchronized-objects.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/synchronize/synchronize.png
Labels: Internal WIP

#6198 Add LDAP error message to troubleshooting section
  content/en/docs/appstore/modules/ldap.md
Labels: Needs R&D technical verification

#6205 Add Mx7 banner
  content/en/docs/howto7/_index.md
  content/en/docs/refguide7/_index.md
Labels: 10.0 GA

#6170 Add documentation bring your own kafka
  content/en/docs/appstore/modules/business-events.md
Labels: Future release

#6171 Update MendixSSO
  content/en/docs/appstore/modules/deep-link.md
Labels: Future release

#6075 SNS updates
  content/en/docs/appstore/connectors/aws/aws-sns.md
  static/attachments/appstore/connectors/aws-sns/sns_create_microflow.png
  static/attachments/appstore/connectors/aws-sns/sns_publishbatch_actions.png
  static/attachments/appstore/connectors/aws-sns/sns_publishbatch_aws_region.png
  static/attachments/appstore/connectors/aws-sns/sns_subscribe_actions.png
  static/attachments/appstore/connectors/aws-sns/sns_subscribe_aws_region.png
Labels: Internal WIP

#6211 Add majority and threshold decision methods to multi-user task
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/multi-user-task.md
Labels: 10.0 GA

#6176 Tabbed pane testing for XPath constraint docs
  assets/scss/_styles_project.scss
  content/en/docs/refguide/modeling/xpath/_index.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/_index.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-contains.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-day-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-day-of-year-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-ends-with.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-false.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-hours-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-length.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-minutes-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-month-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-not.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-quarter-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-seconds-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-starts-with.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-true.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-week-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-weekday-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-year-from-datetime.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-keywords-and-system-variables.md
Labels: Internal WIP

#6216 Adjust Catalog landscape doc
  content/en/docs/catalog/get-started.md
  content/en/docs/catalog/manage/landscape.md
Labels: Future release

#6193 Web service wizard deprecation
  content/en/docs/refguide/modeling/integration/web-services/consumed-web-services/consume-a-complex-web-service.md
Labels: 10.0 GA

#6229 Add more aliases
  content/en/docs/catalog/_index.md
  content/en/docs/catalog/consume/_index.md
  content/en/docs/catalog/consume/consume.md
  content/en/docs/catalog/integrate/_index.md
  content/en/docs/catalog/integrate/share-data/_index.md
  content/en/docs/catalog/integrate/write-data/_index.md
  content/en/docs/catalog/manage/landscape.md
  content/en/docs/catalog/manage/search.md
  content/en/docs/catalog/manage/security.md
  content/en/docs/catalog/manage/user-roles.md
Labels: Internal WIP

#6157 Licensing info in AWS connector docs
  content/en/docs/appstore/connectors/aws/amazon-eventbridge.md
  content/en/docs/appstore/connectors/aws/amazon-polly.md
  content/en/docs/appstore/connectors/aws/amazon-rekognition.md
  content/en/docs/appstore/connectors/aws/amazon-translate.md
  content/en/docs/appstore/connectors/aws/aws-authentication.md
  content/en/docs/appstore/connectors/aws/aws-dynamodb.md
  content/en/docs/appstore/connectors/aws/aws-iot-twinmaker.md
  content/en/docs/appstore/connectors/aws/aws-lambda-connector.md
  content/en/docs/appstore/connectors/aws/aws-s3-connector.md
  content/en/docs/appstore/connectors/aws/aws-sns.md
  content/en/docs/appstore/connectors/aws/aws-textract.md
Labels: Internal WIP

#6144 10.0 GA RN, remove Beta banner/notes, update MTS info, update cards, add Mx7 banner
  content/en/docs/howto/_index.md
  content/en/docs/howto7/_index.md
  content/en/docs/refguide/_index.md
  content/en/docs/refguide7/_index.md
  content/en/docs/releasenotes/studio-pro/10/10.0.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.18.md
  content/en/docs/releasenotes/studio-pro/9/9.6.md
  content/en/docs/releasenotes/studio-pro/lts-mts.md
  layouts/partials/landingpage/latest-releases.html
  layouts/partials/landingpage/product-cards.html
Labels: 10.0 GA

#6199 Rename Data Hub pane
  content/en/docs/appstore/_index.md
  content/en/docs/appstore/modules/business-events.md
  content/en/docs/catalog/_index.md
  content/en/docs/catalog/consume/_index.md
  content/en/docs/catalog/consume/consume.md
  content/en/docs/catalog/get-started.md
  content/en/docs/catalog/integrate/share-data/_index.md
  content/en/docs/catalog/integrate/without-mendix-cloud/_index.md
  content/en/docs/catalog/integrate/write-data/_index.md
  content/en/docs/catalog/manage/_index.md
  content/en/docs/catalog/manage/curate.md
  content/en/docs/catalog/manage/search.md
  content/en/docs/catalog/manage/security.md
  content/en/docs/catalog/register/automate-registration.md
  content/en/docs/catalog/register/register-data.md
  content/en/docs/catalog/register/register-non-odata-resources.md
  content/en/docs/refguide/modeling/domain-model/entities/_index.md
  content/en/docs/refguide/modeling/domain-model/external-entities.md
  content/en/docs/refguide/modeling/integration/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
  content/en/docs/refguide/modeling/integration/odata-services/wrap-services-odata.md
  content/en/docs/refguide/modeling/menus/view-menu/_index.md
  content/en/docs/refguide/modeling/menus/view-menu/integration-pane.md
Labels: 10.0 GA

#6071 Remove beta labels for ML Kit GA
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/call-ml-model.md
  content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
  content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/_index.md
  content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/advanced-inference-patterns.md
  content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/pre-post-processor-patterns.md
  content/en/docs/refguide/modeling/integration/machine-learning-kit/pretrained-ml-models/_index.md
  content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
  content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/logistic-regression-example.md
  content/en/docs/refguide9/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/_index.md
  content/en/docs/refguide9/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/call-ml-model.md
  content/en/docs/refguide9/modeling/integration/machine-learning-kit/_index.md
  content/en/docs/refguide9/modeling/integration/machine-learning-kit/design-patterns/_index.md
  content/en/docs/refguide9/modeling/integration/machine-learning-kit/design-patterns/advanced-inference-patterns.md
  content/en/docs/refguide9/modeling/integration/machine-learning-kit/design-patterns/pre-post-processor-patterns.md
  content/en/docs/refguide9/modeling/integration/machine-learning-kit/pretrained-ml-models/_index.md
  static/attachments/refguide/modeling/integration/ml-kit/ml-kit/bert-model-input-shapes.png
  static/attachments/refguide/modeling/integration/ml-kit/ml-kit/edit-model-input-shapes.png
  static/attachments/refguide/modeling/integration/ml-kit/ml-kit/ml-model-created-entities.png
  static/attachments/refguide/modeling/integration/ml-kit/ml-kit/model-input-errors.png
Labels: 10.0 GA

#6145 Multi-user task auto assignment
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/show-task-page.md
Labels: 10.0 GA

#6212 Multi-user task UI & decision methods update
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/multi-user-task.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/user-task.md
Labels: 10.0 GA

#6180 Doc update for setting an input parameter as the return value
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/parameter.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/parameter/set-parameter-as-return-value.png
Labels: 10.0 GA

#6179 Text change for design mode default
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/pages/page/_index.md
Labels: 10.0 GA

#6160 Update Preferences Dialog
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
Labels: 10.0 GA

#6207 Update Mx10 upgrade docs for atlas core changes
  content/en/docs/refguide/installation/upgrading-from-9-to-10.md
Labels: 10.0 GA

#6168 mx CLT
  content/en/docs/refguide/general/mx-command-line-tool.md
  content/en/docs/refguide/general/mx-command-line-tool/_index.md
  content/en/docs/refguide/general/mx-command-line-tool/adaptable.md
  content/en/docs/refguide/general/mx-command-line-tool/app.md
  content/en/docs/refguide/general/mx-command-line-tool/export.md
  content/en/docs/refguide/general/mx-command-line-tool/merge.md
  content/en/docs/refguide/general/mx-command-line-tool/module.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/_index.md
  static/attachments/refguide/general/mx-command-line-tool/merge.png
Labels: 10.0 GA

#6204 Updated Open App Dialog
  content/en/docs/refguide/modeling/menus/file-menu/open-app-dialog.md
  static/attachments/refguide/modeling/menus/file-menu/open-app-dialog/open-app.png
  static/attachments/refguide/modeling/menus/file-menu/open-app-dialog/select-app.png
Labels: 10.0 GA

#6234 Occurrence and Separated typos fixed.
  content/en/docs/appstore/partner-solutions/ats/rg-ats/v1/test-dev/std-actions/selenium-actions/rg-one-find/rg-one-find-element-by-css.md
  content/en/docs/appstore/partner-solutions/ats/rg-ats/v1/test-dev/std-actions/selenium-actions/rg-one-find/rg-one-find-element-by-id.md
  content/en/docs/appstore/partner-solutions/ats/rg-ats/v1/test-dev/std-actions/selenium-actions/rg-one-find/rg-one-find-element-by-sizzle.md
  content/en/docs/howto/front-end/styles.md
  content/en/docs/howto7/front-end/styles.md
  content/en/docs/howto8/front-end/styles.md
  content/en/docs/howto9/front-end/styles.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-sources/xpath-source.md
  content/en/docs/refguide9/general/moving-from-8-to-9/moving-from-atlas-2-to-3/_index.md
Labels: Internal WIP

#6213 Calendar
  content/en/docs/releasenotes/feature-release-calendar/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/releasenotes/calendar/themes.png
  static/attachments/releasenotes/mx-world-2021/innovations.png
Labels: Future release

#6169 Update SOAP docs
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/parameter.md
  content/en/docs/refguide/modeling/integration/web-services/published-web-services/expose-a-web-service.md
  content/en/docs/refguide/modeling/integration/web-services/testing-web-services-using-soapui.md
  content/en/docs/refguide9/modeling/integration/web-services/published-web-services/expose-a-web-service.md
  content/en/docs/refguide9/modeling/integration/web-services/testing-web-services-using-soapui.md
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580307.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580309.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580310.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580312.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580313.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580314.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580320.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580322.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580323.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580324.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580326.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580327.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580328.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580329.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580331.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580332.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580334.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/18580339.png
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/model1.jpg
  static/attachments/refguide/modeling/integration/testing-web-services-using-soapui/model2.jpg
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580307.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580309.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580310.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580312.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580313.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580314.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580320.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580322.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580323.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580324.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580326.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580327.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580328.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580329.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580331.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580332.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580334.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/18580339.png
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/model1.jpg
  static/attachments/refguide9/modeling/integration/testing-web-services-using-soapui/model2.jpg
Labels: Internal WIP

#6233 Data Hub MX Dock change
  content/en/docs/catalog/_index.md
  content/en/docs/catalog/integrate/share-data/_index.md
  content/en/docs/catalog/manage/curate.md
  content/en/docs/catalog/manage/search.md
  content/en/docs/catalog/manage/security.md
  content/en/docs/catalog/manage/user-roles.md
  content/en/docs/catalog/register/_index.md
  content/en/docs/catalog/register/register-data.md
  content/en/docs/catalog/register/without-mendix-cloud.md
  content/en/docs/developerportal/control-center/_index.md
  content/en/docs/developerportal/control-center/catalog-admin.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
  content/en/docs/refguide/modeling/integration/odata-services/security-authentication.md
  content/en/docs/refguide8/modeling/integration/consumed-odata-services/consumed-odata-service.md
  content/en/docs/refguide9/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
  content/en/docs/releasenotes/catalog/_index.md
  content/en/docs/releasenotes/developer-portal/_index.md
Labels: Future release

#6237 Update settings manual
  content/en/docs/developerportal/community-tools/mendix-profile.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#6250 Marketplace release notes for June 29th, 2023
  content/en/docs/releasenotes/marketplace/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#6254 Adjust Catalog images
  content/en/docs/catalog/_index.md
  content/en/docs/catalog/integrate/share-data/_index.md
  content/en/docs/catalog/integrate/write-data/_index.md
  content/en/docs/catalog/manage/curate.md
  content/en/docs/catalog/manage/landscape.md
  content/en/docs/catalog/manage/search.md
  content/en/docs/catalog/register/register-data.md
  content/en/docs/catalog/register/register-non-odata-resources.md
  content/en/docs/refguide/modeling/integration/odata-services/security-authentication.md
  static/attachments/catalog/catalog-home.png
  static/attachments/catalog/curate/app-icon-several-services.png
  static/attachments/catalog/curate/application-metadata-screen.png
  static/attachments/catalog/curate/asset-metadata-new-icon.png
  static/attachments/catalog/curate/curate-list.png
  static/attachments/catalog/curate/icon-library.png
  static/attachments/catalog/curate/icon-preview.png
  static/attachments/catalog/curate/icon-upload-dialog.png
  static/attachments/catalog/curate/service-metadata-box.png
  static/attachments/catalog/curate/service-metadata-description.png
  static/attachments/catalog/curate/service-metadata-tags-list.png
  static/attachments/catalog/curate/service-metadata-tags.png
  static/attachments/catalog/landscape/consume-arrow-entities-list.png
  static/attachments/catalog/landscape/dependencies.png
  static/attachments/catalog/landscape/landscape.png
  static/attachments/catalog/landscape/node-apps.png
  static/attachments/catalog/landscape/node-service.png
  static/attachments/catalog/register-data/zip-file-structure.png
  static/attachments/catalog/register-non-odata-resources/non-odata.png
  static/attachments/catalog/search/attributes-associations.png
  static/attachments/catalog/search/dh-filter-box.png
  static/attachments/catalog/search/download_example.png
  static/attachments/catalog/search/metadata.png
  static/attachments/catalog/search/search-details-page.png
  static/attachments/catalog/search/search-pane.png
  static/attachments/catalog/security/authentication-headers-from-microflow.png
  static/attachments/catalog/security/authentication-microflow.png
  static/attachments/catalog/security/federation-with-ADFS-SAML-schematic.png
  static/attachments/catalog/share-data/add-data-in-app.png
  static/attachments/catalog/share-data/customer-odata-service-page.png
  static/attachments/catalog/share-data/data-hub-home.png
  static/attachments/catalog/share-data/data-hub-pane-empty.png
  static/attachments/catalog/share-data/dh-filter-box.png
  static/attachments/catalog/share-data/edit-published-resource-box.png
  static/attachments/catalog/share-data/entity-properties-pane.png
  static/attachments/catalog/share-data/expose-as-odata-resource.png
  static/attachments/catalog/share-data/external-entities-in-domain-model.png
  static/attachments/catalog/share-data/filter-icon.png
  static/attachments/catalog/share-data/landscape-full-screen.png
  static/attachments/catalog/share-data/overview-pages-for-customer-entity.png
  static/attachments/catalog/share-data/search-details-screen.png
  static/attachments/catalog/share-data/select-published-odata-service.png
  static/attachments/catalog/share-data/view-data-hub.png
  static/attachments/catalog/write-data/crud-capabilities.png
  static/attachments/catalog/write-data/validate-data-client-app.png
  static/attachments/catalog/write-data/validate-data-publishing-app.png
Labels: Internal WIP

#6252 Calendar update
  content/en/docs/releasenotes/feature-release-calendar/_index.md
Labels: Internal WIP

#6262 Resolve feedback
  content/en/docs/refguide/modeling/menus/version-control-menu/branch-line-manager-dialog/_index.md
Labels: Internal WIP
