Repository mendix/docs, pull requests merged in 2023-09, with the labels that each got.

#6471 Tech Glossary
  content/en/docs/developerportal/project-management/stories.md
  content/en/docs/howto8/mobile/native-mobile/ui-best-practices.md
  content/en/docs/refguide/mobile/designing-mobile-user-interfaces/design-principles.md
  layouts/landingpage/landingpage.html
Labels: Internal WIP

#6474 Clarifications for Using Eclipse flow
  content/en/docs/refguide/java-programming/using-eclipse.md
  content/en/docs/refguide/modeling/menus/app-menu/_index.md
Labels: Needs R&D technical verification

#6478 Using Eclipse - Review Comments
  content/en/docs/refguide/java-programming/using-eclipse.md
Labels: Needs R&D technical verification

#6334 AWS SiteWise doc draft
  content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
Labels: Future release

#6490 CC Onboard
  content/en/docs/developerportal/control-center/_index.md
  content/en/docs/releasenotes/developer-portal/_index.md
  static/attachments/developerportal/control-center/onboarding-email.png
  static/attachments/developerportal/control-center/onboarding-landing.png
  static/attachments/developerportal/control-center/update-company-branding.png
Labels: Future release

#6488 Added to Developer portal release notes for AppInsights
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#6486 9.24.7 RN
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Future release, Update release and/or featured date

#6500 Add new alias
  content/en/docs/catalog/register/register-data.md
Labels: Internal WIP

#6489 Proofread catalog guide pages
  content/en/docs/catalog/manage/user-roles.md
  content/en/docs/catalog/register/register-data.md
Labels: Internal WIP

#6479 Delete list-view-controls docs.md
  content/en/docs/appstore/widgets/list-view-controls.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.3.md
Labels: Needs R&D technical verification, Internal WIP

#6513 202309 new mendix cloud region
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-ip-addresses.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mxcloudv4/_index.md
  content/en/docs/developerportal/operate/backups/_index.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review

#6519 9.24.8 RN
  content/en/docs/releasenotes/studio-pro/10/10.2.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Future release, Update release and/or featured date

#6413 7.23.36 RN
  content/en/docs/releasenotes/studio-pro/7/7.23.md
Labels: Future release, Update release and/or featured date

#6518 8.18.26 RN
  content/en/docs/releasenotes/studio-pro/8/8.18.md
Labels: Future release, Update release and/or featured date

#6532 updated the release notes
  content/en/docs/releasenotes/deployment/mendix-cloud.md
Labels: Needs R&D technical verification, Update release and/or featured date

#6535 Proofread example
  content/en/docs/howto7/monitoring-troubleshooting/finding-the-root-cause-of-runtime-errors.md
Labels: Internal WIP

#6538 PDF Document Generation: Update Chromium version
  content/en/docs/appstore/modules/document-generation.md
Labels: Needs language review

#6547 Update windows-service.md with release notes for 4.7.2
  content/en/docs/releasenotes/studio-pro/windows-service.md
Labels: Future release

#6557 Change Italics
  content/en/docs/howto7/testing/testing-microflows-using-the-unittesting-module.md
Labels: Internal WIP

#6551 9.24.9 RN
  content/en/docs/refguide9/general/system-requirements.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Future release, Update release and/or featured date

#6529 10.3 RN
  content/en/docs/releasenotes/studio-pro/10/10.2.md
  content/en/docs/releasenotes/studio-pro/10/10.3.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.3

#6473 [CTRL-2617] Port the Batch/Replace translations dialogs to Eto.Forms
  content/en/docs/refguide/modeling/menus/translatable-texts/batch-replace.md
  content/en/docs/refguide/modeling/menus/translatable-texts/batch-translate.md
  static/attachments/refguide/modeling/menus/translatable-texts/batch-replace/batch-replace-modules.png
  static/attachments/refguide/modeling/menus/translatable-texts/batch-replace/batch-replace-replace.png
  static/attachments/refguide/modeling/menus/translatable-texts/batch-replace/batch-replace-replaced.png
  static/attachments/refguide/modeling/menus/translatable-texts/batch-replace/batch-replace-search.png
  static/attachments/refguide/modeling/menus/translatable-texts/batch-replace/batch-replace.png
  static/attachments/refguide/modeling/menus/translatable-texts/batch-translate/batch-translate-excel.png
  static/attachments/refguide/modeling/menus/translatable-texts/batch-translate/batch-translate-languages.png
  static/attachments/refguide/modeling/menus/translatable-texts/batch-translate/batch-translate-search.png
  static/attachments/refguide/modeling/menus/translatable-texts/batch-translate/batch-translate-translate.png
  static/attachments/refguide/modeling/menus/translatable-texts/batch-translate/batch-translate.png
Labels: 10.3

#6520 Document microflow URLs and update page URL documentation
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-view.md
  content/en/docs/refguide/modeling/pages/page/page-properties.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow/microflow-url.png
  static/attachments/refguide/modeling/pages/page/page-url-dialog.png
Labels: 10.3

#6435 [RUN-3373] Move deployment settings in their own tab (for 10.3.0)
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/menus/version-control-menu/download-from-version-control-dialog.md
  content/en/docs/refguide/modeling/menus/version-control-menu/upload-to-version-control-dialog.md
  static/attachments/refguide/modeling/menus/edit-menu/preferences-dialog/preferences.png
Labels: 10.3

#6498 Add microflow decision method to multi-user task
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/multi-user-task.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-versioning.md
  static/attachments/refguide/modeling/application-logic/workflows/workflow-elements/multi-user-task/microflow-decision-fallback.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-elements/multi-user-task/microflow-decision.png
Labels: 10.3

#6541 Add documentation on external enumeration
  content/en/docs/refguide/modeling/resources/enumerations.md
Labels: 10.3

#6543 Change the return value of an end event through the …
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/events/end-event.md
Labels: 10.3

#6431 Update send-external-object activity
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/external-object-activities/send-external-object.md
Labels: 10.3

#6508 Add resolvable mitigation options to parallel branch removed conflict
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-versioning.md
Labels: 10.3

#6521 Document reverse association direction
  content/en/docs/refguide/modeling/domain-model/associations/_index.md
  static/attachments/refguide/modeling/domain-model/associations/reverse-association-direction.png
Labels: 10.3

#6496 Added documentation for subpath support
  content/en/docs/developerportal/deploy/general/deployment-location.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: 10.3

#6491 SOLP-1808 Import module refguide
  content/en/docs/refguide/general/mx-command-line-tool/_index.md
  content/en/docs/refguide/general/mx-command-line-tool/adaptable.md
  content/en/docs/refguide/general/mx-command-line-tool/app.md
  content/en/docs/refguide/general/mx-command-line-tool/merge.md
  content/en/docs/refguide/general/mx-command-line-tool/module.md
Labels: Needs R&D technical verification, 10.3

#6449 Use Share link to update metadata
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
Labels: 10.3

#6487 Autofetch and Push-Pull experience updates
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/auto-fetch.md
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/commit-dialog-incoming.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/commit-dialog.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/commit-pull-first-dialog.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/create-deployment-package.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/deploy-to-cloud.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/history-of-dialog.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/main-branch-line.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-commit.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/repository-state-bar.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/revert-changes-git.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png
Labels: Verify sidebar, 10.3

#6561 Documentation for Managed Dependencies
  content/en/docs/refguide/java-programming/extending-your-application-with-custom-java.md
  content/en/docs/refguide/java-programming/java-api-tutorial.md
  content/en/docs/refguide/java-programming/managed-dependencies.md
  content/en/docs/refguide/java-programming/troubleshooting.md
  content/en/docs/refguide/java-programming/using-eclipse.md
  content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
  static/attachments/refguide/java-programming/managed-dependencies/custom-repository.png
  static/attachments/refguide/java-programming/managed-dependencies/edit-java-dependencies.png
  static/attachments/refguide/java-programming/managed-dependencies/junit-notation-example.png
  static/attachments/refguide/java-programming/managed-dependencies/module-settings.png
  static/attachments/refguide/java-programming/managed-dependencies/synchronize-app-dependencies.png
  static/attachments/refguide/modeling/app-explorer/modules/module-settings/module-settings-dialog.png
  static/attachments/refguide/modeling/app-explorer/modules/module-settings/module-settings-export.png
  static/attachments/refguide/modeling/app-explorer/modules/module-settings/module-settings-java-dependencies.png
Labels: Future release, Changes requested, 10.3

#6546 Qt proofread
  content/en/docs/appstore/connectors/ms-teams-connector.md
  content/en/docs/catalog/integrate/write-data/_index.md
  content/en/docs/catalog/register/automate-registration.md
  content/en/docs/refguide/modeling/integration/odata-services/build-odata-apis.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
  static/attachments/howto7/data-models/denormalize-data-to-improve-performance/18582150.png
Labels: Internal WIP

#6552 Adjust nanoflow properties page
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/nanoflow.md
Labels: Internal WIP

#6540 Release Notes For Catalog 2.94.0 for September 21 2023
  content/en/docs/releasenotes/catalog/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs R&D technical verification

#6569 Update Calendar
  content/en/docs/releasenotes/feature-release-calendar/_index.md
  content/en/docs/releasenotes/studio-pro/10/10.3.md
Labels: Internal WIP
