Repository mendix/docs, pull requests merged in 2023-12, with the labels that each got.

#6893 Kk pmp updates
  content/en/docs/private-platform/configuration/_index.md
  content/en/docs/releasenotes/private-platform/_index.md
  static/attachments/private-platform/pmp-wizard7.png
  static/attachments/private-platform/pmp-wizard8.png
Labels: Future release

#6889 Quickstarts review
  content/en/docs/quickstarts/part1.md
  content/en/docs/quickstarts/part2.md
  static/attachments/quickstarts/part2/mobile-pic-1.png
  static/attachments/quickstarts/part2/mobile-pic-2.png
  static/attachments/quickstarts/part2/mobile-pic-3.png
Labels: Internal WIP

#6905 Language review and updates
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/_index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/node-permissions.md
  content/en/docs/developerportal/general/team/app-roles.md
  static/attachments/developerportal/deploy/mendix-cloud-deploy/licensing-apps/link-node.png
Labels: Internal WIP

#6906 Paragraph on Java source code protection added
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-adapt/sol-adaptability.md
Labels: Internal WIP, Needs language review

#6909 Update _index.md
  content/en/docs/releasenotes/beta-features/_index.md
  content/en/docs/releasenotes/feature-release-calendar/_index.md
  content/en/docs/releasenotes/studio-pro/lts-mts.md
Labels: Needs R&D technical verification

#6926 Kk pmp relnotes reorg
  content/en/docs/releasenotes/private-platform/1/_index.md
  content/en/docs/releasenotes/private-platform/_index.md
Labels: Internal WIP

#6868 updated PMP prerequisites
  content/en/docs/private-platform/pmp-prerequisites.md
Labels: Needs R&D technical verification

#6945 Proofread Alerts
  content/en/docs/developerportal/operate/monitoring-application-health/_index.md
  content/en/docs/developerportal/operate/monitoring-application-health/receive-alerts.md
  static/attachments/developerportal/operate/monitoring-application-health/alert-details.png
  static/attachments/developerportal/operate/monitoring-application-health/application-status.png
Labels: Internal WIP

#6947 Quickstart updates for PMP
  content/en/docs/private-platform/pmp-quickstart.md
Labels: Changes requested

#6949 Proofread and update CICD pipeline doc
  content/en/docs/howto/integration/implement-cicd-pipeline.md
  static/attachments/howto/integration/implement-cicd-pipeline/01APIRightsCloudPortal.png
Labels: Internal WIP

#6911 Image styles
  assets/scss/_styles_project.scss
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
  layouts/shortcodes/figure.html
  static/attachments/developerportal/deploy/mendix-cloud-deploy/environments-details/environment-details.png
Labels: Internal WIP

#6890 Add graphs with dynamic y-axes
  content/en/docs/developerportal/operate/metrics.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  static/attachments/developerportal/operate/metrics/app-cpu.png
  static/attachments/developerportal/operate/metrics/app-disk-usage-pct.png
Labels: Future release

#6944 Update global-navigation.md
  content/en/docs/developerportal/global-navigation.md
Labels: Future release

#6963 Update LoginLocation Constant
  content/en/docs/appstore/modules/oidc-provider.md
  static/attachments/appstore/modules/oidc-provider/Basic_Username_Password.png
  static/attachments/appstore/modules/oidc-provider/Login location.png
Labels: Internal WIP

#6974 Amazon event bridge documentation update for Auth 3.0.0
  content/en/docs/appstore/connectors/aws/amazon-eventbridge.md
Labels: Future release, Needs language review

#6975 Amazon rekognition documentation update for Auth 3.0.0
  content/en/docs/appstore/connectors/aws/amazon-rekognition.md
Labels: Future release, Needs language review

#7006 [Snyk] Upgrade @fortawesome/fontawesome-free from 6.4.2 to 6.5.0
  package-lock.json
  package.json
Labels: Dependencies

#6958 Add info about the portable installer, related to 'Version Selector'
  content/en/docs/refguide/installation/install.md
Labels: Needs language review

#6895 MDA size error message
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#7008 Missing Quotes- OIDC Provider
  content/en/docs/appstore/modules/oidc-provider.md
Labels: Internal WIP

#6952 10.6 RN
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/lts-mts.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.6

#6980 MendixChat documentation (beta)
  content/en/docs/refguide/modeling/mx-assist-studio-pro/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mendix-chat.md
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/feedback-section.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/mendix-chat-example.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/mendix-chat-interface.png
Labels: 10.6

#6960 Wait for timer documentation
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/_index.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/wait-for-timer.md
  static/attachments/refguide/modeling/application-logic/workflows/workflow-elements/wait-for-timer.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-elements/wait-for-timer/wait-for-timer-example.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-elements/wait-for-timer/wait-for-timer-xpath-example.jpg
Labels: 10.6

#6931 Update data-importer.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/data-importer.md
  content/en/docs/refguide/modeling/integration/data-importer/_index.md
  static/attachments/appstore/modules/data-importer-extension/choose-data-importer-template.png
  static/attachments/appstore/modules/data-importer-extension/custom-activity.png
  static/attachments/appstore/modules/data-importer-extension/data-importer-extension.textClipping
  static/attachments/appstore/modules/data-importer-extension/data-importer-menu.png
  static/attachments/appstore/modules/data-importer-extension/example-microflow.png
  static/attachments/appstore/modules/data-importer-extension/local-app-run.png
  static/attachments/appstore/modules/data-importer-extension/preview-data-and-entity.png
  static/attachments/appstore/modules/data-importer-extension/select-file-for-preview.png
  static/attachments/appstore/modules/data-importer-extension/select-sheet-and-header-data-row.png
  static/attachments/appstore/modules/data-importer-extension/source-to-target-mapping.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/import-data-from-file/custom-activity-params.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/import-data-from-file/properties.png
Labels: 10.6

#6130 Documentation for new Database Connector
  content/en/docs/appstore/connectors/database-connector-mx10.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/query-external-database.md
  content/en/docs/refguide/modeling/integration/database-connection/_index.md
  static/attachments/appstore/connectors/database-connector/database-connection-wizard.png
  static/attachments/appstore/connectors/external-database-connector/database-connection-wizard.png
  static/attachments/appstore/connectors/external-database-connector/database-service-document.png
  static/attachments/appstore/connectors/external-database-connector/entity-created-from-database.png
  static/attachments/appstore/connectors/external-database-connector/example-microflow.png
  static/attachments/appstore/connectors/external-database-connector/example-parameter.png
  static/attachments/appstore/connectors/external-database-connector/execute-query.png
  static/attachments/appstore/connectors/external-database-connector/query-external-database.png
  static/attachments/appstore/connectors/external-database-connector/response-structure.png
  static/attachments/appstore/connectors/external-database-connector/return-type.png
  static/attachments/appstore/connectors/external-database-connector/select-query-columns.png
Labels: Needs R&D technical verification, 10.6

#6894 Documentation for Consumed REST Services (beta)
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services-beta
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/consume-a-rest-service.md
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/add-service.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/authentication-setup.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/configuration-screen.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/edit-parameter.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/general-section.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/get-header.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/header.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/json-body-structure.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/json-sample.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/parameter.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/response-data.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/response-structure.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/select-rest-request.png
Labels: 10.6

#7004 Document Foreign Key Constraints
  content/en/docs/refguide/runtime/data-storage/_index.md
Labels: 10.6

#6966 Change Branch to Path for Parallel Splits in Workflows
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/wait-for-notification.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-versioning.md
Labels: 10.6

#6950 Documentation Updates for Logic Editors in GA
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/logic-editors-beta.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot.md
  content/en/docs/releasenotes/studio-pro/10/10.4.md
  content/en/docs/releasenotes/studio-pro/10/10.5.md
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/assist-bulb.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/initial-recommendations.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/search-microflows-nanoflows.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/search-sub-actions.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/search-toolbox.png
Labels: 10.6

#6773 Add Retrieve Workflow Activity Records microflow action
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/retrieve-workflow-activity-records.md
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/retrieve-workflow-activity-records.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/retrieve-workflow-activity-records/properties.png
Labels: 10.6

#6866 Update preferences dialog with the modernized expression editor new feature
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
Labels: 10.6

#6946 Add description for switching between portrait and landscape orientation
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
Labels: 10.6

#7002 Update sort order
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/performance-best-practices.md
  content/en/docs/refguide/modeling/pages/data-widgets/grids/_index.md
  content/en/docs/refguide/modeling/pages/data-widgets/grids/data-grid/_index.md
  content/en/docs/refguide/modeling/pages/data-widgets/grids/sort-bar.md
  content/en/docs/refguide/modeling/pages/data-widgets/grids/template-grid.md
  content/en/docs/refguide/modeling/pages/data-widgets/list-view.md
  content/en/docs/refguide/modeling/pages/input-widgets/reference-set-selector.md
  content/en/docs/refguide/modeling/resources/document-templates/data-grid-document-template/_index.md
  content/en/docs/refguide/modeling/resources/document-templates/template-grid-document-template.md
Labels: 10.6

#6999 Add Atlas Core module page
  content/en/docs/appstore/modules/atlas-core.md
Labels: 10.6

#6935 Updated the comparision between Page/MF URLs with the DeepLink module
  content/en/docs/appstore/modules/deep-link.md
Labels: 10.6

#6812 Update Design Property docs
  content/en/docs/apidocs-mxsdk/apidocs/design-properties.md
  static/attachments/apidocs-mxsdk/apidocs/design-properties/colorpicker.png
  static/attachments/apidocs-mxsdk/apidocs/design-properties/design_property_dropdown_open_studio_pro.png
  static/attachments/apidocs-mxsdk/apidocs/design-properties/design_property_dropdown_studio_pro.png
  static/attachments/apidocs-mxsdk/apidocs/design-properties/design_property_toggle_studio_pro.png
  static/attachments/apidocs-mxsdk/apidocs/design-properties/dropdown.png
  static/attachments/apidocs-mxsdk/apidocs/design-properties/overview.png
  static/attachments/apidocs-mxsdk/apidocs/design-properties/spacing.png
  static/attachments/apidocs-mxsdk/apidocs/design-properties/toggle.png
  static/attachments/apidocs-mxsdk/apidocs/design-properties/toggle_button_group.png
Labels: 10.6

#6916 Document new widget generation setting
  content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
Labels: 10.6

#7000 "How to" for External database connector
  content/en/docs/howto/integration/use-the-external-database-connector.md
  static/attachments/howto/integration/use-the-external-database-connector/1.png
  static/attachments/howto/integration/use-the-external-database-connector/2.png
  static/attachments/howto/integration/use-the-external-database-connector/3.png
  static/attachments/howto/integration/use-the-external-database-connector/4.png
  static/attachments/howto/integration/use-the-external-database-connector/5.png
  static/attachments/howto/integration/use-the-external-database-connector/6.png
  static/attachments/howto/integration/use-the-external-database-connector/7.png
  static/attachments/howto/integration/use-the-external-database-connector/8.png
Labels: 10.6

#6984 Remove instructions for import wizard.
  content/en/docs/refguide/modeling/integration/web-services/consumed-web-services/consume-a-complex-web-service.md
  static/attachments/refguide/modeling/integration/consume-a-complex-web-service/import-web-service-wizard-button.png
  static/attachments/refguide/modeling/integration/consume-a-complex-web-service/port.png
  static/attachments/refguide/modeling/integration/consume-a-complex-web-service/web-service-entity.png
  static/attachments/refguide/modeling/integration/consume-a-complex-web-service/wizard-import-schema.png
  static/attachments/refguide/modeling/integration/consume-a-complex-web-service/wizard-new-operation.png
  static/attachments/refguide/modeling/integration/consume-a-complex-web-service/wizard-select-elements.png
  static/attachments/refguide/modeling/integration/consume-a-complex-web-service/wizard-select-icon.png
  static/attachments/refguide/modeling/integration/consume-a-complex-web-service/wizard-web-service-list.png
Labels: 10.6

#6727 Add notes on complex attributes
  content/en/docs/refguide/modeling/domain-model/entities/external-entities.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service-requirements.md
Labels: Needs R&D technical verification, 10.6

#6942 Beta release of the new Access Rule Editor
  content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  static/attachments/refguide/modeling/domain-model/entities/access-rules/context-menu.png
  static/attachments/refguide/modeling/domain-model/entities/access-rules/create.png
  static/attachments/refguide/modeling/domain-model/entities/access-rules/delete.png
  static/attachments/refguide/modeling/domain-model/entities/access-rules/example-columns.png
  static/attachments/refguide/modeling/domain-model/entities/access-rules/read.png
  static/attachments/refguide/modeling/domain-model/entities/access-rules/write.png
Labels: 10.6

#7015 OIDC SSO-Troubleshooting section update
  content/en/docs/appstore/modules/oidc.md
  static/attachments/appstore/modules/oidc/Community Commons error.png
Labels: Internal WIP

#7020 Add a KI to 10.6
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: 10.6

#7003 Update data-importer how-to document.
  content/en/docs/howto/integration/use-the-data-importer.md
  static/attachments/howto/integration/use-the-data-importer/add-parameter.png
  static/attachments/howto/integration/use-the-data-importer/aggregate-list.png
  static/attachments/howto/integration/use-the-data-importer/choose-data-importer-template.png
  static/attachments/howto/integration/use-the-data-importer/configured-custom-activity.png
  static/attachments/howto/integration/use-the-data-importer/custom-activity-params.png
  static/attachments/howto/integration/use-the-data-importer/custom-activity.png
  static/attachments/howto/integration/use-the-data-importer/data-importer-in-marketplace-module (1).png
  static/attachments/howto/integration/use-the-data-importer/data-importer-in-marketplace-module.png
  static/attachments/howto/integration/use-the-data-importer/data-importer-menu.png
  static/attachments/howto/integration/use-the-data-importer/data-view-file-manager.png
  static/attachments/howto/integration/use-the-data-importer/example-microflow.png
  static/attachments/howto/integration/use-the-data-importer/home-page-button.png
  static/attachments/howto/integration/use-the-data-importer/integration-activity.png
  static/attachments/howto/integration/use-the-data-importer/local-app-run.png
  static/attachments/howto/integration/use-the-data-importer/preview-data-and-entity.png
  static/attachments/howto/integration/use-the-data-importer/select-file-for-preview.png
  static/attachments/howto/integration/use-the-data-importer/select-sheet-and-header-data-row.png
  static/attachments/howto/integration/use-the-data-importer/show-message-with-list-size.png
  static/attachments/howto/integration/use-the-data-importer/source-to-target-mapping.png
Labels: Needs language review, 10.6

#7021 PMP release notes
  content/en/docs/releasenotes/private-platform/1/_index.md
Labels: Future release

#7013 Create openai-connector.md
  content/en/docs/appstore/connectors/openai-connector.md
Labels: Needs language review

#7026 Add a workaround
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: 10.6
