Repository mendix/docs, pull requests merged in 2023-04, with the labels that each got.

#5830 Remove references
  content/en/docs/data-hub/_index.md
  content/en/docs/data-hub/share-data/_index.md
  content/en/docs/data-hub/without-mendix-cloud/_index.md
  content/en/docs/partners/siemens/mindsphere/mindsphere-app-service.md
  content/en/docs/refguide/modeling/integration/consumed-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/consumed-odata-services/consumed-odata-service-requirements.md
  content/en/docs/refguide/modeling/menus/view-menu/data-hub-pane.md
  content/en/docs/refguide8/modeling/integration/consumed-odata-services/_index.md
  content/en/docs/refguide8/modeling/integration/consumed-odata-services/consumed-odata-service-requirements.md
  content/en/docs/refguide8/modeling/menus/view-menu/data-hub-pane.md
  content/en/docs/releasenotes/data-hub/_index.md
Labels: Internal WIP

#5784 Rewrite Studio how-to for SP - Configure List and Details on One Page
  content/en/docs/refguide/modeling/pages/data-widgets/configure-list-and-details-on-one-page.md
  static/attachments/refguide/modeling/pages/data-widgets/configure-list-and-details-on-one-page/attributes-replaced.png
  static/attachments/refguide/modeling/pages/data-widgets/configure-list-and-details-on-one-page/configured-page.png
  static/attachments/refguide/modeling/pages/data-widgets/configure-list-and-details-on-one-page/data-view.png
  static/attachments/refguide/modeling/pages/data-widgets/configure-list-and-details-on-one-page/domain-model.png
  static/attachments/refguide/modeling/pages/data-widgets/configure-list-and-details-on-one-page/list-configured.png
  static/attachments/refguide/modeling/pages/data-widgets/configure-list-and-details-on-one-page/master-detail-page.png
Labels: Internal WIP

#5840 AWS EventBridge dependency
  content/en/docs/appstore/connectors/aws/amazon-eventbridge.md
Labels: Internal WIP

#5788 Update switch-to menu
  content/en/docs/developerportal/_index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/node-permissions.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/operate/monitoring-application-health/receive-alerts.md
  static/attachments/developerportal/deploy/mendix-cloud-deploy/node-permissions/go-to-nodes-page.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/go-to-nodes-page.png
  static/attachments/developerportal/operate/monitoring-application-health/receive-alerts/cloud-nodes.png
  static/attachments/developerportal/switcher.png
Labels: Future release

#5812 Kk sap runtime
  content/en/docs/developerportal/deploy/sap-cloud-platform.md
  static/attachments/developerportal/deploy/sap-cloud-platform/12-sap-model-options.png
  static/attachments/developerportal/deploy/sap-cloud-platform/custom-environment-variables-unsupported.png
  static/attachments/developerportal/deploy/sap-cloud-platform/custom-environment-variables.png
  static/attachments/developerportal/deploy/sap-cloud-platform/environment-details.png
  static/attachments/developerportal/deploy/sap-cloud-platform/environments-page.png
  static/attachments/developerportal/deploy/sap-cloud-platform/sap-transport.png
  static/attachments/developerportal/deploy/sap-cloud-platform/service-tab.png
Labels: Internal WIP

#5771 Clarify use of Mendix SSO
  content/en/docs/apidocs-mxsdk/apidocs/user-management-api.md
  content/en/docs/appstore/modules/mendix-sso.md
  content/en/docs/developerportal/collaborate/general-settings/_index.md
  content/en/docs/developerportal/control-center/set-up-sso-byoidp.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-sso.md
  static/attachments/appstore/modules/mendix-sso/after-startup-remove.png
  static/attachments/appstore/modules/mendix-sso/after-startup.png
  static/attachments/appstore/modules/mendix-sso/create-new-entity.png
  static/attachments/appstore/modules/mendix-sso/custom-afterstartup-microflow.png
  static/attachments/appstore/modules/mendix-sso/domain-model-token.png
  static/attachments/appstore/modules/mendix-sso/edit-members.png
  static/attachments/appstore/modules/mendix-sso/module-user-roles.png
  static/attachments/appstore/modules/mendix-sso/mxsso-app-store-module.png
  static/attachments/appstore/modules/mendix-sso/my-tokens.png
  static/attachments/appstore/modules/mendix-sso/set-module-role.png
  static/attachments/appstore/modules/mendix-sso/snippets.png
  static/attachments/appstore/modules/mendix-sso/theme-folder-remove.png
  static/attachments/appstore/modules/mendix-sso/token-administration.png
  static/attachments/appstore/modules/mendix-sso/token-datagrid.png
  static/attachments/appstore/modules/mendix-sso/token-navigation.png
  static/attachments/appstore/modules/mendix-sso/token-pages.png
  static/attachments/appstore/modules/mendix-sso/token-snippets.png
Labels: Needs R&D technical verification

#5859 Deprecate fiori 2.5 doc
  content/en/docs/partners/sap/sap-fiori-3-0/sap-fiori-building-blocks.md
Labels: Internal WIP

#5867 Adjust connector names
  content/en/docs/appstore/connectors/email-connector.md
  content/en/docs/appstore/connectors/ms-teams-connector.md
Labels: Internal WIP

#5588 Integration doc reorganization
  content/en/docs/howto/integration/_index.md
  content/en/docs/refguide/modeling/integration/_index.md
  content/en/docs/refguide/modeling/integration/business-event-services/_index.md
  content/en/docs/refguide/modeling/integration/json-structures.md
  content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
  content/en/docs/refguide/modeling/integration/mapping-documents/_index.md
  content/en/docs/refguide/modeling/integration/message-definitions.md
  content/en/docs/refguide/modeling/integration/odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service-requirements.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_MAPPING.txt
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/odata-query-options.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/odata-representation.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-attribute.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-resource.md
  content/en/docs/refguide/modeling/integration/odata-services/wrap-services-odata.md
  content/en/docs/refguide/modeling/integration/rest-services/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/consume-a-rest-service.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/server-side-paging.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/using-a-proxy-to-call-a-rest-service.md
  content/en/docs/refguide/modeling/integration/rest-services/http-request-and-response-entities.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/generate-rest-resource.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/publish-microflow-as-rest-operation.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/publish-rest-service.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/cors-settings.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/gfm-syntax.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/published-rest-operation-parameter.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/published-rest-operation.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/published-rest-path-parameters.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/published-rest-query-parameters.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/published-rest-resource.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-technical-details/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-technical-details/open-api.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-technical-details/published-rest-authentication-parameter.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-technical-details/published-rest-routing.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-technical-details/published-rest-service-json-schema.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/version-rest-service.md
  content/en/docs/refguide/modeling/integration/rest-services/rest-binary.md
  content/en/docs/refguide/modeling/integration/web-services/_index.md
  content/en/docs/refguide/modeling/integration/web-services/consumed-web-services/_index.md
  content/en/docs/refguide/modeling/integration/web-services/consumed-web-services/consume-a-complex-web-service.md
  content/en/docs/refguide/modeling/integration/web-services/consumed-web-services/consume-a-simple-web-service.md
  content/en/docs/refguide/modeling/integration/web-services/consumed-web-services/consumed-web-service.md
  content/en/docs/refguide/modeling/integration/web-services/consumed-web-services/numeric-formatting.md
  content/en/docs/refguide/modeling/integration/web-services/consumed-web-services/using-a-proxy-to-call-a-webservice.md
  content/en/docs/refguide/modeling/integration/web-services/published-web-services/_index.md
  content/en/docs/refguide/modeling/integration/web-services/published-web-services/expose-a-web-service.md
  content/en/docs/refguide/modeling/integration/web-services/published-web-services/operations.md
  content/en/docs/refguide/modeling/integration/web-services/published-web-services/published-web-service.md
  content/en/docs/refguide/modeling/integration/xml-schemas/_index.md
Labels: Internal WIP

#5869 Remove scheduler
  .github/workflows/remunusedattachments.yml
Labels: Internal WIP

#5873 Kk aws prereqs
  content/en/docs/appstore/connectors/aws/amazon-eventbridge.md
  content/en/docs/appstore/connectors/aws/amazon-polly.md
  content/en/docs/appstore/connectors/aws/amazon-rekognition.md
  content/en/docs/appstore/connectors/aws/amazon-translate.md
  content/en/docs/appstore/connectors/aws/aws-dynamodb.md
  content/en/docs/appstore/connectors/aws/aws-lambda-connector.md
  content/en/docs/appstore/connectors/aws/aws-s3-connector.md
  content/en/docs/appstore/connectors/aws/aws-sns.md
  content/en/docs/appstore/connectors/aws/aws-textract.md
Labels: Internal WIP

#5866 9.12.12 RN
  content/en/docs/releasenotes/studio-pro/9/9.12.md
Labels: Future release

#5855 9.24.1 RN
  content/en/docs/releasenotes/studio-pro/9/9.24.md
  layouts/partials/landingpage/latest-releases.html
Labels: Update release and/or featured date, 9.24.1

#5863 Document the new option to convert between nanoflow and microflow
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md
Labels: 9.24.1

#5868 9.18.6 RN
  content/en/docs/releasenotes/studio-pro/9/9.18.md
Labels: Update release and/or featured date

#5884 9.18.6 RN
  content/en/docs/releasenotes/studio-pro/9/9.18.md
Labels: Update release and/or featured date

#5753 self-service
  content/en/docs/developerportal/control-center/_index.md
  static/attachments/developerportal/control-center/apps-overview.png
  static/attachments/developerportal/control-center/cloud-provisioning.png
  static/attachments/developerportal/control-center/edit-technical-contact.png
  static/attachments/developerportal/control-center/entitlements.png
  static/attachments/developerportal/control-center/new-environment.png
  static/attachments/developerportal/control-center/offboarding.png
Labels: Needs R&D technical verification

#5882 Give needed attachments a new home
  static/originals/developerportal/204371729-pic5.pptx
  static/originals/developerportal/exchange-apps.pptx
  static/originals/developerportal/migratev4.pptx
  static/originals/developerportal/migration-flow.pptx
  static/originals/developerportal/mx4pc-architecture.pptx
  static/originals/developerportal/mx4pc-diagrams.pptx
  static/originals/developerportal/mx4pc-environments.pptx
  static/originals/refguide/Collaboration Flow.pptx
  static/originals/refguide/conversion-table.pptx
  static/originals/refguide/examplelocationurl.docx
  static/originals/refguide/query-over-example-database.xlsx
  static/originals/refguide/runtime-diagrams.pptx
Labels: Internal WIP

#5890 removing unused images
  static/originals/developerportal/migratev4.pptx
  static/originals/developerportal/migration-flow.pptx
Labels: Internal WIP

#5889 Correct infomation about retrieving objects in a microflow
  content/en/docs/refguide/modeling/domain-model/generalization-and-association.md
Labels: Needs R&D technical verification

#5892 updating the package store URL
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
Labels: Internal WIP

#5904 Emphasize jar dependencies for DB connector
  content/en/docs/appstore/connectors/database-connector.md
Labels: Internal WIP

#5906 9.12.13 RN
  content/en/docs/releasenotes/studio-pro/9/9.12.md
Labels: Update release and/or featured date

#5911 Correct patch RN
  content/en/docs/releasenotes/studio-pro/7/7.23.md
  content/en/docs/releasenotes/studio-pro/8/8.18.md
  content/en/docs/releasenotes/studio-pro/9/9.12.md
  content/en/docs/releasenotes/studio-pro/9/9.6.md
  content/en/docs/releasenotes/studio-pro/lts-mts.md
Labels: Internal WIP

#5886 Splunk metadata
  content/en/docs/developerportal/operate/metrics/monitoring-with-apm/splunk-metrics.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs R&D technical verification, Update release and/or featured date

#5912 Update email-connector docs for Shared Mailbox configuration.
  content/en/docs/appstore/connectors/email-connector.md
Labels: Future release

#5921 minor update to phrasing
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-monitor.md
Labels: Internal WIP

#5929 Draft Upgrade Guide
  content/en/docs/refguide/general/moving-from-8-to-9/_index.md
  content/en/docs/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/_index.md
  content/en/docs/refguide/general/moving-from-8-to-9/moving-from-atlas-2-to-3/atlas3-change-summary.md
  content/en/docs/refguide/general/upgrading-from-9-to-10.md
Labels: Internal WIP, 10.0.0

#5896 7.23.35 RN
  content/en/docs/refguide7/general/system-requirements.md
  content/en/docs/releasenotes/studio-pro/7/7.23.md
Labels: Update release and/or featured date

#5891 Patch 22
  content/en/docs/appstore/modules/model-reflection.md
Labels: Needs R&D technical verification

#5924 10.0.0 RN Beta 1 (recreated)
  content/en/docs/releasenotes/studio-pro/10/10.0.md
  content/en/docs/releasenotes/studio-pro/10/_index.md
  content/en/docs/releasenotes/studio-pro/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.0.0

#5927 Removed message about preferIPv4Stack
  content/en/docs/refguide/general/system-requirements.md
Labels: 10.0.0

#5876 release notes and a minor api doc fix
  content/en/docs/apidocs-mxsdk/apidocs/private-cloud-build-api.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Future release

#5926 Exposed name clash
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-attribute.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-resource.md
Labels: 10.0.0

#5925 Publishing OData 3 is deprecated
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/odata-query-options.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-attribute.md
  content/en/docs/refguide/modeling/integration/odata-services/wrap-services-odata.md
Labels: 10.0.0

#5923 updates to prerequisites and installation
  content/en/docs/appstore/modules/saml.md
  static/attachments/appstore/modules/saml/saml-versions.png
Labels: Internal WIP

#5942 9.12.14 RN
  content/en/docs/releasenotes/studio-pro/9/9.12.md
Labels: Update release and/or featured date

#5954 Rename Marketplace RN
  content/en/docs/appstore/_index.md
  content/en/docs/releasenotes/marketplace/_index.md
  content/en/docs/releasenotes/studio-pro/7/7.0.md
  content/en/docs/releasenotes/studio-pro/7/7.1.md
  content/en/docs/releasenotes/studio-pro/7/7.10.md
  content/en/docs/releasenotes/studio-pro/7/7.11.md
  content/en/docs/releasenotes/studio-pro/7/7.12.md
  content/en/docs/releasenotes/studio-pro/7/7.13.md
  content/en/docs/releasenotes/studio-pro/7/7.14.md
  content/en/docs/releasenotes/studio-pro/7/7.15.md
  content/en/docs/releasenotes/studio-pro/7/7.16.md
  content/en/docs/releasenotes/studio-pro/7/7.17.md
  content/en/docs/releasenotes/studio-pro/7/7.18.md
  content/en/docs/releasenotes/studio-pro/7/7.19.md
  content/en/docs/releasenotes/studio-pro/7/7.2.md
  content/en/docs/releasenotes/studio-pro/7/7.20.md
  content/en/docs/releasenotes/studio-pro/7/7.21.md
  content/en/docs/releasenotes/studio-pro/7/7.22.md
  content/en/docs/releasenotes/studio-pro/7/7.23.md
  content/en/docs/releasenotes/studio-pro/7/7.3.md
  content/en/docs/releasenotes/studio-pro/7/7.4.md
  content/en/docs/releasenotes/studio-pro/7/7.5.md
  content/en/docs/releasenotes/studio-pro/7/7.6.md
  content/en/docs/releasenotes/studio-pro/7/7.7.md
  content/en/docs/releasenotes/studio-pro/7/7.8.md
  content/en/docs/releasenotes/studio-pro/7/7.9.md
  content/en/docs/releasenotes/studio-pro/8/8.0.md
  content/en/docs/releasenotes/studio-pro/8/8.1.md
  content/en/docs/releasenotes/studio-pro/8/8.2.md
  content/en/docs/releasenotes/studio-pro/8/8.3.md
  content/en/docs/releasenotes/studio-pro/8/8.4.md
  content/en/docs/releasenotes/studio-pro/8/8.5.md
  content/en/docs/releasenotes/studio-pro/8/8.6.md
  content/en/docs/releasenotes/studio-pro/8/8.7.md
  content/en/docs/releasenotes/studio-pro/8/8.8.md
  content/en/docs/releasenotes/studio-pro/8/8.9.md
  layouts/partials/landingpage/latest-releases.html
Labels: Internal WIP

#5939 Update information about running in a iframe
  content/en/docs/developerportal/deploy/general/running-in-iframe.md
Labels: Needs R&D technical verification, Needs Support verification

#5837 Update SAML documentation for 3.5
  content/en/docs/appstore/modules/saml.md
  content/en/docs/developerportal/deploy/on-premises-design/ms-windows/_index.md
  static/attachments/appstore/modules/saml/saml-versions.png
Labels: Future release, Needs R&D technical verification
