Repository mendix/docs, pull requests merged in 2023-05, with the labels that each got.

#5970 Maintain app translations
  content/en/docs/appstore/general/app-store-content.md
Labels: Internal WIP

#5969 LDAP Module Documentation
  content/en/docs/appstore/modules/ldap.md
  static/attachments/appstore/modules/ldap/ldap-admin-user-role.png
Labels: Needs R&D technical verification, Internal WIP

#5941 9.6.17 RN
  content/en/docs/refguide9/general/system-requirements.md
  content/en/docs/releasenotes/studio-pro/9/9.6.md
Labels: Update release and/or featured date

#5957 Add section on NPE creation
  content/en/docs/refguide/modeling/domain-model/entities/persistability.md
Labels: Needs R&D technical verification

#5976 Make Mendix Version Numeric in Algolia
  content/en/docs/addons/_index.md
  content/en/docs/apidocs-mxsdk/_index.md
  content/en/docs/appstore/_index.md
  content/en/docs/data-hub/_index.md
  content/en/docs/developerportal/_index.md
  content/en/docs/howto/_index.md
  content/en/docs/howto7/_index.md
  content/en/docs/howto8/_index.md
  content/en/docs/howto9/_index.md
  content/en/docs/partners/_index.md
  content/en/docs/refguide/_index.md
  content/en/docs/refguide7/_index.md
  content/en/docs/refguide8/_index.md
  content/en/docs/refguide9/_index.md
  content/en/docs/releasenotes/_index.md
  content/en/docs/releasenotes/studio-pro/7/_index.md
  content/en/docs/releasenotes/studio-pro/8/_index.md
  content/en/docs/releasenotes/studio-pro/9/_index.md
  content/en/docs/releasenotes/studio/7.11-7.23.md
  content/en/docs/releasenotes/studio/8.0-8.6.md
  content/en/docs/releasenotes/studio/8.7-8.18.md
  content/en/docs/releasenotes/studio/9.0-9.6.md
  content/en/docs/releasenotes/studio/9.7-9.20.md
  content/en/docs/studio-how-to/_index.md
  content/en/docs/studio-how-to8/_index.md
  content/en/docs/studio/_index.md
  content/en/docs/studio7/_index.md
  content/en/docs/studio8/_index.md
Labels: Internal WIP

#5940 9.18.7 RN
  content/en/docs/releasenotes/studio-pro/9/9.18.md
Labels: Update release and/or featured date

#5989 Document Mendix integration in Datadog Marketplace
  content/en/docs/developerportal/operate/metrics/monitoring-with-apm/datadog-metrics.md
Labels: Needs Support verification

#5990 Validate webhook in Mendix
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/webhooks.md
  static/attachments/developerportal/deploy/webhooks/validation-microflow.png
Labels: Needs Support verification

#5668 Update Custom Domain Certificate image
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/custom-domains.md
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/newcustomdomain.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/upload-certificate.png
Labels: Future release, Needs R&D technical verification

#5965 9.24.2 RN
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: 9.24.2

#5964 Reproduce PR 5915
  content/en/docs/refguide/general/mx-command-line-tool.md
  content/en/docs/refguide9/general/mx-command-line-tool.md
Labels: 9.24.2

#5996 Release notes Sprintr 2023.05.04
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#5986 Add license
  content/en/docs/appstore/general/sisw-end-user-license-agreement-freeware.md
Labels: Internal WIP

#5998 Release Notes for Mendix Cloud 4 May 2023
  content/en/docs/apidocs-mxsdk/apidocs/build-api.md
  content/en/docs/apidocs-mxsdk/apidocs/deploy-api/_index.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs R&D technical verification

#5991 Adjust GH action workflow trigger time
  .github/workflows/remunusedattachments.yml
Labels: Internal WIP

#6009 Update links to version 7 Runtime APIs from later documents
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/mxcloudv4/_index.md
  content/en/docs/howto/extensibility/howto-datastorage-api.md
  content/en/docs/howto8/extensibility/howto-datastorage-api.md
  content/en/docs/howto9/extensibility/howto-datastorage-api.md
  static/attachments/howto/extensibility/howto-datastorage-api/image009.png
  static/attachments/howto9/extensibility/howto-datastorage-api/image009.png
Labels: Needs R&D technical verification, Internal WIP

#6019 Quickstart updates
  content/en/docs/refguide/quickstart-guide/_index.md
  content/en/docs/refguide/quickstart-guide/quickstart-part1.md
  content/en/docs/refguide/quickstart-guide/quickstart-part2.md
Labels: Internal WIP

#5946 Update to accomodate asynchronous invocation of lambda functions
  content/en/docs/appstore/connectors/aws/aws-lambda-connector.md
Labels: Future release

#6032 Datahub release 2.79.0
  content/en/docs/releasenotes/data-hub/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#6025 Implement feedback on building connectors best practices doc
  content/en/docs/appstore/creating-content/connector-guide-build/connector-guide-best-practices.md
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/app-initial-setup.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/app-post-setup.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/complex-config-create-microflow.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/complex-config-entity.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/complex-config-security-2.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/complex-config-security.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/gradle-library.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/implementation-folder.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/microflow-action.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-change-value.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-constant.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-new-constants.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-select-constant.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-settings.png
  static/attachments/appstore/creating-content/connector-guide-build/connector-guide-best-practices/simple-config-value.png
Labels: Internal WIP

#5988 Transfer Studio how-to use case to SP guide (domain model)
  content/en/docs/howto/data-models/denormalize-data-to-improve-performance.md
  content/en/docs/howto/front-end/create-your-first-two-overview-and-detail-pages.md
  content/en/docs/howto/integration/export-xml-documents.md
  content/en/docs/howto/integration/importing-excel-documents/_index.md
  content/en/docs/howto/integration/importing-xml-documents.md
  content/en/docs/howto/integration/integrating-a-legacy-system-into-a-mendix-app.md
  content/en/docs/howto/security/create-a-secure-app.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/working-with-lists-in-a-microflow.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/debug-microflows-and-nanoflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
  content/en/docs/refguide/modeling/dev-best-practices.md
  content/en/docs/refguide/modeling/domain-model/_index.md
  content/en/docs/refguide/modeling/domain-model/create-a-basic-data-layer.md
  content/en/docs/refguide/modeling/domain-model/setting-up-data-validation.md
  content/en/docs/refguide/modeling/integration/odata-services/wrap-services-odata.md
  content/en/docs/refguide/modeling/integration/web-services/published-web-services/expose-a-web-service.md
  content/en/docs/refguide/modeling/pages/button-widgets/create-a-custom-save-button.md
  content/en/docs/refguide/modeling/pages/data-widgets/configure-list-and-details-on-one-page.md
  content/en/docs/refguide/modeling/xpath/define-access-rules-using-xpath.md
  content/en/docs/refguide/modeling/xpath/filtering-data-on-an-overview-page.md
  static/attachments/refguide/modeling/domain-model/create-a-basic-data-layer/domain-model-online-shop.png
Labels: Internal WIP

#6041 Fix link to demo app
  content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/logistic-regression-example.md
  content/en/docs/refguide9/modeling/integration/machine-learning-kit/using-ml-kit/logistic-regression-example.md
Labels: Internal WIP

#6002 Kk aws twinmaker
  content/en/docs/appstore/connectors/aws/aws-iot-twinmaker.md
  static/attachments/appstore/connectors/aws-iot-twinmaker/addentity.png
  static/attachments/appstore/connectors/aws-iot-twinmaker/addmicroflow.png
  static/attachments/appstore/connectors/aws-iot-twinmaker/appsettings.png
  static/attachments/appstore/connectors/aws-iot-twinmaker/awsregions.png
  static/attachments/appstore/connectors/aws-iot-twinmaker/createlist.png
  static/attachments/appstore/connectors/aws-iot-twinmaker/createobject.png
  static/attachments/appstore/connectors/aws-iot-twinmaker/credentials.png
  static/attachments/appstore/connectors/aws-iot-twinmaker/fullmicroflow.png
  static/attachments/appstore/connectors/aws-iot-twinmaker/microflow.png
  static/attachments/appstore/connectors/aws-iot-twinmaker/selectassociation.png
Labels: Internal WIP

#6045 adding new prerequisite for SAP native
  content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
Labels: Changes requested

#6029 Endpoint for SVN using PAT
  content/en/docs/developerportal/collaborate/team-server/_index.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
Labels: Future release

#6021 BYOIDP GA
  content/en/docs/developerportal/control-center/set-up-sso-byoidp.md
Labels: Future release

#6031 Kk aws rekognition feedback
  content/en/docs/appstore/connectors/aws/amazon-rekognition.md
Labels: Internal WIP

#6053 PC release notes
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/openapi-spec/private-cloud-build-api.yaml
Labels: Future release

#6059 fixing the image errors
  content/en/docs/appstore/connectors/aws/amazon-eventbridge.md
Labels: Internal WIP

#5972 Implement REST Best Practices with OData
  content/en/docs/refguide/modeling/integration/odata-services/build-odata-apis.md
  static/attachments/refguide/modeling/integration/build-odata-apis/call-send-email-logic.png
  static/attachments/refguide/modeling/integration/build-odata-apis/create-customer-email-request-entity.png
  static/attachments/refguide/modeling/integration/build-odata-apis/create-resources-associations.png
  static/attachments/refguide/modeling/integration/build-odata-apis/customer-home-address-npe.png
  static/attachments/refguide/modeling/integration/build-odata-apis/define-insert-action.png
  static/attachments/refguide/modeling/integration/build-odata-apis/delete-operation.png
  static/attachments/refguide/modeling/integration/build-odata-apis/edit-published-resource.png
  static/attachments/refguide/modeling/integration/build-odata-apis/error-422.png
  static/attachments/refguide/modeling/integration/build-odata-apis/example-domain-model.png
  static/attachments/refguide/modeling/integration/build-odata-apis/expand-expression.png
  static/attachments/refguide/modeling/integration/build-odata-apis/expose-single-resource-domain-model.png
  static/attachments/refguide/modeling/integration/build-odata-apis/fetch-all-customers.png
  static/attachments/refguide/modeling/integration/build-odata-apis/fetch-single-customer.png
  static/attachments/refguide/modeling/integration/build-odata-apis/filter-sort-page-attribute.png
  static/attachments/refguide/modeling/integration/build-odata-apis/generate-validation-microflow.png
  static/attachments/refguide/modeling/integration/build-odata-apis/get-call.png
  static/attachments/refguide/modeling/integration/build-odata-apis/get-microflow.png
  static/attachments/refguide/modeling/integration/build-odata-apis/get-resource-sent.png
  static/attachments/refguide/modeling/integration/build-odata-apis/insert-microflow.png
  static/attachments/refguide/modeling/integration/build-odata-apis/insert-new-data.png
  static/attachments/refguide/modeling/integration/build-odata-apis/json-schema.png
  static/attachments/refguide/modeling/integration/build-odata-apis/long-queries.png
  static/attachments/refguide/modeling/integration/build-odata-apis/modify-existing-data-1.png
  static/attachments/refguide/modeling/integration/build-odata-apis/modify-existing-data-2.png
  static/attachments/refguide/modeling/integration/build-odata-apis/openapi-contract.png
  static/attachments/refguide/modeling/integration/build-odata-apis/oql-database.png
  static/attachments/refguide/modeling/integration/build-odata-apis/prefer-header.png
  static/attachments/refguide/modeling/integration/build-odata-apis/query-resource-endpoint.png
  static/attachments/refguide/modeling/integration/build-odata-apis/select-attributes-associations.png
  static/attachments/refguide/modeling/integration/build-odata-apis/sort-top-skip.png
  static/attachments/refguide/modeling/integration/build-odata-apis/specify-use-microflow.png
  static/attachments/refguide/modeling/integration/build-odata-apis/standard-error-codes.png
  static/attachments/refguide/modeling/integration/build-odata-apis/subquery.png
  static/attachments/refguide/modeling/integration/build-odata-apis/swagger-doc.png
  static/attachments/refguide/modeling/integration/build-odata-apis/task-queue.png
  static/attachments/refguide/modeling/integration/build-odata-apis/test-page.png
  static/attachments/refguide/modeling/integration/build-odata-apis/translate-to-odl-expression.png
  static/attachments/refguide/modeling/integration/build-odata-apis/validation-microflow.png
  static/attachments/refguide/modeling/integration/build-odata-apis/validation-response-payload.png
  static/attachments/refguide/modeling/integration/build-odata-apis/validation-rules.png
  static/attachments/refguide/modeling/integration/build-odata-apis/versioning.png
  static/attachments/refguide/modeling/integration/build-odata-apis/view-log-line-details.png
Labels: Internal WIP

#6068 Fix APD links
  content/en/docs/appstore/partner-solutions/apd/_index.md
  content/en/docs/appstore/partner-solutions/apd/ig/_index.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/_index.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-installation-steps/_index.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-installation-steps/ig-one-after-startup-error.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-installation-steps/ig-one-constants.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-prerequisites/_index.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-prerequisites/ig-one-java-security-settings.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-prerequisites/ig-one-sizing-impact.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-uninstall-steps.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-one/ig-one-upgrade-steps.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-three.md
  content/en/docs/appstore/partner-solutions/apd/ig/ig-two.md
  content/en/docs/appstore/partner-solutions/apd/release-notes/index.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/_index.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/_index.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-configuration.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-dashboard.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-download-license.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-jvm-browser.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-load-test-recorder.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-log-tool.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-measurements-tool.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-performance-tool/_index.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-performance-tool/rg-one-inserting-context-information.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-performance-tool/rg-one-performance-tool-results.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-query-tool.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-statistics-tool.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-trap-tool.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-one-apm/rg-one-triggers.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/_index.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-apps.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-dashboard.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-environments.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-logs.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-long-running-actions.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-recorder/_index.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-recorder/rg-three-browser-recorder-results.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-recorder/rg-three-runtime-recorder-results.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-settings.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-three-apd/rg-three-statistics.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/_index.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-apps.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-dashboard.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-environments.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-logs.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-long-running-actions.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-recorder/_index.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-recorder/rg-two-browser-recorder-results.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-recorder/rg-two-runtime-recorder-results.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-settings.md
  content/en/docs/appstore/partner-solutions/apd/rg-apd/rg-two-apm/rg-two-statistics.md
  content/en/docs/appstore/partner-solutions/apd/uc/_index.md
  content/en/docs/appstore/partner-solutions/apd/uc/uc-one.md
  content/en/docs/appstore/partner-solutions/apd/uc/uc-three.md
  content/en/docs/appstore/partner-solutions/apd/uc/uc-two.md
  content/en/docs/developerportal/support/submit-support-request.md
  content/en/docs/howto/monitoring-troubleshooting/manage-app-performance/manage-app-performance-with-new-relic.md
  content/en/docs/howto8/monitoring-troubleshooting/manage-app-performance/manage-app-performance-with-new-relic.md
  content/en/docs/howto9/monitoring-troubleshooting/manage-app-performance/manage-app-performance-with-new-relic.md
Labels: Internal WIP

#6062 Add OData doc references
  content/en/docs/refguide/modeling/integration/odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service-requirements.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
Labels: Internal WIP

#6042 9.19.1 RN
  content/en/docs/releasenotes/studio-pro/9/9.19.md
Labels: Future release

#6072 Update published OData service doc
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
Labels: Internal WIP

#6070 Ensure Mendix 10 is included in IAM documention version information
  content/en/docs/appstore/modules/oidc.md
  content/en/docs/appstore/modules/saml.md
Labels: Needs R&D technical verification

#6069 Introduction into Adaptable Solutions & Start of the best practices
  content/en/docs/appstore/creating-content/sol-solutions-guide/_index.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/comm-sol-partner-program.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-adapt/_index.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-adapt/sol-adaptability.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-adapt/sol-architecting.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-adapt/sol-ip-protection.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-development/_index.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-development/sol-architecting.md
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-development/sol-ip-protection.md
  content/en/docs/appstore/creating-content/sol-solutions-impl-guide/_index.md
  content/en/docs/appstore/creating-content/sol-solutions-impl-guide/sol-set-up.md
  content/en/docs/appstore/creating-content/sol-solutions-impl-guide/sol-upgrade.md
  content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/refguide9/modeling/app-explorer/app/app-settings/_index.md
  static/attachments/appstore/creating-content/sol-solutions-guide/sol-adapt/sol-adaptability-best-practices/adaptability-domain-model-example.png
  static/attachments/appstore/creating-content/sol-solutions-guide/sol-adapt/sol-architecting/adaptable-solution-architecture.png
  static/attachments/appstore/creating-content/sol-solutions-guide/sol-adapt/sol-architecting/mendix-plm-for-fashion-and-retail.png
  static/attachments/appstore/creating-content/sol-solutions-guide/sol-adapt/solution-deployment.png
  static/attachments/appstore/creating-content/sol-solutions-guide/sol-adapt/solution-lifecycle.png
  static/attachments/appstore/creating-content/sol-solutions-guide/sol-adapt/solution-three-parts.png
  static/attachments/appstore/creating-content/sol-solutions-guide/sol-development/sol-architecting/adaptive-solution-architecture.png
  static/attachments/appstore/creating-content/sol-solutions-guide/sol-development/sol-architecting/adaptive-solution-composition.png
Labels: Internal WIP

#6081 flexible environments - minor clarification
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
Labels: Changes requested

#6033 Workflow engine
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/call-microflow.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-engine.md
  static/attachments/refguide/modeling/application-logic/workflows/workflow-engine/user-task-states.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-engine/workflow-data.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-engine/workflow-states.png
Labels: Needs R&D technical verification

#6082 Update _index.md
  content/en/docs/releasenotes/marketplace/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#6085 MG gov
  content/en/docs/appstore/general/share-app-store-content.md
Labels: Internal WIP

#6094 Clarify creating an email template
  content/en/docs/appstore/connectors/email-connector.md
Labels: Internal WIP

#5995 Add a new microflow how-to (retrieve the current user)
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/retrieving-current-user-with-a-microflow.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/retrieving-current-user/retrieving-current-user.png
Labels: Internal WIP

#6020 Update icons for microflow and nanoflow activities
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/change-workflow-state.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/_index.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/aggregate-list.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/apply-jump-to-option.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/call-ML-model.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/call-java-action.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/call-javascript-action.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/call-microflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/call-nanoflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/call-rest-service.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/call-web-service.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/cast-object.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/change-list.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/change-object.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/change-variable.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/change-workflow-state.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/close-page.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/commit-object.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/complete-task.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/counter.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/create-list.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/create-object.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/create-variable.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/delete-external-object.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/delete-object.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/download-file.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/export-with-mapping.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/gauge.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/generate-document.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/generate-jump-to-options.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/import-with-mapping.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/increment-counter.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-operation.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/lock-workflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/log-message.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/open-task-page.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/open-workflow-page.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/retrieve-workflow-context.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/retrieve.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/rollback.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/send-external-object.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/show-home-page.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/show-message.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/show-page.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/synchronize-to-device.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/synchronize.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/unlock-workflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/validation-feedback.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-call.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/activity.png
Labels: Internal WIP

#6061 Initial version of document generation documentation
  content/en/docs/appstore/modules/document-generation.md
  static/attachments/appstore/modules/document-generation/request-flow.png
Labels: 10.0.0 Beta 2

#6098 MG UI updates
  content/en/docs/appstore/general/app-store-overview.md
  content/en/docs/appstore/general/share-app-store-content.md
  content/en/docs/releasenotes/developer-portal/_index.md
  content/en/docs/releasenotes/marketplace/_index.md
  static/attachments/appstore/general/app-store-overview/bell.png
  static/attachments/appstore/general/app-store-overview/company-content.png
  static/attachments/appstore/general/app-store-overview/company-subscriptions.jpg
  static/attachments/appstore/general/app-store-overview/company-subscriptions.png
  static/attachments/appstore/general/app-store-overview/group-content-context.png
  static/attachments/appstore/general/app-store-overview/group-content.png
  static/attachments/appstore/general/app-store-overview/guests.png
  static/attachments/appstore/general/app-store-overview/home-page.png
  static/attachments/appstore/general/app-store-overview/members.png
  static/attachments/appstore/general/app-store-overview/my-content.png
  static/attachments/appstore/general/app-store-overview/my-draft-menu-options.png
  static/attachments/appstore/general/app-store-overview/my-draft.png
  static/attachments/appstore/general/app-store-overview/my-drafts.png
  static/attachments/appstore/general/app-store-overview/partner.png
  static/attachments/appstore/general/app-store-overview/premium.png
  static/attachments/appstore/general/app-store-overview/saved.png
  static/attachments/appstore/general/app-store-overview/your-reviews.png
Labels: Internal WIP
