Repository mendix/docs, pull requests merged in 2024-03, with the labels that each got.

#7361 Add reference to React client setting in RN 10.7
  content/en/docs/releasenotes/studio-pro/10/10.7.md
Labels: Needs language review

#7350 Add text for Renew app registration button for PDF Document Generation documentation
  content/en/docs/appstore/modules/document-generation.md
Labels: Internal WIP, Needs language review

#7365 Update environments-details.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
Labels: Needs language review

#7372 pmp azure ci/cd
  content/en/docs/private-platform/configuration/pmp-configure-azure.md
  static/attachments/private-platform/pmp-cicd4.png
Labels: Internal WIP

#7235 New Doc Mobile SSO
  content/en/docs/appstore/modules/mobile-sso.md
  static/attachments/appstore/modules/mobile-sso/Configure client information.png
  static/attachments/appstore/modules/mobile-sso/Custom login.png
  static/attachments/appstore/modules/mobile-sso/Deeplink.png
  static/attachments/appstore/modules/mobile-sso/Manifest.png
  static/attachments/appstore/modules/mobile-sso/Module architecture.png
  static/attachments/appstore/modules/mobile-sso/Okta deployed.png
  static/attachments/appstore/modules/mobile-sso/Okta local.png
  static/attachments/appstore/modules/mobile-sso/Okta1.png
  static/attachments/appstore/modules/mobile-sso/Public client flows.png
  static/attachments/appstore/modules/mobile-sso/architecture.png
  static/attachments/appstore/modules/mobile-sso/configuring navigation.png
Labels: Future release, Internal WIP

#7379 Operator2_15 release
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-standard-operator.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-operator.md
  content/en/docs/developerportal/deploy/private-cloud/secret-store-credentials.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Needs language review

#7384 PMP K8s CI/CD Help Me feature
  content/en/docs/private-platform/configuration/pmp-configure-k8s.md
Labels: Changes requested

#7352 [RUN-3894] Create Java version migration document
  content/en/docs/refguide/java-programming/java-version-migration.md
  content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
  content/en/docs/refguide8/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
  content/en/docs/refguide9/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
Labels: Needs language review

#7394 Add section on consuming enumerations
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/_index.md
  content/en/docs/refguide/modeling/resources/enumerations.md
Labels: Internal WIP

#7383 Add clarification about reason phrases and HTTP/2
  content/en/docs/refguide/modeling/integration/rest-services/http-request-and-response-entities.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/published-rest-operation.md
  content/en/docs/releasenotes/studio-pro/10/10.0.md
Labels: Internal WIP, Needs language review

#7307 Update macOS Beta version System Requirements
  content/en/docs/refguide/installation/system-requirements.md
Labels: Needs language review

#6919 MG Reviews update
  content/en/docs/appstore/overview/_index.md
  content/en/docs/appstore/overview/my-marketplace.md
  content/en/docs/releasenotes/marketplace/_index.md
Labels: Future release

#7402 PMP release notes 1.6.1
  content/en/docs/releasenotes/private-platform/1.6.md
Labels: Future release

#7382 [RUN 3912] Add information about SBOM in Dependency Synchronization section
  content/en/docs/refguide/java-programming/managed-dependencies.md
Labels: Needs language review

#7409 Deep link info in the Forgot Password module
  content/en/docs/appstore/modules/forgot-password.md
Labels: Internal WIP

#7408 Module roles update for Mendix SSO
  content/en/docs/appstore/modules/mendix-sso.md
  static/attachments/appstore/modules/mendix-sso/User_roles.png
Labels: Internal WIP

#7438 proofreading
  content/en/docs/appstore/modules/mobile-sso.md
Labels: Internal WIP

#7414 Add 10.6.5 RN
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/10/10.8.md
Labels: Update release and/or featured date, 10.6.5

#7428 Runtime setting for JSON string length in mapping 10.6.5
  content/en/docs/refguide/modeling/integration/mapping-documents/import-mappings.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: 10.6.5

#7343 [RUN-3911] Update Managed Dependency docs page with information about proxy settings
  content/en/docs/refguide/java-programming/managed-dependencies.md
Labels: Needs language review

#7434 Bedrock/prompt templates
  content/en/docs/appstore/modules/aws/amazon-bedrock.md
Labels: Needs language review

#7413 Add 9.24.17 RN
  content/en/docs/releasenotes/studio-pro/10/10.8.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: 9.24.17

#7346 [RUN-3889] Changes for BatchSize config for clean up actions (9.24.17)
  content/en/docs/refguide9/modeling/resources/task-queue.md
  content/en/docs/refguide9/runtime/custom-settings/_index.md
Labels: 9.24.17

#7429 Runtime setting for JSON string length in mapping 9.24.17
  content/en/docs/refguide9/modeling/integration/mapping-documents/import-mappings.md
  content/en/docs/refguide9/runtime/custom-settings/_index.md
Labels: 9.24.17

#7333 Process around PenTest
  content/en/docs/support/_index.md
Labels: Needs R&D technical verification, Internal WIP, Needs Support verification

#7392 Add texts for supporting Mendix dedicated cloud in PDF Document Generation module docs
  content/en/docs/appstore/modules/document-generation.md
Labels: Internal WIP, Needs language review

#7447 Update Azure storage settings configuration documentation
  content/en/docs/community-tools/contribute-to-mendix-docs/indentation-spacing-test.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: Needs R&D technical verification

#7458 Remove old versions from Sitemap
  content/en/docs/howto7/_index.md
  content/en/docs/howto8/_index.md
  content/en/docs/howto9/_index.md
  content/en/docs/refguide7/_index.md
  content/en/docs/refguide8/_index.md
  content/en/docs/refguide9/_index.md
  layouts/_default/sitemap.xml
Labels: Internal WIP

#7463 Updated system requirements about JDK support
  content/en/docs/refguide8/general/system-requirements.md
  content/en/docs/refguide9/general/system-requirements.md
Labels: Needs language review

#7455 [MOO-1333] Update native mobile prerequisites
  content/en/docs/howto8/mobile/native-mobile/common-issues.md
  content/en/docs/refguide/mobile/getting-started-with-mobile/prerequisites.md
  content/en/docs/refguide9/mobile/getting-started-with-mobile/prerequisites.md
  static/attachments/howto/mobile/native-mobile/get-started/common-issues/inboundrules.png
  static/attachments/howto8/mobile/native-mobile/common-issues/inboundrules.png
  static/attachments/howto9/mobile/native-mobile/get-started/common-issues/inboundrules.png
Labels: Needs language review

#7484 Updated migration eligibility criteria
  content/en/docs/developerportal/general/team-server/migrate-to-git.md
Labels: Needs language review

#7362 Proofread and adjust content on workflow system entities
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/lock-workflow.md
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-engine.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
  content/en/docs/refguide/modeling/pages/on-click-event.md
Labels: Internal WIP

#7495 Change erroneous text about task queue table lock
  content/en/docs/refguide/modeling/resources/task-queue.md
Labels: Needs language review

#7494 Add App Center retirement warning
  content/en/docs/refguide/mobile/distributing-mobile-apps/building-native-apps/deploying-native-app.md
Labels: Needs language review

#7475 Peer Review: Mendix Client
  content/en/docs/refguide/runtime/mendix-client/_index.md
Labels: Internal/Peer Review

#7502 Update native client launch
  content/en/docs/refguide/mobile/distributing-mobile-apps/overtheair-updates.md
  content/en/docs/refguide/runtime/mendix-client/_index.md
Labels: Needs language review

#7507 Add 9.24.18 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: 9.24.18

#7452 Peer review Advanced Audit Trail
  content/en/docs/appstore/modules/advanced-audit-trail/_index.md
Labels: Internal/Peer Review

#7469 Add 10.9.0 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/10/10.7.md
  content/en/docs/releasenotes/studio-pro/10/10.8.md
  content/en/docs/releasenotes/studio-pro/10/10.9.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review, Update release and/or featured date, 10.9

#7431 Auth Token Support Docs in 10.9
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/auto-committed-objects.md
  content/en/docs/refguide/mobile/introduction-to-mobile-technologies/progressive-web-app.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/refguide/runtime/custom-settings/tricky-custom-runtime-settings.md
  content/en/docs/refguide/runtime/mendix-client/_index.md
  content/en/docs/refguide/runtime/session-management.md
  static/attachments/refguide/runtime/session.png
Labels: 10.9

#7378 Add new runtime setting for JSON string used with mapping
  content/en/docs/refguide/modeling/integration/mapping-documents/import-mappings.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: Needs language review, 10.9

#7345 [RUN-3889] Changes for BatchSize config for clean up actions (10.9.0)
  content/en/docs/refguide/modeling/resources/task-queue.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/refguide9/modeling/resources/scheduled-events/scheduled-events-legacy.md
Labels: 10.9

#7298 Private constant values in 10.9.0
  content/en/docs/refguide/modeling/app-explorer/app/app-settings/configuration.md
Labels: 10.9

#7493 React Widget Upgrade Changes
  content/en/docs/refguide/modeling/pages/image-and-file-widgets/image-viewer.md
  content/en/docs/refguide/modeling/pages/image-and-file-widgets/image.md
  content/en/docs/refguide/modeling/pages/input-widgets/drop-down.md
  content/en/docs/refguide/modeling/pages/input-widgets/input-reference-set-selector.md
  content/en/docs/refguide/modeling/pages/input-widgets/reference-selector.md
  content/en/docs/refguide/modeling/pages/input-widgets/reference-set-selector.md
Labels: 10.9

#7474 UFC - Update docs and screenshot for continue all functionality
  content/en/docs/refguide/general/studio-pro-overview.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/debug-microflows-and-nanoflows/_index.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/debug-microflows-and-nanoflows/add-breakpoint.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/debug-microflows-and-nanoflows/breakpoints-pane.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/debug-microflows-and-nanoflows/debugger-pane.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/debug-microflows-and-nanoflows/debugging-panes.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/debug-microflows-and-nanoflows/variables-pane.png
Labels: 10.9

#7364 Add docs on query string parameters for microflow URLs
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow/microflow-url.png
Labels: 10.9

#7303 Added small note to object type decision for nanoflows
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/decisions/object-type-decision.md
Labels: 10.9

#7341 Update consumed-rest-services-beta file to include support for DELETE method
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services-beta.md
Labels: 10.9

#7492 "Updated Release Notes, How to and documentation for external database connector for 10.9 release.
  content/en/docs/appstore/modules/database-connector-mx10.md
  content/en/docs/howto/integration/use-the-external-database-connector.md
  static/attachments/appstore/modules/external-database-connector/execute-query.png
  static/attachments/appstore/modules/external-database-connector/response-structure.png
  static/attachments/appstore/modules/external-database-connector/select-query-columns.png
  static/attachments/howto/integration/use-the-external-database-connector/3.png
  static/attachments/howto/integration/use-the-external-database-connector/4.png
  static/attachments/howto/integration/use-the-external-database-connector/5.png
  static/attachments/howto/integration/use-the-external-database-connector/6.png
  static/attachments/howto/integration/use-the-external-database-connector/7.png
Labels: 10.9

#7465 Page and microflow URL info
  content/en/docs/appstore/modules/oidc.md
Labels: Internal WIP

#7503 Mention PWA
  content/en/docs/appstore/modules/oidc.md
Labels: Future release, Internal WIP

#7510 Release documentation for metamodel & Model SDK 10.9.0
  content/en/docs/releasenotes/sdk/metamodel/metamodel-10/metamodel-10.9.md
  content/en/docs/releasenotes/sdk/model-sdk/model-sdk-4.md
Labels: Needs language review

#7472 Peer review- Validation Assist
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-validation-assist.md
Labels: Internal/Peer Review

#7480 Update automate-mendix-deployment-on-microsoft-windows.md
  content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
Labels: Needs language review

#7514 Investigate and remove the "!default" flag for custom variables
  assets/scss/_variables_project.scss
Labels: Internal WIP

#7479 Moving the OIDC Cognito config to a separate file
  content/en/docs/appstore/modules/aws/amazon-cognito.md
  content/en/docs/appstore/modules/oidc.md
Labels: Needs R&D technical verification
