Repository mendix/docs, pull requests merged in 2024-12, with the labels that each got.

#8705 Deletion of Unused Free Apps (to be released on December 1)
  content/en/docs/apidocs-mxsdk/apidocs/apps/app-repository-api.md
  content/en/docs/apidocs-mxsdk/apidocs/deployment/deploy-api-1.md
  content/en/docs/apidocs-mxsdk/mxsdk/sdk-howtos/using-platform-sdk.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/mendix-feedback.md
  content/en/docs/control-center/apps/application-health-dashboard.md
  content/en/docs/control-center/apps/apps-overview.md
  content/en/docs/control-center/apps/deployed-apps.md
  content/en/docs/deployment/mendix-cloud-deploy/_index.md
  content/en/docs/deployment/mendix-cloud-deploy/environments-new.md
  content/en/docs/deployment/mendix-cloud-deploy/migrating-to-different-cloud.md
  content/en/docs/developerportal/general/settings/_index.md
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
  content/en/docs/releasenotes/developer-portal/_index.md
  content/en/docs/support/prepare-your-app.md
  content/en/docs/support/submit-support-request.md
  static/openapi-spec/projects-v2.yaml
Labels: Future release, Needs language review

#8749 TW-2499 updates
  content/en/docs/appstore/use-content/platform-supported-content/services/oidc-provider.md
Labels: Internal WIP

#8747 Remove Team Server API documentation
  content/en/docs/apidocs-mxsdk/apidocs/apps/team-server-api.md
  content/en/docs/apidocs-mxsdk/apidocs/deployment/build-api.md
  content/en/docs/howto/integration/implement-cicd-pipeline.md
  content/en/docs/howto8/integration/implement-cicd-pipeline.md
  content/en/docs/howto9/integration/implement-cicd-pipeline.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  static/attachments/apidocs-mxsdk/apidocs/team-server-api/425989.png
  static/attachments/howto/integration/implement-cicd-pipeline/02GetLatestRevision.png
  static/attachments/howto8/integration/implement-cicd-pipeline/02GetLatestRevision.png
  static/attachments/howto9/integration/implement-cicd-pipeline/02GetLatestRevision.png
Labels: Needs R&D technical verification

#8728 Add section on empty values in XPath expressions
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-keywords-and-system-variables.md
Labels: Needs language review

#8741 Update teamcenter-extension.md V3.1
  content/en/docs/appstore/use-content/platform-supported-content/modules/teamcenter-extension.md
Labels: Needs language review

#8737 Update docs for MxModelReflection 8.0.3
  content/en/docs/appstore/use-content/platform-supported-content/modules/model-reflection.md
Labels: Needs R&D technical verification

#8710 Remove feature flag
  content/en/docs/appstore/create-content/create-solutions/implement-solutions/sol-upgrade.md
Labels: Needs R&D technical verification

#8743 Changed analyze-mpr display-path
  content/en/docs/refguide/general/mx-command-line-tool/_index.md
  content/en/docs/refguide/general/mx-command-line-tool/analyze-mpr.md
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
Labels: Needs R&D technical verification

#8681 Highlight output in Travis log
  .travis.yml
Labels: Internal WIP

#8767 9.24.31 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Update release and/or featured date, Release Notes, 9.24.31

#8766 8.18.33 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/8/8.18.md
Labels: Update release and/or featured date, Release Notes, 8.18.33

#8738 Update Marketplace Release notes
  content/en/docs/apidocs-mxsdk/apidocs/apps/app-repository-api.md
  content/en/docs/apidocs-mxsdk/apidocs/deployment/deploy-api-1.md
  content/en/docs/apidocs-mxsdk/mxsdk/sdk-howtos/using-platform-sdk.md
  content/en/docs/appstore/overview/component-details.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/mendix-feedback.md
  content/en/docs/control-center/apps/application-health-dashboard.md
  content/en/docs/control-center/apps/apps-overview.md
  content/en/docs/control-center/apps/deployed-apps.md
  content/en/docs/deployment/mendix-cloud-deploy/_index.md
  content/en/docs/deployment/mendix-cloud-deploy/environments-new.md
  content/en/docs/deployment/mendix-cloud-deploy/migrating-to-different-cloud.md
  content/en/docs/developerportal/general/settings/_index.md
  content/en/docs/partners/siemens/3d-viewer/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/committing-objects.md
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
  content/en/docs/releasenotes/developer-portal/_index.md
  content/en/docs/releasenotes/marketplace/general-marketplace.md
  content/en/docs/releasenotes/studio-pro/10/10.17.md
  content/en/docs/support/prepare-your-app.md
  content/en/docs/support/submit-support-request.md
  static/openapi-spec/projects-v2.yaml
Labels: Future release, Update release and/or featured date, Release Notes

#8778 New v1.0.5 release of the Tekton Pipelines (planned for release on December 11)
  content/en/docs/deployment/private-cloud/private-cloud-tekton/_index.md
  content/en/docs/deployment/private-cloud/private-cloud-tekton/private-cloud-tekton-airgap.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Future release, Needs language review

#8714 CAT-2925 update registration form documentation
  content/en/docs/catalog/register/register-data.md
  content/en/docs/catalog/register/register-non-odata-resources.md
Labels: Future release

#8772 Release notes and documentation updated for portunus 7_8_0 release
  content/en/docs/deployment/private-cloud/private-cloud-deploy.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/deployment/private-cloud/private-cloud-deploy/image10.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/image11.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/image12.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/image17.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/image20.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/image5.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/image9.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/lock.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/technicalContact.png
Labels: Future release, Needs language review

#8731 (12 Dec) Offboard My Subscriptions and Company Subscriptions in the Marketplace
  content/en/docs/appstore/overview/component-details.md
  content/en/docs/appstore/overview/marketplace-home-page.md
  content/en/docs/partners/siemens/3d-viewer/_index.md
  content/en/docs/releasenotes/marketplace/general-marketplace.md
Labels: Future release, Needs language review, Update release and/or featured date

#8787 Remove documentation of a 64,000 file limit on MDAs
  content/en/docs/deployment/mendix-cloud-deploy/behavior-of-app.md
Labels: Needs R&D technical verification

#8786 Link from Control Center to Alert Thresholds
  content/en/docs/control-center/apps/application-health-dashboard.md
  content/en/docs/deployment/mendix-cloud-deploy/monitoring-application-health/_index.md
Labels: Needs R&D technical verification

#8756 (Dec 12) Update mendix-cloud.md for the new alerts app
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#8782 Fix rendering issue with images in an alert box
  layouts/partials/hooks/body-end.html
  layouts/shortcodes/figure.html
Labels: Internal/Peer Review

#8587 Create new Catalog API docs and index
  content/en/docs/apidocs-mxsdk/apidocs/catalog.md
  content/en/docs/apidocs-mxsdk/apidocs/catalog/_index.md
  content/en/docs/apidocs-mxsdk/apidocs/catalog/registration-api.md
  content/en/docs/apidocs-mxsdk/apidocs/catalog/search-api.md
  content/en/docs/catalog/get-started.md
  content/en/docs/catalog/manage/search.md
  content/en/docs/catalog/register/_index.md
  content/en/docs/catalog/register/automate-registration.md
  content/en/docs/catalog/register/register-data.md
  content/en/docs/catalog/register/register-non-odata-resources.md
  content/en/docs/catalog/register/without-mendix-cloud.md
  content/en/docs/releasenotes/catalog/_index.md
  static/openapi-spec/catalog-common-definitions_v5.yaml
  static/openapi-spec/catalog-registration_v5.yaml
  static/openapi-spec/catalog-search_v5.yaml
Labels: Future release

#8775 [UIA-886] Global Platform static IP + DocGen IP whitelisting
  content/en/docs/appstore/use-content/platform-supported-content/modules/document-generation.md
  content/en/docs/deployment/mendix-cloud-deploy/mendix-ip-addresses.md
Labels: Needs language review

#8771 10.18.0 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.1.md
  content/en/docs/releasenotes/studio-pro/10/10.10.md
  content/en/docs/releasenotes/studio-pro/10/10.11.md
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.13.md
  content/en/docs/releasenotes/studio-pro/10/10.14.md
  content/en/docs/releasenotes/studio-pro/10/10.15.md
  content/en/docs/releasenotes/studio-pro/10/10.16.md
  content/en/docs/releasenotes/studio-pro/10/10.17.md
  content/en/docs/releasenotes/studio-pro/10/10.18.md
  content/en/docs/releasenotes/studio-pro/10/10.2.md
  content/en/docs/releasenotes/studio-pro/10/10.3.md
  content/en/docs/releasenotes/studio-pro/10/10.4.md
  content/en/docs/releasenotes/studio-pro/10/10.5.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/10/10.7.md
  content/en/docs/releasenotes/studio-pro/10/10.8.md
  content/en/docs/releasenotes/studio-pro/10/10.9.md
  layouts/partials/landingpage/latest-releases.html
Labels: Update release and/or featured date, Release Notes, 10.18

#8806 Release documentation for metamodel & Model SDK 10.18.0
  content/en/docs/releasenotes/sdk/metamodel/metamodel-10/metamodel-10.18.md
  content/en/docs/releasenotes/sdk/model-sdk/model-sdk-4.md
Labels: 10.18

#8770 Start on Security Overview beta release docs
  content/en/docs/refguide/modeling/menus/app-menu/_index.md
  content/en/docs/refguide/modeling/security/_index.md
  content/en/docs/refguide/modeling/security/security-overview.md
  static/attachments/refguide/modeling/security/app-security/user-roles/security-overview.png
Labels: Needs language review, 10.18

#8744 Added MPRv2 explanation, limitations and conversion
  content/en/docs/refguide/modeling/menus/file-menu/_index.md
  content/en/docs/refguide/version-control/_index.md
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
  static/attachments/refguide/modeling/menus/file-menu/file-menu.png
Labels: Needs language review, Edit images after merging, 10.18

#8742 Documentation Updates for Changes Pane to Include File Change Display
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/changes-pane-file-changes.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/commit-git-changes-on-disk.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/commit-git.png
Labels: Needs language review, 10.18

#8765 [RUN-4383] Remove reference to Gradle 7.6 from Mendix 10 documentation (10.18.0)
  content/en/docs/refguide/installation/system-requirements.md
Labels: 10.18

#8758 Documentation update for new menu option : App -> Tools -> Generate Bill of Materials
  content/en/docs/control-center/security/software-composition.md
  content/en/docs/refguide/general/sbom-generation.md
  content/en/docs/refguide/modeling/menus/app-menu/_index.md
Labels: 10.18

#8788 Domain Model Generator updates in 10.18
  content/en/docs/refguide/modeling/mendix-ai-assistance/domain-model-generator.md
Labels: 10.18

#8763 PAG release UI recommender
  content/en/docs/refguide/modeling/mendix-ai-assistance/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/ui-recommender.md
  content/en/docs/refguide/modeling/pages/page/_index.md
  static/attachments/refguide/modeling/mendix-ai-assistance/ui-recommender/blue-plus-sign.png
  static/attachments/refguide/modeling/mendix-ai-assistance/ui-recommender/dialog.png
  static/attachments/refguide/modeling/mendix-ai-assistance/ui-recommender/search-in-dialog.png
Labels: 10.18

#8773 Added changes for Live preview and setting result format to JSON for snowflake
  content/en/docs/appstore/use-content/platform-supported-content/modules/database-connector-mx10.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/snowflake/snowflake-edc.md
  content/en/docs/refguide/modeling/integration/use-extensions/external-database-connection.md
  content/en/docs/refguide/modeling/integration/use-extensions/use-the-external-database-connector.md
Labels: 10.18

#8769 Update data-importer-extension.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/data-importer-extension.md
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/create-DI-doc-with-import-mapping.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/create-import-mapping.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/data-imported-from-input-file.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/data-importer-doc-updated.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/entity-name-persist-change.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/import-with-mapping-params.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/map-automatically.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/preview-data-structure.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/select-file-for-structure-preview.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/select-schema-elements-for-imm.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/update-data-importer-doc-confirmation.png
Labels: 10.18

#8546 Added new capability to mx.exe - for 10.17
  content/en/docs/refguide/general/mx-command-line-tool/app.md
Labels: 10.18

#8802 introduction to native template version 11
  content/en/docs/releasenotes/mobile/native-template/_index.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/_index.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-10-rn.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-11-rn.md
Labels: 10.18

#8768 WIP: [RUN-4401] Documentation for tracing beta (10.18.0)
  content/en/docs/refguide/runtime/tracing-in-runtime.md
Labels: 10.18

#8808 React Client Update
  content/en/docs/appstore/use-content/platform-supported-content/modules/model-reflection.md
  content/en/docs/refguide/runtime/mendix-client/content-readiness.md
Labels: Needs language review

#8803 Security summary
  content/en/docs/developerportal/security-summary.md
  layouts/partials/landingpage/user-journey-cards.html
Labels: Needs R&D technical verification

#8811 How to configure Json logging.
  content/en/docs/refguide/runtime/monitoring-mendix-runtime.md
Labels: Needs language review

#8822 OIDC 4.0.0 updates
  content/en/docs/appstore/use-content/platform-supported-content/modules/oidc.md
Labels: Needs R&D technical verification

#8827 OIDC Provider 4.1.0 updates
  content/en/docs/appstore/use-content/platform-supported-content/services/oidc-provider.md
Labels: Needs R&D technical verification

#8820 Add 4XL-5XLDB CRP
  content/en/docs/deployment/mendix-cloud-deploy/_index.md
Labels: Needs language review

#8831 PMP installer updates for Dec 31st
  content/en/docs/private-platform/pmp-quickstart.md
  static/attachments/private-platform/pmp-install8.png
Labels: Future release

#8832 PMP relnotes 1.17 for Dec 31st
  content/en/docs/releasenotes/private-platform/1.17.md
  content/en/docs/releasenotes/private-platform/_index.md
Labels: Future release
