Repository mendix/docs, pull requests merged in 2024-06, with the labels that each got.

#7729 Add introduction and business use cases for workflows
  content/en/docs/appstore/creating-content/connector-guide-build/connector-guide-best-practices.md
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
  content/en/docs/refguide/modeling/application-logic/workflows/perform-workflow-basic-functions.md
  content/en/docs/releasenotes/studio-pro/10/10.4.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Internal WIP

#7802 Added 'shallow clone' for Git in pipeline
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
Labels: Needs language review

#7835 Updated timeline
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
Labels: Needs language review

#7837 Remove limitation for React client support
  content/en/docs/appstore/modules/document-generation.md
Labels: Future release, Needs language review

#7823 Version upgrade
  README.md
  assets/scss/_styles_project.scss
  config/_default/hugo.toml
  config/development/hugo.toml
  config/production/hugo.toml
  content/en/docs/appstore/modules/aws/amazon-rekognition.md
  content/en/docs/appstore/modules/aws/aws-authentication.md
  content/en/docs/community-tools/contribute-to-mendix-docs/markdown-shortcodes.md
  content/en/docs/howto/integration/use-excel-documents/import-a-large-excel-file.md
  content/en/docs/howto7/integration/consume-a-rest-service.md
  content/en/docs/howto7/mobile/publishing-a-mendix-hybrid-mobile-app-in-mobile-app-stores.md
  content/en/docs/howto8/integration/consume-a-rest-service.md
  content/en/docs/howto8/integration/publish-rest-service.md
  content/en/docs/howto9/integration/importing-excel-documents/import-a-large-excel-file.md
  content/en/docs/quickstarts/hello-world.md
  content/en/docs/refguide/modeling/domain-model/associations/query-over.md
  content/en/docs/refguide/modeling/xpath/_index.md
  content/en/docs/refguide7/desktop-modeler/integration/consumed-rest-services/_index.md
  content/en/docs/refguide7/desktop-modeler/integration/published-rest-services/_index.md
  content/en/docs/refguide7/desktop-modeler/integration/published-rest-services/published-rest-service/_index.md
  content/en/docs/refguide7/desktop-modeler/integration/published-rest-services/published-rest-service/published-rest-operation.md
  content/en/docs/refguide8/modeling/integration/consumed-rest-services/_index.md
  content/en/docs/refguide8/modeling/integration/published-rest-services/_index.md
  content/en/docs/refguide8/modeling/integration/published-rest-services/published-rest-service/_index.md
  content/en/docs/refguide8/modeling/integration/published-rest-services/published-rest-service/published-rest-operation.md
  content/en/docs/refguide8/modeling/xpath/_index.md
  content/en/docs/refguide9/modeling/domain-model/associations/query-over.md
  content/en/docs/refguide9/modeling/xpath/_index.md
  content/en/docs/releasenotes/studio-pro/7/7.11.md
  content/en/docs/releasenotes/studio-pro/7/7.12.md
  content/en/docs/releasenotes/studio-pro/7/7.13.md
  content/en/docs/releasenotes/studio-pro/7/7.14.md
  content/en/docs/releasenotes/studio-pro/7/7.15.md
  content/en/docs/releasenotes/studio-pro/7/7.16.md
  content/en/docs/releasenotes/studio-pro/7/7.3.md
  content/en/docs/releasenotes/studio-pro/7/7.6.md
  content/en/docs/releasenotes/studio-pro/8/8.0.md
  content/en/docs/releasenotes/studio-pro/9/9.7.md
  layouts/_default/content.html
  layouts/docs/list.html
  layouts/partials/breadcrumb.html
  layouts/partials/scripts.html
  layouts/partials/section-index.html
  layouts/swagger/list.html
  package-lock.json
  package.json
Labels: Internal WIP

#7845 Release Notes For Catalog 2.124.0 for June 6 2024
  content/en/docs/releasenotes/catalog/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs language review

#7848 Clarify limitations of private repositories
  content/en/docs/refguide/version-control/on-premises-git.md
Labels: Needs language review

#7857 Update excel-exporter.md
  content/en/docs/appstore/modules/excel-exporter.md
Labels: Needs language review

#7833 Updated the Mendix Data Loader documentation
  content/en/docs/appstore/modules/snowflake/_index.md
  content/en/docs/appstore/modules/snowflake/mendix-data-loader.md
Labels: Needs language review

#7856 Update mqtt.md to inform WSS protocol is supported
  content/en/docs/appstore/modules/mqtt.md
Labels: Needs language review

#7859 Added missing release notes for Native Template 8
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-8-rn.md
Labels: Needs language review

#7847 Add 9.24.23 RN
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Update release and/or featured date, 9.24.23

#7854 Release Notes Sprintr and update to the developer portal guide
  content/en/docs/developerportal/_index.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/developerportal/app-tiles.png
  static/attachments/developerportal/apps-overview.png
  static/attachments/developerportal/company-apps.png
Labels: Future release, Needs language review

#7792 OIDC Provider updates
  content/en/docs/appstore/services/oidc-provider.md
Labels: Future release, Internal WIP

#7866 Update Release Notes
  content/en/docs/releasenotes/security-advisories/_index.md
  content/en/docs/releasenotes/studio-pro/10/10.11.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/9/9.13.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Future release, Needs R&D technical verification

#7875 [DAT-3717] Add documentation for import call object parameter usage in Database Replication Module
  content/en/docs/appstore/modules/database-replication.md
Labels: Needs language review

#7862 Add 10.6.10 release notes
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Future release, Update release and/or featured date

#7855 Kk aws textract
  content/en/docs/appstore/modules/aws/aws-textract.md
  static/attachments/appstore/modules/aws-textract/analyze-document-configure-microflow.png
  static/attachments/appstore/modules/aws-textract/analyze-document-properties.png
Labels: Needs R&D technical verification

#7877 OIDC SSO JIRA Tickets
  content/en/docs/appstore/modules/oidc.md
Labels: Internal WIP

#7870 Release notes for Mx4PC 2.17.1 - planned to be released on June 12
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Future release, Needs language review, Update release and/or featured date

#7878 Update managed-dependencies.md
  content/en/docs/refguide/java-programming/managed-dependencies.md
Labels: Needs R&D technical verification, Needs language review

#7841 Describe MPR (v2) description
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
Labels: Needs language review

#7811 [DB-2932] Adding changes for access control and user access
  content/en/docs/appstore/services/business-events.md
  content/en/docs/appstore/services/event-broker.md
  static/attachments/appstore/services/event-broker/event_broker_access_control_defaults.png
  static/attachments/appstore/services/event-broker/event_broker_access_control_overview.png
  static/attachments/appstore/services/event-broker/event_broker_access_control_overview_2.png
  static/attachments/appstore/services/event-broker/event_broker_access_control_overview_3.png
  static/attachments/appstore/services/event-broker/event_broker_external_user.png
  static/attachments/appstore/services/event-broker/event_broker_internal_user.png
  static/attachments/appstore/services/event-broker/event_broker_internal_user_2.png
Labels: Needs language review

#7827 Update Language Menu
  content/en/docs/refguide/modeling/menus/translatable-texts/translate-your-app-content.md
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-replace-initial.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-replace-russian-capitals.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-replace-russian-initial.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-translate-cancel-delete-edit.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-translate-cancel-edit.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-translate-initial.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-translate-myfirstmodule.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-translate-order-2-translations.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-translate-order-split.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/batch-translate-order.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/change-language.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/home-page-chinese.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/home-page-russian.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/home-page-text.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/language-settings-belarusian.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/language-settings-singapore.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/language-settings.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/order-button.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/product-new-edit-order-chinese.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/product-new-edit-order-russian.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/product-new-edit-order.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/product-new-edit-partial-translation.png
  static/attachments/refguide/modeling/menus/translatable-texts/translate-your-app-content/untranslated-texts.png
Labels: Internal WIP

#7901 Update dump-mpr.md
  content/en/docs/refguide/general/mx-command-line-tool/dump-mpr.md
Labels: Needs language review

#7861 Documented the Java and JS variable name setting
  content/en/docs/refguide/modeling/resources/java-actions.md
  content/en/docs/refguide/modeling/resources/javascript-actions.md
  content/en/docs/refguide9/modeling/resources/java-actions.md
  content/en/docs/refguide9/modeling/resources/javascript-actions.md
Labels: Needs language review

#7882 Rename pages with duplicate titles
  content/en/docs/appstore/modules/_index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/metrics.md
  content/en/docs/developerportal/project-management/epics/epics.md
  content/en/docs/releasenotes/deployment/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
Labels: Internal WIP

#7884 Ensure navigation is still shown on non-JS browsers (e.g. Google Search).
  layouts/partials/sidebar-tree.html
  layouts/partials/sidebar.html
Labels: Internal WIP, Awaiting response

#7907 Update deep-link.md
  content/en/docs/appstore/modules/deep-link.md
Labels: Needs R&D technical verification, Needs language review

#7918 Indicate we do not support alias with spaces in OQL
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-select-clause.md
  content/en/docs/refguide7/desktop-modeler/data-sets/oql/oql-select-clause.md
  content/en/docs/refguide8/modeling/resources/data-sets/oql/oql-select-clause.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-select-clause.md
Labels: Needs language review

#7898 10.12.0 rn
  content/en/docs/refguide/runtime/datasource-runtime-behavior.md
  content/en/docs/releasenotes/studio-pro/10/10.10.md
  content/en/docs/releasenotes/studio-pro/10/10.11.md
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.3.md
  content/en/docs/releasenotes/studio-pro/10/10.4.md
  content/en/docs/releasenotes/studio-pro/10/10.5.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/10/10.7.md
  content/en/docs/releasenotes/studio-pro/10/10.8.md
  content/en/docs/releasenotes/studio-pro/10/10.9.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.12

#7794 [UFC-1171] Add documentation for optional parameters in JavaScript Actions
  content/en/docs/refguide/modeling/resources/javascript-actions.md
  static/attachments/refguide/modeling/resources/javascript-actions/call-js-action-dialog.png
  static/attachments/refguide/modeling/resources/javascript-actions/documentation-js-file.png
  static/attachments/refguide/modeling/resources/javascript-actions/documentation-pro.png
  static/attachments/refguide/modeling/resources/javascript-actions/expose-jsaction.png
  static/attachments/refguide/modeling/resources/javascript-actions/javascript-action-settings-no-para.png
  static/attachments/refguide/modeling/resources/javascript-actions/parameter-naming.png
  static/attachments/refguide/modeling/resources/javascript-actions/type-parameter.png
  static/attachments/refguide/modeling/resources/javascript-actions/workshop-exposed.png
Labels: 10.12

#7836 [SOLP-2504] Menu item “Reverse Merge Changes ....” should be renamed with "Revert a commit ..."
  content/en/docs/refguide/modeling/menus/version-control-menu/_index.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  static/attachments/refguide/modeling/menus/version-control-menu/version-control-menu.png
Labels: 10.12

#7917 Edb document update
  content/en/docs/appstore/modules/database-connector-mx10.md
  content/en/docs/appstore/modules/snowflake/snowflake-edc.md
  content/en/docs/howto/integration/use-extensions/use-the-external-database-connector.md
  static/attachments/appstore/modules/external-database-connector/database-connection-wizard.png
  static/attachments/appstore/modules/external-database-connector/example-parameter.png
  static/attachments/howto/integration/use-the-external-database-connector/2.png
  static/attachments/howto/integration/use-the-external-database-connector/4.png
Labels: 10.12

#7896 Added support for remote enumeration values
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service-requirements.md
Labels: 10.12

#7895 Configuration microflow for consumed OData service
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
  static/attachments/catalog/security/authentication-headers-from-microflow.png
  static/attachments/catalog/security/authentication-microflow.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/consumed-odata-service-screen.png
Labels: 10.12

#7863 [RUN-3787][RUN-3855][RUN-3666] Add documentation for managed dependency improvements (10.12.0)
  content/en/docs/refguide/java-programming/managed-dependencies.md
  content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
  static/attachments/refguide/java-programming/managed-dependencies/custom-repository.png
  static/attachments/refguide/java-programming/managed-dependencies/edit-exclusion.png
  static/attachments/refguide/java-programming/managed-dependencies/edit-java-dependencies.png
  static/attachments/refguide/java-programming/managed-dependencies/exclusions.png
  static/attachments/refguide/java-programming/managed-dependencies/module-settings.png
  static/attachments/refguide/modeling/app-explorer/modules/module-settings/module-settings-java-dependencies.png
Labels: 10.12

#7807 Update list of supported languages
  content/en/docs/refguide/modeling/menus/translatable-texts/language-settings.md
Labels: 10.12

#7906 Add a section for passing parameters from a page to flows
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/parameter.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/parameter/parameter-expression.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/parameter/parameter-grid.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/parameter/parameter-variable.png
Labels: 10.12

#7872 Extend retry handling for multi-user tasks.
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/workflow-activities/change-workflow-state.md
Labels: 10.12

#7846 Document the return variable name of microflow or nanoflow
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/action-call-activities/microflow-call.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/nanoflow-call.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/events/end-event.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/events/end-event/end-event-form.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/events/end-event/return-variable-name.png
Labels: 10.12

#7940 Documentation Updates for Mendix AI Assistance (Maia)
  content/en/docs/howto/monitoring-troubleshooting/detect-and-resolve-performance-issues.md
  content/en/docs/quickstarts/responsive-web-app.md
  content/en/docs/refguide/general/studio-pro-overview.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md
  content/en/docs/refguide/modeling/community-best-practices-for-app-performance.md
  content/en/docs/refguide/modeling/domain-model/mx-validation-assist.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/menus/translatable-texts/batch-translate.md
  content/en/docs/refguide/modeling/menus/view-menu/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mendix-chat.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/_index.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/performance-best-practices.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/translation-generator.md
  content/en/docs/refguide/modeling/mx-assist-studio-pro/workflow-recommender.md
  content/en/docs/releasenotes/feature-release-calendar/_index.md
  static/attachments/refguide/modeling/domain-model/mx-validation-assist/extract-sub-microflow-dialog.png
  static/attachments/refguide/modeling/domain-model/mx-validation-assist/extract-sub-microflow.png
  static/attachments/refguide/modeling/domain-model/mx-validation-assist/generate-validation-microflow-dialog.png
  static/attachments/refguide/modeling/domain-model/mx-validation-assist/generate-validation-microflow-option.png
  static/attachments/refguide/modeling/domain-model/mx-validation-assist/validation-microflow.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/maia-chat-example.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/maia-chat-interface.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/mendix-chat-example.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/mendix-chat-interface.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/assist-bulb.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/initial-recommendations.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/search-microflows-nanoflows.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/search-sub-actions.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/search-sub-flows.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-logic-bot/search-toolbox.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/app-model.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/best-practice-recommendation.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/best-practice.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/fix-issue.jpg
  static/attachments/refguide/modeling/mx-assist-studio-pro/mx-assist-performance-bot/fix-issue.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/translation-generator/confirmation.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/translation-generator/enable-translation-generator.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/translation-generator/translation-generator.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/workflow-recommender/blue-plus.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/workflow-recommender/initial-recommendations.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/workflow-recommender/search-toolbox.png
Labels: 10.12

#7920 GenAI 10.12
  content/en/docs/appstore/modules/aws/amazon-bedrock.md
  content/en/docs/appstore/modules/genai/_index.md
  content/en/docs/appstore/modules/genai/bedrock.md
  content/en/docs/appstore/modules/genai/concepts/_index.md
  content/en/docs/appstore/modules/genai/concepts/function-calling.md
  content/en/docs/appstore/modules/genai/concepts/prompt-engineering.md
  content/en/docs/appstore/modules/genai/concepts/rag-example-implementation.md
  content/en/docs/appstore/modules/genai/conversational-ui.md
  content/en/docs/appstore/modules/genai/genai-commons.md
  content/en/docs/appstore/modules/genai/openai/_index.md
  content/en/docs/appstore/modules/genai/pg-vector-knowledge-base/_index.md
  content/en/docs/appstore/modules/genai/pg-vector-knowledge-base/vector-database-setup.md
  content/en/docs/appstore/modules/openai/_index.md
  content/en/docs/appstore/modules/openai/function-calling.md
  static/attachments/appstore/modules/genai/conversational-ui/domain-model.png
  static/attachments/appstore/modules/genai/function-calling/function-calling-with-clarification.png
  static/attachments/appstore/modules/genai/function-calling/function-calling.png
  static/attachments/appstore/modules/genai/openai/domain-model-configuration.png
  static/attachments/appstore/modules/genai/openai/domain-model-embeddings-with-data-batch.png
  static/attachments/appstore/modules/genai/openai/domain-model-images.png
  static/attachments/appstore/modules/genai/openai/domain-model-openai-request_extension.png
  static/attachments/appstore/modules/openai-connector/domain-model-chat-completions.png
  static/attachments/appstore/modules/openai-connector/domain-model-configuration.png
  static/attachments/appstore/modules/openai-connector/domain-model-embeddings-with-data-batch.png
  static/attachments/appstore/modules/openai-connector/domain-model-generalizations.png
  static/attachments/appstore/modules/openai-connector/domain-model-images.png
  static/attachments/appstore/modules/openai-connector/function-calling/function-calling-with-clarification.png
  static/attachments/appstore/modules/openai-connector/function-calling/function-calling.png
Labels: Needs R&D technical verification, Internal WIP, Needs language review

#7889 Create permalinks for anchors rather than numbered links
  content/en/docs/appstore/creating-content/connector-guide-build/_index.md
  content/en/docs/appstore/modules/deep-link.md
  content/en/docs/appstore/modules/genai/pg-vector-knowledge-base/_index.md
  content/en/docs/appstore/modules/ldap.md
  content/en/docs/appstore/modules/mobile-sso.md
  content/en/docs/appstore/modules/native-mobile-resources.md
  content/en/docs/appstore/modules/oidc.md
  content/en/docs/appstore/modules/saml.md
  content/en/docs/control-center/apps.md
  content/en/docs/control-center/company-settings.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/licensing-apps/_index.md
  content/en/docs/developerportal/deploy/private-cloud/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
  content/en/docs/developerportal/general/team/_index.md
  content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-one.md
  content/en/docs/howto/front-end/create-your-first-two-overview-and-detail-pages.md
  content/en/docs/howto/integration/publish-rest-service.md
  content/en/docs/private-platform/pmp-quickstart.md
  content/en/docs/private-platform/pmp-user-guide.md
  content/en/docs/quickstarts/leading-mendix-implementation.md
  content/en/docs/refguide/mobile/designing-mobile-user-interfaces/navigation.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/local-notifications/local-notif-schedule-cancel.md
  content/en/docs/refguide/modeling/integration/odata-services/build-odata-apis.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/supported-odata-operations.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-view.md
  content/en/docs/refguide/modeling/resources/java-actions.md
  content/en/docs/refguide/modeling/security/app-security/anonymous-users.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/refguide/runtime/logging.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
  content/en/docs/refguide9/mobile/designing-mobile-user-interfaces/navigation.md
  content/en/docs/refguide9/mobile/using-mobile-capabilities/local-notifications/local-notif-schedule-cancel.md
  content/en/docs/refguide9/modeling/app-explorer/_index.md
  content/en/docs/refguide9/modeling/application-logic/workflows/_index.md
  content/en/docs/refguide9/modeling/domain-model/setting-up-data-validation.md
  content/en/docs/refguide9/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service-requirements.md
  content/en/docs/refguide9/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide9/modeling/menus/file-menu/new-app.md
  content/en/docs/refguide9/modeling/mx-assist-studio-pro/mx-validation-assist.md
  content/en/docs/refguide9/modeling/resources/enumerations.md
  content/en/docs/refguide9/modeling/xpath/xpath-constraints/xpath-expressions.md
  content/en/docs/refguide9/modeling/xpath/xpath-constraints/xpath-keywords-and-system-variables.md
  content/en/docs/releasenotes/control-center/_index.md
  content/en/docs/releasenotes/studio-pro/10/10.10.md
Labels: Internal WIP

#7952 10.6.11 RNs
  content/en/docs/releasenotes/studio-pro/10/10.3.md
  content/en/docs/releasenotes/studio-pro/10/10.4.md
  content/en/docs/releasenotes/studio-pro/10/10.5.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: 10.6.11

#7950 Added documentation and screenshots for Snowflake
  content/en/docs/appstore/modules/snowflake/snowflake-edc.md
  content/en/docs/appstore/modules/snowflake/snowflake-rest-sql.md
  static/attachments/appstore/modules/snowflake-rest-sql/snowsight-account-identifier.png
  static/attachments/appstore/modules/snowflake-rest-sql/snowsight-account-url.png
Labels: Internal WIP, Needs language review

#7964 Rename Maia markdown files
  content/en/docs/refguide/modeling/mendix-ai-assistance/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/best-practice-recommender/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/best-practice-recommender/performance-best-practices.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/logic-bot-recommender.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-chat.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/translation-generator.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/workflow-recommender.md
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/anti-pattern-overview.jpg
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/app-model.png
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/auto-fixable.png
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/best-practice-recommendation.jpg
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/best-practice-recommendation.png
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/best-practice-recommender-pane.png
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/best-practice.png
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/drop-down-menu.jpg
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/fix-issue.png
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/fix-performance-issue.jpg
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/indicator-in-editor.jpg
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/performance-bot-pane.png
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/performance-recommendation.jpg
  static/attachments/refguide/modeling/mendix-ai-assistance/best-practice-recommender/viewing-anti-pattern.jpg
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-bot-recommender/assist-bulb.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-bot-recommender/initial-recommendations.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-bot-recommender/mendix-assist-icon.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-bot-recommender/mx-assist-on-off-button.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-bot-recommender/mx-assist-recommendations.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-bot-recommender/mx-assist-system-variables.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-bot-recommender/search-sub-actions.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-bot-recommender/search-sub-flows.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-bot-recommender/search-toolbox.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-chat/feedback-section.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-chat/maia-chat-example.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-chat/maia-chat-interface.png
  static/attachments/refguide/modeling/mendix-ai-assistance/translation-generator/confirmation.png
  static/attachments/refguide/modeling/mendix-ai-assistance/translation-generator/enable-translation-generator.png
  static/attachments/refguide/modeling/mendix-ai-assistance/translation-generator/translation-generator.png
  static/attachments/refguide/modeling/mendix-ai-assistance/workflow-recommender/blue-plus.png
  static/attachments/refguide/modeling/mendix-ai-assistance/workflow-recommender/initial-recommendations.png
  static/attachments/refguide/modeling/mendix-ai-assistance/workflow-recommender/search-toolbox.png
Labels: Internal WIP

#7961 Update scheduled-events.md
  content/en/docs/refguide/modeling/resources/scheduled-events.md
Labels: Needs language review
