Repository mendix/docs, pull requests merged in 2024-05, with the labels that each got.

#7630 Add 10.10 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.10.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.10

#7505 [RUN-3810] Update Gradle to 8.5 (Mendix 10.10)
  content/en/docs/refguide/installation/install.md
Labels: 10.10

#7530 Update language-settings.md
  content/en/docs/refguide/modeling/menus/translatable-texts/language-settings.md
Labels: 10.10

#7539 Updated git versions installed with StP
  content/en/docs/refguide/installation/install.md
  content/en/docs/refguide/installation/system-requirements.md
Labels: 10.10

#7641 Visual Builder Improvements 10.10
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-how-to-configure.md
  content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/_index.md
  static/attachments/refguide/modeling/domain-model/entities/access-rules/access-rule-xpath-tab.png
  static/attachments/refguide/modeling/xpath/xpath-constraints/thomson-and-thompson.png
Labels: 10.10

#7572 Create documentation for subqueries in OQL
  content/en/docs/refguide/modeling/resources/data-sets/_index.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/_index.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-coalesce.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-datediff.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-datepart.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-length.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-lower.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-rangebegin.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-rangeend.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-replace.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-round.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-upper.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-operators/oql-case-expression.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-parameters.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-subqueries.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-from-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-group-by-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-limit-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-order-by-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-select-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-where-clause.md
Labels: 10.10

#7543 Add section for new Foreign Key Constraints runtime setting
  content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
  content/en/docs/refguide/runtime/data-storage/_index.md
Labels: 10.10

#7501 Explain DefaultAzureCredential support
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: 10.10

#7601 Document the Optimize bundle settings 10.10
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
Labels: 10.10

#7679 Update jira-connector.md
  content/en/docs/developerportal/project-management/jira-connector.md
Labels: 10.10

#7666 Mendix Chat Updates
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mendix-chat.md
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/feedback-section.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/mendix-chat-example.png
Labels: 10.10

#7654 Document the different sorting strategies in microflows and nanoflows: 10.10
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/list-operation.md
Labels: 10.10

#7652 Update the description of the 'Stories' pane in Studio Pro
  content/en/docs/refguide/modeling/menus/view-menu/stories-pane.md
  static/attachments/refguide/modeling/menus/view-menu/stories-pane/open-document-icon.png
  static/attachments/refguide/modeling/menus/view-menu/stories-pane/stories-pane.png
  static/attachments/refguide/modeling/menus/view-menu/stories-pane/story-details.png
Labels: 10.10

#7674 Added snowflake support for External Database Connector
  content/en/docs/appstore/modules/database-connector-mx10.md
  content/en/docs/howto/integration/use-the-external-database-connector.md
  content/en/docs/refguide/modeling/integration/database-connection/_index.md
  static/attachments/appstore/modules/external-database-connector/database-connection-wizard.png
  static/attachments/howto/integration/use-the-external-database-connector/2.png
Labels: 10.10

#7680 Release documentation for metamodel & Model SDK 10.10.0
  content/en/docs/releasenotes/sdk/metamodel/metamodel-10/metamodel-10.10.md
  content/en/docs/releasenotes/sdk/model-sdk/model-sdk-4.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review, 10.10

#7671 Add proxy notice to CE9805
  content/en/docs/refguide/java-programming/managed-dependencies.md
Labels: Needs language review

#7698 Include three new operations in Pgvector Module
  content/en/docs/appstore/modules/pgvector-knowledge-base/_index.md
Labels: Needs language review

#7700 Updated commit images, corrected diagram, improved texts
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/commit-dialog-incoming.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/commit-dialog.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/commit-git.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-commit.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png
Labels: Needs language review

#7703 Kk pmp relnotes
  content/en/docs/private-platform/configuration/_index.md
  content/en/docs/releasenotes/private-platform/1.9.md
  content/en/docs/releasenotes/private-platform/_index.md
Labels: Needs R&D technical verification

#7706 Portunus 6.5.0 Release
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/AutoAcceptClusterManager.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/AutoAcceptInvite.png
  static/attachments/developerportal/deploy/private-cloud/private-cloud-deploy/LicensePCLM.png
  static/openapi-spec/private-cloud-build-api.yaml
  static/openapi-spec/private-cloud-deploy-api.yaml
Labels: Future release

#6922 OIDC SSO Release - 8 December 2023
  content/en/docs/appstore/modules/oidc.md
  static/attachments/appstore/modules/oidc/enable-oidc-provider-parsing_needtodelete.png
  static/attachments/appstore/modules/oidc/enable-sam-parsing_needtodelete.png
  static/attachments/appstore/modules/oidc/oidcprovider_parsing.png
  static/attachments/appstore/modules/oidc/parsing_sam_token.png
  static/attachments/appstore/modules/oidc/user commons.png
  static/attachments/appstore/modules/oidc/user-roles.png
  static/attachments/appstore/modules/oidc/user_roles.png
Labels: Needs R&D technical verification

#7727 more clarity about rest vs edc for snowflake
  content/en/docs/appstore/modules/snowflake/_index.md
Labels: Needs R&D technical verification

#7736 Update NT 7 release notes
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-7-rn.md
Labels: Needs language review

#7732 OIDC proofreading
  content/en/docs/appstore/modules/oidc.md
  static/attachments/appstore/modules/oidc/enable-oidc-provider-parsing_needtodelete.png
  static/attachments/appstore/modules/oidc/enable-sam-parsing_needtodelete.png
  static/attachments/appstore/modules/oidc/enable-sam.png
  static/attachments/appstore/modules/oidc/oidc-provider-parsing.png
  static/attachments/appstore/modules/oidc/oidcprovider_parsing.png
  static/attachments/appstore/modules/oidc/parsing_sam_token.png
Labels: Internal WIP

#7728 Reflect current limitations in drop-down with associations
  content/en/docs/appstore/modules/data-widgets/data-grid-2.md
Labels: Needs language review

#7737 Release notes for Catalog 2.121.0 on 16-5-24
  content/en/docs/releasenotes/catalog/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#7746 add missing info-OIDC
  content/en/docs/appstore/modules/oidc.md
Labels: Internal WIP

#7713 Kk snow rbac fix
  content/en/docs/appstore/modules/snowflake/_index.md
  content/en/docs/appstore/modules/snowflake/snowflake-rbac.md
  static/attachments/appstore/modules/snowflake-rest-sql/connection-details-account.png
  static/attachments/appstore/modules/snowflake-rest-sql/connection-details-microflow.png
  static/attachments/appstore/modules/snowflake-rest-sql/connection-details-newedit.png
  static/attachments/appstore/modules/snowflake-rest-sql/create-statement-object.png
  static/attachments/appstore/modules/snowflake-rest-sql/domain-model.png
  static/attachments/appstore/modules/snowflake-rest-sql/execute-statement-microflow.png
  static/attachments/appstore/modules/snowflake-rest-sql/execute-statement.png
  static/attachments/appstore/modules/snowflake-rest-sql/mapping-entity.png
  static/attachments/appstore/modules/snowflake-rest-sql/retrieve-details.png
  static/attachments/appstore/modules/snowflake-rest-sql/sample-results.png
  static/attachments/appstore/modules/snowflake-rest-sql/snowflake_architecture_setup.png
  static/attachments/appstore/modules/snowflake-rest-sql/test-user1-mendix.png
  static/attachments/appstore/modules/snowflake-rest-sql/test-user1-snowflake.png
  static/attachments/appstore/modules/snowflake-rest-sql/test-user2-mendix.png
  static/attachments/appstore/modules/snowflake-rest-sql/test-user2-snowflake.png
Labels: Future release

#7693 Mendix Data Loader mx doc
  content/en/docs/appstore/modules/snowflake/mendix-data-loader.md
Labels: Future release, Needs language review

#7759 Mobile SSO-Small fix
  content/en/docs/appstore/modules/mobile-sso.md
Labels: Internal WIP

#7768 Added information in Storage plan and secret storage document
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-storage-plans.md
  content/en/docs/developerportal/deploy/private-cloud/secret-store-credentials.md
Labels: Needs language review

#7777 Clarify scheduled event disable/enable KI
  content/en/docs/releasenotes/studio-pro/10/10.10.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/10/10.7.md
  content/en/docs/releasenotes/studio-pro/10/10.8.md
  content/en/docs/releasenotes/studio-pro/10/10.9.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Needs language review

#7772 Add 9.24.22 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Future release, Update release and/or featured date, 9.24.22

#7763 OIDC Update: response_mode
  content/en/docs/appstore/modules/oidc.md
Labels: Internal WIP

#7790 Update _index.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
Labels: Needs language review

#7712 Generating a Software Bill of Materials
  content/en/docs/refguide/general/mxbuild.md
  content/en/docs/refguide/general/sbom-generation.md
Labels: Needs language review

#7788 Add a known issue
  content/en/docs/releasenotes/studio-pro/10/10.11.md
Labels: Needs language review, 10.11

#7773 Add 10.6.9 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Future release, Update release and/or featured date, 10.6.9

#7758 Clarify well-known endpoint tw-2393
  content/en/docs/appstore/modules/oidc.md
  content/en/docs/control-center/security/set-up-sso-byoidp.md
Labels: Internal WIP

#7801 Clarify log level behavior on ConnectionBus_Queries
  content/en/docs/refguide/runtime/custom-settings/tricky-custom-runtime-settings.md
Labels: Needs Support verification

#7782 Data Loader Documentation
  content/en/docs/appstore/modules/snowflake/mendix-data-loader.md
Labels: Needs language review, Awaiting response

#7771 Add 10.11 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.10.md
  content/en/docs/releasenotes/studio-pro/10/10.11.md
  content/en/docs/releasenotes/studio-pro/10/10.7.md
  content/en/docs/releasenotes/studio-pro/10/10.8.md
  content/en/docs/releasenotes/studio-pro/10/10.9.md
  layouts/partials/landingpage/latest-releases.html
Labels: Update release and/or featured date, 10.11

#7695 Update Studio Pro prerequisites
  content/en/docs/refguide/installation/install.md
  content/en/docs/refguide/installation/system-requirements.md
Labels: 10.11

#7506 [RUN-3806] Add known date formatting change in JDK 21 (Mendix 10.11)
  content/en/docs/refguide/java-programming/java-version-migration.md
  content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
Labels: 10.11

#7799 Update the description of the 'View' main menu in Studio Pro
  content/en/docs/refguide/modeling/menus/view-menu/_index.md
  static/attachments/refguide/modeling/menus/view-menu/view-menu.png
Labels: 10.11

#7585 [RUN-3915][RUN-3813] Add page for JDK installation instructions (Mx10.11)
  content/en/docs/appstore/modules/model-reflection.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-monitor.md
  content/en/docs/refguide/installation/install.md
  content/en/docs/refguide/installation/jdk-installation.md
  content/en/docs/refguide/installation/system-requirements.md
  content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
  content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-decimal-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/string-function-calls.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/resources/regular-expressions.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-week-from-datetime.md
  content/en/docs/refguide/runtime/metrics.md
  content/en/docs/refguide/runtime/monitoring-mendix-runtime.md
Labels: 10.11

#7806 Create a documentation for the 'Support Tools' sub-menu of the 'Help' menu (Performance logging & Profiling)
  content/en/docs/refguide/modeling/menus/_index.md
  content/en/docs/refguide/modeling/menus/help-menu/_index.md
  content/en/docs/refguide/modeling/menus/help-menu/performance-logging.md
  content/en/docs/refguide/modeling/menus/help-menu/profiling.md
  static/attachments/refguide/modeling/menus/help-menu/performance-logging/compare-measurements-dialog.png
  static/attachments/refguide/modeling/menus/help-menu/performance-logging/compare-measurements.png
  static/attachments/refguide/modeling/menus/help-menu/performance-logging/naming-new-session.png
  static/attachments/refguide/modeling/menus/help-menu/performance-logging/performance-logging-menu.png
  static/attachments/refguide/modeling/menus/help-menu/performance-logging/view-measurements.png
  static/attachments/refguide/modeling/menus/help-menu/profiling/profiling-menu.png
Labels: 10.11

#7665 Add CanApplyJumpTo attribute
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-engine.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-versioning.md
Labels: 10.11

#7805 Proofreading and adding keyboard support for MendixChat
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mendix-chat.md
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/feedback-section.png
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/mendix-chat-example.png
Labels: 10.11

#7716 Add OpenAPI Documentation pane
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
  content/en/docs/refguide/modeling/menus/view-menu/_index.md
Labels: 10.11

#7779 Add Enable Hermes engine option to native mobile applications
  .idea/workspace.xml
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/_index.md
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/hermes.md
Labels: 10.11

#7735 remove file-manager warning as it is no longer applicable
  content/en/docs/refguide/modeling/pages/image-and-file-widgets/file-manager.md
Labels: 10.11

#7672 Add renderMode to pluggable-widgets-studio-apis.md
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-studio-apis.md
Labels: 10.11

#7648 Add Sidebar(Drawer) documentation
  content/en/docs/refguide/mobile/designing-mobile-user-interfaces/navigation.md
  static/attachments/refguide/mobile/native-mobile/native-navigation/includesidebar.png
  static/attachments/refguide/mobile/native-mobile/native-navigation/selectsidebarlayout.png
  static/attachments/refguide/mobile/native-mobile/native-navigation/sidebarlayout.png
Labels: 10.11

#7606 Add Navigation Transition options
  content/en/docs/refguide/mobile/designing-mobile-user-interfaces/navigation.md
  static/attachments/refguide/mobile/native-mobile/native-navigation/navigationtransition.png
Labels: 10.11
