Repository mendix/docs, pull requests merged in 2024-10, with the labels that each got.

#8404 Add Mac-supported shortcut keys for logic editors
  content/en/docs/refguide/general/studio-pro-overview/keyboard-shortcuts.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md
  content/en/docs/refguide/modeling/resources/rules.md
  content/en/docs/releasenotes/studio-pro/10/10.8.md
Labels: Internal WIP

#8351 Update saml.md
  content/en/docs/appstore/use-content/modules/saml.md
Labels: Needs language review

#8433 Add 8.18.32 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/8/8.18.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Update release and/or featured date, 8.18.32

#8441 Mobile SSO remove limitation: 5% sign in failure on iOS
  content/en/docs/appstore/use-content/modules/mobile-sso.md
Labels: Internal WIP

#8414 Update authentication token docs
  content/en/docs/refguide/runtime/session-management.md
Labels: Needs R&D technical verification, Awaiting response

#8446 Update private-cloud-license-manager.md
  content/en/docs/deployment/private-cloud/private-cloud-license-manager.md
Labels: Needs language review

#8452 Add more information on the alert event for webhooks.
  content/en/docs/deployment/general/webhooks.md
Labels: Needs language review

#8456 Mendix Cloud supports Mozilla CA Bundle
  content/en/docs/deployment/mendix-cloud-deploy/certificates.md
Labels: Needs R&D technical verification, Internal WIP

#8436 CVE 8.18.32
  content/en/docs/releasenotes/studio-pro/8/8.18.md
Labels: Needs R&D technical verification, 8.18.32

#8412 Explanation of 'changes on disk' dialog added, focusing on 'file comparison'
  content/en/docs/refguide/installation/system-requirements.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/changes-on-disk.png
Labels: Needs language review

#8457 Native Template Release Notes Update
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-9-rn.md
Labels: Needs language review, Release Notes

#8432 Add 10.12.7 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: Update release and/or featured date, 10.12.7, Release Notes

#8462 Update private-cloud-global-operator.md
  content/en/docs/deployment/private-cloud/private-cloud-cluster/private-cloud-global-operator.md
Labels: Needs language review

#8459 9.24.29 RNs
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Update release and/or featured date, Release Notes, 9.24.29

#8471 Add SP KIs (10.6 and 10.12)
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Release Notes

#8478 Handle RUN-4294 Known Issue
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Release Notes

#8472 Removed timeline
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
Labels: Needs language review

#8480 OIDC SSO: Remove duplicate constants
  content/en/docs/appstore/platform-supported-content/modules/oidc.md
Labels: Internal WIP

#8481 Release notes for new Private cloud portal release and updated Deploy…
  content/en/docs/apidocs-mxsdk/apidocs/deployment/private-cloud-deploy-api.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/openapi-spec/private-cloud-deploy-api.yaml
Labels: Future release, Needs language review

#8301 CAT-2926: Update documentation to include BE when talking about autom…
  content/en/docs/appstore/creating-content/connector-guide-build/_index.md
  content/en/docs/catalog/_index.md
  content/en/docs/catalog/get-started.md
  content/en/docs/catalog/register/register-data.md
  static/attachments/catalog/catalog-home.png
Labels: Future release

#8333 Create Environments Beta page
  content/en/docs/deployment/mendix-cloud-deploy/deploying-to-mendix-cloud.md
  content/en/docs/deployment/mendix-cloud-deploy/environments-new.md
  content/en/docs/deployment/mendix-cloud-deploy/environments.md
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/1-select-branch.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/1-select-package.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/2-configure-environment.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/2-select-revision.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/3-backup.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/3-choose-tag.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/4-deploy.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/activity-tab.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/change-scaling.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/deployment-packages-tab.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/deployment-summary.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/edit-configuration.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/environment-expanded.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/manage-cloud-settings.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/manage-env-settings.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/overview-more-options.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/overview-tab.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/permissions-tab.png
  static/attachments/deployment/mendix-cloud-deploy/environments-beta/promote-dialog.png
Labels: Future release, Internal WIP

#8483 10.6.17 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Release Notes, 10.6.17

#8484 10.12.8 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: Release Notes, 10.12.8

#8473 Added information about new .mpr format: MPRv2
  content/en/docs/refguide/version-control/_index.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
Labels: Needs language review

#8467 Update release note for native template
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-7-rn.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-9-rn.md
Labels: Needs language review

#8464 Kk pmp refguide
  content/en/docs/private-platform/pmp-user-guide.md
  content/en/docs/private-platform/reference/_index.md
  content/en/docs/private-platform/reference/common/_index.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-account.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-company.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-getstudio.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-group.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-groupapps.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-groupcontent.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-myapps.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-mycontent.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-nav.md
  content/en/docs/private-platform/reference/common/pmp-ref-common-signin.md
  static/attachments/private-platform/pmp-account-menu.png
  static/attachments/private-platform/pmp-content-details.png
  static/attachments/private-platform/pmp-group-content-details.png
  static/attachments/private-platform/pmp-homepage.png
  static/attachments/private-platform/pmp-manage-credentials.png
  static/attachments/private-platform/pmp-manage-my-group.png
  static/attachments/private-platform/pmp-manage-pat.png
  static/attachments/private-platform/pmp-manage-profile.png
  static/attachments/private-platform/pmp-navigation-menu.png
  static/attachments/private-platform/pmp-notifications.png
  static/attachments/private-platform/pmp-ref-download-studio.png
  static/attachments/private-platform/pmp-ref-signin.png
  static/attachments/private-platform/pmp-refguide-company-content.png
  static/attachments/private-platform/pmp-refguide-groupapps.png
  static/attachments/private-platform/pmp-refguide-mycontent.png
  static/attachments/private-platform/pmp-refguide-mygroupcontent.png
Labels: Needs R&D technical verification

#8454 Revise REST Services index
  content/en/docs/appstore/creating-content/connector-guide-build/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/consumed-rest-services-beta.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/server-side-paging.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/use-call-rest-action-in-microflow.md
Labels: Internal WIP

#8491 Conversationalui restructuring and toolbox renaming
  content/en/docs/appstore/platform-supported-content/modules/genai/conversational-ui.md
Labels: Needs language review

#8541 Fix GenAI image issue
  content/en/docs/appstore/platform-supported-content/modules/genai/conversational-ui.md
  content/en/docs/appstore/platform-supported-content/modules/genai/openai/_index.md
  content/en/docs/appstore/platform-supported-content/modules/genai/pg-vector-knowledge-base/_index.md
  content/en/docs/appstore/platform-supported-content/modules/opc-ua-connector.md
  static/attachments/appstore/platform-supported-content/modules/doc-pane.png
Labels: Internal WIP

#8455 Clarify scope of create variable
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/variable-activities/create-variable.md
Labels: Needs R&D technical verification, Internal WIP

#8539 Warning about revisions on SVN for Build API
  content/en/docs/apidocs-mxsdk/apidocs/deployment/build-api.md
Labels: Needs R&D technical verification

#8535 10.12.9 Studio Pro Release Notes
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: Release Notes, 10.12.9

#8570 Proofreading: Conversational UI
  content/en/docs/appstore/platform-supported-content/modules/genai/conversational-ui.md
Labels: Internal WIP

#8515 10.16 Studio Pro Release Notes
  content/en/docs/releasenotes/studio-pro/10/10.15.md
  content/en/docs/releasenotes/studio-pro/10/10.16.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review, Update release and/or featured date, 10.16, Release Notes

#8521 Added details for SSL based Authentication
  content/en/docs/appstore/platform-supported-content/modules/database-connector-mx10.md
  content/en/docs/appstore/platform-supported-content/modules/snowflake/snowflake-edc.md
  content/en/docs/howto/integration/use-extensions/use-the-external-database-connector.md
  static/attachments/appstore/platform-supported-content/modules/external-database-connector/certificates-tab.png
  static/attachments/appstore/platform-supported-content/modules/external-database-connector/edit-configuration.png
  static/attachments/appstore/platform-supported-content/modules/external-database-connector/example-SSL-connection.png
Labels: 10.16

#8523 Update macOS limitations in System Requirements
  content/en/docs/refguide/installation/system-requirements.md
Labels: 10.16

#8556 Update edit menu with back and forward navigation menu items
  content/en/docs/refguide/modeling/menus/edit-menu/_index.md
  static/attachments/refguide/modeling/menus/edit-menu/edit-menu.png
Labels: 10.16

#8496 Clarify required versions of JDK and Gradle w.r.t. Mendix versions
  content/en/docs/refguide/installation/install.md
Labels: 10.16

#8453 Add info box about Web vs Classic version in Consumed REST Service
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/consumed-rest-services-beta.md
Labels: 10.16

#8428 Add docs about customizing http response for OData action and OData from microflow
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-entity.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-microflow.md
Labels: 10.16

#8426 Adds the Collect Support Information tool to the help menu documentation
  content/en/docs/refguide/modeling/menus/help-menu/_index.md
Labels: 10.16

#8413 Add new options to `dump-mpr` command
  content/en/docs/refguide/general/mx-command-line-tool/dump-mpr.md
Labels: 10.16

#8554 Updated Native vs PWA
  content/en/docs/refguide/mobile/introduction-to-mobile-technologies/_index.md
  content/en/docs/refguide/mobile/introduction-to-mobile-technologies/progressive-web-app.md
  content/en/docs/refguide9/mobile/introduction-to-mobile-technologies/_index.md
  content/en/docs/refguide9/mobile/introduction-to-mobile-technologies/progressive-web-app.md
Labels: 10.16

#8437 Webp image support
  content/en/docs/refguide/modeling/images.md
  content/en/docs/refguide/modeling/pages/page-resources/image-collection.md
Labels: 10.16

#8380 [WTF-1940] Allow default values for data sources
  content/en/docs/apidocs-mxsdk/apidocs/frontend/pluggable-widgets/pluggable-widgets-property-types.md
Labels: 10.16

#8461 [RUN-4196] Add information about disabling Gradle synchronization
  content/en/docs/refguide/java-programming/managed-dependencies.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  static/attachments/refguide/modeling/menus/edit-menu/preferences-dialog/preferences-deployment-tab.png
Labels: 10.16

#8497 Add boundary events GA changes to the docs
  content/en/docs/refguide/modeling/application-logic/workflows/boundary-events.md
  static/attachments/refguide/modeling/application-logic/workflows/boundary-events/context-menu.png
  static/attachments/refguide/modeling/application-logic/workflows/boundary-events/enable-boundary-events.png
Labels: 10.16

#8548 Release documentation for metamodel & Model SDK 10.16.0
  content/en/docs/releasenotes/sdk/metamodel/metamodel-10/metamodel-10.16.md
  content/en/docs/releasenotes/sdk/model-sdk/model-sdk-4.md
Labels: 10.16, Release Notes
