Repository mendix/docs, pull requests merged in 2024-04, with the labels that each got.

#7508 Adjusted for public beta Git cleanup
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
  static/attachments/refguide/version-control/troubleshoot-version-control-issues/git_fixer_mode.png
  static/attachments/refguide/version-control/troubleshoot-version-control-issues/git_fixer_modes.png
Labels: Future release, Needs language review

#7504 Add 10.6.6 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Update release and/or featured date, 10.6.6

#7511 Update data grid widget warning
  content/en/docs/appstore/modules/data-widgets/_index.md
  content/en/docs/appstore/modules/data-widgets/data-grid-2.md
  content/en/docs/refguide/modeling/pages/data-widgets/grids/data-grid/_index.md
Labels: Needs language review

#7532 Update native-mobile-resources.md
  content/en/docs/appstore/modules/native-mobile-resources.md
Labels: Needs language review

#7481 Adding User Identifiers API documentation
  content/en/docs/apidocs-mxsdk/apidocs/user-identifiers-api.md
  static/openapi-spec/user-identifier-api.yaml
Labels: Future release, Needs language review

#7449 Proofreading - Using Version Control in Studio Pro
  content/en/docs/refguide/modeling/menus/version-control-menu/merge-dialog.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/changes-pane.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/commit-button.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/history-button.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/pull-button.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/update-button.png
Labels: Internal WIP, Internal/Peer Review

#7544 Portunus 6 4 0 release
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-global-operator.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-storage-plans.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/create-cluster.png
  static/openapi-spec/private-cloud-deploy-api.yaml
Labels: Future release

#7489 Peer Review Mendix Cloud
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/_index.md
Labels: Internal WIP, Internal/Peer Review

#7548 Add /p rewrite rule for Mendix Service Console
  content/en/docs/developerportal/deploy/on-premises-design/ms-windows/_index.md
Labels: Needs R&D technical verification, Internal WIP

#7555 Kk pmp releasenotes
  content/en/docs/releasenotes/private-platform/1.5.md
  content/en/docs/releasenotes/private-platform/1.6.md
  content/en/docs/releasenotes/private-platform/1.7.md
  content/en/docs/releasenotes/private-platform/1.8.md
  content/en/docs/releasenotes/private-platform/_index.md
Labels: Needs R&D technical verification

#7556 additional changes for oidc
  content/en/docs/appstore/modules/oidc.md
Labels: Internal WIP

#7150 Mention Mobile SSO -TW-2333
  content/en/docs/appstore/modules/oidc.md
Labels: Internal WIP

#7549 Remove outdated info about URLs
  content/en/docs/appstore/modules/deep-link.md
Labels: Needs language review

#7576 Wrote release notes for Catalog 2.117.0 release
  content/en/docs/releasenotes/catalog/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs language review

#7542 Deep Link info in the Forgot Password
  content/en/docs/appstore/modules/forgot-password.md
  static/attachments/appstore/modules/forgot-password/mendix9-10-errors.png
Labels: Future release, Internal WIP

#7579 Add shortcode and markdown example page
  content/en/docs/community-tools/contribute-to-mendix-docs/markdown-shortcodes.md
Labels: Internal WIP

#7571 Add 9.24.19 Release Notes
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: 9.24.19

#7569 Add 10.6.7 Release Notes
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: 10.6.7

#7531 Restructure OData Query Options document
  content/en/docs/appstore/modules/sap/sap-odata-connector.md
  content/en/docs/refguide/modeling/integration/odata-services/build-odata-apis.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-entity.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/supported-odata-operations.md
Labels: Internal WIP, Needs language review

#7596 Add 9.24.20 SP release notes
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Update release and/or featured date, 9.24.20

#7589 Add 8.18.29 SP Release Notes
  content/en/docs/releasenotes/studio-pro/8/8.18.md
Labels: 8.18.29

#7611 Release notes for Catalog 2.118.0 release
  content/en/docs/releasenotes/catalog/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review

#7612 Small change to Marketplace module OIDC
  content/en/docs/appstore/modules/oidc.md
Labels: Needs R&D technical verification, Needs language review

#7592 Update introduction: Discouraging Docker Buildpack for K8S.
  content/en/docs/developerportal/deploy/docker-deploy/_index.md
  static/attachments/developerportal/deploy/docker-deploy/dockerbuildpack-vs-mxoperator.png
Labels: Needs language review

#7609 Add 10.6.8 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Future release, Update release and/or featured date

#7617 OIDC - section 4.2- Anonymous user-update
  content/en/docs/appstore/modules/oidc.md
Labels: Internal WIP

#7598 Update microflow best practice for retrieve over association
  content/en/docs/refguide/modeling/community-best-practices-for-app-performance.md
Labels: Needs R&D technical verification, Internal WIP

#7289 Update docs for Java 17 (Mx 8 and Mx 9) (must be merged after release of 8.18.29, 9.24.17)
  content/en/docs/howto8/general/install.md
  content/en/docs/refguide8/general/system-requirements.md
  content/en/docs/refguide8/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
  content/en/docs/refguide8/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-week-from-datetime.md
  content/en/docs/refguide8/runtime/monitoring-mendix-runtime.md
  content/en/docs/refguide8/runtime/runtime-deployment.md
  content/en/docs/refguide9/general/install.md
  content/en/docs/refguide9/general/system-requirements.md
  content/en/docs/refguide9/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-week-from-datetime.md
  content/en/docs/refguide9/runtime/metrics.md
  content/en/docs/refguide9/runtime/monitoring-mendix-runtime.md
  content/en/docs/refguide9/runtime/runtime-deployment.md
Labels: 8.18.29

#7446 Update Combobox docs with new source type additions
  content/en/docs/appstore/widgets/combobox.md
Labels: Internal WIP, Needs language review

#7500 Add Events widget documentation
  content/en/docs/appstore/widgets/events.md
Labels: Needs language review

#7644 Release notes for Catalog 2.119.0 (25-4-24)
  content/en/docs/releasenotes/catalog/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review

#7619 Add exceptions to PDF document generation docs
  content/en/docs/appstore/modules/document-generation.md
Labels: Future release

#7655 10.10 Release Notes for External Database Connector
  content/en/docs/releasenotes/studio-pro/10/10.10.md
Labels: 10.10

#7642 Add rich-text banners
  content/en/docs/community-tools/contribute-to-mendix-docs/icon-demo.md
  content/en/docs/community-tools/contribute-to-mendix-docs/indentation-spacing-test.md
  content/en/docs/community-tools/contribute-to-mendix-docs/markdown-shortcodes.md
  content/en/docs/howto7/_index.md
  content/en/docs/howto8/_index.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/building-min.md
  content/en/docs/refguide7/_index.md
  content/en/docs/refguide8/_index.md
  layouts/partials/version-banner.html
Labels: Internal WIP

#7673 Add a release note about the cursor in the new expression editor
  content/en/docs/releasenotes/studio-pro/10/10.10.md
Labels: 10.10
