Repository mendix/docs, pull requests merged in 2024-01, with the labels that each got.

#7051 Update Mendix Cloud docs
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/access-restrictions.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/custom-domains.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/licensing-apps/migrate-free-app-to-basic.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/scale-environment.md
  content/en/docs/developerportal/operate/backups/create-backup.md
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/app-env-certificates.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/custom-domain.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/environment-details.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/generate-cert-req.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/network.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/new-certificate.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/new-custom-domain.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/pem-format.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/custom-domains/signed-certificate.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/environments/activity.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/environments/deploy-flex-environments.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/environments/reorder-environments.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/scale-environment/change-scaling.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/scale-environment/scale.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/scale-environment/scaling-example.png
  static/attachments/developerportal/deploy/mendix-cloud-deploy/scale-environment/scaling.png
Labels: Internal WIP

#7011 10.6.1 RN
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  layouts/partials/landingpage/latest-releases.html
Labels: Update release and/or featured date, 10.6.1

#6972 Notification Bars for Update flow
  content/en/docs/refguide/modeling/menus/version-control-menu/_index.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Conflicts/Interactive_Merge.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Conflicts/Merge_First.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Conflicts/Rebase_First.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Conflicts/Rebase_Mine_Change.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/DomainModel/First_Local_Commit.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/DomainModel/Remote_State.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/DomainModel/Second_Local_Commit.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/DomainModel/Starting_State.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/NotificationBars/Merge_Conclude.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/NotificationBars/Merge_Conflicts.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/NotificationBars/Rebase_Conclude.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/NotificationBars/Rebase_Conflicts.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/NotificationBars/Rebase_Continue.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Merge_End_state.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Merge_Step_1.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Merge_Step_2.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Merge_Step_3.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Merge_Step_4.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Rebase_End_state.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Rebase_Starting_state.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Rebase_Step_1.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Rebase_Step_2.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Rebase_Step_3.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Rebase_Step_4.png
  static/attachments/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm/Steps/Rebase_Step_5.png
Labels: 10.6.1

#7039 9.24.14 RN
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Update release and/or featured date

#7065 Cloud updates
  content/en/docs/developerportal/deploy/_index.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/access-restrictions.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
  content/en/docs/developerportal/general/buzz.md
  content/en/docs/developerportal/general/documents.md
  content/en/docs/developerportal/general/team/_index.md
  content/en/docs/developerportal/operate/backups/restore-backup-locally.md
  content/en/docs/developerportal/operate/logs.md
  static/attachments/developerportal/operate/logs/activity-log.png
Labels: Internal WIP

#7085 Override Swagger's scroll
  layouts/swagger/baseof.html
Labels: Internal WIP

#7077 Kk pc global operator
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-cli-non-interactive.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-global-operator.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-migrating.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-standard-operator.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-storage-plans.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-operator.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-technical-appendix/private-cloud-technical-appendix-02.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-upgrade-guide.md
  content/en/docs/private-platform/configuration/_index.md
  content/en/docs/private-platform/configuration/pmp-configure-k8s.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/developerportal/deploy/private-cloud/global-operator/global-operator1.png
  static/attachments/developerportal/deploy/private-cloud/global-operator/global-operator2.png
  static/attachments/developerportal/deploy/private-cloud/global-operator/global-operator3.png
  static/attachments/developerportal/deploy/private-cloud/global-operator/global-operator4.png
  static/attachments/developerportal/deploy/private-cloud/global-operator/global-operator5.png
  static/attachments/developerportal/deploy/private-cloud/global-operator/global-operator6.png
  static/attachments/developerportal/deploy/private-cloud/global-operator/global-operator7.png
  static/attachments/developerportal/deploy/private-cloud/global-operator/global-operator8.png
  static/attachments/developerportal/deploy/private-cloud/global-operator/global-operator9.png
Labels: Future release

#7087 Private cloud portal 6 0 0 release
  content/en/docs/apidocs-mxsdk/apidocs/private-cloud-build-api.md
  content/en/docs/apidocs-mxsdk/apidocs/private-cloud-deploy-api.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-cli-non-interactive.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-registry.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-deploy.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
  content/en/docs/developerportal/deploy/private-cloud/private-cloud-velero.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/developerportal/deploy/private-cloud/private-cloud-cluster/Customization.png
Labels: Future release, Needs language review

#7124 Create Support Guide
  content/en/docs/appstore/modules/mendix-sso.md
  content/en/docs/appstore/sharing-content/governance-process.md
  content/en/docs/community-tools/_index.md
  content/en/docs/control-center/cloud.md
  content/en/docs/control-center/company-settings.md
  content/en/docs/control-center/deployed-apps.md
  content/en/docs/developerportal/deploy/general/licensing-apps-outside-mxcloud.md
  content/en/docs/developerportal/deploy/mendix-cloud-deploy/migrating-to-different-cloud.md
  content/en/docs/developerportal/global-navigation.md
  content/en/docs/developerportal/operate/monitoring-application-health/_index.md
  content/en/docs/howto7/collaboration-requirements-management/troubleshoot-version-control-issues.md
  content/en/docs/howto8/collaboration-requirements-management/troubleshoot-version-control-issues.md
  content/en/docs/howto8/mobile/native-mobile/build-native-apps/use-cli-docs/deploying-native-app-cli.md
  content/en/docs/private-platform/_index.md
  content/en/docs/refguide9/general/moving-from-8-to-9/_index.md
  content/en/docs/refguide9/version-control/version-control-troubleshooting/_index.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  content/en/docs/releasenotes/studio-pro/7/7.23.md
  content/en/docs/releasenotes/studio-pro/lts-mts.md
  content/en/docs/support/_MAPPING.txt
  content/en/docs/support/_index.md
  content/en/docs/support/escalation-management-process.md
  content/en/docs/support/new-app-node-request-template.md
  content/en/docs/support/prepare-your-app.md
  content/en/docs/support/security-findings-faq.md
  content/en/docs/support/submit-support-request.md
  content/en/docs/support/ticket-priority.md
  static/attachments/support/escalation-management-process/escalation.png
  static/attachments/support/escalation-management-process/escalation_process_overview.png
  static/attachments/support/escalation-management-process/zendesk.png
  static/attachments/support/legend.png
  static/attachments/support/mendix-cloud.png
  static/attachments/support/on-premises.png
  static/attachments/support/private-cloud.png
  static/attachments/support/sap-cloud-platform.png
  static/attachments/support/submit-support-request/204371729-pic5.png
  static/attachments/support/submit-support-request/activities.png
  static/attachments/support/submit-support-request/follow.png
  static/attachments/support/submit-support-request/issue.png
  static/attachments/support/submit-support-request/recommendations.png
  static/attachments/support/submit-support-request/request.png
  static/attachments/support/tencent.png
Labels: Internal WIP

#7113 Use percentage for the images' width on the activities index page
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/action-call-activities/java-action-call.md
Labels: Internal WIP

#7122 CSS KI
  content/en/docs/refguide9/version-control/using-version-control-in-studio-pro/_index.md
  content/en/docs/releasenotes/studio-pro/10/10.0.md
  content/en/docs/releasenotes/studio-pro/10/10.1.md
  content/en/docs/releasenotes/studio-pro/10/10.2.md
  content/en/docs/releasenotes/studio-pro/10/10.3.md
  content/en/docs/releasenotes/studio-pro/10/10.4.md
  content/en/docs/releasenotes/studio-pro/10/10.5.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Internal WIP

#7121 Added troublehsooting for merge issues and line-endings in css files
  content/en/docs/refguide/version-control/version-control-troubleshooting/_index.md
  content/en/docs/refguide9/version-control/version-control-troubleshooting/troubleshoot-git-issues.md
Labels: Needs language review

#7105 10.6.2 RN
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  layouts/partials/landingpage/latest-releases.html
Labels: Update release and/or featured date

#7125 disambiguation for PC vs PMP API
  content/en/docs/apidocs-mxsdk/apidocs/private-cloud-build-api.md
  content/en/docs/apidocs-mxsdk/apidocs/private-cloud-deploy-api.md
  content/en/docs/apidocs-mxsdk/apidocs/private-platform/_index.md
  content/en/docs/apidocs-mxsdk/apidocs/private-platform/group-api.md
  content/en/docs/apidocs-mxsdk/apidocs/private-platform/marketplace-api.md
  content/en/docs/apidocs-mxsdk/apidocs/private-platform/project-api.md
  content/en/docs/apidocs-mxsdk/apidocs/private-platform/user-api.md
Labels: Internal WIP

#7119 Add retention schedule
  content/en/docs/developerportal/operate/logs.md
Labels: Needs language review

#7110 IdPs included in the OIDC SSO
  content/en/docs/appstore/modules/oidc.md
Labels: Internal WIP

#7148 10.7.0 External Database Connector Release Notes
  content/en/docs/releasenotes/studio-pro/10/10.7.md
Labels: 10.7

#7156 10.7 RN review
  content/en/docs/releasenotes/studio-pro/10/10.7.md
Labels: Internal WIP, 10.7

#7152 Portfolio Management Release January 25
  content/en/docs/control-center/portfolios.md
  content/en/docs/developerportal/portfolio-management/_index.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/developerportal/portfolio-management/portfolio-landscape-overview.png
Labels: Needs language review

#7134 updated the epics api specs yaml file
  static/openapi-spec/epics.yaml
Labels: Future release

#7160 Embeddings
  content/en/docs/appstore/connectors/openai-connector.md
Labels: Needs language review

#7182 Bedrock 2.1.0
  content/en/docs/appstore/connectors/aws/amazon-bedrock.md
Labels: Changes requested

#7141 10.7.0 RN
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/10/10.7.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.7

#7146 MendixChat Updates
  content/en/docs/refguide/modeling/mx-assist-studio-pro/mendix-chat.md
  static/attachments/refguide/modeling/mx-assist-studio-pro/mendix-chat/mendix-chat-example.png
Labels: 10.7

#7055 [WTF-1633] Make selection api public [10.7.0]
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types/selection.png
Labels: 10.7

#7041 [WTF-809] Add documentation on data view conditional editability [10.7.0]
  content/en/docs/refguide/modeling/pages/common-widget-properties.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-view.md
Labels: 10.7

#7166 Update data-importer-extension for CSV import
  content/en/docs/appstore/modules/data-importer-extension.md
  static/attachments/appstore/modules/data-importer-extension/preview-csv-data-and-entity.png
  static/attachments/appstore/modules/data-importer-extension/source-csv-data.png
Labels: 10.7

#7043 Host OData service on any path
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/_index.md
Labels: 10.7

#7054 Add PATCH method to the docs
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services-beta.md
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/accept-header.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/header-example.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/header.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/json-example.png
  static/attachments/refguide/modeling/integration/consumed-rest-services-beta/json-sample.png
Labels: 10.7

#7137 Add parameter support to header value in Consumed REST service
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services-beta.md
Labels: 10.7

#7139 Update system-requirements.md
  content/en/docs/refguide/_index.md
  content/en/docs/refguide/installation/install.md
  content/en/docs/refguide/installation/system-requirements.md
  content/en/docs/refguide/installation/using-mendix-studio-pro-on-a-mac.md
Labels: Needs language review, 10.7

#7185 Add limitation for React client beta
  content/en/docs/appstore/modules/document-generation.md
Labels: Needs language review, 10.7

#7191 Update Sub-Microflow screenshot
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extract-and-use-sub-microflows.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extracting-and-using-sub-microflows/submicroflow-in-parent-microflow.png
Labels: Internal WIP

#7174 Add new Integration activities to Application Logic
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/send-rest-request.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services-beta.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/increment-counter.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/lock-workflow.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/query-external-database.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/send-rest-request.png
Labels: Internal WIP

#7210 Kk pmp relnotes
  content/en/docs/releasenotes/private-platform/1/1.5.md
  content/en/docs/releasenotes/private-platform/1/1.6.md
  content/en/docs/releasenotes/private-platform/1/_index.md
  content/en/docs/releasenotes/private-platform/_index.md
Labels: Needs R&D technical verification
