Repository mendix/docs, pull requests merged in 2024-08, with the labels that each got.

#8086 [RUN-4165] Add documentation for the mx show-java-version command
  content/en/docs/refguide/general/mx-command-line-tool/_index.md
  content/en/docs/refguide/general/mx-command-line-tool/app.md
Labels: Needs language review, 10.14, 10.12.2

#8119 Document a KI fix
  content/en/docs/releasenotes/studio-pro/10/10.11.md
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.13.md
Labels: 10.13

#8142 Access Provider template updates
  content/en/docs/appstore/use-content/services/oidc-provider.md
Labels: Needs R&D technical verification

#8127 Added information on session deletion
  content/en/docs/refguide/runtime/session-management.md
Labels: Needs language review

#8118 Add 10.13.1 Release Notes
  content/en/docs/releasenotes/studio-pro/10/10.13.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.13.1

#8141 OData: nested parameters and results
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/call-external-action.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-entity.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-microflow.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/supported-odata-operations.md
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/call-external-action/edit-parameter-mapping.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/call-external-action/general.png
Labels: Needs language review

#8126 Update implement-sso-on-a-hybrid-app-with-mendix-and-saml.md
  content/en/docs/howto8/mobile/hybrid-mobile/implement-sso-on-a-hybrid-app-with-mendix-and-saml.md
Labels: Needs language review

#8155 Add 9.24.26 release notes
  content/en/docs/refguide/runtime/metrics.md
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.13.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Update release and/or featured date, 9.24.26

#7843 Disable on-click link to images and open images as pop-ups
  assets/scss/_styles_project.scss
  layouts/partials/hooks/body-end.html
  layouts/shortcodes/figure.html
  static/js/medium-zoom.js
Labels: Internal WIP

#8161 Update email-connector.md
  content/en/docs/appstore/use-content/modules/email-connector.md
Labels: Needs language review

#8143 [RUN-4169] Update documentation for PerformDeleteFromStorage runtime setting
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: Internal WIP, Needs language review

#8166 Upload 7.23.38 RNs
  content/en/docs/releasenotes/studio-pro/7/7.23.md
Labels: Update release and/or featured date, 7.23.38

#8162 10.12.3 RNs
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: Update release and/or featured date, 10.12.3

#8176 Dataloader redirect url
  content/en/docs/appstore/use-content/modules/snowflake/mendix-data-loader.md
Labels: Needs language review

#8173 Troubleshooting and Microflow URL updates
  content/en/docs/appstore/use-content/modules/oidc.md
  static/attachments/appstore/use-content/modules/oidc/runtime-failed.png
Labels: Needs R&D technical verification

#8164 10.6.12 RNs
  content/en/docs/refguide/general/mx-command-line-tool/app.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: 10.6.12

#8196 Update certificates.md
  content/en/docs/deployment/mendix-cloud-deploy/certificates.md
Labels: Needs language review

#8202 Update teamcenter-extension.md
  content/en/docs/appstore/use-content/modules/teamcenter-extension.md
Labels: Needs language review

#8204 Update database versions in system requirements
  content/en/docs/refguide/installation/system-requirements.md
Labels: Needs language review

#8186 [SOLP-2681] Add info about PAT storing solutions
  content/en/docs/refguide/version-control/on-premises-git.md
Labels: Needs language review

#8220 Sprintr release 2024.08.25
  content/en/docs/developerportal/general/buzz.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/developerportal/general/buzz/app-buzz.png
Labels: Future release, Needs language review

#8216 Added warning for commandline clones
  content/en/docs/developerportal/general/team-server/_index.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  content/en/docs/refguide9/version-control/using-version-control-in-studio-pro/_index.md
Labels: Needs language review

#8224 Format OQL as SQL without line numbers
  content/en/docs/appstore/use-content/modules/snowflake/snowflake-rest-sql.md
  content/en/docs/refguide/modeling/domain-model/entities/indexes.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-subqueries.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-limit-clause.md
  content/en/docs/refguide8/modeling/domain-model/entities/indexes.md
  content/en/docs/refguide8/modeling/resources/data-sets/_index.md
  content/en/docs/refguide8/modeling/resources/data-sets/oql/oql-from-clause.md
  content/en/docs/refguide8/modeling/resources/data-sets/oql/oql-group-by-clause.md
  content/en/docs/refguide8/modeling/resources/data-sets/oql/oql-limit-clause.md
  content/en/docs/refguide8/modeling/resources/data-sets/oql/oql-order-by-clause.md
  content/en/docs/refguide8/modeling/resources/data-sets/oql/oql-select-clause.md
  content/en/docs/refguide8/modeling/resources/data-sets/oql/oql-where-clause.md
  content/en/docs/refguide9/modeling/domain-model/entities/indexes.md
  content/en/docs/refguide9/modeling/resources/data-sets/_index.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-coalesce.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-datediff.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-datepart.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-length.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-lower.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-rangebegin.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-rangeend.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-replace.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-round.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-upper.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-operators/oql-case-expression.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-parameters.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-from-clause.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-group-by-clause.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-limit-clause.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-order-by-clause.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-select-clause.md
  content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-where-clause.md
Labels: Internal WIP

#8200 Add 10.14 Release Notes
  content/en/docs/refguide/general/mx-command-line-tool/app.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/user-task.md
  content/en/docs/releasenotes/studio-pro/10/10.14.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.14

#8211 Update App from Spreadsheet
  content/en/docs/refguide/modeling/app-from-spreadsheet.md
  static/attachments/refguide/modeling/app-from-spreadsheet/attribute-type-drop-down.jpg
  static/attachments/refguide/modeling/app-from-spreadsheet/data-preview.jpg
  static/attachments/refguide/modeling/app-from-spreadsheet/drag-and-drop.jpg
  static/attachments/refguide/modeling/app-from-spreadsheet/manage-relations.jpg
Labels: 10.14

#8218 Publish GraphQL
  content/en/docs/refguide/modeling/app-explorer/modules/_index.md
  content/en/docs/refguide/modeling/import-and-export/_index.md
  content/en/docs/refguide/modeling/integration/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/graphql-representation.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/odata-representation.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-attribute.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-entity.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/published-odata-microflow.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/supported-graphql-operations.md
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/supported-odata-operations.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/security/module-security.md
  content/en/docs/refguide/runtime/_index.md
  content/en/docs/refguide/runtime/logging.md
  content/en/docs/refguide/runtime/metrics.md
  static/attachments/refguide/modeling/integration/published-odata-attribute/edit-published-attribute.png
  static/attachments/refguide/modeling/security/module-security/odata-access-tab.png
Labels: 10.14

#8235 Update tab container docs
  content/en/docs/refguide/modeling/pages/structure-widgets/tab-container.md
Labels: 10.14

#8021 [WTF-1862] Handle expression variables with long paths in the linked action property
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
Labels: 10.14

#8232 Update sap-cloud-platform.md
  content/en/docs/releasenotes/deployment/sap-cloud-platform.md
Labels: Needs language review

#8215 Documentation update for using Translation Generator in the new system texts editor
  content/en/docs/refguide/modeling/app-explorer/app/system-texts.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/translation-generator.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/menus/translatable-texts/_index.md
  static/attachments/refguide/modeling/mendix-ai-assistance/translation-generator/batch-translate.png
  static/attachments/refguide/modeling/mendix-ai-assistance/translation-generator/translate-system-text.png
Labels: 10.14

#8229 Release documentation for metamodel & Model SDK 10.14.0
  content/en/docs/releasenotes/sdk/metamodel/metamodel-10/metamodel-10.14.md
  content/en/docs/releasenotes/sdk/model-sdk/model-sdk-4.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review, 10.14

#8121 Update release-notes.md
  content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/release-notes.md
Labels: Needs language review, 10.14

#8234 Add 10.12.4 SP Release Notes
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: 10.12.4

#8240 Relocate SCIM images
  content/en/docs/.vscode/spellright.dict
  content/en/docs/appstore/use-content/modules/scim.md
  static/attachments/appstore/use-content/modules/scim/alias.png
  static/attachments/appstore/use-content/modules/scim/provisioning_revised.png
  static/attachments/appstore/use-content/modules/scim/user_commons.png
  static/attachments/appstore/use-content/modules/scim/user_roles.png
  static/attachments/appstore/use-content/modules/scim/users_and_groups.png
Labels: Internal WIP

#8243 Release notes for Catalog 2.131.0
  content/en/docs/releasenotes/catalog/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release, Needs language review

#8253 Custom microflow information update
  content/en/docs/appstore/use-content/modules/oidc.md
  content/en/docs/appstore/use-content/modules/scim.md
Labels: Needs R&D technical verification

#8205 Update the procedure about how to edit a doc
  content/en/docs/community-tools/contribute-to-mendix-docs/_index.md
  static/attachments/community-tools/contribute-to-mendix-docs/base-development.png
  static/attachments/community-tools/contribute-to-mendix-docs/file-in-editor.png
  static/attachments/community-tools/contribute-to-mendix-docs/fork-this-repository.png
  static/attachments/community-tools/contribute-to-mendix-docs/propose-changes.png
  static/attachments/community-tools/contribute-to-mendix-docs/server-set-up.png
  static/attachments/community-tools/contribute-to-mendix-docs/table-of-built-pages.png
Labels: Internal WIP
