Repository mendix/docs, pull requests merged in 2024-09, with the labels that each got.

#8245 Changed partial clone from public beta to GA, including release note
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/clone-type.md
  content/en/docs/releasenotes/studio-pro/10/10.14.md
Labels: Needs language review

#8261 PMP release notes
  content/en/docs/releasenotes/private-platform/1.13.md
  content/en/docs/releasenotes/private-platform/_index.md
Labels: Needs R&D technical verification

#8266 Add 8.18.31 SP Release Notes
  content/en/docs/releasenotes/studio-pro/8/8.18.md
Labels: Update release and/or featured date

#8267 Add 9.24.27 SP Release Notes
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Future release, Update release and/or featured date

#8290 Add links to Domain Model Generator
  content/en/docs/refguide/modeling/domain-model/_index.md
  content/en/docs/refguide/modeling/domain-model/create-a-basic-data-layer.md
Labels: Needs R&D technical verification, Internal WIP

#8292 Updated Git migration limits
  content/en/docs/developerportal/general/team-server/migrate-to-git.md
Labels: Needs language review

#8310 Proofread Mendix Best Practices for Development
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/extract-and-use-sub-microflows.md
  content/en/docs/refguide/modeling/dev-best-practices.md
Labels: Internal WIP

#8319 Add backups to archiving
  content/en/docs/deployment/mendix-cloud-deploy/_index.md
Labels: Needs language review

#8278 Updated the java 17/21 support with operator 2.15.0 and above
  content/en/docs/deployment/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/deployment/private-cloud/private-cloud-deploy.md
Labels: Needs language review

#8306 Bedrockshowcasedeprecation
  content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
Labels: Awaiting response

#8284 Review Expressions docs
  content/en/docs/appstore/creating-content/sol-solutions-guide/sol-adapt/sol-adaptability.md
  content/en/docs/refguide/java-programming/java-version-migration.md
  content/en/docs/refguide/modeling/application-logic/expressions/_index.md
  content/en/docs/refguide/modeling/application-logic/expressions/add-date-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/arithmetic-expressions.md
  content/en/docs/refguide/modeling/application-logic/expressions/begin-of-date-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/between-date-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/boolean-expressions.md
  content/en/docs/refguide/modeling/application-logic/expressions/date-creation.md
  content/en/docs/refguide/modeling/application-logic/expressions/end-of-date-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/enumerations-in-expressions.md
  content/en/docs/refguide/modeling/application-logic/expressions/mathematical-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-decimal-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/relational-expressions.md
  content/en/docs/refguide/modeling/application-logic/expressions/special-checks.md
  content/en/docs/refguide/modeling/application-logic/expressions/string-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/subtract-date-function-calls.md
  content/en/docs/refguide/modeling/application-logic/expressions/trim-to-date.md
  content/en/docs/refguide/modeling/application-logic/expressions/unary-expressions.md
Labels: Internal WIP

#8317 Add 10.6.14 SP RN and review
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Future release, Update release and/or featured date

#8316 Add 10.12.5 SP RN
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: Future release, Update release and/or featured date

#8280 Control Center: no need to deactivate BYOIDP
  content/en/docs/control-center/company-settings.md
Labels: Needs R&D technical verification

#8336 Mobile SSO-2.1.0 updates
  content/en/docs/appstore/use-content/modules/mobile-sso.md
Labels: Needs R&D technical verification

#8339 SAML: page and microflow URL update
  content/en/docs/appstore/use-content/modules/saml.md
Labels: Needs R&D technical verification

#8343 Update UserInfoParameter
  content/en/docs/appstore/use-content/modules/oidc.md
  content/en/docs/appstore/use-content/modules/scim.md
Labels: Internal WIP

#8314 Add Pipelines API doc
  content/en/docs/apidocs-mxsdk/apidocs/pipeline-api.md
  content/en/docs/releasenotes/deployment/mendix-cloud.md
  static/openapi-spec/pipelines.yaml
Labels: Future release

#8332 Updated Mendix Feedback
  content/en/docs/appstore/use-content/modules/mendix-feedback.md
  static/attachments/appstore/use-content/modules/mendix-feedback/Feedback_SendToServer.png
Labels: Needs language review

#8342 Update Database replication documentation, fix custom(er) constraint
  content/en/docs/appstore/use-content/modules/database-replication.md
Labels: Needs language review

#8347 docs(environment-details): add info about maintenance task exit states
  content/en/docs/deployment/mendix-cloud-deploy/environments-details.md
Labels: Needs language review, Awaiting response

#8353 Token monitor (new minor feature)
  content/en/docs/appstore/use-content/modules/genai/conversational-ui.md
  content/en/docs/appstore/use-content/modules/genai/genai-commons.md
Labels: Needs language review

#8294 [RUN-3490] Add explanation of user role and session behaviour
  content/en/docs/refguide/modeling/security/app-security/user-roles.md
  content/en/docs/refguide/runtime/clustered-mendix-runtime.md
Labels: Needs language review

#8268 Updated the Git version 2.43 which we install with 10.6.10+ MTS
  content/en/docs/refguide/installation/install.md
Labels: Needs language review

#8327 Add 10.15 SP release notes
  content/en/docs/releasenotes/studio-pro/10/10.15.md
  layouts/partials/landingpage/latest-releases.html
Labels: 10.15

#8359 Release documentation for metamodel & Model SDK 10.15.0
  content/en/docs/releasenotes/sdk/metamodel/metamodel-10/metamodel-10.15.md
  content/en/docs/releasenotes/sdk/model-sdk/model-sdk-4.md
Labels: 10.15

#8276 Prepare for release of x-ray mode
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/pages/page/_index.md
  static/attachments/refguide/modeling/pages/page/design-mode-no-x-ray.png
  static/attachments/refguide/modeling/pages/page/design-mode-x-ray.png
Labels: 10.15

#8273 [WTF-1935] Allow default values for client actions
  content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
Labels: 10.15

#8260 Using expressions for conditional visibility and dynamic classes
  content/en/docs/refguide/modeling/pages/common-widget-properties.md
Labels: 10.15

#8291 [CTRL-2950] Create the ability to profile memory from within SP
  content/en/docs/refguide/modeling/menus/help-menu/profiling.md
  static/attachments/refguide/modeling/menus/help-menu/profiling/profiling-menu.png
Labels: 10.15

#8271 Update MxBuild documentation for Mendix 10.15
  content/en/docs/refguide/general/mxbuild.md
Labels: 10.15

#8187 [SOLP-2592] Adding info about version control dump
  content/en/docs/refguide/modeling/menus/help-menu/_index.md
Labels: 10.15

#8330 Keyboard support of "Ctrl/Command + Mouse scroll wheel" in the workflow editor
  content/en/docs/refguide/general/studio-pro-overview/keyboard-shortcuts.md
Labels: 10.15

#8257 [APPEXT-563] Add the untyped model api docs
  content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/_index.md
  content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/extensibility-api-howtos/untyped-model-api.md
  content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/release-notes.md
Labels: 10.15

#8365 OIDC SSO: Mention 'online' for PWA
  content/en/docs/appstore/use-content/modules/oidc.md
Labels: Internal WIP

#8364 OIDC SSO: Default attribute mapping
  content/en/docs/appstore/use-content/modules/oidc.md
  static/attachments/appstore/use-content/modules/oidc/default_mapping.png
Labels: Internal WIP

#8344 Update log nodes and logging documentation
  content/en/docs/howto/monitoring-troubleshooting/log-levels.md
  content/en/docs/howto9/monitoring-troubleshooting/log-levels.md
  content/en/docs/refguide/runtime/logging.md
  content/en/docs/refguide9/runtime/logging.md
Labels: Needs language review

#8367 Revert "OIDC SSO: Mention 'online' for PWA"
  content/en/docs/appstore/use-content/modules/oidc.md
Labels: Internal WIP

#8368 Link from GenAI to Machine Learning
  content/en/docs/appstore/use-content/modules/genai/_index.md
Labels: Needs R&D technical verification

#8360 Add Project API and BYOIDP references.
  content/en/docs/apidocs-mxsdk/apidocs/user-management-api.md
Labels: Internal WIP

#8371 [APPEXT-839] Update release notes for 10.15.0
  content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/release-notes.md
Labels: Needs language review, 10.15

#8376 Caatalog release 2.133.0
  content/en/docs/releasenotes/catalog/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#8329 He pmt release 1.26
  content/en/docs/developerportal/portfolio-management/archive.md
  content/en/docs/developerportal/portfolio-management/export-import-initiatives.md
  content/en/docs/developerportal/portfolio-management/initiatives-overview/_index.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/developerportal/portfolio-management/archived-initiatives.png
  static/attachments/developerportal/portfolio-management/initiatives-overview.png
  static/attachments/developerportal/portfolio-management/list-view.png
  static/attachments/developerportal/portfolio-management/planning-view.png
Labels: Future release

#8045 OIDC Provider- Introduction and Use Cases
  content/en/docs/appstore/use-content/services/oidc-provider.md
  static/attachments/appstore/use-content/services/oidc-provider/API_consumption.png
  static/attachments/appstore/use-content/services/oidc-provider/SSO_within_multiapp.png
  static/attachments/appstore/use-content/services/oidc-provider/brokering.png
Labels: Internal WIP

#8375 Terminology consistency check - use "persistable/non-persistable" for entity/entities/object(s)
  content/en/docs/appstore/use-content/modules/deep-link.md
  content/en/docs/appstore/use-content/modules/excel-exporter.md
  content/en/docs/appstore/use-content/modules/excel-importer.md
  content/en/docs/appstore/use-content/modules/snowflake/snowflake-edc.md
  content/en/docs/appstore/use-content/services/business-events.md
  content/en/docs/catalog/register/register-non-odata-resources.md
  content/en/docs/deployment/private-cloud/private-cloud-cluster/private-cloud-storage-plans.md
  content/en/docs/refguide/mobile/best-practices/batch-synchronization.md
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/local-data-security.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/authenticating-users.md
  content/en/docs/refguide/modeling/application-logic/workflows/jump-to.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
  content/en/docs/refguide/modeling/integration/odata-services/build-odata-apis.md
  content/en/docs/refguide/modeling/resources/task-queue.md
  content/en/docs/refguide9/mobile/building-efficient-mobile-apps/offlinefirst-data/local-data-security.md
  content/en/docs/refguide9/modeling/application-logic/workflows/_index.md
  content/en/docs/refguide9/modeling/application-logic/workflows/jump-to.md
  content/en/docs/refguide9/modeling/integration/odata-services/wrap-services-odata.md
  content/en/docs/refguide9/modeling/resources/task-queue.md
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: Internal WIP

#8382 Add 10.6.15 RNs
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: 10.6.15

#8377 Update implement-sso-on-a-hybrid-app-with-mendix-and-saml.md
  content/en/docs/howto8/mobile/hybrid-mobile/implement-sso-on-a-hybrid-app-with-mendix-and-saml.md
Labels: Needs language review

#8369 Add 10.12.6 RNs
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: 10.12.6

#8378 Proofread Workflow docs
  content/en/docs/refguide/general/studio-pro-overview/keyboard-shortcuts.md
  content/en/docs/refguide/modeling/application-logic/workflows/_index.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/_index.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/call-microflow.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/call-workflow.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/decision-in-workflows.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/jump-activity.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/parallel-split.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/timer.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/wait-for-notification.md
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/workflow-parameters.md
  content/en/docs/refguide9/modeling/application-logic/workflows/workflow-elements/call-microflow.md
  content/en/docs/refguide9/modeling/application-logic/workflows/workflow-elements/call-workflow.md
  content/en/docs/refguide9/modeling/application-logic/workflows/workflow-elements/decision-in-workflows.md
  content/en/docs/refguide9/modeling/application-logic/workflows/workflow-elements/jump-activity.md
  content/en/docs/refguide9/modeling/application-logic/workflows/workflow-elements/parallel-split.md
  static/attachments/refguide/modeling/application-logic/workflows/workflow-elements/workflow-context.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-elements/workflow-parameters/workflow-parameter.png
  static/attachments/refguide/modeling/application-logic/workflows/workflow-elements/workflow-parameters/workflow-parameters.png
Labels: Internal WIP
