Repository mendix/docs, pull requests merged in 2025-05, with the labels that each got.

#9440 Add Studio Pro version and Story service
  static/openapi-spec/projects-v2.yaml
Labels: Future release

#9460 Remove old Mendix 10 references
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro/runtime-api.md
  content/en/docs/apidocs-mxsdk/mxsdk/sdk-refguide/understanding-the-metamodel/pages-metamodel.md
  content/en/docs/refguide/modeling/domain-model/associations/association-storage.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-sources/_index.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-sources/database-source.md
  content/en/docs/refguide/modeling/pages/data-widgets/data-sources/xpath-source.md
  content/en/docs/refguide/modeling/pages/data-widgets/grids/control-bar.md
  content/en/docs/refguide/modeling/xpath/xpath-constraints/_index.md
  content/en/docs/refguide/runtime/session-management.md
Labels: 11.0.0 beta 1

#9319 [RUN-3523] Remove ObjectManagement.StrictChangeBehavior runtime setting
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: 11.0.0 beta 1

#9450 Update how-to-set-up-your-partner-profile.md
  content/en/docs/community-tools/how-to-set-up-your-partner-profile.md
Labels: Needs R&D technical verification, Needs language review

#9436 10.22 Studio Pro release notes
  content/en/docs/refguide/modeling/domain-model/generalization-and-association.md
  content/en/docs/refguide8/modeling/domain-model/generalization-and-association.md
  content/en/docs/refguide9/modeling/domain-model/generalization-and-association.md
  content/en/docs/releasenotes/studio-pro/10/10.22.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review, Update release and/or featured date, Release Notes, 10.22

#9273 [BUX-1101] Rename Maia sessions
  content/en/docs/refguide/modeling/domain-model/_index.md
  content/en/docs/refguide/modeling/domain-model/create-a-basic-data-layer.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/domain-model-generator.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/logic-recommender.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-for-domain-model.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-for-pages.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/page-generator.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/pages/page/_index.md
  static/attachments/refguide/modeling/mendix-ai-assistance/domain-model-generator/chat-interface.png
  static/attachments/refguide/modeling/mendix-ai-assistance/domain-model-generator/domain-model-generator.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-recommender/assist-bulb.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-recommender/initial-recommendations.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-recommender/mendix-assist-icon.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-recommender/mx-assist-on-off-button.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-recommender/mx-assist-recommendations.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-recommender/mx-assist-system-variables.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-recommender/search-sub-actions.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-recommender/search-sub-flows.png
  static/attachments/refguide/modeling/mendix-ai-assistance/logic-recommender/search-toolbox.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-for-domain-model/chat-interface.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-for-domain-model/maia-for-domain-model.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-for-pages/chat-interface.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-for-pages/maia-for-pages.png
  static/attachments/refguide/modeling/mendix-ai-assistance/page-generator/page-generator.png
Labels: 10.22

#9390 Update documentation for the re-implemented missing keyboard functionality
  content/en/docs/refguide/general/studio-pro-overview/keyboard-shortcuts.md
Labels: 10.22

#9399 [SOLP-3259] Update history-dialog Mx 10
  content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
Labels: Needs language review, 10.22

#9491 Remove Max Retrieve Size runtime setting REDO
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/releasenotes/mobile/native-template/_index.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/_index.md
Labels: 10.22

#9351 XPath constraints for page variables
  content/en/docs/refguide/modeling/pages/page/page-properties.md
Labels: 10.22

#9381 Add new help menu option (Contact Support)
  content/en/docs/refguide/modeling/menus/help-menu/_index.md
Labels: 10.22

#9327 Change the location of the Navigation settings after [CTRL-3192]
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
Labels: 10.22

#9284 Add show and delete private values to mx tool
  content/en/docs/refguide/general/mx-command-line-tool/_index.md
  content/en/docs/refguide/general/mx-command-line-tool/private-values.md
Labels: 10.22

#9260 [CTRL-3213] Release the Microsoft Defender whitelist feature
  content/en/docs/refguide/installation/performance-tips.md
  content/en/docs/refguide/modeling/app-performance/antivirus-exclusion.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  static/attachments/refguide/modeling/app-performance/exclude-folder.png
Labels: 10.22

#9396 LDAP Updates
  content/en/docs/appstore/use-content/platform-supported-content/modules/ldap.md
Labels: Future release

#9422 Duplicate PR #9390 in Mendix-11 branch - Re-implemented missing keyboard functionality
  content/en/docs/refguide10/general/studio-pro-overview/keyboard-shortcuts.md
Labels: 11.0.0 beta 1, Has 10.22 duplicate

#9400 Add show and delete private values Mx11
  content/en/docs/refguide/general/mx-command-line-tool/_index.md
  content/en/docs/refguide10/general/mx-command-line-tool/_index.md
  content/en/docs/refguide10/general/mx-command-line-tool/private-values.md
Labels: 11.0.0 beta 1, Has 10.22 duplicate

#9493 Adjust Maia docs for 11 beta 1 and remove Mx 10 instances
  content/en/docs/refguide/modeling/application-logic/workflows/workflow-setting-up-app.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/best-practice-recommender/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/logic-recommender.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-for-domain-model.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-for-oql.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-for-pages.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-learn.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide10/modeling/mendix-ai-assistance/maia-for-domain-model.md
  content/en/docs/refguide10/modeling/mendix-ai-assistance/maia-for-pages.md
Labels: 11.0.0 beta 1

#9382 Add new help menu option (Contact Support)
  content/en/docs/refguide10/modeling/menus/help-menu/_index.md
Labels: 11.0.0 beta 1, Has 10.22 duplicate

#9392 [SOLP-2255] Mendix-11 Rename port fix to Cherry-pick
  content/en/docs/refguide/modeling/menus/version-control-menu/merge-dialog.md
Labels: Needs language review, 11.0.0 beta 1, Has 10.22 duplicate

#9379 Update table with date format tokens (Mx 11)
  content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
  content/en/docs/refguide/modeling/menus/translatable-texts/language-settings.md
Labels: 11.0.0 beta 1

#9278 [CTRL-3213] Release the Microsoft Defender whitelist feature to v11
  content/en/docs/refguide10/installation/performance-tips.md
  content/en/docs/refguide10/modeling/app-performance/antivirus-exclusion.md
  content/en/docs/refguide10/modeling/menus/edit-menu/preferences-dialog.md
Labels: 11.0.0 beta 1, Has 10.22 duplicate

#9494 Added PAT explanation for Mendix platform
  content/en/docs/refguide/version-control/on-premises-git.md
Labels: Needs language review

#9407 Added documentation for network timeout settings
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/_index.md
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/network-request-timeout.md
Labels: Needs language review, 11.0.0 beta 1

#9331 Correct System.SynchronizationFailure to System.SynchronizationError
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/synchronize.md
  content/en/docs/refguide10/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/synchronize.md
  content/en/docs/refguide8/modeling/application-logic/activities/client-activities/synchronize.md
  content/en/docs/refguide9/modeling/application-logic/microflows-and-nanoflows/activities/client-activities/synchronize.md
Labels: 11.0.0 beta 1

#9464 Delete deprecated Augmented Reality doc
  content/en/docs/refguide/mobile/using-mobile-capabilities/augmented-reality/_index.md
  content/en/docs/refguide/mobile/using-mobile-capabilities/augmented-reality/how-to-ar-simple-cube.md
Labels: 11.0.0 beta 1

#9479 SOLP-3302 removing git-merge command from refguide
  content/en/docs/refguide10/general/mx-command-line-tool/_index.md
  content/en/docs/refguide10/general/mx-command-line-tool/merge.md
Labels: 11.0.0 beta 1, Has 10.22 duplicate

#9403 Add documentation and sample for the notifications api
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro-10/extensibility-api/web/_index.md
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro-11/extensibility-api/web/_index.md
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro-11/extensibility-api/web/get-started.md
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro-11/extensibility-api/web/web-extensions-howtos/dialog-api.md
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro-11/extensibility-api/web/web-extensions-howtos/notification-api.md
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro-11/extensibility-api/web/web-extensions-howtos/preference-api.md
  content/en/docs/deployment/mendix-cloud-deploy/backups/_index.md
  content/en/docs/developerportal/global-navigation.md
  content/en/docs/developerportal/project-management/epics/board.md
  content/en/docs/developerportal/project-management/epics/planning.md
  content/en/docs/howto/extensibility/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-explain.md
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
  content/en/docs/releasenotes/developer-portal/_index.md
  content/en/docs/releasenotes/private-platform/1.21.md
  content/en/docs/releasenotes/private-platform/_index.md
  content/en/docs/releasenotes/studio-pro/10/10.17.md
  content/en/docs/releasenotes/studio-pro/csharp-extensibility-api.md
  package-lock.json
  static/attachments/apidocs-mxsdk/apidocs/extensibility-api/web/notifications/notification.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-chat/maia-chat-interface.png
  static/attachments/refguide/modeling/mendix-ai-assistance/page-generator/chat-interface.png
  static/openapi-spec/projects-v2.yaml
Labels: Needs language review, 11.0.0 beta 1

#9501 Add a note about git merge being retracted
  content/en/docs/releasenotes/studio-pro/10/10.21.md
  content/en/docs/releasenotes/studio-pro/10/10.22.md
Labels: Needs R&D technical verification

#9503 User Identifier API changes
  content/en/docs/apidocs-mxsdk/apidocs/governance/user-identifiers-api.md
Labels: Internal WIP

#9511 Session Management: broken links
  content/en/docs/refguide/runtime/session-management.md
  content/en/docs/refguide10/runtime/session-management.md
Labels: Internal WIP

#9191 Expanded Git Connectivity troubleshooting
  content/en/docs/refguide/version-control/version-control-troubleshooting/troubleshoot-team-server-issues.md
  content/en/docs/refguide10/version-control/version-control-troubleshooting/troubleshoot-team-server-issues.md
Labels: Internal WIP, Needs language review

#9529 Adding section about token consumption monitoring
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/mendix-cloud-genai/navigate_mxgenai.md
  static/attachments/appstore/platform-supported-content/modules/genai/navigate_mxgenai/GenAIResource_TokenConsumptionMonitor.png
Labels: Needs R&D technical verification

#9507 Restructure EDC docs
  content/en/docs/appstore/use-content/platform-supported-content/modules/external-database-connector.md
  content/en/docs/refguide/modeling/integration/use-extensions/_index.md
  content/en/docs/refguide/modeling/integration/use-extensions/external-database-connector/_index.md
  content/en/docs/refguide/modeling/integration/use-extensions/external-database-connector/execute-an-sql-statement-on-an-external-database.md
  content/en/docs/refguide/modeling/integration/use-extensions/external-database-connector/query-and-integrate-external-data.md
  content/en/docs/refguide10/modeling/integration/use-extensions/_index.md
  content/en/docs/refguide10/modeling/integration/use-extensions/external-database-connection/_index.md
  content/en/docs/refguide10/modeling/integration/use-extensions/external-database-connection/execute-an-sql-statement-on-an-external-database.md
  content/en/docs/refguide10/modeling/integration/use-extensions/external-database-connection/use-the-external-database-connector.md
Labels: Internal WIP

#9557 Add cookie controls
  layouts/partials/footer.html
  layouts/partials/hooks/head-end.html
Labels: Internal WIP

#9538 Update marketplace-curation.md
  assets/scss/_badge.scss
  assets/scss/_variables_project.scss
  content/en/docs/control-center/marketplace/marketplace-curation.md
  content/en/docs/releasenotes/control-center/_index.md
  static/attachments/control-center/marketplace/marketplace-curation/curation-settings.png
  static/attachments/control-center/marketplace/marketplace-curation/curation_settings.png
  static/attachments/control-center/marketplace/marketplace-curation/displaying-company-approved-content.png
  static/attachments/control-center/marketplace/marketplace-curation/displaying-recommended-mp-content.png
  static/attachments/control-center/marketplace/marketplace-curation/marketplace-content-list.png
  static/attachments/control-center/marketplace/marketplace-curation/marketplace_content_list.png
Labels: Future release

#9551 Update create-backup.md
  content/en/docs/deployment/mendix-cloud-deploy/backups/create-backup.md
Labels: Needs language review

#9523 Update table with date format tokens (Mx 10)
  content/en/docs/refguide10/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
  content/en/docs/refguide10/modeling/menus/translatable-texts/language-settings.md
Labels: 10.22

#9586 docs(planned-maintenance): update and add info about maintenance
  content/en/docs/deployment/mendix-cloud-deploy/environments-details-new.md
  static/attachments/deployment/mendix-cloud-deploy/environments-details-beta/maintenance.png
Labels: Needs language review

#9546 [DBR-2559] HTTP Bridge Documentation
  content/en/docs/appstore/use-content/platform-supported-content/services/event-broker.md
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/event_broker_bridges_create.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/event_broker_bridges_create_2_sqs.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/event_broker_bridges_create_3_sqs.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/event_broker_bridges_create_4_sqs.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/event_broker_bridges_create_5_sqs.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/event_broker_bridges_create_6_sqs.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/event_broker_bridges_overview_sqs.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/http/event_broker_bridges_create_3_http.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/http/event_broker_bridges_create_4_http.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/http/event_broker_bridges_create_6_http.png
  static/attachments/appstore/platform-supported-content/services/event-broker/bridges/http/event_broker_bridges_create_7_http.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_access_control_defaults.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_access_control_overview.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_access_control_overview_2.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_access_control_overview_3.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges_create_1.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges_create_2.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges_create_3.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges_create_4.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges_create_5.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges_create_6.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges_create_7.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges_management.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_bridges_overview.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_add_bridge.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_create_1.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_create_1_errors.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_create_2.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_create_3.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_create_4.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_event_page.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_event_usages.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_get_started.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_import_file.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_imported_file.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_overview.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_ede_service_page.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_external_user.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_internal_user.png
  static/attachments/appstore/platform-supported-content/services/event-broker/event_broker_internal_user_2.png
Labels: Needs R&D technical verification

#9127 Added version remark to client api
  content/en/docs/apidocs-mxsdk/apidocs/frontend/client-api.md
Labels: Needs language review

#9552 11 Beta 2 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/11/11.0.md
  layouts/partials/landingpage/latest-releases.html
Labels: Release Notes, 11.0.0 beta 2

#9549 Remove entity access rules editor option from new features tab docs
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
Labels: Needs language review, 11.0.0 beta 2

#9455 [RUN-4642] Add new flag to mx create-module-package docs (10.23.0)
  content/en/docs/refguide10/general/mx-command-line-tool/export.md
Labels: 10.23

#9325 Updated docs to include remote key-mapping out of sync side effect
  content/en/docs/refguide10/modeling/domain-model/entities/external-entities.md
  content/en/docs/refguide9/modeling/domain-model/external-entities.md
Labels: 10.23

#9528 [RUN-4610] Remove deprecated Microflows.RemoveVariableOnDeleteObjectsActivity runtime setting (Mx11)
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: 11.0.0 beta 2

#9505 Clarify behavior of math operators in XPath
  content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-operators.md
Labels: 11.0.0 beta 2

#9527 Update the warning dialog for nf mf conversion (Mx 10)
  content/en/docs/refguide10/modeling/application-logic/microflows-and-nanoflows/microflows/_index.md
  content/en/docs/refguide10/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md
  static/attachments/refguide10/modeling/application-logic/microflows-and-nanoflows/microflows/warning-dialog.png
  static/attachments/refguide10/modeling/application-logic/microflows-and-nanoflows/nanoflows/warning-dialog.png
Labels: 10.23

#9567 [WOR-2509]: Implement first version of Maia for Workflows Documentation
  content/en/docs/refguide/modeling/mendix-ai-assistance/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-explain.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-for-domain-model.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-for-pages.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-for-workflows.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-for-workflows/chat-interface.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-for-workflows/maia-for-workflows.png
Labels: 11.0.0 beta 2

#9506 Workflow Commons - New WorkflowEndedUserTask + OQL View approach
  content/en/docs/appstore/use-content/platform-supported-content/modules/workflow-commons.md
Labels: Future release

#9591 [SOLP-3381] Update Import due to security issues
  content/en/docs/refguide/modeling/import-and-export/_index.md
  content/en/docs/refguide10/modeling/import-and-export/_index.md
  content/en/docs/refguide9/modeling/import-and-export/_index.md
Labels: Needs language review

#9585 Removed 'look in' from Find
  content/en/docs/refguide/modeling/menus/edit-menu/find-and-find-advanced.md
  content/en/docs/refguide10/modeling/menus/edit-menu/find-and-find-advanced.md
  content/en/docs/refguide9/modeling/menus/edit-menu/find-and-find-advanced.md
  static/attachments/refguide/modeling/menus/edit-menu/find-and-find-advanced/find-options.png
  static/attachments/refguide/modeling/menus/edit-menu/find-and-find-advanced/find.png
  static/attachments/refguide/modeling/menus/edit-menu/find-and-find-advanced/look-in.jpg
  static/attachments/refguide10/modeling/menus/edit-menu/find-and-find-advanced/find-options.png
  static/attachments/refguide10/modeling/menus/edit-menu/find-and-find-advanced/find.png
  static/attachments/refguide10/modeling/menus/edit-menu/find-and-find-advanced/look-in.jpg
  static/attachments/refguide9/modeling/menus/edit-menu/find-and-find-advanced/find-options.jpg
  static/attachments/refguide9/modeling/menus/edit-menu/find-and-find-advanced/find-options.png
  static/attachments/refguide9/modeling/menus/edit-menu/find-and-find-advanced/find.png
  static/attachments/refguide9/modeling/menus/edit-menu/find-and-find-advanced/look-in.jpg
Labels: Needs language review
