Repository mendix/docs, pull requests merged in 2025-03, with the labels that each got.

#9128 Remove .md suffix
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/reference-guide/genai-for-mendix/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/reference-guide/genai-for-mendix/conversational-ui.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/reference-guide/genai-for-mendix/genai-commons.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/reference-guide/genai-for-mendix/prompt-management.md
Labels: Internal WIP

#9106 Peer review: View Entities
  content/en/docs/refguide/modeling/domain-model/entities/view-entities/_index.md
Labels: Internal WIP, Internal/Peer Review

#9137 [UIA-1111] Add certificate requirements to limitations
  content/en/docs/appstore/use-content/platform-supported-content/modules/document-generation.md
Labels: Needs language review

#9144 Clarified log message structure
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/logging.md
Labels: Needs language review

#9138 Global Operator GA Release
  content/en/docs/deployment/private-cloud/private-cloud-cluster/private-cloud-global-operator.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Needs language review

#9151 Update type of entities image
  content/en/docs/refguide/modeling/domain-model/entities/_index.md
  static/attachments/refguide/modeling/domain-model/entities/type-of-entities.jpg
  static/attachments/refguide/modeling/domain-model/entities/type-of-entities.png
Labels: Internal WIP

#9070 Portunus 7 10 0 (postponed from 20 feb)
  content/en/docs/deployment/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/deployment/private-cloud/private-cloud-cluster/private-cloud-storage-plans.md
  content/en/docs/deployment/private-cloud/private-cloud-deploy.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
  static/attachments/deployment/private-cloud/private-cloud-cluster/CreateRole.png
  static/attachments/deployment/private-cloud/private-cloud-cluster/Invitemember.png
  static/attachments/deployment/private-cloud/private-cloud-cluster/RolesAndPermission.png
  static/attachments/deployment/private-cloud/private-cloud-cluster/deleteRole.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/PCLM.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/customizeEnvironmentNamespaceSelection.png
  static/attachments/deployment/private-cloud/private-cloud-deploy/customizeEnvironmentPage1.png
Labels: Future release

#9154 Update email-connector.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/email-connector.md
Labels: Needs language review

#9131 Update teamcenter-extension.md (V3.3.0)
  content/en/docs/appstore/use-content/platform-supported-content/modules/teamcenter-extension.md
  static/attachments/appstore/platform-supported-content/modules/teamcenter-extension/menu-tab.png
Labels: Needs language review

#9133 SAML Updates
  content/en/docs/appstore/use-content/platform-supported-content/modules/SAML/_index.md
Labels: Future release

#9163 Explain that remote entities can cause synchronization errors
  content/en/docs/refguide/modeling/domain-model/entities/external-entities.md
Labels: Needs language review

#9102 Added backup download URL and clarified backup expiry
  content/en/docs/developerportal/general/team-server/migrate-to-git.md
Labels: Internal WIP, Needs language review

#9103 10.18.4 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.18.md
Labels: Update release and/or featured date, Release Notes, 10.18.4

#9152 Release notes and documentation changes for Mx4PC 2.21.1 (planned for release around March 12)
  content/en/docs/deployment/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Future release, Needs language review

#9172 User Identifiers: Max limit of users
  content/en/docs/apidocs-mxsdk/apidocs/governance/user-identifiers-api.md
Labels: Internal WIP

#9171 Pclm cli 0 10 1 release
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Future release, Needs language review

#9174 OQL is for persistable and view entities only.
  content/en/docs/refguide/modeling/domain-model/oql/_index.md
Labels: Needs R&D technical verification

#9097 Commit and combine
  content/en/docs/refguide/modeling/menus/version-control-menu/commit-dialog.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
  static/attachments/refguide/modeling/menus/version-control-menu/commit-dialog/commit-and-combine.jpg
  static/attachments/refguide/modeling/menus/version-control-menu/commit-dialog/commit-dialog-disk-changes.png
  static/attachments/refguide/modeling/menus/version-control-menu/commit-dialog/commit-dialog-model-changes.png
  static/attachments/refguide/modeling/menus/version-control-menu/commit-dialog/commit-dialog-stories.png
  static/attachments/refguide/modeling/menus/version-control-menu/commit-dialog/commit-options.jpg
Labels: Needs R&D technical verification

#9186 Improved discoverability of Windows Authentication setting by mention…
  content/en/docs/refguide/version-control/on-premises-git.md
Labels: Needs language review

#9169 BYOIDP: standard / premium platform license is a prerequisite
  content/en/docs/control-center/security/set-up-sso-byoidp.md
Labels: Internal WIP

#9190 Updated documentation to inform users about sync delay
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/mendix-cloud-genai/Mx GenAI Connector.md
Labels: Needs language review

#9195 app insights 2.19.0 release
  content/en/docs/releasenotes/developer-portal/_index.md
Labels: Needs language review

#9184 Added --use-mpr-format-v1 command line parameter
  content/en/docs/refguide/general/mx-command-line-tool/app.md
Labels: Needs language review

#9202 Update customize-styling-new.md
  content/en/docs/howto/front-end/atlas-ui/customize-styling-new.md
Labels: Needs language review

#9206 Added information about git name and email
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
Labels: Needs language review

#9225 Mx on Azure Cluster Manager Administration fixes
  content/en/docs/deployment/mx-azure/mx-azure-installation.md
  content/en/docs/deployment/mx-azure/mx-azure-support.md
  content/en/docs/releasenotes/deployment/mendix-azure.md
Labels: Needs language review

#9229 Update docs for Unit Testing module version 9.6.0
  content/en/docs/appstore/use-content/platform-supported-content/modules/unit-testing.md
  content/en/docs/deployment/mendix-cloud-deploy/pipelines.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
  static/attachments/appstore/platform-supported-content/modules/unit-testing/unit-test-example.png
  static/attachments/appstore/platform-supported-content/modules/unit-testing/unit-test-overview.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing/UnitTesting-page.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing/example-passed-test.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing/promote-to-medior.png
  static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing/unit-testing-overview.png
Labels: Needs language review

#9230 Add workflow-instances KI to SP 10 MTS versions (including patches)
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.18.md
  content/en/docs/releasenotes/studio-pro/10/10.21.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Release Notes, 10.21

#9249 Release documentation for metamodel & Model SDK 10.21.0
  content/en/docs/releasenotes/sdk/metamodel/metamodel-10/metamodel-10.21.md
  content/en/docs/releasenotes/sdk/model-sdk/model-sdk-4.md
Labels: Needs language review, 10.21

#9239 New [SOLP-2927] Support command line merge for V2
  content/en/docs/refguide/general/mx-command-line-tool/_index.md
  content/en/docs/refguide/general/mx-command-line-tool/merge.md
Labels: Needs R&D technical verification, 10.21

#9235 Update module security docs
  content/en/docs/refguide/modeling/security/module-security.md
  static/attachments/refguide/modeling/security/module-security/entity-access-tab.png
  static/attachments/refguide/modeling/security/module-security/microflow-access-tab.png
  static/attachments/refguide/modeling/security/module-security/module-roles-tab.png
  static/attachments/refguide/modeling/security/module-security/nanoflow-access-tab.png
  static/attachments/refguide/modeling/security/module-security/odata-access-tab.png
  static/attachments/refguide/modeling/security/module-security/page-access-tab.png
  static/attachments/refguide/modeling/security/module-security/rest-access-tab.png
Labels: 10.21

#9167 Update about new features in the go to dialog
  content/en/docs/refguide/modeling/menus/edit-menu/go-to-option.md
Labels: Edit images after merging, 10.21

#9094 Add OpenAPI features to Consumed REST Service doc
  content/en/docs/appstore/create-content/create-connectors/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/_index.md
  content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/send-rest-request.md
  content/en/docs/refguide/modeling/integration/rest-services/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/consumed-rest-service.md
  content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/server-side-paging.md
  content/en/docs/releasenotes/studio-pro/10/10.17.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  static/attachments/refguide/modeling/integration/consumed-rest-service/accept-header.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/add-consumed-rest-service.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/add-request-button.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/add-request.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/add-service.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/adding-parameters.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/authentication-setup.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/base-url.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/body-structure-example.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/body-structure-tab.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/configuration-screen.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/dynamic-base-url.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/general-section.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/get-header.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/header-example.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/json-example.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/parameter.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/parameters-for-header.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/response-structure-tab.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/response-structure.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/response-tab.png
  static/attachments/refguide/modeling/integration/consumed-rest-service/send-request-activity.png
Labels: 10.21

#9232 Remove custom runtime settings
  content/en/docs/refguide/runtime/custom-settings/_index.md
  content/en/docs/refguide9/runtime/custom-settings/_index.md
Labels: 10.21

#9231 Add a list of Maia Chat's Data Sources
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-chat.md
Labels: 10.21

#9227 Maia Explain Documentation
  content/en/docs/refguide/modeling/mendix-ai-assistance/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-explain.md
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-explain/maia-explain-interface.png
Labels: 10.21

#9207 Add microflow parameter type to JavaScript action parameter types table
  content/en/docs/refguide/modeling/resources/javascript-actions.md
Labels: 10.21

#9193 Page generator docs
  content/en/docs/refguide/modeling/mendix-ai-assistance/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/page-generator.md
  content/en/docs/refguide/modeling/pages/page/_index.md
  static/attachments/refguide/modeling/mendix-ai-assistance/page-generator/chat-interface.png
  static/attachments/refguide/modeling/mendix-ai-assistance/page-generator/page-generator.png
Labels: 10.21

#9183 Support importing workflows from modules
  content/en/docs/refguide/modeling/import-and-export/_index.md
  static/attachments/refguide/modeling/import-and-export/import-module.png
Labels: 10.21

#9240 Add Native Template release for Dependencies update and Cookie Encryption
  content/en/docs/releasenotes/mobile/native-template/_index.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/nt-13-rn.md
Labels: 10.21

#9130 [WTF-2113] Add documentation on the use of variables on pages and snippets
  content/en/docs/refguide/modeling/pages/common-widget-properties.md
  content/en/docs/refguide/modeling/pages/page-resources/snippet.md
  content/en/docs/refguide/modeling/pages/page/_index.md
  content/en/docs/refguide/modeling/pages/page/page-properties.md
Labels: 10.21

#9143 Clarified Java version in system requirements
  content/en/docs/refguide/installation/system-requirements.md
Labels: 10.21

#9129 [CTRL-3166] Release the happiness tracking feature - documentation
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/menus/help-menu/_index.md
  content/en/docs/refguide/modeling/menus/help-menu/feedback-survey.md
  static/attachments/refguide/modeling/menus/help-menu/feedback-survey/disable-feedback-survey.png
  static/attachments/refguide/modeling/menus/help-menu/feedback-survey/feedback-survey.png
  static/attachments/refguide/modeling/menus/help-menu/feedback-survey/submit-feedback.png
Labels: 10.21

#9215 Added Java 21 note to migration guide 9 -> 10
  content/en/docs/refguide/installation/upgrading-from-9-to-10.md
Labels: 10.21

#9093 PAG ColorPicker preview color updated
  content/en/docs/apidocs-mxsdk/apidocs/frontend/design-properties.md
Labels: 10.21

#9226 Action Variables [WTF-2181]
  content/en/docs/apidocs-mxsdk/apidocs/frontend/pluggable-widgets/pluggable-widgets-client-apis/_index.md
  content/en/docs/apidocs-mxsdk/apidocs/frontend/pluggable-widgets/pluggable-widgets-property-types.md
  static/attachments/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types/action-variable.png
Labels: 10.21

#9253 Marked MPRv2 as GA
  content/en/docs/refguide/version-control/version-control-troubleshooting/repository-size.md
Labels: Needs language review, 10.21

#9255 Remove invalid multiple revisions port fix
  content/en/docs/refguide/modeling/menus/version-control-menu/merge-dialog.md
Labels: Needs language review

#9234 Clarified use of nvm for older mx versions
  content/en/docs/refguide/mobile/distributing-mobile-apps/building-native-apps/bitrise.md
Labels: Needs language review

#9247 Update data-importer-extension.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/data-importer-extension.md
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/IM-with-mapping-param-association.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/create-DI-doc-with-import-mapping.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/create-import-mapping.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/select-file-for-preview.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/select-file-for-structure-preview.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/select-schema-elements-for-imm.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/source-to-target-mapping.png
  static/attachments/appstore/platform-supported-content/modules/data-importer-extension/update-data-importer-doc-confirmation.png
Labels: Needs language review, 10.21

#9252 [SOLP-3133] make git CLI installation mandatory
  content/en/docs/refguide/installation/install.md
Labels: Needs language review

#9256 Add a Known Issue
  content/en/docs/releasenotes/studio-pro/10/10.21.md
Labels: Needs R&D technical verification, 10.21

#9113 OIDC Provider: LoginLocation Constant
  content/en/docs/appstore/use-content/platform-supported-content/services/oidc-provider.md
Labels: Future release

#9258 Do not use direct associations in imported modules
  content/en/docs/appstore/create-content/guidelines-content-creators.md
  content/en/docs/refguide/modeling/domain-model/associations/association-storage.md
  content/en/docs/releasenotes/studio-pro/10/10.21.md
Labels: 10.21

#9270 Studio Pro 10.21.1 RNs
  content/en/docs/releasenotes/studio-pro/10/10.21.md
Labels: Release Notes, 10.21.1
