Repository mendix/docs, pull requests merged in 2025-04, with the labels that each got.

#9268 Kk pmp secret
  content/en/docs/private-platform/pmp-quickstart.md
Labels: Internal WIP

#9277 Update amazon-bedrock.md - SAS-1176: parts on new bedrock JAs added
  content/en/docs/appstore/use-content/platform-supported-content/modules/aws/amazon-bedrock.md
Labels: Needs language review

#9308 9.24.34 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Needs language review, Update release and/or featured date, 9.24.34

#9134 [CTRL-3166] Release the happiness tracking feature - documentation to 9.24
  content/en/docs/refguide9/modeling/menus/_index.md
  content/en/docs/refguide9/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide9/modeling/menus/help-menu/feedback-survey.md
  static/attachments/refguide9/modeling/menus/feedback-survey/disable-feedback-survey.png
  static/attachments/refguide9/modeling/menus/feedback-survey/feedback-survey.png
  static/attachments/refguide9/modeling/menus/feedback-survey/submit-feedback.png
Labels: 9.24.34

#9091 Introduce setting TrackUserLastLoginForODataAndREST in 9.24.34
  content/en/docs/refguide9/runtime/custom-settings/_index.md
Labels: 9.24.34

#9233 Update .NET version in 9.24 ref guide
  content/en/docs/refguide9/general/install.md
  content/en/docs/refguide9/general/system-requirements.md
Labels: 9.24.34

#9259 Update Integration pane docs and images
  content/en/docs/refguide/installation/system-requirements.md
  content/en/docs/refguide/modeling/domain-model/entities/external-entities.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
  content/en/docs/refguide/modeling/integration/share-data-sources/write-data-to-another-app.md
  content/en/docs/refguide/modeling/menus/view-menu/integration-pane.md
  content/en/docs/refguide8/modeling/domain-model/external-entities.md
  content/en/docs/refguide8/modeling/integration/consumed-odata-services/_index.md
  content/en/docs/refguide8/modeling/integration/consumed-odata-services/consumed-odata-service.md
  content/en/docs/refguide8/modeling/menus/view-menu/data-hub-pane.md
  content/en/docs/refguide9/general/system-requirements.md
  content/en/docs/refguide9/modeling/domain-model/external-entities.md
  content/en/docs/refguide9/modeling/integration/odata-services/consumed-odata-services/_index.md
  content/en/docs/refguide9/modeling/integration/odata-services/consumed-odata-services/consumed-odata-service.md
  content/en/docs/refguide9/modeling/integration/odata-services/wrap-services-odata.md
  content/en/docs/refguide9/modeling/menus/view-menu/data-hub-pane.md
  content/en/docs/refguide9/runtime/data-storage/_index.md
  static/attachments/refguide/modeling/domain-model/external-entities/consumed-service-docs.png
  static/attachments/refguide/modeling/domain-model/external-entities/data-hub-app.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/consuming-from-service-endpoints.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/integration-pane-2.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/integration-pane.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/major-service-updates.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/orders.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/salesorders-header.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/switch-dialog-box.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/switching-consumed-services.png
  static/attachments/refguide/modeling/integration/consumed-odata-services/consumed-odata-service/update-dialog-box.png
  static/attachments/refguide/modeling/integration/write-data/crud-capabilities.png
  static/attachments/refguide/modeling/menus/view-menu/data-hub-pane/expand-service-list.png
  static/attachments/refguide/modeling/menus/view-menu/data-hub-pane/filter-icon.png
  static/attachments/refguide/modeling/menus/view-menu/data-hub-pane/integration-pane-info.png
  static/attachments/refguide/modeling/menus/view-menu/data-hub-pane/integration-pane-menu.png
  static/attachments/refguide/modeling/menus/view-menu/data-hub-pane/multiple-associations.png
  static/attachments/refguide/modeling/menus/view-menu/data-hub-pane/update-available.png
  static/attachments/refguide/modeling/menus/view-menu/data-hub-pane/used-in-your-app.png
  static/attachments/refguide/modeling/menus/view-menu/integration-pane/actions.png
  static/attachments/refguide/modeling/menus/view-menu/integration-pane/business-events.png
  static/attachments/refguide/modeling/menus/view-menu/integration-pane/expand-service-list.png
  static/attachments/refguide/modeling/menus/view-menu/integration-pane/filter-icon.png
  static/attachments/refguide/modeling/menus/view-menu/integration-pane/integration-pane-info.png
  static/attachments/refguide/modeling/menus/view-menu/integration-pane/integration-pane-menu.png
  static/attachments/refguide/modeling/menus/view-menu/integration-pane/unsupported-elements.png
  static/attachments/refguide/modeling/menus/view-menu/integration-pane/update-available.png
  static/attachments/refguide/modeling/menus/view-menu/integration-pane/used-in-your-app.png
Labels: Internal WIP, Needs language review

#9318 Rename "Contact Reporter" to "Reporter Comments"
  content/en/docs/developerportal/app-insights/feedback.md
  content/en/docs/releasenotes/developer-portal/_index.md
Labels: Internal WIP, Awaiting response

#9274 Update default value of OptimizeSecurityColumns
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: 11.0.0 beta 1

#9317 Update _index.md
  content/en/docs/appstore/create-content/upload-content/_index.md
Labels: Needs language review

#9346 Removed module updates, added MPRv2 to release calendar
  content/en/docs/releasenotes/feature-release-calendar/_index.md
Labels: Needs language review

#9326 10.6.22 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Update release and/or featured date, Release Notes, 10.6.22

#9334 10.12.16 Studio Pro RNs
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.18.md
  content/en/docs/releasenotes/studio-pro/10/10.21.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Update release and/or featured date, Release Notes, 10.12.16

#9358 Add Native Template 7.0.25 release notes
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-7-rn.md
Labels: Needs language review

#9217 [RUN-4514] Update installation page with JDK 21 information (9.24.34, 10.6.22)
  content/en/docs/refguide/installation/install.md
  content/en/docs/refguide9/general/install.md
Labels: Needs language review, 10.6.22

#9340 Update teamcenter-extension.md V4.0.0
  content/en/docs/appstore/use-content/platform-supported-content/modules/teamcenter-extension.md
  static/attachments/appstore/platform-supported-content/modules/teamcenter-extension/edit-configuration.png
  static/attachments/appstore/platform-supported-content/modules/teamcenter-extension/teamcenter-configuration.png
  static/attachments/appstore/platform-supported-content/modules/teamcenter-extension/teamcenter-sso.png
Labels: Needs language review

#9372 Snowflake change date
  content/en/docs/appstore/use-content/platform-supported-content/modules/snowflake/mendix-data-loader.md
Labels: Needs language review

#9300 OIDC Provider: CustomRedirectLogicMicroflow update
  content/en/docs/appstore/use-content/platform-supported-content/services/oidc-provider.md
Labels: Future release

#9368 BYOIDP-Trobleshooting
  content/en/docs/control-center/security/set-up-sso-byoidp.md
Labels: Internal WIP

#9413 Clarify status of Maia tools
  content/en/docs/refguide/modeling/domain-model/create-a-basic-data-layer.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/domain-model-generator.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-explain.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/translation-generator.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
  content/en/docs/refguide/modeling/menus/translatable-texts/batch-translate.md
Labels: Internal WIP

#9421 Rephrased 10.21 and 10.18.5 release note
  content/en/docs/releasenotes/studio-pro/10/10.18.md
  content/en/docs/releasenotes/studio-pro/10/10.21.md
Labels: Needs language review, Release Notes

#9301 Add icons
  layouts/shortcodes/icon.html
Labels: Internal WIP

#9377 8.18.34 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/8/8.18.md
Labels: Release Notes, 8.18.34

#9405 10.18.6 Studio Pro RNs
  content/en/docs/releasenotes/studio-pro/10/10.18.md
Labels: Update release and/or featured date, Release Notes, 10.18.6

#9410 Studio Pro 10.6.23 RNs
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Update release and/or featured date, Release Notes, 10.6.23

#9420 Added section on moving away from Team Server
  content/en/docs/refguide/version-control/on-premises-git.md
Labels: Needs language review

#9451 Added section on moving away from Team Server
  content/en/docs/refguide10/version-control/on-premises-git.md
Labels: 11.0.0 beta 1

#9309 Add docs for security overview export command
  content/en/docs/refguide/general/mx-command-line-tool/_index.md
  content/en/docs/refguide/general/mx-command-line-tool/security.md
  content/en/docs/refguide/modeling/security/security-overview.md
Labels: Needs language review, 11.0.0 beta 1

#9387 [RUN-4642] Add new flag to mx create-module-package docs
  content/en/docs/refguide/general/mx-command-line-tool/export.md
Labels: 11.0.0 beta 1

#9373 Added troubleshooting section on Git name/email
  content/en/docs/refguide/version-control/version-control-troubleshooting/_index.md
Labels: Needs language review

#9457 Add troubleshooting section on Git name/email for Mx11
  content/en/docs/refguide10/version-control/version-control-troubleshooting/_index.md
Labels: 11.0.0 beta 1

#9280 Add go-to image to refguide10
  content/en/docs/refguide10/modeling/menus/edit-menu/go-to-option.md
Labels: 11.0.0 beta 1

#9401 [DUX-478] Add View Entity Document Changes to Existing Documentation
  content/en/docs/refguide/modeling/domain-model/entities/view-entities/_index.md
  content/en/docs/refguide/modeling/domain-model/entities/view-entities/abstracting-data.md
  content/en/docs/refguide/modeling/domain-model/entities/view-entities/use-view-entities.md
  content/en/docs/refguide/modeling/domain-model/entities/view-entities/view-entity-data-versioning.md
  content/en/docs/refguide/modeling/domain-model/entities/view-entities/view-entity-export-data.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/_index.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/maia-for-oql.md
  static/attachments/refguide/modeling/domain-model/use-view-entities/customer-with-address.png
  static/attachments/refguide/modeling/domain-model/use-view-entities/view-entity-contextual-menu.png
  static/attachments/refguide/modeling/domain-model/use-view-entities/view-entity-dialog.png
  static/attachments/refguide/modeling/domain-model/use-view-entities/view-entity-document.png
  static/attachments/refguide/modeling/domain-model/use-view-entities/view-entity.png
  static/attachments/refguide/modeling/domain-model/view-entities/abstracting-data/export-level-hidden.png
  static/attachments/refguide/modeling/domain-model/view-entities/abstracting-data/export-level-usable.png
  static/attachments/refguide/modeling/domain-model/view-entities/abstracting-data/export-level.png
  static/attachments/refguide/modeling/domain-model/view-entities/abstracting-data/usable.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-oql-generator/maia-for-oql-button.png
  static/attachments/refguide/modeling/mendix-ai-assistance/maia-oql-generator/maia-pane-for-oql-generator.png
Labels: Needs language review, 11.0.0 beta 1

#9385 Add OpenAPI Documentation pane to Published REST service
  content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/_index.md
  content/en/docs/refguide/modeling/menus/view-menu/_index.md
Labels: 11.0.0 beta 1

#9459 Include remote key-mapping out of sync side effect
  content/en/docs/refguide/modeling/domain-model/entities/external-entities.md
Labels: 11.0.0 beta 1

#9452 Security overview became generally available in 10.21.0
  content/en/docs/refguide/modeling/menus/app-menu/_index.md
  content/en/docs/refguide/modeling/security/_index.md
  content/en/docs/refguide/modeling/security/security-overview.md
  static/attachments/refguide/modeling/menus/app-menu/app-menu.png
Labels: Needs language review

#9414 Recorded the behaviour of commit message when conflict are auto resolved
  content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
Labels: Needs language review

#9477 Increase Atlas 3 to 4 migration guidance
  content/en/docs/refguide/installation/upgrading-from-10-to-11.md
Labels: 11.0.0 beta 1

#9472 Client-side breaking changes
  content/en/docs/refguide/installation/upgrading-from-10-to-11.md
Labels: 11.0.0 beta 1
