Repository mendix/docs, pull requests merged in 2025-01, with the labels that each got.

#8840 [RUN-4280] Add release note for commons-io upgrade
  content/en/docs/releasenotes/studio-pro/8/8.18.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Needs language review

#8819 10.12.11 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.13.md
  content/en/docs/releasenotes/studio-pro/10/10.15.md
Labels: 10.12.11

#8847 5 Jan 2025: Apps Mendix Portal Release
  content/en/docs/control-center/people/roles-permissions.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Future release

#8858 Added missing alias
  content/en/docs/howto/security/csp.md
Labels: Needs language review

#8868 Update data grid mention of react
  content/en/docs/refguide/modeling/pages/data-widgets/grids/data-grid/_index.md
Labels: Needs language review

#8852 GenAI how-to
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/concepts/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/concepts/prompt-engineering.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/concepts/rag-example-implementation.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/conversational-ui.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/using_genai/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/using_genai/start_from_a_starter_app.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/using_genai/start_from_blank_app.md
  static/attachments/appstore/platform-supported-content/modules/genai/genai-howto-blankapp/blank_genai_interface.jpg
  static/attachments/appstore/platform-supported-content/modules/genai/genai-howto-blankapp/blank_genai_mf.jpg
  static/attachments/appstore/platform-supported-content/modules/genai/genai-howto-starterapp/starter_genai_interface.jpg
Labels: Needs R&D technical verification

#8873 Navigation roles for PWA
  content/en/docs/appstore/use-content/platform-supported-content/modules/oidc.md
Labels: Internal WIP

#8843 Replace Images with code blocks for datastorage API how to (#8518)
  content/en/docs/howto/extensibility/howto-datastorage-api.md
  content/en/docs/refguide/modeling/resources/data-sets/_index.md
  static/attachments/howto/extensibility/howto-datastorage-api/image001.png
  static/attachments/howto/extensibility/howto-datastorage-api/image021.png
  static/attachments/howto/extensibility/howto-datastorage-api/image026.png
  static/attachments/howto/extensibility/howto-datastorage-api/image027.png
  static/attachments/howto/extensibility/howto-datastorage-api/image028.png
  static/attachments/howto/extensibility/howto-datastorage-api/image032.png
  static/attachments/howto/extensibility/howto-datastorage-api/image034.png
  static/attachments/howto/extensibility/howto-datastorage-api/image035.png
  static/attachments/howto/extensibility/howto-datastorage-api/image036.png
  static/attachments/howto/extensibility/howto-datastorage-api/image043.png
Labels: Needs R&D technical verification, Internal WIP

#8881 10.6.19 RNs
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Release Notes

#8859 OIDC SSO: app-initiated IdP logout (TW-2504)
  content/en/docs/appstore/use-content/platform-supported-content/modules/oidc.md
Labels: Needs R&D technical verification, Internal WIP

#8717 Add Application Data Replication feature in Control Center (to be released in Q1)
  content/en/docs/control-center/security/security-settings.md
  content/en/docs/control-center/security/security.md
  content/en/docs/deployment/mendix-cloud-deploy/_index.md
  static/attachments/control-center/security/security-settings/security.jpg
Labels: Future release

#8887 10.18.1 RNs
  content/en/docs/releasenotes/studio-pro/10/10.18.md
  content/en/docs/releasenotes/studio-pro/lts-mts.md
  layouts/partials/landingpage/latest-releases.html
Labels: Update release and/or featured date, Release Notes

#8886 SAML 4.0.0
  content/en/docs/appstore/use-content/platform-supported-content/modules/SAML/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/SAML/advanced_configuration.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/SAML/idp_attributes.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/saml.md
  content/en/docs/private-platform/configuration/_index.md
  static/attachments/appstore/platform-supported-content/modules/saml/Easy-default.png
  static/attachments/appstore/platform-supported-content/modules/saml/endpoints.png
  static/attachments/appstore/platform-supported-content/modules/saml/non-default.png
  static/attachments/appstore/platform-supported-content/modules/saml/runtime-config.png
  static/attachments/appstore/platform-supported-content/modules/saml/saml-azure.png
  static/attachments/appstore/platform-supported-content/modules/saml/saml-okta.png
Labels: Needs R&D technical verification

#8900 Update react readiness for SAML
  content/en/docs/refguide/runtime/mendix-client/content-readiness.md
Labels: Needs language review

#8893 GenAI Documentation changes for 10.18 Release
  content/en/docs/appstore/use-content/platform-supported-content/modules/aws/amazon-bedrock.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/Mx GenAI Connector.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/conversational-ui.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/genai-commons.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/openai/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/using_genai/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/using_genai/start_from_a_starter_app.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/using_genai/start_from_blank_app.md
  static/attachments/appstore/platform-supported-content/modules/aws-bedrock/chat-completions-mf-old.png
  static/attachments/appstore/platform-supported-content/modules/aws-bedrock/chat-completions-mf.png
  static/attachments/appstore/platform-supported-content/modules/genai/conversational-ui/domain-model.png
  static/attachments/appstore/platform-supported-content/modules/genai/genaicommons/demain-model.png
  static/attachments/appstore/platform-supported-content/modules/genai/genaicommons/genai-commons-domain-model.png
  static/attachments/appstore/platform-supported-content/modules/genai/mxgenAI-connector/MxGenAIConnector_Configuration.png
  static/attachments/appstore/platform-supported-content/modules/genai/mxgenAI-connector/MxGenAIConnector_ConfigureRAG.png
  static/attachments/appstore/platform-supported-content/modules/genai/mxgenAI-connector/PushTicketstoMxKB.png
  static/attachments/appstore/platform-supported-content/modules/genai/mxgenAI-connector/knowledgebase-using-mendix-object.png
  static/attachments/appstore/platform-supported-content/modules/genai/mxgenAI-connector/synthia-domain-model.png
Labels: Future release, Needs language review

#8651 [IN-6784] Updated docs for List [HttpHeader] auth. microflow params
  content/en/docs/refguide/modeling/integration/odata-services/published-odata-services/_index.md
  content/en/docs/refguide/modeling/integration/rest-services/http-request-and-response-entities.md
Labels: Future release

#8898 Update a workflow KI
  content/en/docs/releasenotes/studio-pro/10/10.10.md
  content/en/docs/releasenotes/studio-pro/10/10.11.md
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.13.md
  content/en/docs/releasenotes/studio-pro/10/10.14.md
  content/en/docs/releasenotes/studio-pro/10/10.15.md
  content/en/docs/releasenotes/studio-pro/10/10.16.md
  content/en/docs/releasenotes/studio-pro/10/10.3.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/10/10.7.md
  content/en/docs/releasenotes/studio-pro/10/10.8.md
  content/en/docs/releasenotes/studio-pro/10/10.9.md
Labels: Needs R&D technical verification

#8875 fix version number (nbui)
  content/en/docs/releasenotes/mobile/mendix-native-mobile-builder.md
Labels: Needs language review

#8882 added alias used in make it native
  content/en/docs/refguide/mobile/getting-started-with-mobile/prerequisites.md
Labels: Needs language review

#8905 Update NT release notes and Hermes Engine docs
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/_index.md
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/hermes.md
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/logging.md
  content/en/docs/refguide/mobile/distributing-mobile-apps/building-native-apps/deploying-native-app.md
  content/en/docs/refguide/mobile/getting-started-with-mobile/prerequisites.md
  content/en/docs/refguide9/mobile/building-efficient-mobile-apps/logging.md
  content/en/docs/refguide9/mobile/getting-started-with-mobile/prerequisites.md
  content/en/docs/releasenotes/mobile/make-it-native-parent/make-it-native-10.md
  content/en/docs/releasenotes/mobile/mendix-mobile-app.md
  content/en/docs/releasenotes/mobile/mendix-native-mobile-builder.md
  content/en/docs/releasenotes/mobile/native-builder.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/_index.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/nt-10-rn.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/nt-11-rn.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/nt-8-rn.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/nt-9-rn.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-8-parent/nt-5.2-rn.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/_index.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-6-rn.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-7-rn.md
Labels: Internal WIP

#8921 OIDC SSO: Anonymous user info update
  content/en/docs/appstore/use-content/platform-supported-content/modules/mobile-sso.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/oidc.md
Labels: Needs R&D technical verification, Internal WIP

#8924 Improved documentation for the clear_cache cookie
  content/en/docs/refguide/runtime/mendix-client/_index.md
  content/en/docs/refguide9/runtime/mendix-client.md
Labels: Needs language review

#8931 Update security-findings-faq.md
  content/en/docs/support/security-findings-faq.md
Labels: Needs language review

#8940 Add an improvement to 10.18.1
  content/en/docs/releasenotes/studio-pro/10/10.18.md
Labels: Needs R&D technical verification

#8757 Kk pmp adminref
  content/en/docs/private-platform/configuration/_index.md
  content/en/docs/private-platform/configuration/pmp-configure-azure.md
  content/en/docs/private-platform/configuration/pmp-configure-k8s.md
  content/en/docs/private-platform/configuration/pmp-version-control.md
  content/en/docs/private-platform/pmp-admin.md
  content/en/docs/private-platform/reference/admin/_index.md
  content/en/docs/private-platform/reference/admin/pmp-ref-admin-manage.md
  content/en/docs/private-platform/reference/admin/pmp-ref-admin-system.md
  content/en/docs/releasenotes/private-platform/1.11.md
  content/en/docs/releasenotes/private-platform/1.13.md
  static/attachments/private-platform/pmp-admin1.png
  static/attachments/private-platform/pmp-admin4.png
  static/attachments/private-platform/pmp-admin5.png
  static/attachments/private-platform/pmp-admin6.png
  static/attachments/private-platform/pmp-admin7.png
  static/attachments/private-platform/pmp-admin8.png
  static/attachments/private-platform/pmp-admin9.png
  static/attachments/private-platform/pmp-config1.png
Labels: Needs R&D technical verification

#8932 Encryption key updates
  content/en/docs/appstore/use-content/platform-supported-content/modules/encryption.md
  static/attachments/appstore/platform-supported-content/modules/encryption/encryption-constant.png
Labels: Internal WIP

#8950 Add CVE and update link
  content/en/docs/releasenotes/security-advisories/_index.md
Labels: Needs R&D technical verification

#8919 Added auth token discussion
  content/en/docs/refguide/runtime/session-management.md
Labels: Needs R&D technical verification, Needs language review

#8955 OIDC: microflow update
  content/en/docs/appstore/use-content/platform-supported-content/modules/oidc.md
Labels: Internal WIP

#8956 Update User Type
  content/en/docs/appstore/use-content/platform-supported-content/modules/SAML/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/oidc.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/scim.md
Labels: Internal WIP

#8960 Userrole info
  content/en/docs/appstore/use-content/platform-supported-content/modules/SAML/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/oidc.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/scim.md
Labels: Needs R&D technical verification, Internal WIP

#8895 10.12.12 Studio Pro RN
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: Update release and/or featured date, Release Notes, 10.12.12

#8953 Add release notes for Sprintr 2025.01.26
  content/en/docs/control-center/people/roles-permissions.md
  content/en/docs/developerportal/general/team/_index.md
  content/en/docs/developerportal/general/team/app-roles.md
  content/en/docs/releasenotes/developer-portal/_index.md
  layouts/partials/landingpage/latest-releases.html
  static/attachments/control-center/people/roles-permissions/learn-more.png
  static/attachments/developerportal/general/team/team.png
Labels: Release Notes

#8949 Overhaul of GenAI docs after 10.18
  content/en/docs/appstore/use-content/platform-supported-content/modules/aws/amazon-bedrock.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/Mx GenAI Connector.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/genai-commons.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/openai/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/pg-vector-knowledge-base/_index.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/using_genai/start_from_blank_app.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/snowflake/snowflake-rest-sql.md
  static/attachments/appstore/platform-supported-content/modules/genai/genai-howto-blankapp/blank_genai_mf.jpg
Labels: Needs language review

#8943 10.19.0 Studio Pro Release Notes
  content/en/docs/releasenotes/studio-pro/10/10.19.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review, Update release and/or featured date, Release Notes, 10.19

#8923 Update widget-conversion-limitations.md
  content/en/docs/refguide/runtime/mendix-client/widget-conversion-limitations.md
Labels: Needs language review, 10.19

#8946 Online sync mode documentation
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/_index.md
  content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/online-sync-mode.md
  content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
Labels: 10.19

#8913 10.19 OP-Sqlite implementation doc for Native Template
  content/en/docs/releasenotes/mobile/native-template/_index.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/_index.md
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/nt-12-rn.md
Labels: Update release and/or featured date, 10.19

#8909 Documentation for new menu option Help->Support Tools->Fetch Repository.
  content/en/docs/refguide/modeling/menus/help-menu/_index.md
Labels: 10.19

#8951 Added changes for BYOD. 10.19 release of Studio Pro
  content/en/docs/appstore/use-content/platform-supported-content/modules/database-connector-mx10.md
  content/en/docs/refguide/modeling/integration/use-extensions/use-the-external-database-connector.md
Labels: 10.19

#8947 Default access in beta access rule editor
  content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
  static/attachments/refguide/modeling/domain-model/entities/access-rules/access-rule-editor.png
Labels: 10.19

#8939 Update tracing documentation to use the Java agent
  content/en/docs/refguide/runtime/tracing-in-runtime.md
Labels: 10.19

#8431 Documentation for OQL
  content/en/docs/apidocs-mxsdk/mxsdk/sdk-howtos/creating-the-domain-model.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/aws/aws-authentication.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/genai/genai-commons.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/sap/sap-event-mesh-connector.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/sap/sap-odata-connector.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/snowflake/snowflake-rest-sql.md
  content/en/docs/appstore/use-content/platform-supported-content/services/use-sap-model-creator.md
  content/en/docs/deployment/private-cloud/reduced-downtime-deployment.md
  content/en/docs/refguide/modeling/consistency-errors/_index.md
  content/en/docs/refguide/modeling/domain-model/_index.md
  content/en/docs/refguide/modeling/domain-model/entities/data-sets.md
  content/en/docs/refguide/modeling/domain-model/entities/indexes.md
  content/en/docs/refguide/modeling/domain-model/oql/_index.md
  content/en/docs/refguide/modeling/domain-model/oql/oql-clauses.md
  content/en/docs/refguide/modeling/domain-model/oql/oql-expression-syntax.md
  content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
  content/en/docs/refguide/modeling/domain-model/oql/oql-v2.md
  content/en/docs/refguide/modeling/mendix-ai-assistance/domain-model-generator.md
  content/en/docs/refguide/modeling/menus/edit-menu/go-to-option.md
  content/en/docs/refguide/modeling/pages/data-widgets/configure-form.md
  content/en/docs/refguide/modeling/pages/data-widgets/configure-list-and-details-on-one-page.md
  content/en/docs/refguide/modeling/pages/image-and-file-widgets/attach-images.md
  content/en/docs/refguide/modeling/pages/image-and-file-widgets/configure-files.md
  content/en/docs/refguide/modeling/resources/_index.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/_index.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/_index.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-aggregation.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/_index.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-cast.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-coalesce.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-datediff.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-datepart.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-length.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-lower.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-rangebegin.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-rangeend.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-replace.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-round.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-functions/oql-upper.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-operators/_index.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-operators/oql-case-expression.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-parameters.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-subqueries.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-from-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-group-by-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-limit-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-order-by-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-select-clause.md
  content/en/docs/refguide/modeling/resources/data-sets/oql/oql-where-clause.md
  content/en/docs/releasenotes/studio-pro/10/10.19.md
Labels: 10.19

#8969 Release documentation for metamodel & Model SDK 10.19.0
  content/en/docs/releasenotes/sdk/metamodel/metamodel-10/metamodel-10.19.md
  content/en/docs/releasenotes/sdk/model-sdk/model-sdk-4.md
Labels: Release Notes, 10.19

#8948 Catalog release 2.139.0
  content/en/docs/releasenotes/catalog/_index.md
Labels: Future release

#8972 Update Make It Native support versions
  content/en/docs/refguide/mobile/getting-started-with-mobile/prerequisites.md
Labels: Needs language review, 10.19

#8976 Positioning error KI fix
  content/en/docs/releasenotes/studio-pro/10/10.10.md
  content/en/docs/releasenotes/studio-pro/10/10.11.md
  content/en/docs/releasenotes/studio-pro/10/10.12.md
  content/en/docs/releasenotes/studio-pro/10/10.13.md
  content/en/docs/releasenotes/studio-pro/10/10.14.md
  content/en/docs/releasenotes/studio-pro/10/10.15.md
  content/en/docs/releasenotes/studio-pro/10/10.16.md
  content/en/docs/releasenotes/studio-pro/10/10.17.md
  content/en/docs/releasenotes/studio-pro/10/10.6.md
  content/en/docs/releasenotes/studio-pro/10/10.7.md
  content/en/docs/releasenotes/studio-pro/10/10.8.md
  content/en/docs/releasenotes/studio-pro/10/10.9.md
Labels: Needs R&D technical verification

#8975 [RUN-4426] Add com.mendix.core.LenientDateTimeParsing to Runtime Customization page
  content/en/docs/refguide/runtime/custom-settings/_index.md
Labels: Needs language review

#8986 [RUN-4452] Clarify Java agent location
  content/en/docs/refguide/runtime/tracing-in-runtime.md
Labels: Internal WIP, Needs language review, Awaiting response

#8968 Added explanation how to use SVN backup post-migration
  content/en/docs/developerportal/general/team-server/migrate-to-git.md
Labels: Needs language review
