Repository mendix/docs, pull requests merged in 2025-08, with the labels that each got.

#9934 Add 10.18.10 Studio Pro Release Notes
  content/en/docs/releasenotes/studio-pro/10/10.18.md
  content/en/docs/releasenotes/studio-pro/11/11.1.md
Labels: Needs language review, Update release and/or featured date, Release Notes, 10.18.10

#9946 Remove 8 from LTS
  content/en/docs/howto8/_index.md
  content/en/docs/refguide8/_index.md
  content/en/docs/releasenotes/studio-pro/8/8.18.md
  content/en/docs/releasenotes/studio-pro/lts-mts.md
Labels: Needs R&D technical verification

#9935 Add 10.24.3 Studio Pro Release Notes
  content/en/docs/releasenotes/studio-pro/10/10.18.md
  content/en/docs/releasenotes/studio-pro/10/10.24.md
  content/en/docs/releasenotes/studio-pro/11/11.1.md
Labels: Update release and/or featured date, Release Notes, 10.24.3

#9932 Supported ONNX versions in Studio Pro 10
  content/en/docs/refguide10/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
Labels: Future release

#9162 Update generator command
  content/en/docs/howto/extensibility/build-native-widget.md
Labels: Needs language review

#9954 Add 10.18.11 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.18.md
Labels: Release Notes, 10.18.11

#9746 Added prerequisite for community commons
  content/en/docs/marketplace/platform-supported-content/modules/email-connector.md
  static/attachments/appstore/platform-supported-content/modules/email-connector/app-permissions.png
  static/attachments/appstore/platform-supported-content/modules/email-connector/client-cred-api-permissions.png
Labels: Future release

#9974 Update teamcenter-extension.md
  content/en/docs/marketplace/platform-supported-content/modules/teamcenter-extension.md
Labels: Needs language review

#9968 Add 9.24.37 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Release Notes, 9.24.37

#9955 Added warning of long filepath limit while importing modules
  content/en/docs/refguide/modeling/import-and-export/_index.md
Labels: Needs language review

#10001 Mention database deprecations in 11.2 RN
  content/en/docs/releasenotes/studio-pro/11/11.2.md
Labels: Release Notes, 11.2.0

#9966 OIDC SSO section update: Creating IdP Attribute Manually
  content/en/docs/marketplace/platform-supported-content/modules/oidc.md
Labels: Internal WIP

#9972 SAML: CustomUserProvisioning is deprecated
  content/en/docs/marketplace/platform-supported-content/modules/SAML/_index.md
Labels: Internal WIP

#10017 Update release notes for deprecated Kotlin extension function usage fix
  content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-10-parent/nt-11-rn.md
Labels: Needs language review, Release Notes

#10010 update docs to include that old installation packages can be found th…
  content/en/docs/releasenotes/studio-pro/lts-mts.md
Labels: Needs language review

#9985 Add association storage migration performance measurements
  content/en/docs/refguide/modeling/domain-model/associations/association-storage.md
  content/en/docs/refguide/runtime/data-storage/association-storage-migration-time.md
  static/attachments/refguide/runtime/data-storage/association-storage-migration-time/association-storage-model.png
  static/attachments/refguide/runtime/data-storage/association-storage-migration-time/storage-migration-mssql.png
  static/attachments/refguide/runtime/data-storage/association-storage-migration-time/storage-migration-mysql.png
  static/attachments/refguide/runtime/data-storage/association-storage-migration-time/storage-migration-postgres.png
  static/attachments/refguide/runtime/data-storage/association-storage-migration-time/storage-migration-saphana.png
Labels: Needs language review

#10008 Release notes for Mx4PC (MxOK) Operator 2.23.0, planned for release around August 27
  content/en/docs/deployment/private-cloud/_index.md
  content/en/docs/deployment/private-cloud/private-cloud-cluster/_index.md
  content/en/docs/deployment/private-cloud/private-cloud-deploy.md
  content/en/docs/deployment/private-cloud/private-cloud-operator.md
  content/en/docs/deployment/private-cloud/private-cloud-supported-environments.md
  content/en/docs/deployment/private-cloud/private-cloud-technical-appendix/private-cloud-technical-appendix-02.md
  content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
Labels: Future release, Needs language review

#9909 [CTRL-2855] Make mx command line tools work on MacOS
  content/en/docs/refguide/general/mx-command-line-tool/_index.md
  content/en/docs/refguide/general/mxbuild.md
  content/en/docs/refguide/installation/system-requirements.md
Labels: 11.2.0

#10025 Update order of items of view menu docs
  content/en/docs/refguide/modeling/menus/view-menu/_index.md
  static/attachments/refguide/modeling/menus/view-menu/view-menu.png
Labels: 11.2.0

#10036 Release documentation for metamodel & Model SDK 11.2.0
  content/en/docs/releasenotes/sdk/metamodel/metamodel-11/metamodel-11.2.md
Labels: 11.2.0

#9939 Remove Current Limitation and add Jumping from Current Activity to Itself
  content/en/docs/refguide/modeling/application-logic/workflows/boundary-events.md
  content/en/docs/refguide/modeling/application-logic/workflows/jump-to.md
Labels: 11.2.0

#9667 [WOR-2480] Add new feature workflow groups
  content/en/docs/marketplace/platform-supported-content/modules/workflow-commons.md
Labels: 11.2.0
