Repository mendix/docs, pull requests merged in 2025-06, with the labels that each got.

#9593 Rephrased sentence
  content/en/docs/refguide/version-control/on-premises-git.md
Labels: Needs language review

#9458 Update data-importer-extension.md
  content/en/docs/appstore/use-content/platform-supported-content/modules/data-importer-extension.md
Labels: Future release

#9605 10.12.17 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: Needs language review, Update release and/or featured date, Release Notes, 10.12.17

#9606 10.18.7 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.18.md
  content/en/docs/releasenotes/studio-pro/10/10.19.md
  content/en/docs/releasenotes/studio-pro/10/10.23.md
Labels: Needs language review, Update release and/or featured date, Release Notes, 10.18.7

#9573 Update table with date format tokens (Mx 10 patch releases)
  content/en/docs/refguide10/modeling/application-logic/expressions/parse-and-format-date-function-calls.md
Labels: 10.18.7, 10.12.17

#9623 Clarified release note on merge driver
  content/en/docs/releasenotes/studio-pro/10/10.21.md
  content/en/docs/releasenotes/studio-pro/10/10.22.md
Labels: Needs language review, Release Notes

#9617 10.6.24 Studio Pro release notes
  content/en/docs/releasenotes/studio-pro/10/10.6.md
Labels: Release Notes, 10.6.24

#9618 9.24.35 Studio Pro release note
  content/en/docs/releasenotes/studio-pro/11/11.0.md
  content/en/docs/releasenotes/studio-pro/9/9.24.md
Labels: Release Notes, 9.24.35

#9634 Update maintenance-windows.md
  content/en/docs/deployment/mendix-cloud-deploy/maintenance-windows.md
Labels: Needs language review

#9635 Update maintenance-windows.md
  content/en/docs/deployment/mendix-cloud-deploy/maintenance-windows.md
Labels: Needs language review

#9647 Added guide how to create complex intervals
  content/en/docs/refguide/modeling/resources/scheduled-events.md
Labels: Needs language review

#9665 Remove flag --webview-remote-debugging
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro-11/extensibility-api/web/get-started.md
Labels: Needs language review

#9675 Added SALT Guide
  content/en/docs/deployment/general/_index.md
  content/en/docs/deployment/general/salt.md
Labels: Needs language review

#9560 On-premises Git screenshot update + Subversion removal
  content/en/docs/refguide/version-control/on-premises-git.md
  content/en/docs/refguide10/version-control/on-premises-git.md
  static/attachments/refguide/version-control/on-premises-git/app-settings.png
  static/attachments/refguide/version-control/on-premises-git/download-from-version-control-server-extended.png
  static/attachments/refguide/version-control/on-premises-git/export-project-package-dialog.png
  static/attachments/refguide/version-control/on-premises-git/import-project-package-git-dialog.png
  static/attachments/refguide/version-control/on-premises-git/import-project-package-menu.png
  static/attachments/refguide/version-control/on-premises-git/open-app-dialog.png
  static/attachments/refguide/version-control/on-premises-git/preferences-git.png
  static/attachments/refguide/version-control/on-premises-git/progress-dialog.png
  static/attachments/refguide/version-control/on-premises-git/project-uploaded-confirmation.png
  static/attachments/refguide/version-control/on-premises-git/upload-to-vc-menu.png
  static/attachments/refguide/version-control/on-premises-git/upload-to-vc-server.png
  static/attachments/refguide10/version-control/on-premises-git/app-settings.png
  static/attachments/refguide10/version-control/on-premises-git/download-from-version-control-server-extended.png
  static/attachments/refguide10/version-control/on-premises-git/export-project-package-dialog.png
  static/attachments/refguide10/version-control/on-premises-git/import-project-package-git-dialog.png
  static/attachments/refguide10/version-control/on-premises-git/import-project-package-menu.png
  static/attachments/refguide10/version-control/on-premises-git/open-app-dialog.png
  static/attachments/refguide10/version-control/on-premises-git/preferences-git.png
  static/attachments/refguide10/version-control/on-premises-git/progress-dialog.png
  static/attachments/refguide10/version-control/on-premises-git/project-uploaded-confirmation.png
  static/attachments/refguide10/version-control/on-premises-git/upload-to-vc-menu.png
  static/attachments/refguide10/version-control/on-premises-git/upload-to-vc-server.png
Labels: Needs language review

#9592 Updated migration page for 10.24
  content/en/docs/developerportal/general/team-server/migrate-to-git.md
Labels: Needs language review, 10.24

#9680 Update preferences-dialog.md
  content/en/docs/refguide10/modeling/menus/edit-menu/preferences-dialog.md
Labels: 10.24

#9701 Update Tracing in Runtime - 10.24 version
  content/en/docs/refguide10/modeling/app-explorer/app/app-settings/configuration.md
  content/en/docs/refguide10/runtime/tracing-in-runtime.md
  static/attachments/refguide10/runtime/tracing-in-runtime/tracing-configuration.png
Labels: Needs R&D technical verification, 10.24

#9728 Duplicate #9641 for Mx10
  content/en/docs/refguide10/modeling/app-explorer/modules/_index.md
  content/en/docs/refguide10/modeling/application-logic/microflows-and-nanoflows/activities/_index.md
  content/en/docs/refguide10/modeling/application-logic/microflows-and-nanoflows/activities/generate-document.md
  content/en/docs/refguide10/modeling/images.md
  content/en/docs/refguide10/modeling/resources/document-templates/_index.md
  content/en/docs/refguide10/modeling/resources/document-templates/creating-your-own-documents.md
  content/en/docs/refguide10/modeling/resources/document-templates/data-grid-document-template/_index.md
  content/en/docs/refguide10/modeling/resources/document-templates/data-grid-document-template/columns-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/data-view-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/dynamic-image-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/dynamic-label-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/footer-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/header-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/line-break-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/page-break-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/static-image-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/static-label-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/style.md
  content/en/docs/refguide10/modeling/resources/document-templates/table-document-template/_index.md
  content/en/docs/refguide10/modeling/resources/document-templates/table-document-template/row-document-template/_index.md
  content/en/docs/refguide10/modeling/resources/document-templates/table-document-template/row-document-template/cell-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/template-grid-document-template.md
  content/en/docs/refguide10/modeling/resources/document-templates/title-document-template.md
Labels: 10.24

#9716 Online expansion in offline-first apps
  content/en/docs/refguide10/mobile/building-efficient-mobile-apps/offlinefirst-data/_index.md
Labels: 10.24

#9706 Add 11 GA Studio Pro release notes
  content/en/docs/howto/_index.md
  content/en/docs/refguide/_index.md
  content/en/docs/releasenotes/studio-pro/11/11.0.md
  content/en/docs/releasenotes/studio-pro/11/_index.md
  layouts/partials/landingpage/latest-releases.html
Labels: Needs language review, Update release and/or featured date, Release Notes, 11.0.0 GA

#9736 Pluggable Widget Converting Properties
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro-11/pluggable-widgets/pluggable-widgets-property-types.md
Labels: 11.0.0 GA

#9694 Add Migration note - Removal of EmailModule
  content/en/docs/refguide/installation/upgrading-from-10-to-11.md
  content/en/docs/releasenotes/studio-pro/10/10.12.md
Labels: 11.0.0 GA

#9661 Update tracing-in-runtime.md
  content/en/docs/refguide/modeling/app-explorer/app/app-settings/configuration.md
  content/en/docs/refguide/runtime/tracing-in-runtime.md
  static/attachments/refguide/runtime/tracing-in-runtime/tracing-configuration.png
Labels: 11.0.0 GA

#9726 Add documentation for the private PDF Document Generation service
  content/en/docs/apidocs-mxsdk/apidocs/studio-pro-10/pluggable-widgets/_index.md
  content/en/docs/marketplace/platform-supported-content/modules/document-generation/_index.md
  content/en/docs/marketplace/platform-supported-content/modules/document-generation/private-service.md
  content/en/docs/marketplace/platform-supported-content/modules/snowflake/mendix-data-loader.md
  content/en/docs/releasenotes/marketplace/general-marketplace.md
Labels: Needs language review

#9391 [SOLP-3215] Rename Port fix to Cherry pick
  content/en/docs/refguide/modeling/menus/version-control-menu/merge-dialog.md
  content/en/docs/refguide10/modeling/menus/version-control-menu/merge-dialog.md
  static/attachments/refguide/modeling/menus/version-control-menu/merge-dialog/merge-dialog.png
Labels: Future release
